{
  "hash": "f78918a9370b93df465a0a0beaa056ad",
  "result": {
    "engine": "knitr",
    "markdown": "# Problems in Logistic Regression\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **define** complete and quasi-complete separation as conditions on the data,\nstated through the existence of a coefficient vector whose linear predictor\nclassifies every observation correctly,\n- **derive**, from the Bernoulli log-likelihood, why separation leaves $\\ell$\nwith a supremum but no finite maximizer,\n- **diagnose** an enormous coefficient paired with a still larger standard\nerror, alongside a `glm.fit` warning, as separation rather than as evidence\nabout the feature,\n- **evaluate** the responses available when separation occurs — a larger\nsample, a simpler model, or a fit still usable for prediction away from the\nseparated region — and **distinguish** separation from a warning that a single\nextreme observation caused, and\n- **compare** the potential problems of linear regression against their\nlogistic regression counterparts and **identify** which do not transfer.\n:::\n\n## Separation\n\nEvery logistic regression in the previous three lectures converged, returned\nstandard errors of a believable size, and produced $z$-statistics that could be\nread against a normal distribution. Nothing in those outputs suggested that\nmaximum likelihood might do anything else.\n\nIt can. Least squares always returns an estimate as long as $X^\\top X$ is\ninvertible, because $\\hat\\beta = (X^\\top X)^{-1}X^\\top y$ is a formula. Maximum\nlikelihood for logistic regression has no formula: $\\hat\\beta$ is defined as\nthe maximizer of $\\ell(\\beta)$, and a function need not have one.\n\nSo ask what happens at the opposite extreme from a useless feature: one that\npredicts the response perfectly.\n\n### Perfectly predictive feature\n\n**Question.** Suppose a single feature sorts the two classes without a single\nmistake. What does `glm()` estimate?\n\n**Data.** Ten observations, constructed rather than collected, because the\npoint is about a data-generating arrangement rather than about any real\nmeasurement:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 1:10\ny <- as.numeric(x > 5)\ntoy <- tibble(x = x, y = y, class = factor(y))\n```\n:::\n\n\n- $x_i$ takes the values $1, 2, \\ldots, 10$, and\n- $y_i = 1$ exactly when $x_i > 5$, so the five smallest feature values carry\n$y = 0$ and the five largest carry $y = 1$.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\ntoy_eda_plot <- ggplot(toy, aes(x = x, y = y, color = class, shape = class)) +\n  geom_vline(xintercept = 5.5, linetype = \"dashed\", color = \"grey50\") +\n  geom_point(size = 3) +\n  scale_x_continuous(breaks = x) +\n  scale_y_continuous(breaks = c(0, 1)) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  labs(x = \"x\", y = \"y\", color = \"y\", shape = \"y\",\n       title = \"A perfectly predictive feature\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](40-problems-in-logistic-regression_files/figure-html/toy-eda-figure-1.png){width=672}\n:::\n:::\n\n\nEvery $y = 0$ lies to the left of the dashed line and every $y = 1$ lies to the\nright, with a gap of one unit between the last $0$ and the first $1$. No\nobservation contradicts the rule \"predict $1$ when $x > 5.5$,\" and the dashed\nline could be moved anywhere in $(5, 6)$ without changing that.\n\nNow fit the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntoy_glm <- glm(y ~ x, data = toy, family = \"binomial\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: glm.fit: algorithm did not converge\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(toy_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = y ~ x, family = \"binomial\", data = toy)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)\n(Intercept)   -245.8   337834.2  -0.001    0.999\nx               44.7    61172.1   0.001    0.999\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1.3863e+01  on 9  degrees of freedom\nResidual deviance: 7.8648e-10  on 8  degrees of freedom\nAIC: 4\n\nNumber of Fisher Scoring iterations: 25\n```\n\n\n:::\n:::\n\n\n**The two warnings are the output of the chunk above, not a defect in it.**\nThis lecture is about the condition that produces them, so they are left\nvisible here and in the second example below rather than suppressed;\nrecognizing the exact strings `glm.fit: algorithm did not converge` and\n`glm.fit: fitted probabilities numerically 0 or 1 occurred` is part of what is\nbeing taught.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the values quoted below\n\n::: {.cell}\n\n```{.r .cell-code}\ntoy_coef <- summary(toy_glm)$coefficients\ntoy_b    <- toy_coef[, \"Estimate\"]\ntoy_se   <- toy_coef[, \"Std. Error\"]\ntoy_z    <- toy_coef[, \"z value\"]\ntoy_p    <- toy_coef[, \"Pr(>|z|)\"]\ntoy_ratio <- toy_se / abs(toy_b)\n```\n:::\n\n:::\n\nRead the coefficient table one column at a time.\n\n- The estimates are $\\hat\\beta_0 = -245.8$ and\n$\\hat\\beta_1 = 44.7$. A slope of\n$44.7$ log-odds per unit of $x$ is an odds ratio of\n$e^{44.7}$, a number with\n20 digits before the decimal point.\n- The standard errors are larger still:\n337,834 and\n61,172, each roughly\n1,400 times the coefficient it\nbelongs to.\n- So $z = 0.001$ for the slope, with a $p$-value of\n$0.999$. **The feature that predicts the response\nwithout error is not statistically significant.**\n\nTwo more lines of the output say the same thing in different ways. The number\nof Fisher scoring iterations is 25, which is `glm()`'s default\nmaximum, so the algorithm stopped because it ran out of iterations rather than\nbecause it arrived anywhere, and `toy_glm$converged` is\nFALSE. The residual deviance is\n$7.9 \\times 10^{-10}$, which is $-2\\ell(\\hat\\beta)$: the log-likelihood\nat the reported estimates is zero to within rounding, meaning the model\nreproduces all 10 observed responses exactly.\n\nA model that fits the training data perfectly and reports no significant\ncoefficient is not a contradiction. It is the signature of separation.\n\n### Complete and quasi-complete separation\n\nSeparation is defined through the linear predictor rather than through a\npicture.\n\nWrite $x_i$ for the $i$th row of the model matrix and $b$ for a candidate\ncoefficient vector, so $x_i b$ is the linear predictor that $b$ assigns to\nobservation $i$. The data exhibit **complete separation** (also called perfect\nseparation) if there exists a $b$ with\n\n$$x_i b > 0 \\ \\text{ for every } i \\text{ with } y_i = 1, \\qquad x_i b < 0 \\ \\text{ for every } i \\text{ with } y_i = 0,$$\n\nwhere\n\n- $x_i = (1, x_{i1}, \\ldots, x_{ip})$ is the feature row for observation $i$,\n- $b$ is any vector in $\\mathbb{R}^{p+1}$, not necessarily the maximum\nlikelihood estimate, and\n- $y_i \\in \\{0, 1\\}$ is the observed response.\n\nNote that this is a condition on the data, not on a fitted model: it asks\nwhether *some* $b$ works, and says nothing about $\\hat\\beta$, which under this\ncondition does not exist. Since the probability that $b$ implies exceeds $0.5$\nexactly when $x_i b > 0$, the condition says the decision boundary of the\nprevious lecture, drawn using $b$, classifies every training observation\ncorrectly, with no observation lying on the boundary itself.\n\nThe data exhibit **quasi-complete separation** if the strict inequalities can\nbe weakened to\n\n$$x_i b \\ge 0 \\ \\text{ for every } i \\text{ with } y_i = 1, \\qquad x_i b \\le 0 \\ \\text{ for every } i \\text{ with } y_i = 0,$$\n\nfor some $b \\ne 0$, with equality holding for at least one observation. Some\nobservations sit exactly on the boundary; none sits on the wrong side of it.\n\nBoth conditions break maximum likelihood, and neither is visible in a\ncoefficient table without knowing what to look for.\n\n::: {.callout-note collapse=\"true\"}\n### For example, one tie is enough\n\nComplete separation needs a gap between the classes. Quasi-complete separation\ndoes not: it needs only that no observation falls strictly on the wrong side.\nGive two observations the same feature value and opposite responses, and leave\neverything else separated:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxq <- c(1, 2, 3, 4, 5, 5, 6, 7, 8, 9)\nyq <- c(0, 0, 0, 0, 0, 1, 1, 1, 1, 1)\n```\n:::\n\n\nWith $b = (-5\\beta_1, \\beta_1)$ for any $\\beta_1 > 0$, the two observations at\n$x = 5$ get a linear predictor of exactly $0$ and every other observation gets\nthe sign its response requires, so this is quasi-complete separation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquasi <- tibble(xq = xq, yq = yq)\nquasi_glm <- glm(yq ~ xq, data = quasi, family = \"binomial\")\nsummary(quasi_glm)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Estimate Std. Error      z value  Pr(>|z|)\n(Intercept) -98.15825  39288.592 -0.002498391 0.9980066\nxq           19.63165   7857.718  0.002498391 0.9980066\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquasi_coef <- summary(quasi_glm)$coefficients\n```\n:::\n\n\nThe estimates are as unusable as in the completely separated case —\n$\\hat\\beta_1 = 19.6$ with a standard error of\n7,858 — but this fit reports\n`quasi_glm$converged` as TRUE, in\n21 iterations. The only warning it raises is the\n`fitted probabilities numerically 0 or 1` one, suppressed in this callout;\nthere is no convergence warning to go with it. A reported convergence is not\nevidence that an estimate is trustworthy.\n\nThe two tied observations are why the residual deviance is\n2.77 rather than zero: the fitted\nprobability at $x = 5$ is forced to $0.5$, contributing\n$-2 \\times 2 \\log(0.5) = 2.77$ no matter how large\n$\\beta_1$ grows.\n:::\n\n### Maximum likelihood failure\n\nThe simple logistic regression lecture derived the Bernoulli log-likelihood\n\n$$\\ell(\\beta_0, \\beta_1) = \\sum_{i=1}^n \\left\\{ y_i (\\beta_0 + \\beta_1 x_i) - \\log\\left(1 + e^{\\beta_0 + \\beta_1 x_i}\\right) \\right\\},$$\n\nand nothing beyond that is needed to see what goes wrong. With one feature,\n$x_i$ is the scalar feature value again rather than the model-matrix row of the\ndefinitions above.\n\nRestrict attention to a one-parameter family of coefficient vectors that all\nplace the decision boundary at $x = 5.5$, by setting $\\beta_0 = -5.5\\beta_1$.\nThen the linear predictor is $\\eta_i = \\beta_1(x_i - 5.5)$ and\n\n$$\\ell(\\beta_1) = \\sum_{i=1}^n \\left\\{ y_i \\beta_1 (x_i - 5.5) - \\log\\left(1 + e^{\\beta_1(x_i - 5.5)}\\right) \\right\\},$$\n\nwhere\n\n- $\\beta_1$ is the only free parameter, and\n- $p_i = \\text{logistic}(\\beta_1(x_i - 5.5))$ is the probability the family\nimplies for observation $i$.\n\nDifferentiating with respect to $\\beta_1$, by the same steps that produced the\nscore equations,\n\n$$\\frac{d\\ell}{d\\beta_1} = \\sum_{i=1}^n (x_i - 5.5)\\left(y_i - p_i\\right).$$\n\nNow use the separation. Every observation with $y_i = 1$ has $x_i > 5.5$, so\n$x_i - 5.5 > 0$, and $y_i - p_i = 1 - p_i > 0$ because $p_i < 1$ always. Every\nobservation with $y_i = 0$ has $x_i < 5.5$, so $x_i - 5.5 < 0$, and\n$y_i - p_i = -p_i < 0$. Both cases contribute a positive product, so\n\n$$\\frac{d\\ell}{d\\beta_1} > 0 \\quad \\text{for every finite } \\beta_1.$$\n\nThe derivative is never zero, so there is no stationary point and no finite\nmaximizer. Meanwhile $\\ell < 0$ for every finite $\\beta_1$, and as\n$\\beta_1 \\to \\infty$ each $p_i$ approaches the $y_i$ it is paired with, so\nevery term approaches $\\log 1 = 0$ and $\\ell \\to 0$. The log-likelihood has a\n**supremum** of $0$ that it attains only in the limit.\n\nWhat `glm()` reports is therefore not an estimate. It is whatever point the\niteration happened to be at when it stopped, and the reported standard errors\ncome from the curvature of $\\ell$ at that point — curvature that is flattening\ntoward zero as the iteration runs, which is why they grow without bound.\n\nDrawing the fitted curve at a few values of $\\beta_1$ along this family shows\nwhat the derivative is describing.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\ntoy_curve_betas <- c(0.5, 1, 2, 5)\n\ntoy_curves <- expand_grid(beta1 = toy_curve_betas,\n                          xg = seq(0, 11, length.out = 400)) |>\n  mutate(p = plogis(beta1 * (xg - 5.5)),\n         beta1 = factor(sprintf(\"beta[1] == %.1f\", beta1),\n                        levels = sprintf(\"beta[1] == %.1f\", toy_curve_betas)))\n\ntoy_curve_plot <- ggplot(toy_curves,\n                         aes(x = xg, y = p, color = beta1, linetype = beta1)) +\n  geom_line(linewidth = 0.9) +\n  geom_point(data = toy, aes(x = x, y = y), inherit.aes = FALSE,\n             size = 2, alpha = 0.7) +\n  scale_color_manual(values = c(\"#E69F00\", \"#56B4E9\", \"#009E73\", \"#CC79A7\"),\n                     labels = scales::parse_format()) +\n  scale_linetype_manual(values = c(\"solid\", \"dashed\", \"dotted\", \"dotdash\"),\n                        labels = scales::parse_format()) +\n  scale_y_continuous(breaks = c(0, 0.5, 1)) +\n  labs(x = \"x\", y = \"p(x)\", color = NULL, linetype = NULL,\n       title = \"Fitted curves along the family with boundary fixed at 5.5\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](40-problems-in-logistic-regression_files/figure-html/toy-curves-figure-1.png){width=672}\n:::\n:::\n\n\nEach increase in $\\beta_1$ steepens the curve at the boundary and pushes it\ncloser to $0$ on the left and to $1$ on the right, so every fitted probability\nmoves toward the response it is paired with. Nothing stops this: the curve\napproaches a step function and the likelihood approaches $1$.\n\nEvaluating $\\ell$ along the same family puts numbers on it.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the table and figure below\n\n::: {.cell}\n\n```{.r .cell-code}\ntoy_loglik <- function(beta1) {\n  eta <- beta1 * (toy$x - 5.5)\n  sum(toy$y * eta - log(1 + exp(eta)))\n}\n\ntoy_ll_table <- tibble(beta1 = c(0, 0.5, 1, 2, 5, 8)) |>\n  mutate(ll = map_dbl(beta1, toy_loglik),\n         L  = exp(ll)) |>\n  mutate(beta1 = sprintf(\"%.1f\", beta1),\n         ll    = sprintf(\"%.3f\", ll),\n         L     = sprintf(\"%.3f\", L)) |>\n  knitr::kable(col.names = c(\"$\\\\beta_1$\", \"$\\\\ell(\\\\beta_1)$\",\n                             \"$L(\\\\beta_1)$\"),\n               align = \"ccc\")\n\ntoy_ll_curve <- tibble(beta1 = seq(0, 8, length.out = 400)) |>\n  mutate(ll = map_dbl(beta1, toy_loglik))\n\ntoy_ll_plot <- ggplot(toy_ll_curve, aes(x = beta1, y = ll)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_line(color = \"#0072B2\", linewidth = 0.9) +\n  labs(x = expression(beta[1]), y = \"Log-likelihood\",\n       title = expression(paste(\"Log-likelihood along the family \",\n                                beta[0] == -5.5 * beta[1])))\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| $\\beta_1$ | $\\ell(\\beta_1)$ | $L(\\beta_1)$ |\n|:---------:|:---------------:|:------------:|\n|    0.0    |     -6.931      |    0.001     |\n|    0.5    |     -2.950      |    0.052     |\n|    1.0    |     -1.590      |    0.204     |\n|    2.0    |     -0.739      |    0.477     |\n|    5.0    |     -0.159      |    0.853     |\n|    8.0    |     -0.036      |    0.964     |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](40-problems-in-logistic-regression_files/figure-html/toy-loglik-figure-1.png){width=672}\n:::\n:::\n\n\nThe log-likelihood rises steeply at first and then flattens against the dashed\nline at $0$ without ever touching it, exactly as the derivative predicted. The\nlikelihood column reaches\n0.964 at $\\beta_1 = 8$ and would keep\nclimbing toward $1$ for larger values.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nTwo numerical artifacts surface when $\\ell$ is evaluated by hand at large\n$\\beta_1$. Neither changes any conclusion above, and neither is tested here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntoy_loglik_prob <- function(beta1) {\n  p <- plogis(beta1 * (toy$x - 5.5))\n  sum(toy$y * log(p) + (1 - toy$y) * log(1 - p))\n}\n\nartifact_grid <- seq(0.1, 400, by = 0.1)\nfirst_nan <- artifact_grid[which(is.na(map_dbl(artifact_grid,\n                                               toy_loglik_prob)))[1]]\nfirst_inf <- artifact_grid[which(is.infinite(map_dbl(artifact_grid,\n                                                     toy_loglik)))[1]]\n```\n:::\n\n\nEvaluating $\\ell$ on the probability scale as\n$\\sum_i \\{y_i \\log p_i + (1 - y_i)\\log(1 - p_i)\\}$ is algebraically identical\nto the form used above, but in this example it returns `NaN` from\n$\\beta_1 = 8.2$ onward. Once $p_i$ rounds to exactly $1$, the term\n$(1 - y_i)\\log(1 - p_i)$ becomes $0 \\times \\log 0 = 0 \\times (-\\infty)$, which\nis `NaN`.\n\nThe $\\eta$-scale form survives further but eventually fails too: at\n$\\beta_1 = 157.8$ the largest $e^{\\eta_i}$ overflows to `Inf`, and\n$\\ell$ returns $-\\infty$.\n\nNeither is a property of $\\ell$, which is finite, negative, and increasing at\nevery one of those values. Both are finite-precision arithmetic running out of\nroom, which is also the mechanism behind the `fitted probabilities numerically\n0 or 1` warning. The range $0 \\le \\beta_1 \\le 8$ plotted above stays clear of\nboth.\n:::\n\n## Muscular dystrophy carrier screening\n\nConstructed data makes the mechanism visible, and it also makes separation look\nunmistakable. It is not always. Real data can trigger the same warning without\nbeing separated at all, and telling the two cases apart takes one more step\nafter the warning appears.\n\n**Question.** Duchenne muscular dystrophy is inherited through female\ncarriers, who show no symptoms themselves. Can a blood test identify likely\ncarriers, so that a woman with a family history can be counseled about her\nrisk?\n\n**Data.** `Sleuth3::ex2012` records\n120 women, each already classified by other means:\n\n- `Group`: `Case` for a known carrier, `Control` otherwise. There are\n38 carriers and\n82 non-carriers. This is the response,\nwith $Y_i = 1$ for a carrier.\n- `CK`: serum creatine kinase, an enzyme that leaks from damaged muscle.\nThis is the feature.\n- `H`: serum hemopexin, a second blood measurement, recorded but not used\nbelow.\n\n`Case` is the first level of `Group`, and `glm()` models the probability of a\nfactor's *second* level, so the event has to be set explicitly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndmd <- Sleuth3::ex2012 |>\n  mutate(Group = relevel(Group, ref = \"Control\"),\n         case01 = as.numeric(Group == \"Case\"))\nlevels(dmd$Group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Control\" \"Case\"   \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\n# The jitter is computed once and stored, rather than left to geom_jitter(),\n# so re-rendering does not move the points.\nset.seed(20260919)\ndmd <- dmd |> mutate(case_jittered = case01 + runif(n(), -0.04, 0.04))\n\nmax_control_ck <- max(dmd$CK[dmd$Group == \"Control\"])\nn_above        <- sum(dmd$CK > max_control_ck)\nn_case_below   <- sum(dmd$Group == \"Case\" & dmd$CK <= max_control_ck)\n\ndmd_eda_plot <- ggplot(dmd, aes(x = CK, y = case_jittered,\n                                color = Group, shape = Group)) +\n  geom_vline(xintercept = max_control_ck, linetype = \"dashed\",\n             color = \"grey50\") +\n  geom_point(size = 1.8, alpha = 0.8) +\n  scale_y_continuous(breaks = c(0, 1),\n                     labels = c(\"Control (0)\", \"Case (1)\")) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  labs(x = \"Serum creatine kinase (CK)\", y = \"Carrier status\",\n       title = \"Sleuth3::ex2012\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](40-problems-in-logistic-regression_files/figure-html/dmd-eda-figure-1.png){width=672}\n:::\n:::\n\n\nThe dashed line marks 130, the largest `CK` recorded on any\nnon-carrier. All 13 observations to its right are carriers. To its\nleft the two groups overlap heavily: 25 of the\n38 carriers have `CK` values in the same range as the\nnon-carriers. Carriers have a median `CK` of\n102.5 against\n35 for non-carriers. No threshold on\n`CK` classifies these women without error, so this is not separation under\neither definition above.\n\nFit the model anyway.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndmd_glm <- glm(Group ~ CK, data = dmd, family = \"binomial\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(dmd_glm)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error   z value     Pr(>|z|)\n(Intercept) -3.96219273  0.6719084 -5.896924 3.703413e-09\nCK           0.05073407  0.0106958  4.743364 2.101984e-06\n```\n\n\n:::\n:::\n\n\nThe warning from the toy example has reappeared. The convergence warning has\nnot, and again this chunk's warning is intended output rather than a defect.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the values and table below\n\n::: {.cell}\n\n```{.r .cell-code}\ndmd_b   <- coef(dmd_glm)\ndmd_se  <- summary(dmd_glm)$coefficients[, \"Std. Error\"]\ndmd_eta <- predict(dmd_glm)\ndmd_p   <- fitted(dmd_glm)\n\ndmd_or10    <- unname(exp(10 * dmd_b[\"CK\"]))\ndmd_ci10    <- exp(10 * confint.default(dmd_glm)[\"CK\", ])\nglm_eps     <- 10 * .Machine$double.eps\nn_triggered <- sum(dmd_p > 1 - glm_eps | dmd_p < glm_eps)\n\n# The true mathematical value of 1 - logistic(eta), computed without ever\n# forming logistic(eta) itself, so it is not limited by how close to 1 a\n# double can get.\ntrue_gap <- exp(-max(dmd_eta)) / (1 + exp(-max(dmd_eta)))\n\ndmd_tail_gaps <- (1 - dmd_p)[order(-dmd$CK)][1:5]\n\ndmd_tail_table <- dmd |>\n  mutate(eta = dmd_eta, p = dmd_p) |>\n  slice_max(CK, n = 5) |>\n  transmute(CK,\n            Group = as.character(Group),\n            eta = sprintf(\"%.1f\", eta),\n            gap = sprintf(\"$%s$\", sci(1 - p))) |>\n  knitr::kable(col.names = c(\"CK\", \"Group\", \"$\\\\hat\\\\eta$\", \"$1 - \\\\hat p$\"),\n               align = \"ccrr\")\n```\n:::\n\n:::\n\nThe estimated slope is $\\hat\\beta_1 = 0.0507$ with a\nstandard error of 0.0107, a ratio of\n$z = 4.74$. The algorithm reports\n`dmd_glm$converged` as TRUE after\n7 iterations. Nothing in the coefficient table resembles the\ntoy example's standard error of\n61,172.\n\nWhat the warning is responding to sits at the far right of the plot. The last\ncolumn below is $1 - \\hat p$ as `fitted()` reports it.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| CK  | Group | $\\hat\\eta$|          $1 - \\hat p$|\n|:---:|:-----:|----------:|---------------------:|\n| 925 | Case  |       43.0| $2.2 \\times 10^{-16}$|\n| 657 | Case  |       29.4| $1.8 \\times 10^{-13}$|\n| 560 | Case  |       24.4| $2.4 \\times 10^{-11}$|\n| 440 | Case  |       18.4|  $1.1 \\times 10^{-8}$|\n| 363 | Case  |       14.5|  $5.3 \\times 10^{-7}$|\n\n\n:::\n:::\n\n\nThe largest linear predictor in the fit is\n$\\hat\\eta = 42.97$. Mathematically,\n\n$$1 - \\text{logistic}(\\hat\\eta) = \\frac{e^{-\\hat\\eta}}{1 + e^{-\\hat\\eta}} = 2.2 \\times 10^{-19}$$\n\nat that value — far below $2^{-53} = 1.1 \\times 10^{-16}$, the gap between $1$ and\nthe largest double-precision number below it (`.Machine$double.eps`\n$= 2^{-52} = 2.2 \\times 10^{-16}$ is the corresponding gap just\n*above* $1$). No double can hold a probability that close to $1$: computed\ndirectly, $1$ minus that gap rounds to exactly $1$. A fitted probability of\nexactly $0$ or $1$ would make the deviance infinite for any observation whose\nresponse disagreed with it, and would give that observation zero weight in\nthe next iteration, so `glm()` does not let it happen — it clamps the linear\npredictor before inverting the link, and `fitted()` never leaves\n$[2.2 \\times 10^{-16},\\ 1 - 2.2 \\times 10^{-16}]$. The top\nrow of the table is therefore the clamped value rather than the true one:\n3 orders of magnitude larger\nthan the true gap just derived, and\n3 orders of\nmagnitude smaller than the row beneath it in the table — the column only\nlooks like it descends smoothly.\n\n`glm()` warns whenever a fitted probability comes within\n$2.2 \\times 10^{-15}$ of $0$ or $1$, and here exactly\n1 of the 120 observations does.\n\nSo the warning fired for a reason that has nothing to do with the estimator\nfailing. One woman has a `CK` of 925, while the other\n119 observations sit at\n657 or below, and the fitted curve has\nsaturated well before it reaches her.\n\n**Conclusion.** Creatine kinase is strongly associated with carrier status:\neach additional 10 units of `CK` multiplies the estimated odds of being a\ncarrier by 1.66 (95% CI\n1.35 to 2.05). The\nestimate is finite, its standard error is small relative to it, and the\niteration converged, so the warning here is a report about one extreme\nobservation rather than about the estimator. The same warning in the toy\nexample meant the estimate did not exist.\n\n## Separation diagnosis and response\n\nThe two examples give the same warning for different reasons, so the warning is\nwhere an investigation starts rather than where it ends. What settles the\nquestion is the coefficient table.\n\n### Recognizing separation\n\n- A `glm.fit: algorithm did not converge` warning. This one is close to\nconclusive: when a strictly concave log-likelihood has a finite maximizer, the\nalgorithm locates it in a handful of iterations.\n- A `glm.fit: fitted probabilities numerically 0 or 1 occurred` warning. This\none is not conclusive on its own, as the muscular dystrophy example shows, but\nseparation always produces it.\n- A coefficient whose magnitude is absurd on the feature's own scale. An odds\nratio of $e^{44.7}$ per unit is not a quantity any\nreal process produces.\n- A standard error far larger than the coefficient it belongs to, so that a\nfeature which classifies the training data perfectly returns $z \\approx 0$ and\na $p$-value near $1$. This is the diagnostic that is hardest to misread,\nbecause it is the reverse of what a strong feature normally looks like.\n- Under complete separation, a residual deviance of essentially zero, meaning\nthe fitted probabilities reproduce every observed response exactly. Under\nquasi-complete separation the deviance settles at whatever the tied\nobservations on the boundary contribute, so it is small rather than zero.\n- Fitted probabilities numerically indistinguishable from $0$ or $1$ in\n`fitted()`, for observations on the separated side of the boundary. They are\nnever *exactly* $0$ or $1$: `glm()` clamps them into\n$[2.2 \\times 10^{-16},\\ 1 - 2.2 \\times 10^{-16}]$, so that is\nwhat a separated observation returns.\n\nChecking `fit$converged` and comparing each $|\\hat\\beta_j|$ against its\nstandard error takes one line and distinguishes the two situations.\n\n### Available responses\n\nWithin the methods this course has covered, there are three responses.\n\n**Collect more data.** Separation is a property of a sample, not of the\npopulation it came from. Ten observations and one threshold feature separate\nalmost by construction; 120 observations with two overlapping\ndistributions do not, even with one `CK` value\n22 times the sample median. The\nprobability that a sample happens to be separated falls as $n$ grows and as the\nclasses overlap more.\n\n**Simplify the model.** If a feature or a dummy-coded level is what makes the\ndata separable, and that feature is not the object of the analysis, dropping it\nor merging it with another level removes the separation. This is most common\nwith a categorical feature that has a level in which the event never occurs:\nthat level alone can separate the data, and combining it with a neighboring\nlevel fixes the fit without touching the rest of the model.\n\n**Use the fit for what it can still support.** Separation destroys the\n*coefficient*, not necessarily the *classification*. The toy model's slope is\nmeaningless, but its decision boundary sits between $x = 5$ and $x = 6$ and\nclassifies every observation correctly. A model that separates on one feature\ncan still produce usable predicted classes away from the separated region, as\nlong as no probability, odds ratio, standard error, or $p$-value involving the\noffending coefficient is reported.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nThe principled fix is to stop maximizing $\\ell(\\beta)$ by itself and maximize a\n*penalized* version, $\\ell(\\beta) - \\lambda \\cdot \\text{pen}(\\beta)$, where the\npenalty grows with the magnitude of $\\beta$. A penalty that increases without\nbound as $\\|\\beta\\| \\to \\infty$ restores a finite maximizer no matter how the\ndata are arranged, because the penalty eventually outruns the gain in $\\ell$.\n\n**Firth's penalized likelihood** uses a penalty derived from the information\nmatrix and is the standard remedy for separation; it also removes most of the\nsmall-sample bias in $\\hat\\beta$. The **ridge** and **lasso** penalties\nforward-referenced in the multiple linear regression lecture do the same job\nfrom a different motivation, and both apply to logistic regression unchanged.\nA Bayesian analysis with a proper prior on $\\beta$ achieves the same effect\nagain, since the prior plays the role of the penalty.\n\nAll of these are shrinkage methods, and shrinkage is ISLR2 Chapter 6 material.\nName the fix if you meet separation before then; do not try to implement it\nfrom this callout.\n:::\n\n## Linear regression problems revisited\n\nThe flexibility lecture listed six potential problems for a linear regression:\nnon-linearity, correlated errors, non-constant variance, outliers,\nhigh-leverage points, and collinearity. Separation has no counterpart on that\nlist: whenever $X^\\top X$ is invertible, least squares evaluates a formula and\nso cannot fail this way. The six themselves transfer to logistic regression\nunevenly.\n\n### Correlated observations transfer unchanged\n\nCorrelated errors are the one that transfers with no change at all — the same\nitem, under the name **correlated observations**, since logistic regression has\nno $\\epsilon_i$ to call correlated. The Bernoulli log-likelihood is a sum over\nobservations precisely because they were assumed independent, so responses\ncorrelated in time or space distort every standard error from `glm()`, for the\nsame reason and in the same direction as in linear regression: positively\ncorrelated observations carry less information than their count suggests, and\nthe reported standard errors come out too small.\n\n### Non-constant variance requires no assumption\n\nLinear regression assumes $Var[\\epsilon_i] = \\sigma^2$ and needs that\nassumption checked, usually by looking for a fan shape in a plot of residuals\nagainst fitted values.\n\nLogistic regression has nothing to check. The simple logistic regression\nlecture established that\n\n$$Var[Y_i|X_i] = p(X_i)\\left[1 - p(X_i)\\right]$$\n\nis a consequence of $Y_i$ being Bernoulli, not an extra assumption laid on top\nof the model. The variance is *required* to change with $X_i$, and it is\ndetermined once $p(X_i)$ is, which is also why the model has no $\\sigma^2$\nparameter. A residual plot that fanned out would not be evidence against this\nmodel.\n\n### Log-odds non-linearity\n\nWhat logistic regression does assume is that the *log-odds* are linear in the\nfeatures,\n\n$$\\log\\left(\\frac{p(x_i)}{1 - p(x_i)}\\right) = x_i\\beta.$$\n\nThat assumption can fail, and the previous lecture is where it was addressed:\ninteractions let a feature's log-odds slope depend on another feature, and\npolynomial and step-function columns let it bend within a single feature. Both\nenter as columns of the model matrix, and both are checked the same way — fit\nthe more flexible model and test the added coefficients.\n\n### Collinearity, leverage, and outliers\n\nThese three carry over in substance. Features carrying nearly the same\ninformation still leave the data unable to separate their contributions, so\n$\\text{SE}(\\hat\\beta_j)$ inflates and a $z$-test loses power. An observation\nwith an unusual feature value still has disproportionate pull on the fit, and\nan observation whose response disagrees with the rest of the data still\ndistorts it.\n\nWhat does not carry over is the arithmetic. The hat matrix\n$H = X(X^\\top X)^{-1}X^\\top$, studentized residuals, and Cook's distance were\nall defined through the least squares fit, and none of those formulas applies\nto a likelihood maximized iteratively. Whether the woman with\n`CK` = 925 counts as a high-leverage point is a question the two\nfits answer differently, and the least squares formula gives the wrong answer.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nEach of the three has a generalized-linear-model analogue, built from the\nweighted least squares problem that the iterative algorithm solves at its last\nstep. The weights $\\hat p_i(1 - \\hat p_i)$ from that final iteration produce a\nweighted hat matrix, and from it a leverage, a standardized residual, and a\nCook's distance that mean what their linear-model namesakes mean. In R,\n`hatvalues()`, `rstudent()`, and `cooks.distance()` all accept a `glm` object\nand return exactly these.\n\nThe weighting is what settles the question above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndmd_extreme <- which.max(dmd$CK)\n\ndmd_lm  <- lm(case01 ~ CK, data = dmd)\nh_lm    <- hatvalues(dmd_lm)\nh_glm   <- hatvalues(dmd_glm)\ncd_glm  <- cooks.distance(dmd_glm)\n\n# The weights p(1-p) computed from eta rather than from the clamped fitted(),\n# so the extreme one is its true mathematical value rather than a floored one.\nw_eta       <- exp(-dmd_eta) / (1 + exp(-dmd_eta))^2\nw_true      <- unname(w_eta[which.max(dmd$CK)])\nw_ratio_min <- min(w_eta[-which.max(dmd$CK)]) / w_true\n\n# Fixed notation where it reads well, scientific where it does not.\nfmt_val <- function(v) ifelse(abs(v) >= 1e-3, sprintf(\"%.3f\", v), sci(v))\n\ndmd_leverage_table <- tibble(\n  Quantity = c(\"Least squares leverage $h_i$\",\n               \"Logistic leverage $h_i$\",\n               \"Logistic Cook's distance\"),\n  Value    = sprintf(\"$%s$\", fmt_val(c(h_lm[dmd_extreme], h_glm[dmd_extreme],\n                                       cd_glm[dmd_extreme]))),\n  Rank     = c(\"largest\", \"smallest\", \"smallest\")\n) |>\n  knitr::kable(col.names = c(\"Quantity\",\n                             sprintf(\"Value for the `CK` = %d woman\",\n                                     max(dmd$CK)),\n                             sprintf(\"Rank among the %d\", nrow(dmd))),\n               align = \"lcc\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Quantity                     | Value for the `CK` = 925 woman | Rank among the 120 |\n|:----------------------------|:------------------------------:|:------------------:|\n|Least squares leverage $h_i$ |            $0.385$             |      largest       |\n|Logistic leverage $h_i$      |     $1.9 \\times 10^{-14}$      |      smallest      |\n|Logistic Cook's distance     |     $2.1 \\times 10^{-30}$      |      smallest      |\n\n\n:::\n:::\n\n\nRegressing the $0/1$ response on `CK` by least squares makes her the\nhighest-leverage observation in the data, since leverage there depends only on\nhow far a feature value sits from the mean. The logistic fit weights that\ngeometry by $\\hat p_i(1 - \\hat p_i)$ — reweighting $X^\\top X$ along with it,\nnot just scaling her row — and that weight at\n$\\hat\\eta = 42.97$ is $2.2 \\times 10^{-19}$ — smaller\nthan every other observation's weight by a factor of at least\n800,000. So she\nends up with the *smallest* leverage of the\n120 observations, against a maximum of\n0.055, and the smallest Cook's distance. Saturating\nthe curve is exactly what costs an observation its influence: the model has\nalready committed to a $\\hat p$ indistinguishable from $1$ for her, and no\nsmall change in $\\hat\\beta$ alters that, so she cannot pull the fit anywhere.\nThis is the other half of why the fit converged to something usable despite the\nwarning she triggered.\n\nCollinearity needs no new definition: the variance inflation factor of the\nflexibility lecture, $1/(1-R_j^2)$, is computed from the features alone and\nnever looks at the response, so that quantity is unchanged. (`car::vif()`\nrun on a `glm` reports a different, weighted version built from\n$(X^\\top\\hat W X)^{-1}$, so the two do not agree numerically — the *idea*\ncarries over, not the specific number a package function returns.)\n\nNone of this is tested in this course, which is why the diagnostics in the\nexamples above were read off the fitted coefficients and the data rather than\noff these quantities.\n:::\n\n## Conclusion\n\nMaximum likelihood for logistic regression can fail in a way least squares\ncannot. When some linear predictor classifies every training observation\ncorrectly — complete separation, or quasi-complete separation if ties are\nallowed on the boundary — the log-likelihood climbs toward a supremum it\nattains only in the limit, so no finite $\\hat\\beta$ maximizes it. What `glm()`\nprints in that situation is an arbitrary point along a divergent path, with\nstandard errors that grow as the curvature of $\\ell$ flattens.\n\nThe resulting output is recognizable once its signature is familiar: a\n`glm.fit` warning, a coefficient far too large for its feature's scale, a\nstandard error larger still, a $z$-statistic near zero despite the feature\nbeing (or nearly being) a perfect predictor, and a residual deviance far\nsmaller than the fit has earned — essentially zero under complete separation,\nsmall but not zero under the quasi-complete kind. The same signature can come\nfrom a handful of constructed observations or from a categorical level in\nwhich the event never occurs, and it appears whether the fit fails to converge\noutright or the algorithm converges to coefficients the data no longer pin\ndown. A `glm.fit` warning on its own does not establish it: a single extreme\nfeature value can trigger the same warning while leaving a finite estimate, a\nsmall standard error, and a large $z$ — the coefficient table, not the\nwarning, is what settles the question.\n\nThat completes what this course covers of logistic regression before Exam 1.\n",
    "supporting": [
      "40-problems-in-logistic-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}