{
  "hash": "94656e40592f8a3771567deccc708b74",
  "result": {
    "engine": "knitr",
    "markdown": "# Simple Logistic Regression\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **explain** why a linear regression model is a poor model for a binary\nresponse,\n- **write** the simple logistic regression model in both its probability and\nlog-odds forms, and **define** the odds of an event,\n- **derive** the Bernoulli log-likelihood for $\\beta_0$ and $\\beta_1$ and\n**explain** why, unlike least squares, it has no closed-form maximizer,\n- **fit** a simple logistic regression with `glm()` and **predict** the\nprobability of the event at a given feature value,\n- **interpret** $\\hat\\beta_0$ as a log-odds and $\\hat\\beta_1$ as a change in\nlog-odds, with $e^{\\hat\\beta_1}$ an odds ratio, and\n- **test** $H_0: \\beta_1 = 0$ with a $z$-statistic and **construct** a\nconfidence interval for $\\beta_1$ and for the odds ratio $e^{\\beta_1}$.\n:::\n\n## Binary response\n\nEvery model we have *fit* so far has had a quantitative response. Now take the\nclassification setup from the classification lecture, with $C = 2$ classes, and\ncode the response numerically,\n\n$$Y_i = \\begin{cases} 1 & \\text{the event of interest occurs for observation } i \\\\ 0 & \\text{otherwise,}\\end{cases}$$\n\nwhere\n\n- $Y_i$ is the response for observation $i$, and\n- \"the event of interest\" is whichever of the two classes we choose to call a\nsuccess.\n\nThe coding is a choice, and it is not innocent: the model below describes the\nclass coded $1$, so swapping the labels flips the sign of every coefficient.\n\nThe expected value of a $0/1$ response is a probability,\n\n$$E[Y_i|X_i] = 1 \\cdot P(Y_i = 1|X_i) + 0 \\cdot P(Y_i = 0|X_i) = P(Y_i = 1|X_i) \\equiv p(X_i),$$\n\nwhere\n\n- $X_i$ is the feature for observation $i$ (a scalar throughout this lecture),\nand\n- $p(X_i) = P(Y_i = 1|X_i)$ is the conditional probability that the event\noccurs.\n\nSo modeling the mean of a binary response *is* modeling a probability, and any\nmodel for $p(X)$ has to respect $0 \\le p(X) \\le 1$ for every $X$.\n\n### Credit card default\n\n**Question.** Does a customer's credit card balance tell us whether that\ncustomer will default?\n\n**Data.** `ISLR2::Default` holds 10,000\ncredit card customers. The data are simulated rather than observed, and we use\nthem because they are the canonical demonstration of this method. Today we use\ntwo of its four variables:\n\n- `default`: did the customer default? A factor with levels\nNo and Yes. This is the response.\n- `balance`: the average balance remaining on the card after the monthly\npayment, in dollars. This is the feature.\n\nDefaulting is the rarer and more consequential outcome, so it is the event of\ninterest: $Y_i = 1$ when customer $i$ defaults. In this sample\n3.33% of customers default.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\nDefault <- Default |>\n  mutate(default01 = as.numeric(default == \"Yes\"))\n\ndefault_plot <- ggplot(Default, aes(x = balance, y = default01)) +\n  geom_jitter(height = 0.03, width = 0, alpha = 0.08, size = 0.7) +\n  scale_y_continuous(breaks = c(0, 1), labels = c(\"No (0)\", \"Yes (1)\")) +\n  labs(x = \"Credit card balance ($)\", y = \"Default\",\n       title = \"ISLR2::Default\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-logistic-regression_files/figure-html/default-eda-figure-1.png){width=672}\n:::\n:::\n\n\nThe points are jittered vertically, since every response is exactly $0$ or\nexactly $1$ and thousands of customers would otherwise stack on top of one\nanother.\n\nNo customer with a balance under\n\\$652 defaulted, and\ndefaults become steadily more common as the balance grows, while above \\$2,000\nthe non-defaulters thin out. Exact\nproportions cannot be read off jittered points, but the shape can: whatever\ncurve describes $p(\\text{balance})$ sits near $0$ on the left, rises through\nthe middle, and has to stay below $1$ on the right.\n\nThe obvious next step is to fit the model we already have, by least squares,\nto this $0/1$ response — expand the note below to see why that does not work.\n\n::: {.callout-note collapse=\"true\"}\n### Linear regression fails\n\nApplying the linear regression model of the earlier lectures to this $0/1$\nresponse gives\n\n$$Y_i = \\beta_0 + \\beta_1 X_i + \\epsilon_i.$$\n\nSince $E[Y_i|X_i] = p(X_i)$, this model says the probability of default is a\nstraight line in balance. Least squares will happily fit that line to the\ndefault data, so the fastest way to see what goes wrong is to draw it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_lm <- lm(default01 ~ balance, data = Default)\n\nlm_plot <- ggplot(Default, aes(x = balance, y = default01)) +\n  geom_jitter(height = 0.03, width = 0, alpha = 0.08, size = 0.7) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey40\") +\n  geom_abline(intercept = coef(default_lm)[1], slope = coef(default_lm)[2],\n              color = \"#0072B2\", linewidth = 1) +\n  coord_cartesian(xlim = range(Default$balance),\n                  ylim = c(min(fitted(default_lm)) - 0.02, 1.03)) +\n  scale_y_continuous(breaks = c(-0.05, 0, 0.5, 1)) +\n  labs(x = \"Credit card balance ($)\", y = \"Default (0/1)\",\n       title = \"ISLR2::Default\")\n\nzero_crossing <- -coef(default_lm)[1] / coef(default_lm)[2]\npercent_negative <- 100 * mean(fitted(default_lm) < 0)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-logistic-regression_files/figure-html/default-lm-figure-1.png){width=672}\n:::\n:::\n\n\nThe fitted line drops below the dashed zero line on the left. It crosses zero\nat a balance of \\$579, so every customer carrying less\nthan that — 31% of the sample — is assigned a\n*negative* estimated probability of default. A negative probability is not a\npoor estimate; it is not a probability.\n\nThree objections:\n\n1. **Fitted values leave $[0,1]$.** A line is unbounded, and $p(X)$ is not.\nTruncating at $0$ and $1$ after the fact fixes the printed number without\nfixing the model that produced it.\n\n2. **A constant additive effect cannot be right.** The fitted slope says every\nextra dollar of balance raises the line's value by the same\n$0.00013$ regardless of\nwhere we start. Wherever the line's value reaches $0.99$, only $0.01$ of room\nis left, and just\n77 more dollars of balance pushes it past\n$1$ — a \"probability\" of more than 100%. A probability has to flatten as it\napproaches either boundary, and a line never flattens.\n\n3. **The error assumptions fail by construction.** $Y_i$ is Bernoulli, not\nnormal, so $\\epsilon_i = Y_i - p(X_i)$ takes exactly two values, and\n$$Var[Y_i|X_i] = p(X_i)\\left[1 - p(X_i)\\right]$$\ndepends on $X_i$ through $p(X_i)$. Constant variance is impossible unless\n$p(X)$ is constant. Every standard error, t-test, and interval from `lm()`\nrests on assumptions the response itself contradicts.\n\nWhat we need is a model that is flexible in the middle and bends toward $0$\nand $1$ at the ends — the shape the data already showed us.\n:::\n\n## Logistic regression model\n\nThe **simple logistic regression** model is\n\n$$p(X) = P(Y = 1|X) = \\frac{e^{\\beta_0 + \\beta_1 X}}{1 + e^{\\beta_0 + \\beta_1 X}},$$\n\nwhere\n\n- $p(X)$ is the probability the event occurs at feature value $X$,\n- $\\beta_0$ is the intercept on the log-odds scale (defined below), and\n- $\\beta_1$ is the slope on the log-odds scale.\n\nWrite $\\eta = \\beta_0 + \\beta_1 X$ for the **linear predictor**. The function\n\n$$\\text{logistic}(\\eta) = \\frac{e^{\\eta}}{1 + e^{\\eta}}$$\n\nis the **logistic function**, available in R as `plogis()`. It maps the whole\nreal line into $(0,1)$: $e^{\\eta} > 0$ makes $\\text{logistic}(\\eta) > 0$, and\n$e^\\eta < 1 + e^\\eta$ makes $\\text{logistic}(\\eta) < 1$. As\n$\\eta \\to -\\infty$, $\\text{logistic}(\\eta) \\to 0$; as $\\eta \\to \\infty$,\n$\\text{logistic}(\\eta) \\to 1$. The boundary problem raised above is gone no\nmatter what values $\\beta_0$, $\\beta_1$, and $X$ take.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nThe logistic function is not the only function that maps the real line onto\n$(0,1)$. Replacing it with the standard normal CDF gives **probit\nregression**, and the whole family — logistic, probit, Poisson regression, and\nothers — travels under the name **generalized linear models**; the inverse\nmap, which takes a probability back to the linear predictor, is called the\n*link function*. `glm()` is named for the family, not for logistic regression\nspecifically.\n:::\n\nPlotting the curve at a few parameter values shows what $\\beta_0$ and $\\beta_1$\neach control:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\nshape_data <- tibble(b0 = c(0, 0, 0, -4), b1 = c(1, 2, -1, 1)) |>\n  mutate(curve = sprintf(\"beta[0] == %d * ',' ~ beta[1] == %d\", b0, b1)) |>\n  mutate(curve = fct_inorder(curve)) |>\n  expand_grid(x = seq(-8, 8, length.out = 400)) |>\n  mutate(p = plogis(b0 + b1 * x))\n\nlogistic_shape_plot <- ggplot(shape_data,\n                              aes(x = x, y = p,\n                                  color = curve, linetype = curve)) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\", color = \"grey60\") +\n  geom_line(linewidth = 0.9) +\n  scale_color_manual(values = c(\"#E69F00\", \"#56B4E9\", \"#009E73\", \"#CC79A7\"),\n                     labels = scales::parse_format()) +\n  scale_linetype_manual(values = c(\"solid\", \"dashed\", \"dotted\", \"dotdash\"),\n                        labels = scales::parse_format()) +\n  labs(x = \"X\", y = \"p(X)\", color = NULL, linetype = NULL)\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-logistic-regression_files/figure-html/logistic-shapes-figure-1.png){width=672}\n:::\n:::\n\n\nEvery curve stays strictly between the two dashed boundaries. Comparing the\nfirst two, doubling $\\beta_1$ makes the curve rise more steeply without moving\nwhere it crosses $0.5$; the third shows that a negative $\\beta_1$ reverses the\ndirection; the fourth shows that changing $\\beta_0$ shifts the curve\nhorizontally without changing its shape. $\\beta_1 = 0$ would give a horizontal\nline at $\\text{logistic}(\\beta_0)$: no relationship between $X$ and the\nprobability.\n\n### Odds and logit\n\nThe **odds** of an event with probability $p$ are\n\n$$\\text{odds} = \\frac{p}{1 - p},$$\n\nthe ratio of the probability the event happens to the probability it does not.\nOdds run over $(0, \\infty)$: $p = 0.5$ gives odds of $1$, and $p = 0.8$ gives\nodds of $4$, quoted as \"4 to 1.\"\n\nApply this to the logistic model. Since\n\n$$1 - p(X) = 1 - \\frac{e^{\\beta_0 + \\beta_1 X}}{1 + e^{\\beta_0 + \\beta_1 X}} = \\frac{1}{1 + e^{\\beta_0 + \\beta_1 X}},$$\n\nthe odds are\n\n$$\\frac{p(X)}{1 - p(X)} = e^{\\beta_0 + \\beta_1 X}.$$\n\nTaking logarithms,\n\n$$\\log\\left(\\frac{p(X)}{1 - p(X)}\\right) = \\beta_0 + \\beta_1 X.$$\n\nThe left side is the **logit**, or **log-odds**, of $p(X)$. It is the inverse\nof the logistic function, and it carries $(0,1)$ onto the whole real line.\n\nThis is the payoff of the logistic form. The model is *linear* — in the\nparameters and in the feature — once the response is expressed on the log-odds\nscale, so the entire linear-model vocabulary transfers over. Only the scale on\nwhich linearity holds has changed.\n\n### Interpreting coefficients\n\nSetting $X = 0$ in the log-odds form gives $\\beta_0$ as the log-odds of the\nevent when $X = 0$, so $e^{\\beta_0}$ is the odds and\n$\\text{logistic}(\\beta_0) = e^{\\beta_0}/(1 + e^{\\beta_0})$ the probability, at\n$X = 0$.\n\nNow increase the feature by one unit from an arbitrary $x$:\n\n$$\\log\\left(\\frac{p(x+1)}{1-p(x+1)}\\right) - \\log\\left(\\frac{p(x)}{1-p(x)}\\right) = \\left[\\beta_0 + \\beta_1 (x+1)\\right] - \\left[\\beta_0 + \\beta_1 x\\right] = \\beta_1.$$\n\nSo $\\beta_1$ is the change in the log-odds of the event per one-unit increase\nin $X$. Exponentiating turns the difference into a ratio,\n\n$$\\frac{p(x+1)/[1-p(x+1)]}{p(x)/[1-p(x)]} = e^{\\beta_1},$$\n\nso $e^{\\beta_1}$ is the **odds ratio**: the multiplicative factor by which the\nodds of the event change per one-unit increase in $X$. An odds ratio of $1$\n($\\beta_1 = 0$) means the odds do not change.\n\nWhat no coefficient reports is a constant change in the probability, because\nthere isn't one. Differentiating $p(x) = \\text{logistic}(\\beta_0 + \\beta_1 x)$,\n\n$$\\frac{d\\, p(x)}{dx} = \\beta_1\\, p(x)\\left[1 - p(x)\\right],$$\n\nwhich depends on $x$ through $p(x)$. It is largest in magnitude,\n$|\\beta_1|/4$, where $p(x) = 0.5$, and it vanishes as $p(x)$ approaches $0$ or\n$1$ — the flattening a bounded probability needs and a line could never\nprovide. A single number is no more \"the effect of $X$ on $p$\" here than a\nsingle coefficient was the effect of $X$ in a polynomial regression.\n\n### Maximum likelihood estimation\n\nUnder the model, the observations are independent Bernoulli trials whose\nsuccess probability depends on the feature,\n\n$$Y_i \\stackrel{ind}{\\sim} \\text{Bernoulli}\\left(p(x_i)\\right), \\qquad i = 1,\\ldots,n,$$\n\nso the probability mass function of a single observation is\n$P(Y_i = y_i|x_i) = p(x_i)^{y_i}\\left[1 - p(x_i)\\right]^{1-y_i}$ for\n$y_i \\in \\{0,1\\}$. The likelihood is the product over the sample,\n\n$$L(\\beta_0, \\beta_1) = \\prod_{i=1}^n p(x_i)^{y_i} \\left[1 - p(x_i)\\right]^{1 - y_i},$$\n\nwhere\n\n- $(x_i, y_i)$ is the observed feature and response for observation $i$, and\n- $p(x_i) = e^{\\beta_0 + \\beta_1 x_i}/(1 + e^{\\beta_0 + \\beta_1 x_i})$ depends\non the parameters being estimated.\n\nThere is no $\\sigma^2$ anywhere: once $p(x_i)$ is specified, the variance\n$p(x_i)[1-p(x_i)]$ is determined, so the model has exactly two unknown\nparameters.\n\nTake logarithms, and use the odds identity\n$p(x_i)/[1 - p(x_i)] = e^{\\beta_0 + \\beta_1 x_i}$ to simplify:\n\n$$\\begin{array}{rl}\n\\ell(\\beta_0, \\beta_1) &= \\displaystyle\\sum_{i=1}^n \\left\\{ y_i \\log p(x_i) + (1 - y_i)\\log\\left[1 - p(x_i)\\right] \\right\\} \\\\[2mm]\n&= \\displaystyle\\sum_{i=1}^n \\left\\{ y_i \\log\\left(\\frac{p(x_i)}{1 - p(x_i)}\\right) + \\log\\left[1 - p(x_i)\\right] \\right\\} \\\\[2mm]\n&= \\displaystyle\\sum_{i=1}^n \\left\\{ y_i (\\beta_0 + \\beta_1 x_i) - \\log\\left(1 + e^{\\beta_0 + \\beta_1 x_i}\\right) \\right\\}.\n\\end{array}$$\n\nThe **maximum likelihood estimators** $\\hat\\beta_0$ and $\\hat\\beta_1$ are the\nvalues maximizing $\\ell$. Differentiating,\n\n$$\\frac{\\partial \\ell}{\\partial \\beta_0} = \\sum_{i=1}^n \\left[y_i - p(x_i)\\right], \\qquad \\frac{\\partial \\ell}{\\partial \\beta_1} = \\sum_{i=1}^n x_i\\left[y_i - p(x_i)\\right],$$\n\nand setting both to zero gives the **score equations**\n\n$$\\sum_{i=1}^n \\left[y_i - p(x_i)\\right] = 0, \\qquad \\sum_{i=1}^n x_i\\left[y_i - p(x_i)\\right] = 0.$$\n\nThese say the residuals $y_i - p(x_i)$ sum to zero and are orthogonal to the\nfeature — the same two conditions the least squares normal equations impose.\nThe difference is what happens next. In least squares, $p(x_i)$ would be\nreplaced by $\\beta_0 + \\beta_1 x_i$, the equations would be *linear* in\n$\\beta_0$ and $\\beta_1$, and solving them would deliver the closed-form least\nsquares estimators of the simple linear regression lecture. Here $p(x_i)$ is\na nonlinear function of $\\beta_0$ and $\\beta_1$, so the equations are\nnonlinear and no rearrangement produces a closed form.\n\nThe estimates are therefore found numerically. The log-likelihood is strictly\nconcave whenever the feature is not constant, so when a maximum exists it is\nunique, and `glm()` locates it with an iterative algorithm.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nThe algorithm `glm()` uses is **iteratively reweighted least squares** (IRLS),\nwhich is Newton-Raphson on $\\ell$ in disguise: each iteration solves a weighted\nleast squares problem whose weights $p(x_i)[1 - p(x_i)]$ are recomputed from\nthe current estimate. Convergence usually takes a handful of iterations, which\nis why `glm()` returns nearly as fast as `lm()` despite having no formula to\nevaluate.\n:::\n\n::: {.callout-note collapse=\"true\"}\n### Log-likelihood and log loss\nDivide the negative log-likelihood by $n$:\n\n$$-\\frac{1}{n}\\ell(\\beta_0,\\beta_1) = -\\frac{1}{n}\\sum_{i=1}^n \\left\\{ y_i \\log p(x_i) + (1 - y_i)\\log\\left[1 - p(x_i)\\right]\\right\\}.$$\n\nThis is exactly the **log loss** defined in the classification lecture,\nspecialized to $C = 2$ classes and evaluated on the training data. Maximizing\nthe likelihood and minimizing training log loss are the same optimization\nproblem.\n:::\n\n### Fitting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm(default ~ balance, data = Default, family = \"binomial\")\n```\n:::\n\n\n`family = \"binomial\"` is what makes this logistic regression; without it,\n`glm()` fits a linear model. Two details govern what the coefficients mean:\n\n- With a factor response, R models the probability of the **second** level.\nHere `levels(Default$default)` is\nNo, Yes, so `glm()` models\n$P(\\texttt{default} = \\texttt{Yes})$, which is the event we chose.\n- The response may also be supplied as a $0/1$ numeric vector, with $1$ as the\nevent.\n\n::: {.callout-note collapse=\"true\"}\n### Other ways to write this model\n`glm()` only needs to know which outcome counts as $Y_i = 1$; it does not\ncare how that information is encoded.\n\n`default`'s second level is already `\"Yes\"`, since factor levels default to\nalphabetical order — but relying on alphabetical order to pick the event is\nfragile. `relevel()` sets the reference level explicitly, moving the named\nlevel to the front so every other level (here, the one level left) is the\nmodeled event regardless of how the factor happened to be built:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDefault$default <- relevel(Default$default, ref = \"No\") # make the reference explicit\n```\n:::\n\n\nThe response can also be recoded into a $0/1$ numeric column or a\n`TRUE`/`FALSE` logical column, or compared to the event of interest right\ninside the formula. All four of the calls below fit identically:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDefault$default01 <- as.numeric(Default$default == \"Yes\") # 0/1 numeric\nDefault$defaultTF <- Default$default == \"Yes\"              # TRUE/FALSE logical\n\nglm(default ~ balance, data = Default, family = \"binomial\")           # factor\nglm(default01 ~ balance, data = Default, family = \"binomial\")         # 0/1 numeric\nglm(defaultTF ~ balance, data = Default, family = \"binomial\")         # logical\nglm(default == \"Yes\" ~ balance, data = Default, family = \"binomial\")  # comparison\n```\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code for the table below\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_prep <- Default |>\n  mutate(default = relevel(default, ref = \"No\"),\n         default01 = as.numeric(default == \"Yes\"),\n         defaultTF = default == \"Yes\")\n\nm_factor     <- glm(default ~ balance, data = default_prep, family = \"binomial\")\nm_numeric    <- glm(default01 ~ balance, data = default_prep, family = \"binomial\")\nm_logical    <- glm(defaultTF ~ balance, data = default_prep, family = \"binomial\")\nm_comparison <- glm(default == \"Yes\" ~ balance, data = default_prep, family = \"binomial\")\n\nequivalent_forms_table <- rbind(\n  factor     = coef(m_factor),\n  \"0/1 numeric\" = coef(m_numeric),\n  \"TRUE/FALSE logical\" = coef(m_logical),\n  comparison = coef(m_comparison)\n)\n\nstopifnot(isTRUE(all.equal(coef(m_factor), coef(m_numeric))),\n          isTRUE(all.equal(coef(m_factor), coef(m_logical))),\n          isTRUE(all.equal(coef(m_factor), coef(m_comparison))))\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|                   | (Intercept)|  balance|\n|:------------------|-----------:|--------:|\n|factor             |   -10.65133| 0.005499|\n|0/1 numeric        |   -10.65133| 0.005499|\n|TRUE/FALSE logical |   -10.65133| 0.005499|\n|comparison         |   -10.65133| 0.005499|\n\n\n:::\n:::\n\n\nThe coefficients agree exactly. A logical vector is coerced to $0/1$ with\n`TRUE` as $1$, which is exactly what `default01` does by hand, and\n`default == \"Yes\"` builds that same logical vector inline without storing it\nas a column at all. Of the four, the comparison form is often the easiest to\nread: the formula states the event being modeled directly, rather than\nleaving it implicit in a factor's level order or a column name.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nThe comparison form generalizes beyond a two-category response. With a\nresponse that has more than two categories, `glm(y == \"target_category\" ~ x,\nfamily = \"binomial\")` fits a binary logistic regression for that one category\nagainst every other category combined, without constructing a separate $0/1$\nor logical column first.\n:::\n:::\n\nFitting it to the credit card data,\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_glm <- glm(default ~ balance, data = Default, family = \"binomial\")\ncoef(default_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)       balance \n-10.651330614   0.005498917 \n```\n\n\n:::\n:::\n\n\nPutting the fitted curve back on the data checks the shape against what the\nplot suggested. Alongside it, the observed proportion defaulting within\n\\$200-wide balance bins gives a model-free estimate of $p(X)$ to compare\nagainst; point size shows how many customers are in each bin, since the\nright-most bins hold very few.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\nbalance_grid <- tibble(balance = seq(0, max(Default$balance), length.out = 400))\nbalance_grid$p_hat <- predict(default_glm, newdata = balance_grid, type = \"response\")\n\nbinned <- Default |>\n  mutate(bin = cut(balance, breaks = seq(0, 2800, by = 200), include.lowest = TRUE)) |>\n  group_by(bin) |>\n  summarize(balance = mean(balance), p = mean(default01), n = n(), .groups = \"drop\")\n\nfit_plot <- ggplot(Default, aes(x = balance, y = default01)) +\n  geom_jitter(height = 0.03, width = 0, alpha = 0.08, size = 0.7) +\n  geom_point(data = binned, aes(y = p, size = n), shape = 1, color = \"#D55E00\") +\n  geom_line(data = balance_grid, aes(y = p_hat),\n            color = \"#0072B2\", linewidth = 1) +\n  scale_y_continuous(breaks = c(0, 0.5, 1)) +\n  scale_size_area(max_size = 5) +\n  labs(x = \"Credit card balance ($)\", y = \"P(default = Yes)\",\n       size = \"Customers\\nin bin\", title = \"ISLR2::Default\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-logistic-regression_files/figure-html/default-fit-figure-1.png){width=672}\n:::\n:::\n\n\nThe fitted curve stays inside $[0,1]$ over the full range of balances, sits\nnear zero out to roughly \\$1,000, and passes through the binned proportions\nwhere those bins contain enough customers to be worth reading.\n\n### Coefficient inference\n\nThe maximum likelihood estimators are approximately normal in large samples,\nwhich gives the test statistic\n\n$$z = \\frac{\\hat\\beta_j - \\beta_j^0}{\\text{SE}(\\hat\\beta_j)},$$\n\nwhere\n\n- $\\beta_j^0$ is the value of $\\beta_j$ under the null hypothesis, almost\nalways $0$, and\n- $\\text{SE}(\\hat\\beta_j)$ is the standard error of $\\hat\\beta_j$, computed by\n`glm()` from the curvature of the log-likelihood at its maximum.\n\nUnder $H_0: \\beta_j = \\beta_j^0$, $z$ is approximately standard normal. The\nstatistic is the same ratio as the t-statistic of the linear regression\nlectures; the reference distribution is normal rather than $t$ because no\nseparate error variance is estimated and because the normality is asymptotic\nrather than exact.\n\n`glm()` reports this test for every coefficient at once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(default_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = default ~ balance, family = \"binomial\", data = Default)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.065e+01  3.612e-01  -29.49   <2e-16 ***\nbalance      5.499e-03  2.204e-04   24.95   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2920.6  on 9999  degrees of freedom\nResidual deviance: 1596.5  on 9998  degrees of freedom\nAIC: 1600.5\n\nNumber of Fisher Scoring iterations: 8\n```\n\n\n:::\n:::\n\n\nThe coefficient table has the same layout as `lm()`'s, with one visible\nchange: `z value` and `Pr(>|z|)` in place of `t value` and `Pr(>|t|)`, for the\nreason just given.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nThe two deviance lines are the likelihood's answer to RSS and TSS. For a\nbinary response, the **residual deviance** is $-2\\ell$ evaluated at\n$\\hat\\beta_0, \\hat\\beta_1$, and the **null deviance** is $-2\\ell$ for the\nintercept-only model. Differences between deviances of nested models play the\nrole that differences in RSS play for an F-test, and `AIC` penalizes the\nresidual deviance by twice the number of estimated parameters.\n:::\n\nAn approximate $(1-\\alpha)100\\%$ confidence interval for $\\beta_j$ follows:\n\n$$\\hat\\beta_j \\pm z_{1-\\alpha/2}\\,\\text{SE}(\\hat\\beta_j),$$\n\nwith $z_{1-\\alpha/2}$ the $(1-\\alpha/2)$ quantile of the standard normal\ndistribution. In R, `confint.default()` on a fitted `glm` returns exactly this\ninterval for $\\beta_j$. Exponentiating both endpoints gives an interval for\nthe odds ratio $e^{\\beta_j}$, because $e^x$ is increasing and therefore\npreserves the order of the endpoints.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nPlain `confint()` on a `glm` object returns a different, *profile likelihood*\ninterval instead, built from the log-likelihood directly rather than from\n$\\hat\\beta_j \\pm z_{1-\\alpha/2}\\text{SE}(\\hat\\beta_j)$, so it will not match\n`confint.default()`'s numbers.\n:::\n\nFor `balance`,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_balance <- summary(default_glm)$coefficients[\"balance\", \"z value\"]\nci_beta1  <- confint.default(default_glm)[\"balance\", ]\n\nround(z_balance, 2)  # z-statistic for beta_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.95\n```\n\n\n:::\n\n```{.r .cell-code}\nround(ci_beta1,  5)  # 95% CI for beta_1, per dollar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  2.5 %  97.5 % \n0.00507 0.00593 \n```\n\n\n:::\n:::\n\n\n$z = 24.95$ is far beyond any conventional critical value,\nso the data are overwhelmingly inconsistent with $\\beta_1 = 0$. The confidence\ninterval for $\\beta_1$ runs from $0.005067$ to\n$0.005931$ log-odds per dollar, and exponentiating both\nendpoints gives an interval for the odds ratio per dollar, entirely above $1$,\nthe odds ratio corresponding to no association.\n\n### Prediction\n\nThe fitted model returns a probability at any feature value,\n\n$$\\hat p(x) = \\frac{e^{\\hat\\beta_0 + \\hat\\beta_1 x}}{1 + e^{\\hat\\beta_0 + \\hat\\beta_1 x}}.$$\n\nIn R, `predict()` on a `glm` object returns the linear predictor\n$\\hat\\beta_0 + \\hat\\beta_1 x$ by default; `type = \"response\"` applies\n$\\text{logistic}(\\cdot)$ and returns $\\hat p(x)$.\n\nEvaluating $\\hat p(x)$ at a few balances spread across the range of the data\nshows how the three scales — log-odds, odds, and probability — move against\none another:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the table below\n\n::: {.cell}\n\n```{.r .cell-code}\npred_balances <- c(500, 1000, 1500, 2000, 2500)\n\npred_data <- tibble(balance = pred_balances) |>\n  mutate(log_odds = predict(default_glm, newdata = tibble(balance = pred_balances)),\n         odds     = exp(log_odds),\n         p_hat    = predict(default_glm, newdata = tibble(balance = pred_balances),\n                            type = \"response\"))\n\npred_table <- pred_data |>\n  mutate(log_odds = sprintf(\"%.2f\", log_odds),\n         odds     = formatC(odds,  format = \"g\", digits = 3),\n         p_hat    = formatC(p_hat, format = \"g\", digits = 3)) |>\n  knitr::kable(col.names = c(\"Balance ($)\", \"Log-odds\", \"Odds\",\n                             \"Estimated P(default)\"),\n               align = \"cccc\")\n\np_at <- function(x) pred_data$p_hat[pred_data$balance == x]\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Balance ($) | Log-odds |  Odds   | Estimated P(default) |\n|:-----------:|:--------:|:-------:|:--------------------:|\n|     500     |  -7.90   | 0.00037 |       0.00037        |\n|    1000     |  -5.15   | 0.00579 |       0.00575        |\n|    1500     |  -2.40   | 0.0905  |        0.0829        |\n|    2000     |   0.35   |  1.41   |        0.586         |\n|    2500     |   3.10   |  22.1   |        0.957         |\n\n\n:::\n:::\n\n\nThe log-odds column increases by the same amount for every \\$500 step, by\nconstruction, and the odds column is multiplied by the same factor. The\nprobability column does neither: the step from \\$1,500 to \\$2,000 raises the\nestimated probability by 0.503, while the\nidentical \\$500 step from \\$500 to \\$1,000 raises it by only\n0.005, because down there the curve is still\npressed against $0$.\n\n## Credit card default probability\n\nPutting the pieces together for `balance` and `default`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb         <- coef(default_glm)\nor_dollar <- unname(exp(b[\"balance\"]))\nor_100    <- unname(exp(100 * b[\"balance\"]))\nci_or_100 <- exp(100 * ci_beta1)\n\nround(c(\"odds ratio per $1\" = or_dollar, \"odds ratio per $100\" = or_100), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  odds ratio per $1 odds ratio per $100 \n             1.0055              1.7331 \n```\n\n\n:::\n:::\n\n\nThe estimated log-odds of default are\n\n$$\\log\\left(\\frac{\\hat p(X)}{1 - \\hat p(X)}\\right) = -10.65 + 0.005499 \\times \\texttt{balance}.$$\n\nThe intercept $\\hat\\beta_0 = -10.65$ is the estimated log-odds of\ndefault for a customer carrying no balance, which corresponds to estimated odds\nof $e^{-10.65} = 0.0000237$\nand an estimated probability of\n$0.0000237$ — odds and\nprobability agree to three significant digits here because $p/(1-p) \\approx p$ whenever $p$ is\nsmall. Unlike many intercepts, this one describes customers who actually exist:\n499 customers in this sample carry a zero balance,\nand 0 of them defaulted.\n\nThe slope $\\hat\\beta_1 = 0.005499$ is positive, so every additional\ndollar of balance raises the log-odds of default by\n$0.005499$ — equivalently, multiplies the odds of default by\n$e^{\\hat\\beta_1} = 1.00551$.\n\nA dollar is too small a unit to read comfortably, and nothing forces us to use\nit: `balance` can be rescaled by any positive constant without changing the\nmodel, since $\\beta_1 X = (100\\beta_1)(X/100)$ — measuring balance in hundreds\nof dollars instead of dollars multiplies the slope by $100$ and leaves the\nfitted probabilities untouched. Scaling up this way, an additional \\$100 of\nbalance multiplies the odds of default by\n\n$$e^{100\\hat\\beta_1} = 1.73,$$\n\na 73% increase in the **odds** of default per \\$100.\nIt is not a 73% increase in the probability of\ndefault; the change in probability depends on the balance you started from.\n\\$100 is simply the increment a person managing a credit line can picture\nwithout doing arithmetic first.\n\nThe same rescaling applies to the confidence interval: from the coefficient\ninference above, multiplying the endpoints of the interval for $\\beta_1$ by\n$100$ and exponentiating gives $(1.66,\n1.81)$ on the per-\\$100 odds-ratio scale, every value of\nit well above $1$.\n\n## Conclusion\n\nCredit card balance is strongly associated with default. Each additional \\$100\nof balance multiplies the estimated odds of default by\n1.73 (95% CI 1.66 to\n1.81), and the estimated probability of default rises\nfrom 0.04% at a \\$500 balance to\n59% at \\$2,000.\n\nThe logistic model delivered this while a linear regression could not, because\nit constrains $p(X)$ to $[0,1]$, lets the effect of a dollar flatten as the\nprobability approaches either boundary, and is estimated under a Bernoulli\nlikelihood that matches how a binary response actually varies.\n\nWhat it has not done is use the rest of the data. `ISLR2::Default` also records\nwhether each customer is a student and what their income is, and answering\n\"does balance matter *after accounting for* those?\" needs more than one\nfeature — multiple logistic regression.\n",
    "supporting": [
      "10-logistic-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}