project:
  type: book
  output-dir: docs

book:
  title: "DS 3030 - Concepts and Applications of Machine Learning"
  site-url: "https://jarad.github.io/DS3030/"
  repo-url: "https://github.com/jarad/DS3030"
  chapters:
    - index.qmd
    - part: "Statistical Learning"
      chapters:
      - learning/02-1-overview.qmd
      - learning/02-2-regression.qmd
      - learning/02-3-classification.qmd
    - part: "Regression"
      chapters:
      - regression/03-1-slr.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
