project:
  type: book
  output-dir: docs

book:
  title: "DS 3030 - Concepts and Applications of Machine Learning"
  site-url: "https://jarad.github.io/DS3030/"
  repo-url: "https://github.com/jarad/DS3030"
  chapters:
    - index.qmd
    - part: "Statistical Learning"
      chapters:
      - 02-learning/10-overview.qmd
      - 02-learning/20-regression.qmd
      - 02-learning/30-classification.qmd
    - part: "Regression"
      chapters:
      - 03-regression/10-slr.qmd
      - 03-regression/15-capm.qmd
      - 03-regression/20-mlr.qmd
      - 03-regression/30-feature-engineering.qmd
      - 03-regression/40-flexibility.qmd
    - part: "Classification"
      chapters:
      - 04-classification/10-logistic-regression.qmd
      - 04-classification/20-multiple-logistic-regression.qmd
      - 04-classification/30-flexible-logistic-regression.qmd
      - 04-classification/40-problems-in-logistic-regression.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
