{
  "hash": "37eaf23fcb3a0327cd2288ed59bad488",
  "result": {
    "engine": "knitr",
    "markdown": "# Cross-Validation\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **explain** why training error cannot choose a model's flexibility, and\n**identify** the two weaknesses of the validation set approach: its estimate\nvaries from one random split to the next, and it overestimates the test error\nof a model fit to all $n$ observations,\n- **define** the leave-one-out and $k$-fold cross-validation estimates of test\nMSE and test error rate, and **implement** each as a loop that fits on all but\none fold and predicts the held-out fold,\n- **derive** the least squares shortcut\n$\\text{CV}_{(n)} = \\frac{1}{n}\\sum_{i=1}^n\\left[\\left(y_i - \\hat y_i\\right)/\\left(1 - h_i\\right)\\right]^2$\nand **interpret** the role of the leverage $h_i$ in it,\n- **compare** the validation set approach, leave-one-out, and $k$-fold\ncross-validation by the bias and variance of their test-error estimates and by\ncomputation, and **justify** the usual choice $k = 5$ or $10$,\n- **use** cross-validation to choose a flexibility setting, such as a\npolynomial degree or the number of neighbors $K$ in KNN, and\n- **identify** the data-dependent steps of a fit (feature screening,\nstandardization, tuning) that must be repeated inside every fold, and\n**explain** why performing them once on all the data makes the\ncross-validation estimate optimistic.\n:::\n\n## Test error estimation\n\n### Horsepower and fuel efficiency\n\n**Question.** How flexible should a regression of a car's fuel efficiency on\nits engine horsepower be?\n\n**Data.** `ISLR2::Auto` records 392 cars. The response is `mpg`,\nmiles per gallon, and the explanatory variable is `horsepower`. The figure\nplots one against the other.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nauto_base <- ggplot(Auto, aes(x = horsepower, y = mpg)) +\n  geom_point(alpha = 0.4, size = 1) +\n  coord_cartesian(ylim = range(Auto$mpg)) +\n  labs(x = \"Horsepower\", y = \"Miles per gallon\", title = \"ISLR2::Auto\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/auto-data-figure-1.png){width=672}\n:::\n:::\n\n\nFuel efficiency falls as horsepower rises, steeply at first and then more\nslowly.\n\n**Model.** To follow that curvature, the candidate models are polynomial\nregressions of degree $d$,\n\n$$\\texttt{mpg}_i = \\beta_0 + \\beta_1\\,\\texttt{horsepower}_i + \\beta_2\\,\\texttt{horsepower}_i^2 + \\cdots + \\beta_d\\,\\texttt{horsepower}_i^d + \\epsilon_i, \\qquad \\epsilon_i \\stackrel{ind}{\\sim} N\\left(0, \\sigma^2\\right),$$\n\nwhere\n\n- $\\texttt{mpg}_i$ and $\\texttt{horsepower}_i$ are the fuel efficiency and\nhorsepower of car $i = 1, \\ldots, n$,\n- $d$ is the **degree** of the polynomial, the flexibility setting to be\nchosen,\n- $\\beta_0, \\ldots, \\beta_d$ are the coefficients and $\\epsilon_i$ the error,\nwith variance $\\sigma^2$, and\n- the features are the $d$ powers of horsepower, so row $i$ of the model\nmatrix $\\mathbf{X}$ is\n$x_i = \\left(1, \\texttt{horsepower}_i, \\ldots, \\texttt{horsepower}_i^d\\right)$.\n\nAs in the feature engineering lecture, `poly(horsepower, d)` fits the same\nmodel with an orthogonal basis of the same column space, so its fitted values\nare identical.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndegrees <- 1:10\nshow_degrees <- c(1, 2, 10)\ndegree_labels <- paste(\"Degree\", show_degrees)\ndegree_colors <- setNames(c(\"#0072B2\", \"#D55E00\", \"#009E73\"), degree_labels)\ndegree_linetypes <- setNames(c(\"solid\", \"dashed\", \"dotdash\"), degree_labels)\n\nhp_grid <- tibble(horsepower = seq(min(Auto$horsepower), max(Auto$horsepower),\n                                   length.out = 400))\ndegree_curves <- map(show_degrees, \\(d) {\n  fit <- lm(mpg ~ poly(horsepower, d), data = Auto)\n  mutate(hp_grid, degree = paste(\"Degree\", d), mpg = predict(fit, hp_grid))\n}) |>\n  list_rbind() |>\n  mutate(degree = factor(degree, levels = degree_labels))\n\nadd_curves <- function(through) {\n  auto_base +\n    geom_line(data = filter(degree_curves, as.integer(degree) <= through),\n              aes(color = degree, linetype = degree), linewidth = 1) +\n    scale_color_manual(values = degree_colors) +\n    scale_linetype_manual(values = degree_linetypes) +\n    labs(color = \"Polynomial\", linetype = \"Polynomial\")\n}\nauto_curve_plots <- map(seq_along(show_degrees), add_curves)\n```\n:::\n\n:::\n\nThe tabs add least squares fits of degree 1, 2, and 10 to the\nplot above.\n\n::: {.panel-tabset}\n#### Degree 1\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/auto-degree1-figure-1.png){width=672}\n:::\n:::\n\n\n#### + Degree 2\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/auto-degree2-figure-1.png){width=672}\n:::\n:::\n\n\n#### + Degree 10\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/auto-degree10-figure-1.png){width=672}\n:::\n:::\n\n:::\n\nThe straight line misses the curvature: it underpredicts at both ends\nand overpredicts in the middle. The quadratic follows the curve. The degree-10\npolynomial follows it too, with extra wiggles at both ends of the range of\nhorsepower, where cars are few.\n\n### Training MSE\n\nThe function below fits a degree-$d$ polynomial to a data set; applied to all\n392 cars it gives the training MSE of each degree.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_degree <- function(d, data) lm(mpg ~ poly(horsepower, d), data = data)\ntrain_mse <- map_dbl(degrees, \\(d) mean(residuals(fit_degree(d, Auto))^2))\n```\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_mse_plot <- ggplot(tibble(degree = degrees, mse = train_mse),\n                         aes(x = degree, y = mse)) +\n  geom_line() +\n  geom_point() +\n  scale_x_continuous(breaks = degrees) +\n  labs(x = \"Polynomial degree d\", y = \"Training MSE\", title = \"ISLR2::Auto\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/train-mse-figure-1.png){width=576}\n:::\n:::\n\n\nThe training MSE falls from 23.94 at degree 1 to\n18.98 at degree 2 and keeps falling, to\n18.01 at degree 10. It cannot do otherwise: the degree-$d$\nmodel is the degree-$(d+1)$ model with $\\beta_{d+1} = 0$, so least squares\nover the larger model can only match or lower the residual sum of squares.\nTraining error rewards flexibility whether or not the flexibility captures\nanything that will appear in new data, so it cannot choose $d$.\n\n### Held-out data\n\nThe regression lecture defined the test MSE as the average squared error on\nobservations that were not used to estimate $\\hat f$. With a large, separate\ntest set, choosing $d$ would be easy: fit each degree to the training data and\nkeep the degree with the smallest test MSE. A separate test set is rarely\navailable. Collecting one costs as much as collecting the training data, and\nsetting aside part of the data already in hand leaves less to fit with.\n\n**Resampling methods** estimate test error from the training data alone, by\nfitting the model to part of the data and measuring its error on the part\nleft out. This lecture develops three, in increasing order of reuse: the\nvalidation set approach, leave-one-out cross-validation, and $k$-fold\ncross-validation.\n\n## Validation set approach\n\nThe figure below shows the cars split at random into two halves of\n196, a training set (blue circles) and a validation set (orange\ntriangles).\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nn_auto <- nrow(Auto)\nn_splits <- 100\nsplits <- map(seq_len(n_splits), \\(r) sample(n_auto, n_auto / 2))\none_split <- splits[[1]]\n\nset_colors <- c(Training = \"#0072B2\", Validation = \"#E69F00\")\nsplit_plot <- Auto |>\n  mutate(set = if_else(row_number() %in% one_split, \"Training\", \"Validation\")) |>\n  ggplot(aes(x = horsepower, y = mpg, color = set, shape = set)) +\n  geom_point(alpha = 0.7, size = 1.3) +\n  scale_color_manual(values = set_colors) +\n  scale_shape_manual(values = c(Training = 16, Validation = 17)) +\n  labs(x = \"Horsepower\", y = \"Miles per gallon\", color = NULL, shape = NULL,\n       title = \"ISLR2::Auto, one random split\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/validation-split-figure-1.png){width=672}\n:::\n:::\n\n\nBoth halves cover the range of horsepower, and either half shows the same\ncurved decline as the full data.\n\n### Algorithm\n\nThe **validation set approach** estimates test MSE in three steps:\n\n1. Split the $n$ observations at random into a training set and a validation\n(hold-out) set $\\mathcal{V}$.\n2. Fit the model to the training set.\n3. Predict every observation in the validation set and average the squared\nerrors,\n\n$$\\text{MSE}_{\\mathcal{V}} = \\frac{1}{n_{\\mathcal{V}}}\\sum_{i \\in \\mathcal{V}}\\left[y_i - \\hat f(x_i)\\right]^2,$$\n\nwhere\n\n- $\\mathcal{V}$ is the set of indices of the validation observations and\n$n_{\\mathcal{V}}$ their number, and\n- $\\hat f$ is the model fit to the training set only.\n\nEvery validation observation is new to $\\hat f$, so $\\text{MSE}_{\\mathcal{V}}$\nis a test MSE in the sense of the regression lecture. In R, with `train_id`\nthe row numbers of the training set:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalidation_mse <- function(d, train_id, data = Auto) {\n  fit <- fit_degree(d, data[train_id, ])\n  valid <- data[-train_id, ]\n  mean((valid$mpg - predict(fit, valid))^2)\n}\none_split_mse <- map_dbl(degrees, validation_mse, train_id = one_split)\n```\n:::\n\n\n### Split variability\n\nThe split above is one of 100 random splits into halves. The first\ntab plots its validation MSE against degree, the second adds the curves of all\n100 splits (grey, with the first in black), and the third counts the\ndegree with the smallest validation MSE in each split.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nval_curves <- expand_grid(split = seq_len(n_splits), degree = degrees) |>\n  mutate(mse = map2_dbl(degree, split, \\(d, r) validation_mse(d, splits[[r]])))\nval_best <- val_curves |>\n  group_by(split) |>\n  slice_min(mse, n = 1, with_ties = FALSE) |>\n  ungroup()\nval_choice_counts <- count(val_best, degree)\nval_mse_d2 <- filter(val_curves, degree == 2)$mse\n# Within each split, the spread of the estimates over degrees 2 through 10.\nwithin_split_range <- val_curves |>\n  filter(degree >= 2) |>\n  group_by(split) |>\n  summarize(range = max(mse) - min(mse), .groups = \"drop\")\n\nmse_limits <- c(14, 30)\nn_off_plot <- n_distinct(filter(val_curves, mse > mse_limits[2])$split)\ndegree_axis <- list(scale_x_continuous(breaks = degrees),\n                    coord_cartesian(ylim = mse_limits))\none_split_plot <- ggplot(tibble(degree = degrees, mse = one_split_mse),\n                         aes(x = degree, y = mse)) +\n  geom_line() +\n  geom_point() +\n  degree_axis +\n  labs(x = \"Polynomial degree d\", y = \"Validation MSE\",\n       title = \"One random split into halves\")\nall_splits_plot <- ggplot(val_curves, aes(x = degree, y = mse, group = split)) +\n  geom_line(color = \"grey70\", linewidth = 0.3) +\n  geom_line(data = filter(val_curves, split == 1), color = \"black\") +\n  geom_point(data = filter(val_curves, split == 1), color = \"black\") +\n  degree_axis +\n  labs(x = \"Polynomial degree d\", y = \"Validation MSE\",\n       title = paste(n_splits, \"random splits into halves\"))\nchoice_plot <- ggplot(val_best, aes(x = factor(degree, levels = degrees))) +\n  geom_bar() +\n  scale_x_discrete(drop = FALSE) +\n  labs(x = \"Degree with the smallest validation MSE\", y = \"Number of splits\",\n       title = paste(n_splits, \"random splits into halves\"))\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### One split\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/one-split-figure-1.png){width=576}\n:::\n:::\n\n\n#### 100 splits\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/all-splits-figure-1.png){width=576}\n:::\n:::\n\n\n#### Chosen degree\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/val-choice-figure-1.png){width=576}\n:::\n:::\n\n:::\n\nEvery curve drops sharply from degree 1 to degree 2, so every split agrees\nthat a quadratic beats a line. Beyond that the splits disagree. The validation\nMSE of the quadratic ranges from 14.50 to\n24.71 across splits, while within a split the estimates\nfor degrees 2 through 10 span a median of\n1.87. Of the 100 curves,\n2 leave the top of the plot at high degree, where a polynomial\nfit to half the cars extrapolates badly to a validation car outside their\nrange of horsepower. The degree with the smallest validation MSE is\n2, 3, 4, 5, 6, 7, 8, 9, and 10 in different splits;\nthe most common choice, degree\n7, wins only\n36 of the 100 splits.\n\nThis is the first weakness of the validation set approach: the estimate, and\nthe model it selects, depend on which observations happen to land in which\nhalf.\n\n### Smaller training sets\n\nThe second weakness is that each model is fit to only part of the data.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_sizes <- c(60, 80, 120, 160, n_auto / 2, 240, 280, 320, 360)\nlearning_degrees <- c(2, 7)\nn_learning_reps <- 400\nlearning <- expand_grid(m = train_sizes, degree = learning_degrees,\n                        rep = seq_len(n_learning_reps)) |>\n  mutate(mse = map2_dbl(m, degree, \\(m, d) validation_mse(d, sample(n_auto, m))))\nlearning_summary <- learning |>\n  group_by(m, degree) |>\n  summarize(median_mse = median(mse), mean_mse = mean(mse), .groups = \"drop\") |>\n  mutate(degree = factor(paste(\"Degree\", degree),\n                         levels = paste(\"Degree\", learning_degrees)))\nlearning_of <- function(m_value, d, col = \"median_mse\") {\n  learning_summary[[col]][learning_summary$m == m_value &\n                            learning_summary$degree == paste(\"Degree\", d)]\n}\n\nlearning_plot <- ggplot(learning_summary,\n                        aes(x = m, y = median_mse, color = degree,\n                            linetype = degree, shape = degree)) +\n  geom_vline(xintercept = n_auto / 2, color = \"grey60\") +\n  geom_line() +\n  geom_point(size = 2) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  labs(x = \"Training set size m (vertical line: half of the cars)\",\n       y = \"Median validation MSE\", color = NULL, linetype = NULL,\n       shape = NULL, title = paste(n_learning_reps, \"random splits at each m\"))\n```\n:::\n\n:::\n\nTo see what that costs, the cars were split at random into a training set of\n$m$ cars and a validation set of the remaining $n - m$, for $m$ from\n60 to 360, 400 times at\neach $m$. Because the validation cars are new to each fit, the typical\nvalidation MSE at a given $m$ estimates the test MSE of a model fit to $m$\ncars. The figure plots the median over splits for degrees\n2 and 7.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/learning-curve-figure-1.png){width=672}\n:::\n:::\n\n\nTest MSE generally falls as the training set grows, and it falls more steeply\nfor the more flexible model. The degree-7 polynomial has a median validation MSE of\n24.07 when fit to 60\ncars, against 19.39 when fit to\n196; the quadratic goes from\n20.05 to\n19.23. (The median is plotted because the mean\nis dominated by a few catastrophic extrapolations: at\n$m = 60$ the mean validation MSE of degree 7 is\n5,778.) The model that will be used is\nfit to all 392 cars, so a validation set estimate computed from fits to\nhalf of them estimates the error of a worse model. The validation set\napproach tends to **overestimate** the test error of the final fit, and more\nso for flexible models and small $n$.\n\n## Leave-one-out cross-validation\n\nThe validation set approach leaves out half the data. Leave-one-out\ncross-validation leaves out one observation at a time. The figure below holds\nout the car with the largest horsepower, a\nPontiac Grand Prix with\n230 horsepower (black triangle), and draws the fit to\nall 392 cars (dashed) and the fit to the other 391\n(solid), for degree 2 in the first tab and degree 10 in the second.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ni_out <- which.max(Auto$horsepower)\nheld_out_summary <- map(c(2, 10), \\(d) {\n  fit_all <- fit_degree(d, Auto)\n  fit_without <- fit_degree(d, Auto[-i_out, ])\n  tibble(degree = d,\n         residual = Auto$mpg[i_out] - fitted(fit_all)[[i_out]],\n         loo_error = Auto$mpg[i_out] - predict(fit_without, Auto[i_out, ]),\n         leverage = hatvalues(fit_all)[[i_out]])\n}) |>\n  list_rbind()\nheld_of <- function(d, col) held_out_summary[[col]][held_out_summary$degree == d]\n\nfit_labels <- c(\"All cars\", \"Car held out\")\nheld_out_plot <- function(d) {\n  curves <- bind_rows(\n    mutate(hp_grid, fit = fit_labels[1],\n           mpg = predict(fit_degree(d, Auto), hp_grid)),\n    mutate(hp_grid, fit = fit_labels[2],\n           mpg = predict(fit_degree(d, Auto[-i_out, ]), hp_grid))) |>\n    mutate(fit = factor(fit, levels = fit_labels))\n  ggplot(Auto, aes(x = horsepower, y = mpg)) +\n    geom_point(data = Auto[-i_out, ], color = \"grey60\", alpha = 0.5, size = 1) +\n    geom_line(data = curves, aes(color = fit, linetype = fit), linewidth = 0.9) +\n    geom_point(data = Auto[i_out, ], shape = 17, size = 3.5) +\n    scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n    scale_linetype_manual(values = c(\"dashed\", \"solid\")) +\n    coord_cartesian(ylim = range(Auto$mpg)) +\n    labs(x = \"Horsepower\", y = \"Miles per gallon\", color = \"Fit to\",\n         linetype = \"Fit to\", title = paste(\"Degree\", d))\n}\nheld_out_plots <- map(c(2, 10), held_out_plot)\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Degree 2\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/held-out-d2-figure-1.png){width=672}\n:::\n:::\n\n\n#### Degree 10\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/held-out-d10-figure-1.png){width=672}\n:::\n:::\n\n:::\n\nFor the quadratic the two fits nearly coincide, and the held-out car is\npredicted about as well without it as with it. For degree 10 the fit to all\ncars bends to pass near the held-out car, and without it the curve swings far\nbelow. The squared error of the held-out prediction measures how well the\nmodel predicts a car it has not seen, which the residual from the fit to all\ncars does not.\n\n### LOOCV estimate\n\n**Leave-one-out cross-validation** (LOOCV) repeats that for every\nobservation:\n\n$$\\text{CV}_{(n)} = \\frac{1}{n}\\sum_{i=1}^n\\left[y_i - \\hat f^{(-i)}(x_i)\\right]^2,$$\n\nwhere\n\n- $\\hat f^{(-i)}$ is the model fit to the $n - 1$ observations other than\nobservation $i$, and\n- $\\hat f^{(-i)}(x_i)$ is its prediction for the held-out observation.\n\nEach fit uses $n - 1$ observations, nearly all of the data, and there is no\nrandom split: every observation is held out exactly once. Written as a loop,\nLOOCV costs $n$ fits per model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloocv_mse <- function(d, data = Auto) {\n  sq_error <- numeric(nrow(data))\n  for (i in seq_len(nrow(data))) {\n    fit <- fit_degree(d, data[-i, ])\n    sq_error[i] <- (data$mpg[i] - predict(fit, data[i, ]))^2\n  }\n  mean(sq_error)\n}\nloocv_loop <- map_dbl(degrees, loocv_mse)\n```\n:::\n\n\n### Least squares shortcut\n\nFor a model fit by least squares, the $n$ fits are unnecessary. Write the\nleast squares fit to all $n$ observations as $\\hat y = \\mathbf{H}y$, with\n\n$$\\mathbf{H} = \\mathbf{X}\\left(\\mathbf{X}^\\top\\mathbf{X}\\right)^{-1}\\mathbf{X}^\\top, \\qquad \\hat y_i = \\sum_{j=1}^n h_{ij}\\,y_j, \\qquad h_i = h_{ii} = x_i\\left(\\mathbf{X}^\\top\\mathbf{X}\\right)^{-1}x_i^\\top,$$\n\nwhere\n\n- $\\mathbf{H}$ is the hat matrix and $h_{ij}$ its $(i, j)$ entry,\n- $\\hat y_i = x_i\\hat\\beta$ is the fitted value of observation $i$ from the fit\nto all $n$ observations, and\n- $h_i$ is the **leverage** of observation $i$, as in the flexibility lecture,\nwith $0 \\le h_i \\le 1$.\n\nLet $\\hat\\beta^{(-i)}$ be the least squares estimate without observation $i$,\nso $\\hat f^{(-i)}(x_i) = x_i\\hat\\beta^{(-i)}$, and assume $\\mathbf{X}$ without\nrow $i$ still has full column rank so that $\\hat\\beta^{(-i)}$ is unique.\n\n**Step 1: a full-data fit that reproduces $\\hat\\beta^{(-i)}$.** Define a\nresponse vector $z$ equal to $y$ except in entry $i$, which is replaced by the\nheld-out prediction: $z_j = y_j$ for $j \\ne i$ and\n$z_i = x_i\\hat\\beta^{(-i)}$. For any $\\beta$,\n\n$$\\sum_{j=1}^n\\left(z_j - x_j\\beta\\right)^2 = \\sum_{j \\ne i}\\left(y_j - x_j\\beta\\right)^2 + \\left(x_i\\hat\\beta^{(-i)} - x_i\\beta\\right)^2.$$\n\nThe first sum is minimized at $\\beta = \\hat\\beta^{(-i)}$, by definition, and\nthe second term is zero there, its smallest possible value. So\n$\\hat\\beta^{(-i)}$ minimizes the left side: it is the least squares estimate\nfor response $z$ with all $n$ rows,\n$\\hat\\beta^{(-i)} = \\left(\\mathbf{X}^\\top\\mathbf{X}\\right)^{-1}\\mathbf{X}^\\top z$.\n\n**Step 2: apply the hat matrix.** Multiplying by $x_i$,\n$x_i\\hat\\beta^{(-i)}$ is entry $i$ of $\\mathbf{H}z$:\n\n$$\\hat f^{(-i)}(x_i) = \\sum_{j=1}^n h_{ij}\\,z_j = \\sum_{j=1}^n h_{ij}\\,y_j - h_i\\,y_i + h_i\\,\\hat f^{(-i)}(x_i) = \\hat y_i - h_i\\,y_i + h_i\\,\\hat f^{(-i)}(x_i).$$\n\n**Step 3: solve.** Collecting the $\\hat f^{(-i)}(x_i)$ terms,\n$\\left(1 - h_i\\right)\\hat f^{(-i)}(x_i) = \\hat y_i - h_i y_i$. The\nfull-rank assumption on $\\mathbf{X}$ without row $i$ makes $h_i < 1$, so\ndividing by $1 - h_i$,\n\n$$y_i - \\hat f^{(-i)}(x_i) = \\frac{\\left(1 - h_i\\right)y_i - \\hat y_i + h_i y_i}{1 - h_i} = \\frac{y_i - \\hat y_i}{1 - h_i}.$$\n\nSquaring and averaging over $i$,\n\n$$\\text{CV}_{(n)} = \\frac{1}{n}\\sum_{i=1}^n\\left(\\frac{y_i - \\hat y_i}{1 - h_i}\\right)^2.$$\n\nThe held-out error is the ordinary residual inflated by $1/(1 - h_i)$. With\n$h_i = 0$ for every $i$ this would be the training MSE. The inflation is\nsmall for a typical observation and large for a high-leverage one, whose\nfitted value the full-data fit pulls toward its own response. The formula\nneeds one fit, its residuals, and `hatvalues()`. It holds for any model fit\nby least squares on fixed features: polynomials, interactions, step functions\nwith fixed cut points. It does not hold for logistic regression or KNN, where\nLOOCV takes $n$ fits.\n\nFor the held-out car in the figure, the quadratic gives leverage\n$h_i = 0.0936$, residual\n$y_i - \\hat y_i = 1.228$, and signed held-out\nerror $y_i - \\hat f^{(-i)}(x_i) = 1.35$; the\ndegree-10 polynomial gives leverage\n$h_i = 0.9018$, residual\n1.168, and signed held-out error\n11.90, which equals\n$1.168/(1 - 0.9018)$\nup to rounding.\n\nThe shortcut for every degree:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloocv_shortcut <- function(d, data = Auto) {\n  fit <- fit_degree(d, data)\n  mean(((data$mpg - fitted(fit)) / (1 - hatvalues(fit)))^2)\n}\nloocv_fast <- map_dbl(degrees, loocv_shortcut)\n```\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nloocv_table <- tibble(degree = degrees,\n                      loop = fmt(loocv_loop, 4),\n                      shortcut = fmt(loocv_fast, 4)) |>\n  knitr::kable(col.names = c(\"Degree $d$\",\n                             paste0(\"Loop (\", n_auto, \" fits)\"),\n                             \"Shortcut (1 fit)\"),\n               align = \"ccc\")\nmax_loocv_diff <- max(abs(loocv_loop - loocv_fast))\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Degree $d$ | Loop (392 fits) | Shortcut (1 fit) |\n|:----------:|:---------------:|:----------------:|\n|     1      |     24.2315     |     24.2315      |\n|     2      |     19.2482     |     19.2482      |\n|     3      |     19.3350     |     19.3350      |\n|     4      |     19.4244     |     19.4244      |\n|     5      |     19.0332     |     19.0332      |\n|     6      |     18.9786     |     18.9786      |\n|     7      |     18.8330     |     18.8330      |\n|     8      |     18.9612     |     18.9612      |\n|     9      |     19.0686     |     19.0686      |\n|     10     |     19.4909     |     19.4909      |\n\n\n:::\n:::\n\n\nThe two columns agree to the digits shown; the largest absolute difference\nis $3.0 \\times 10^{-12}$, rounding error. The loop needed\n3,920 least squares fits and\nthe shortcut 10.\n\n### Degree selection\n\nThe figure below plots the LOOCV estimate and the training MSE against\ndegree.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nloocv_best <- degrees[which.min(loocv_fast)]\nerror_labels <- c(\"Training MSE\", \"LOOCV\")\nloocv_curve_data <- bind_rows(\n  tibble(degree = degrees, mse = train_mse, estimate = error_labels[1]),\n  tibble(degree = degrees, mse = loocv_fast, estimate = error_labels[2])) |>\n  mutate(estimate = factor(estimate, levels = error_labels))\nloocv_curve_plot <- ggplot(loocv_curve_data,\n                           aes(x = degree, y = mse, color = estimate,\n                               linetype = estimate, shape = estimate)) +\n  geom_line() +\n  geom_point(size = 2) +\n  scale_x_continuous(breaks = degrees) +\n  scale_color_manual(values = c(\"grey40\", \"#D55E00\")) +\n  labs(x = \"Polynomial degree d\", y = \"MSE\", color = NULL, linetype = NULL,\n       shape = NULL, title = \"ISLR2::Auto\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/loocv-curve-figure-1.png){width=624}\n:::\n:::\n\n\nThe LOOCV estimate drops from 24.23 at degree 1 to\n19.25 at degree 2 and then barely moves. Its minimum,\n18.83, is at degree 7, only\n0.42 below the quadratic. Unlike the\ntraining MSE, it does not keep falling: at degree 10 it is\n19.49, above its minimum, while the training MSE is at its\nlowest.\n\n## k-fold cross-validation\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nn_folds <- 10\nfold_auto <- sample(rep(seq_len(n_folds), length.out = n_auto))\nfold_sizes <- table(fold_auto)\n\nfold_roles <- c(\"Training\", \"Validation\")\nfold_plot <- map(seq_len(n_folds), \\(l) {\n  mutate(Auto, panel = paste(\"Fold\", l, \"held out\"),\n         role = if_else(fold_auto == l, fold_roles[2], fold_roles[1]))\n}) |>\n  list_rbind() |>\n  mutate(panel = factor(panel, levels = paste(\"Fold\", seq_len(n_folds), \"held out\")),\n         role = factor(role, levels = fold_roles)) |>\n  arrange(role) |>\n  ggplot(aes(x = horsepower, y = mpg, color = role, shape = role, size = role)) +\n  geom_point(alpha = 0.8) +\n  facet_wrap(~ panel, nrow = 2) +\n  scale_color_manual(values = c(\"grey70\", \"black\")) +\n  scale_shape_manual(values = c(16, 17)) +\n  scale_size_manual(values = c(0.5, 1.3)) +\n  labs(x = \"Horsepower\", y = \"Miles per gallon\", color = NULL, shape = NULL,\n       size = NULL, title = \"ISLR2::Auto in 10 folds\") +\n  theme(legend.position = \"bottom\")\n```\n:::\n\n:::\n\nThe figure below splits the 392 cars at random into 10 groups\nof about equal size. Each panel marks one group as black triangles and the\nrest as grey circles.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/auto-folds-figure-1.png){width=864}\n:::\n:::\n\n\nThe groups hold 39 and 40\ncars, and every car appears as a triangle in exactly one panel. Each group is\nscattered across the whole range of horsepower.\n\n### k-fold estimate\n\n**$k$-fold cross-validation** divides the observations at random into $k$\ngroups, or **folds**, $\\mathcal{F}_1, \\ldots, \\mathcal{F}_k$, of about equal\nsize. For each fold $\\ell = 1, \\ldots, k$ it fits the model to the other $k - 1$\nfolds and computes the MSE on fold $\\ell$,\n\n$$\\text{MSE}_\\ell = \\frac{1}{n_\\ell}\\sum_{i \\in \\mathcal{F}_\\ell}\\left[y_i - \\hat f^{(-\\ell)}(x_i)\\right]^2, \\qquad \\text{CV}_{(k)} = \\sum_{\\ell=1}^k \\frac{n_\\ell}{n}\\,\\text{MSE}_\\ell,$$\n\nwhere\n\n- $k$ is the **number of folds**, written lowercase as in the name $k$-fold\ncross-validation; it is unrelated to $K$, the number of neighbors in KNN (or\nof classes in the generative classifier lectures),\n- $\\mathcal{F}_\\ell$ is the set of indices of the observations in fold $\\ell$\nand $n_\\ell$ their number,\n- $\\hat f^{(-\\ell)}$ is the model fit to the observations outside fold\n$\\ell$, and\n- $\\text{CV}_{(k)}$ is the average of the fold MSEs weighted by fold size,\nwhich is $\\frac{1}{k}\\sum_\\ell \\text{MSE}_\\ell$ when every fold has $n/k$\nobservations, and is the average squared held-out error over all $n$\nobservations.\n\nEvery observation is held out exactly once and used for fitting $k - 1$\ntimes. LOOCV is the special case $k = n$, with one observation per fold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkfold_mse <- function(d, fold, data = Auto) {\n  sq_error <- numeric(nrow(data))\n  for (l in unique(fold)) {\n    held_out <- fold == l\n    fit <- fit_degree(d, data[!held_out, ])\n    sq_error[held_out] <- (data$mpg[held_out] - predict(fit, data[held_out, ]))^2\n  }\n  mean(sq_error)\n}\nkfold_10 <- map_dbl(degrees, kfold_mse, fold = fold_auto)\n```\n:::\n\n\nWith the folds in the figure, the 10-fold estimate is\n24.29 at degree 1 and 19.28 at degree 2, and is\nsmallest, 19.19, at degree 7.\n\n### Partition variability\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nn_partitions <- n_splits\npartition_k <- c(5, 10)\nkfold_curves <- expand_grid(k = partition_k, partition = seq_len(n_partitions)) |>\n  mutate(fold = map(k, \\(k) sample(rep(seq_len(k), length.out = n_auto))),\n         mse = map(fold, \\(f) map_dbl(degrees, kfold_mse, fold = f)),\n         degree = list(degrees)) |>\n  select(-fold) |>\n  unnest(c(degree, mse))\n\nmethod_labels <- c(\"Validation set\", \"5-fold\", \"10-fold\")\nresample_curves <- bind_rows(\n  transmute(val_curves, method = method_labels[1], rep = split, degree, mse),\n  transmute(kfold_curves, method = paste0(k, \"-fold\"), rep = partition, degree, mse)) |>\n  mutate(method = factor(method, levels = method_labels))\nresample_summary <- resample_curves |>\n  group_by(method) |>\n  summarize(sd_d2 = sd(mse[degree == 2]), .groups = \"drop\")\nsummary_of <- function(m, col) resample_summary[[col]][resample_summary$method == m]\nchosen_by <- resample_curves |>\n  group_by(method, rep) |>\n  slice_min(mse, n = 1, with_ties = FALSE) |>\n  ungroup()\nchosen_degrees <- function(m) sort(unique(chosen_by$degree[chosen_by$method == m]))\n\nloocv_line <- tibble(degree = degrees, mse = loocv_fast)\nresample_plot <- function(m) {\n  ggplot(filter(resample_curves, method == m), aes(x = degree, y = mse)) +\n    geom_line(aes(group = rep), color = \"grey65\", linewidth = 0.3) +\n    geom_line(data = loocv_line, color = \"black\", linetype = \"dashed\",\n              linewidth = 1) +\n    degree_axis +\n    labs(x = \"Polynomial degree d\", y = \"Estimated test MSE\",\n         title = paste0(m, \", \", n_partitions,\n                        \" random partitions; LOOCV dashed\"))\n}\nresample_plots <- map(method_labels, resample_plot)\n```\n:::\n\n:::\n\nThe 10-fold estimate above comes from one random partition of the\ncars. To\nsee whether it changes from one partition to another, and by how much, the\ntabs below repeat\nthe validation set curves of 100 random splits and add the curves of\n100 random partitions into 5 folds and into\n10 folds, each over the LOOCV curve (black, dashed), on the\nsame axes.\n\n::: {.panel-tabset}\n#### Validation set\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/resample-val-figure-1.png){width=624}\n:::\n:::\n\n\n#### 5-fold\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/resample-5fold-figure-1.png){width=624}\n:::\n:::\n\n\n#### 10-fold\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/resample-10fold-figure-1.png){width=624}\n:::\n:::\n\n:::\n\nThe band of curves narrows from tab to tab. At degree 2 the standard\ndeviation of the estimate across random partitions is\n1.70 for the validation set,\n0.136 for 5-fold, and\n0.093 for 10-fold cross-validation. The\n5-fold and 10-fold curves hug the LOOCV curve, while the validation set\ncurves scatter widely on both sides of it: every observation is held out once\nand the held-out errors are averaged over all $n$ of them, so the estimate\ndepends far less on which observations share a fold. The degree with the smallest estimate\nis still not fixed: across partitions 10-fold cross-validation chooses degree\n2, 6, and 7, because the curves are\nnearly flat from degree 2 on.\n\n### Fold count\n\nAny $k$ from 2 to $n$ gives a cross-validation estimate, and the choice\naffects its bias, its variance, and its computation.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nn_sample <- 50\nn_sims <- 2000\nk_values <- c(2, 5, 10, n_sample)\nk_labels <- c(\"2-fold\", \"5-fold\", \"10-fold\", paste0(\"LOOCV (k = \", n_sample, \")\"))\nk_sims <- map(seq_len(n_sims), \\(r) {\n  id <- sample(n_auto, n_sample)\n  cars <- Auto[id, ]\n  others <- Auto[-id, ]\n  test_mse <- mean((others$mpg - predict(fit_degree(2, cars), others))^2)\n  cv <- map_dbl(k_values, \\(k) {\n    if (k == n_sample) return(loocv_shortcut(2, cars))\n    kfold_mse(2, sample(rep(seq_len(k), length.out = n_sample)), cars)\n  })\n  tibble(sim = r, method = k_labels, estimate = cv, test_mse = test_mse)\n}) |>\n  list_rbind() |>\n  mutate(method = factor(method, levels = k_labels))\nk_summary <- k_sims |>\n  group_by(method) |>\n  summarize(mean_estimate = mean(estimate), sd_estimate = sd(estimate),\n            bias = mean(estimate - test_mse),\n            se_bias = sd(estimate - test_mse) / sqrt(n()), .groups = \"drop\")\nmean_test_mse <- mean(k_sims$test_mse[k_sims$method == k_labels[1]])\nk_of <- function(m, col) k_summary[[col]][k_summary$method == m]\n\n# A few 2-fold estimates are extreme: a quadratic fit to half of a small\n# sample can extrapolate badly to a held-out car.\ntwo_fold <- k_sims$estimate[k_sims$method == k_labels[1]]\nextreme <- two_fold > 5 * mean_test_mse\nn_extreme <- sum(extreme)\nmax_extreme <- max(two_fold)\nsd_two_fold_trimmed <- sd(two_fold[!extreme])\n\nk_plot <- ggplot(k_sims, aes(x = method, y = estimate)) +\n  geom_boxplot(outlier.size = 0.6, outlier.alpha = 0.5) +\n  stat_summary(fun = mean, geom = \"point\", shape = 23, size = 3,\n               fill = \"#E69F00\") +\n  geom_hline(yintercept = mean_test_mse, linetype = \"dashed\") +\n  coord_cartesian(ylim = quantile(k_sims$estimate, c(0.005, 0.995))) +\n  labs(x = NULL, y = \"Cross-validation estimate of test MSE\",\n       title = paste0(format(n_sims, big.mark = \",\"), \" samples of \", n_sample,\n                      \" cars; quadratic; diamond = mean; dashed = mean test MSE\"),\n       caption = \"Vertical axis clipped to the middle 99% of the estimates\")\n```\n:::\n\n:::\n\nTo see how $k$ affects the bias and variance of the estimate, the\n392 cars were treated as a population. Each of 2,000 times, a\nsample of 50 cars was drawn without replacement and a quadratic was\nfit to it; the actual test MSE of that fit is its average squared error on the\n342 cars not drawn. The figure compares the cross-validation\nestimates from the same 50 cars, with $k$ equal to\n2, 5, 10, and 50 (LOOCV), against it.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/k-simulation-figure-1.png){width=720}\n:::\n:::\n\n\nThe average actual test MSE of the fits is 20.38. The\nestimates average 23.08 for 2-fold,\n20.86 for 5-fold,\n20.55 for 10-fold, and\n20.37 for LOOCV. 2-fold\ncross-validation, fitting to 25 cars, overestimates by\n2.70, with a simulation standard error of\n0.52; by $k = 5$ the\noverestimate is small, 0.49, with a simulation\nstandard error of 0.14. The standard\ndeviations of the estimates are 23.06,\n5.35,\n5.15, and\n5.01, so 10-fold and LOOCV vary about\nequally. The 2-fold standard deviation is dominated by 3 of the\n2,000 samples, whose estimates exceed five times\nthe mean test MSE (the largest is 984.29), where a quadratic fit\nto 25 cars extrapolates badly to a held-out car; without them it\nis 7.61. The figure's vertical axis is clipped, so\nthose estimates are not shown.\n\nThree considerations explain these results and trade off in choosing $k$.\n\n- **Computation.** $k$-fold cross-validation needs $k$ fits per model, LOOCV\n$n$. For least squares the shortcut makes LOOCV cost one fit; for most other\nmethods it is $n$ fits, and $k = 5$ or $10$ is a large saving.\n- **Bias.** Each fit uses $n(k-1)/k$ observations: for all 392 cars,\n196 with $k = 2$, about 314 with $k = 5$,\nabout 353 with $k = 10$, and 391 with\nLOOCV. By the learning curve above, a model fit to fewer observations has\nlarger test error, so $\\text{CV}_{(k)}$ overestimates the test error of the\nmodel fit to all $n$, by more as $k$ shrinks. LOOCV is nearly unbiased.\n- **Variance.** $\\text{CV}_{(k)}$ is an average of $k$ fold MSEs. If each has\nvariance $\\tau^2$ and each pair has correlation $\\rho$,\n\n$$Var\\left[\\frac{1}{k}\\sum_{\\ell=1}^k\\text{MSE}_\\ell\\right] = \\frac{1}{k^2}\\sum_{\\ell=1}^k\\sum_{\\ell'=1}^k Cov\\left[\\text{MSE}_\\ell, \\text{MSE}_{\\ell'}\\right] = \\tau^2\\left(\\rho + \\frac{1-\\rho}{k}\\right),$$\n\nwhere $\\ell'$ is a second fold index. Averaging more folds shrinks the\n$(1-\\rho)/k$ term but not $\\rho\\tau^2$. In LOOCV any two fits share $n - 2$\nof their $n - 1$ observations, so their held-out errors are strongly\ncorrelated and averaging $n$ of them reduces the variance less than the\nnumber $n$ suggests; with larger $k$ each fold MSE is also computed from fewer\nobservations, raising $\\tau^2$. Which effect dominates depends on the\nmethod and the data.\n\nThe standard deviations in the simulation combine two sources: which\n50 cars were drawn, shared by all four estimates, and, for $k$-fold,\nthe random partition. The partition alone is the cleaner comparison. With all\n392 cars held fixed, the degree-2 estimate varied across random\npartitions with standard deviation 0.136\nfor 5-fold and 0.093 for 10-fold\ncross-validation, and LOOCV, with no partition, does not vary at all.\n\nFor a quadratic fit to 50 cars, 5-fold and 10-fold\ncross-validation had small bias and variance close to LOOCV's, and for a\nmethod without the least squares shortcut they need 5 or 10 fits rather than\n$n$. That combination is why $k = 5$ or $10$ is the usual choice.\n\n## Classification\n\n### Credit card default data\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# The QDA lecture's split, recreated with its seed; the generator's state is\n# restored afterward so this lecture's later draws are unaffected.\nrng_state <- .Random.seed\nset.seed(20261001)\ntrain_id <- sample(nrow(Default), nrow(Default) / 2)\nassign(\".Random.seed\", rng_state, envir = globalenv())\ntrain <- Default[train_id, ]\ntest  <- Default[-train_id, ]\n\n# The QDA lecture's rule of thumb: the smallest odd integer above sqrt(n).\nodd_above_sqrt <- function(n) {\n  k <- floor(sqrt(n))\n  if (k %% 2 == 0) k + 1 else k + 2\n}\nK_rule <- odd_above_sqrt(nrow(train))\n\ndollar_labels <- function(v) {\n  ifelse(is.na(v), NA,\n         paste0(\"$\", format(v, big.mark = \",\", scientific = FALSE, trim = TRUE)))\n}\ndefault_plot <- ggplot(arrange(train, default),\n                       aes(x = balance, y = income, color = default,\n                           shape = default)) +\n  geom_point(alpha = 0.4, size = 0.9) +\n  scale_color_manual(values = class_colors) +\n  scale_shape_manual(values = c(No = 16, Yes = 17)) +\n  scale_x_continuous(labels = dollar_labels) +\n  scale_y_continuous(labels = dollar_labels) +\n  guides(color = guide_legend(override.aes = list(alpha = 1, size = 2))) +\n  labs(x = \"Credit card balance ($)\", y = \"Income ($)\", color = \"Default\",\n       shape = \"Default\", title = \"ISLR2::Default, training half\")\n```\n:::\n\n:::\n\nThe QDA and naive Bayes lecture classified `ISLR2::Default` credit card\ncustomers as defaulters or not from `balance` and `income`, fitting every\nclassifier to a random half of the\n10,000 customers and evaluating it on the\nother half. Its KNN classifier used $K = 71$ neighbors, the smallest\nodd integer above $\\sqrt{n}$ for the training half, a rule of thumb. The\nfigure below plots the same training half, recreated with the same seed.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/default-figure-1.png){width=672}\n:::\n:::\n\n\nThe training half holds 5,000 customers, of\nwhom 176 (3.52%)\ndefaulted. Defaulters sit at high balances at every income, mixed among\nnon-defaulters with similar balances.\n\n### Cross-validation error rate\n\nCross-validation for a classifier replaces the squared error with a\nclassification loss. With the misclassification indicator,\n\n$$\\text{Err}_\\ell = \\frac{1}{n_\\ell}\\sum_{i \\in \\mathcal{F}_\\ell}\\mathrm{I}\\left(y_i \\ne \\hat y_i^{(-\\ell)}\\right), \\qquad \\text{CV}_{(k)} = \\sum_{\\ell=1}^k\\frac{n_\\ell}{n}\\,\\text{Err}_\\ell,$$\n\nwhere\n\n- $\\hat y_i^{(-\\ell)}$ is the class predicted for observation $i$ by the\nclassifier fit to the observations outside fold $\\ell$, and\n- $\\text{Err}_\\ell$ is the test error rate of that classifier on fold $\\ell$.\n\nAny loss can take the place of the indicator. Log loss, from the\nclassification lecture, scores the predicted probabilities rather than the\nclasses: with $y_i$ coded $1$ for the positive class and $0$ otherwise, it\nreplaces $\\mathrm{I}\\left(y_i \\ne \\hat y_i^{(-\\ell)}\\right)$ with\n$-\\left\\{y_i\\log\\hat p^{(-\\ell)}(x_i) + (1 - y_i)\\log\\left[1 - \\hat p^{(-\\ell)}(x_i)\\right]\\right\\}$,\nwhere $\\hat p^{(-\\ell)}(x_i)$ is the predicted probability of the positive\nclass. A KNN vote share of exactly $0$ or $1$ on a misclassified observation\nmakes it infinite, so log loss suits classifiers whose probabilities stay\naway from $0$ and $1$, such as logistic regression.\n\nFor KNN, the classifier fit to the training folds includes the\nstandardization of the features: their means and standard deviations are\ncomputed from the training folds, as they were computed from the training half\nin the QDA lecture.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeatures <- c(\"balance\", \"income\")\nknn_classify <- function(fit_data, new_data, K) {\n  center <- colMeans(fit_data[features])\n  spread <- map_dbl(fit_data[features], sd)\n  class::knn(scale(fit_data[features], center, spread),\n             scale(new_data[features], center, spread),\n             fit_data$default, k = K)\n}\nknn_cv_error <- function(K, fold, data = train) {\n  wrong <- logical(nrow(data))\n  for (l in unique(fold)) {\n    held_out <- fold == l\n    predicted <- knn_classify(data[!held_out, ], data[held_out, ], K)\n    wrong[held_out] <- predicted != data$default[held_out]\n  }\n  mean(wrong)\n}\n```\n:::\n\n\n### Neighbor count\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nfold_default <- sample(rep(seq_len(n_folds), length.out = nrow(train)))\nK_grid <- seq(1, 201, by = 2)\nknn_errors <- tibble(K = K_grid) |>\n  mutate(Training = map_dbl(K, \\(K) mean(knn_classify(train, train, K) != train$default)),\n         `10-fold CV` = map_dbl(K, knn_cv_error, fold = fold_default),\n         `Test half` = map_dbl(K, \\(K) mean(knn_classify(train, test, K) != test$default)))\nK_cv <- knn_errors$K[which.min(knn_errors$`10-fold CV`)]\nK_test <- knn_errors$K[which.min(knn_errors$`Test half`)]\nshare_test_below <- mean(knn_errors$`Test half` < knn_errors$`10-fold CV`)\nknn_of <- function(K_value, col) knn_errors[[col]][knn_errors$K == K_value]\ntest_below_cv_min <- knn_of(K_cv, \"Test half\") < min(knn_errors$`10-fold CV`)\n\nknn_long <- knn_errors |>\n  pivot_longer(-K, names_to = \"error\", values_to = \"rate\") |>\n  mutate(error = factor(error, levels = c(\"Training\", \"10-fold CV\", \"Test half\")))\nknn_plot <- ggplot(knn_long, aes(x = 1 / K, y = rate, color = error,\n                                 linetype = error, shape = error)) +\n  geom_vline(xintercept = 1 / c(K_cv, K_rule), color = \"grey70\") +\n  geom_line() +\n  geom_point(data = filter(knn_long, K %in% c(1, 3, 5, 11, 21, 51, 101, 201)),\n             size = 2) +\n  annotate(\"text\", x = 1 / c(K_cv, K_rule), y = max(knn_long$rate), hjust = -0.1,\n           label = c(paste(\"K =\", K_cv, \"(CV)\"), paste(\"K =\", K_rule, \"(rule)\")),\n           size = 3) +\n  scale_x_log10(breaks = 1 / c(1, 3, 10, 30, 100, 200),\n                labels = c(\"1\", \"1/3\", \"1/10\", \"1/30\", \"1/100\", \"1/200\")) +\n  scale_y_continuous(labels = \\(v) paste0(100 * v, \"%\")) +\n  scale_color_manual(values = c(\"grey40\", \"#D55E00\", \"#0072B2\")) +\n  labs(x = \"Flexibility 1/K (log scale)\", y = \"Error rate\", color = NULL,\n       linetype = NULL, shape = NULL, title = \"KNN on ISLR2::Default\")\n```\n:::\n\n:::\n\nThe training half was divided into 10 folds, and the\n10-fold cross-validation error rate was computed for every odd $K$\nfrom 1 to 201. The figure plots it against $1/K$,\nthe flexibility, with the training error rate and the error rate on the test\nhalf for comparison.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/knn-cv-figure-1.png){width=720}\n:::\n:::\n\n\nThe training error rate falls to 0.00% at $K = 1$,\nwhere every training customer is its own nearest neighbor. The\ncross-validation error rate is U-shaped instead: 4.72%\nat $K = 1$, a minimum of 2.82% at\n$K = 11$, and 3.52% at\n$K = 201$, where\nKNN classifies every customer as a non-defaulter and its error rate equals the\nproportion of defaulters. The rule of thumb's $K = 71$ has a\ncross-validation error rate of 3.24%.\n\nThe test half, which the cross-validation never touched, gives the same\nshape: its error rate is 2.74% at\n$K = 11$ and 2.88% at $K = 71$,\nand is smallest, 2.60%, at $K = 9$.\nThe test curve lies below the cross-validation curve\nat every value\nof $K$, in part because defaulters\nare rarer in the test half, 3.14% against\n3.52%, which also sets the level of each\ncurve at large $K$.\n\n## Data-dependent steps\n\nThe data sets in this section have thousands of features and only dozens of\nobservations, and none of the features carries any information about the\nresponse. They are simulated rather than real because the point concerns the\ndata-generating process: with no information in the features, the true test\nerror rate of any classifier is known, so a cross-validation estimate can be\nchecked against it.\n\n### Noise feature screening\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nn_noise <- 50\np_noise <- 5000\nq_keep <- 20\nK_noise <- 5\n# Two classes of equal size and no information in the features.\ntrue_error <- 1 / 2\nsimulate_noise <- function() {\n  list(X = matrix(rnorm(n_noise * p_noise), n_noise, p_noise),\n       y = factor(rep(c(\"A\", \"B\"), each = n_noise / 2)))\n}\nscreen <- function(X, y, q) {\n  order(abs(cor(X, as.numeric(y))), decreasing = TRUE)[seq_len(q)]\n}\n\nnoise_example <- simulate_noise()\ntop_two <- screen(noise_example$X, noise_example$y, 2)\ntop_cor <- abs(cor(noise_example$X[, top_two], as.numeric(noise_example$y)))\n# Which class sits higher (second feature) and further right (first feature).\nclass_means <- sapply(top_two, \\(j) tapply(noise_example$X[, j], noise_example$y, mean))\nupper_class <- rownames(class_means)[which.max(class_means[, 2])]\nright_class <- rownames(class_means)[which.max(class_means[, 1])]\nother_class <- function(cl) setdiff(levels(noise_example$y), cl)\nnoise_plot <- tibble(first = noise_example$X[, top_two[1]],\n                     second = noise_example$X[, top_two[2]],\n                     class = noise_example$y) |>\n  ggplot(aes(x = first, y = second, color = class, shape = class)) +\n  geom_point(size = 2.2) +\n  scale_color_manual(values = c(A = \"#0072B2\", B = \"#D55E00\")) +\n  labs(x = paste(\"Feature\", top_two[1]), y = paste(\"Feature\", top_two[2]),\n       color = \"Class\", shape = \"Class\",\n       title = paste(\"The two of\", format(p_noise, big.mark = \",\"),\n                     \"noise features most correlated with the class\"))\n```\n:::\n\n:::\n\nEach simulated data set has $n = 50$ observations in two classes of\n25 and $p = 5{,}000$ features, all\nindependent standard normal draws unrelated to the class, so the true test\nerror rate of any classifier is 50%. A common first step\nwith so many features is **screening**: keep the 20 features most\ncorrelated with the response, then fit a classifier to those. The figure plots\nthe two features of one data set with the largest absolute correlation with\nthe class.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/noise-figure-1.png){width=576}\n:::\n:::\n\n\nThe classes look partly separated: class B tends to sit higher\nthan class A, and class A further\nright than class B. The absolute correlations of\nthese two features with the class are 0.46 and\n0.46. Among\n5,000 features unrelated to the class, some are\ncorrelated with it in a sample of 50 by chance, and screening finds\nexactly those.\n\n### Within-fold screening\n\nThe function below estimates the error rate of \"screen the 20 most\ncorrelated features, then classify by KNN with $K = 5$\" by\n10-fold cross-validation, in one of two ways. With `inside = FALSE`\nit screens once, on all $n$ observations, and cross-validates only the KNN step. With\n`inside = TRUE` it screens again within each fold, using only the training\nfolds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscreen_cv_error <- function(X, y, inside,\n                            fold = sample(rep(seq_len(n_folds), length.out = nrow(X)))) {\n  keep_all <- screen(X, y, q_keep)\n  wrong <- logical(nrow(X))\n  for (l in seq_len(n_folds)) {\n    held_out <- fold == l\n    keep <- if (inside) screen(X[!held_out, ], y[!held_out], q_keep) else keep_all\n    predicted <- class::knn(X[!held_out, keep], X[held_out, keep, drop = FALSE],\n                            y[!held_out], k = K_noise)\n    wrong[held_out] <- predicted != y[held_out]\n  }\n  mean(wrong)\n}\n```\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nn_noise_sims <- 200\nscreen_labels <- c(\"Screen once, then cross-validate\",\n                   \"Screen inside each fold\")\nscreen_sims <- map(seq_len(n_noise_sims), \\(r) {\n  d <- simulate_noise()\n  tibble(approach = screen_labels,\n         error = c(screen_cv_error(d$X, d$y, inside = FALSE),\n                   screen_cv_error(d$X, d$y, inside = TRUE)))\n}) |>\n  list_rbind() |>\n  mutate(approach = factor(approach, levels = screen_labels))\nscreen_mean <- function(a) mean(screen_sims$error[screen_sims$approach == a])\n\n# Screening inside each fold on further data sets, three ways: folds drawn as\n# above; stratified folds, each holding equally many of each class; and class\n# labels drawn independently rather than fixed at n / 2 per class.\nn_check_sims <- 1000\nstratified_fold <- function(y) {\n  fold <- integer(length(y))\n  for (cl in levels(y)) {\n    fold[y == cl] <- sample(rep(seq_len(n_folds), length.out = sum(y == cl)))\n  }\n  fold\n}\ncheck_labels <- c(\"random\", \"stratified\", \"independent\")\ninside_checks <- map(seq_len(n_check_sims), \\(r) {\n  d <- simulate_noise()\n  y_independent <- factor(sample(levels(d$y), n_noise, replace = TRUE),\n                          levels = levels(d$y))\n  tibble(folds = check_labels,\n         error = c(screen_cv_error(d$X, d$y, inside = TRUE),\n                   screen_cv_error(d$X, d$y, inside = TRUE,\n                                   fold = stratified_fold(d$y)),\n                   screen_cv_error(d$X, y_independent, inside = TRUE)))\n}) |>\n  list_rbind() |>\n  group_by(folds) |>\n  summarize(mean = mean(error), se = sd(error) / sqrt(n()), .groups = \"drop\")\ncheck_of <- function(f, col = \"mean\") inside_checks[[col]][inside_checks$folds == f]\n\nscreen_plot <- ggplot(screen_sims, aes(x = error)) +\n  geom_histogram(binwidth = 0.04, boundary = 0, fill = \"grey60\", color = \"white\") +\n  geom_vline(xintercept = true_error, linetype = \"dashed\") +\n  facet_wrap(~ approach, ncol = 1) +\n  scale_x_continuous(labels = \\(v) paste0(100 * v, \"%\"), limits = c(0, 1)) +\n  labs(x = \"10-fold cross-validation error rate\", y = \"Simulated data sets\",\n       title = paste0(n_noise_sims, \" simulated data sets; true error rate \",\n                      pct(true_error, 0), \" (dashed)\"))\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-cross-validation_files/figure-html/screen-figure-1.png){width=672}\n:::\n:::\n\n\nAcross 200 simulated data sets, screening once and then\ncross-validating gives an average estimated error rate of\n5.1%, against a true error rate of\n50%. Screening inside each fold gives\n51.8%. The first approach selected the\nfeatures using the responses of the very observations it later held out, so\nthose observations were not new to the classifier.\n\nScreening is part of the fit. So is every other step that uses the data to\nbuild a classifier or a regression, and a cross-validation estimate is honest\nonly if all of those steps are repeated, inside every fold, using only the\ntraining folds.\n\nThe second estimate sits slightly above 50%. To see why,\nscreening inside each fold was cross-validated on\n1,000 further simulated data sets in three\nways. With folds drawn at random as\nabove, the average estimated error rate is 51.8%. With\nstratified folds, each holding equally many observations of each class, it is\n50.1%. With each class label drawn independently,\nA and B equally likely, so that the class counts\nvary from one data set to the next, it is 49.9%.\nEach of these averages has a simulation standard error of at most\n0.33 percentage points.\n\nOnly the first combines fixed class counts with folds that ignore the class.\nEach data set has exactly 25 observations per class, so a\nheld-out fold with more of one class leaves the training folds with fewer of\nit. A classifier with no information leans toward the class that is more\ncommon in its training folds, which is the less common class in the held-out\nfold. Stratified folds remove the imbalance between held-out and training\nfolds, and independent labels remove the fixed counts that tie them together,\nand both estimates are within simulation error of 50%.\n\n### Standardization and tuning\n\nThe same rule covers every data-dependent step.\n\n- **Standardization.** `knn_classify()` computes the feature means and\nstandard deviations from the training folds and applies them to the held-out\nfold. Standardizing the whole data set first lets the held-out observations\ninfluence the scale, the same kind of leak as screening.\n- **Tuning.** Choosing $K$ by cross-validation is itself a data-dependent\nstep. The smallest of 101 cross-validation error rates,\n2.82%, is the minimum of noisy estimates,\nso over repeated data sets it tends to fall below the test error rate of the\nclassifier it chooses. An honest estimate of the error of \"choose $K$ by\n10-fold cross-validation, then fit\" needs data not used in the\nchoosing: here the test half, where $K = 11$ has error rate\n2.74%. On this one split that is\nbelow the cross-validation minimum,\nthe opposite of the tendency, because the test curve lies below the cross-validation curve.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\n- **One-standard-error rule.** When the cross-validation curve is nearly flat\nnear its minimum, as for the polynomial degree of the cars, choose the\nsimplest model whose estimate is within one standard error of the minimum,\nthe standard error computed from the $k$ fold MSEs.\n- **Repeated and stratified $k$-fold.** Averaging $k$-fold estimates over\nseveral random partitions reduces their dependence on the partition;\nstratifying the folds keeps the class proportions the same in every fold,\nwhich matters when one class is rare, as defaulters are.\n- **Nested cross-validation.** An outer cross-validation loop around the\nwhole procedure \"choose the tuning parameter by inner cross-validation, then\nfit\" estimates the test error of that procedure without a separate test set.\n:::\n\n## Conclusion\n\nTraining error falls as flexibility increases, so it cannot choose a model's\nflexibility. Resampling methods estimate test error by fitting to part of the\ndata and measuring error on the part held out.\n\nThe validation set approach holds out one random part. Its estimate varies\nwith the split, and because each model is fit to only part of the data it\ntends to overestimate the test error of the model fit to all $n$. Leave-one-out\ncross-validation holds out each observation in turn and averages the $n$\nsquared held-out errors. It involves no random split and is nearly unbiased.\nFor least squares it needs a single fit, since the held-out error of\nobservation $i$ is its residual divided by $1 - h_i$.\n\n$k$-fold cross-validation divides the data into $k$ folds, fits $k$ times, and\naverages the held-out errors. Choosing $k$ trades bias, variance, and\ncomputation. Smaller $k$ means smaller training sets and so more upward bias;\nlarger $k$ averages more, but more strongly correlated, fold errors, so its\nvariance falls more slowly than the number of folds suggests; and each\nadditional fold is another fit. $k = 5$ or $10$ is the usual choice because\neach fit uses 80% or 90% of the data, which keeps the bias modest, while a\nmethod without the least squares shortcut needs only 5 or 10 fits rather than\n$n$. For classification the squared\nerror becomes the misclassification indicator or another loss such as log\nloss, and the cross-validation curve chooses a flexibility setting, such as\nthe number of neighbors in KNN, as it chooses a polynomial degree.\n\nA cross-validation estimate is honest only when every data-dependent step,\nincluding feature screening, standardization, and tuning, is repeated inside\neach fold using only the training folds. Selecting features or tuning\nparameters on all the data first lets the held-out observations shape the\nfit, and the estimate becomes optimistic.\n\nThe next lecture turns from estimating test error to estimating the\nvariability of an estimate: the bootstrap resamples the observations with\nreplacement to approximate a statistic's sampling distribution.\n",
    "supporting": [
      "10-cross-validation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}