---
title: "Regression"
format: html
---

## Response variables

For regression models, our response variable is quantitative, continuous value.s

::: {.callout-note collapse="true"}
### For example,
- Salary
- Yield
- Score
- Concentration
:::


## True Model

The non-linear regression model of interest is

$$Y = f(X) + \epsilon$$
where

- $Y$ is the response variable,
- $X = (X_1,\ldots,X_p)$ is the collection of explanatory variables, and
- $\epsilon$ is the error with $E[\epsilon] = 0$ and independent of $x$.


::: {.callout-note collapse="true"}
### Goal
Based on data $(x_i, y_i)$ for $i=1,\ldots,n$, 
obtain an estimate of the function, $\hat{f}()$.
:::



## Prediction vs Understanding

Prediction: we don't care about interpretation, we just want the model that fits the best

Understanding: we would like the model to fit well, but are willing to sacrifice
some fit to have a model that is simple to understand

::: {.callout-note collapse="true"}
### Examples
- Compared to a high school diploma, having a bachelor's degree increases starting salary by $20,000. 
- A master’s degree in data science typically yields a 5% to 25% salary increase compared to a bachelor’s degree. 
- The log odds of initial job placement for those with a high school diploma are not statistically significantly different from those with a bachelor's degree.
:::



## Model Evaluation

When prediction is the goal, we evaluate the model through its mean squared error:

$$MSE 
= \frac{1}{n} \sum_{i=1}^n (y_i - \hat{y}_i)^2 
= \frac{1}{n} \sum_{i=1}^n \left[y_i - \hat{f}(x_i)\right]^2$$
as written, this is the *training MSE* since we used the same data to estimate
$\hat{f}$ as we used to compute the MSE.

We are actually more interested in how well our model fits *test* data, 
i.e. data that were not used to estimate $\hat{f}$. 
Thus, we typically estimate the *expected test MSE*:

$$MSE = E\left\{\left[Y - \hat{f}(X)\right]^2\right\}\approx \frac{1}{m} \sum_{i=1}^m \left[\tilde{y}_i - \hat{f}(\tilde{x}_i)\right]^2$$
and we refer to this simply as the *test MSE*.



## In-class activity

[R script](bv_example.R)

## Bias-variance Tradeoff

::: {.callout-note collapse="true"}
### Code
```{r}
library("tidyverse")
library("MASS")

set.seed(20260902) # for reproducible results
n <- dim(Boston)[1]
train_index  <- sample.int(n, size = n / 2, replace = FALSE)
train_boston <- Boston[ train_index, ]
test_boston  <- Boston[-train_index, ]

train_predict <- test_predict <- list()
for (i in 1:9) {
    m <- lm(medv ~ poly(lstat, i), data = train_boston)
    train_predict[[i]] <- predict(m, newdata = train_boston)
    test_predict[[ i]] <- predict(m, newdata = test_boston)
}



mse_train <- train_boston |> 
  dplyr::select(lstat, medv) |>
  mutate(
    order1 = train_predict[[1]],
    order2 = train_predict[[2]],
    order3 = train_predict[[3]],
    order4 = train_predict[[4]],
    order5 = train_predict[[5]],
    order6 = train_predict[[6]],
    order7 = train_predict[[7]],
    order8 = train_predict[[8]],
    order9 = train_predict[[9]],
  ) |>
  pivot_longer(
    cols      = starts_with("order"),
    names_to  = "model",
    values_to = "prediction"
  ) |>
  group_by(model) |>
  summarize(
    mse = mean((medv-prediction)^2)         
  )

mse_test <- test_boston |> 
  dplyr::select(lstat, medv) |>
  mutate(
    order1 = test_predict[[1]],
    order2 = test_predict[[2]],
    order3 = test_predict[[3]],
    order4 = test_predict[[4]],
    order5 = test_predict[[5]],
    order6 = test_predict[[6]],
    order7 = test_predict[[7]],
    order8 = test_predict[[8]],
    order9 = test_predict[[9]]
  ) |>
  pivot_longer(
    cols      = starts_with("order"),
    names_to  = "model",
    values_to = "prediction"
  ) |>
  group_by(model) |>
  summarize(
    mse = mean((medv-prediction)^2)         
  )


mse <- bind_rows(
    mse_train |> mutate(type = "train"),
    mse_test  |> mutate(type = "test" )
)

ggplot(mse, aes(x = model, y = mse, 
                color = type, linetype = type, group = type)) +
    geom_line() + 
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "bottom") +
    labs(
        x     = "Flexibilty", 
        y     = "Mean squared error",    
        title = "Bias-variance tradeoff")
```
:::


## Bias-variance Tradeoff (Mathematically)

$$E\left[\left(Y-\hat{f}(X))^2\right)\right] 
= Var[\hat{f}(X)] + Bias[\hat{f}(X)]^2 + Var[\epsilon]$$

where, over different **training** data

- $Var[\hat{f}(X)]$ is the variance 
- $Bias[\hat{f}(X)]$ is the bias
- $Var[\epsilon]$ is the irreducible error
