{
  "hash": "3b94ea5b037e2fd7adc0d713f0e64bea",
  "result": {
    "engine": "knitr",
    "markdown": "# Flexible Logistic Regression\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **write** a logistic regression model with an interaction between a\nquantitative feature and an indicator, and **derive** the two group-specific\nlog-odds slopes $\\beta_1$ and $\\beta_1 + \\beta_3$,\n- **interpret** $e^{\\beta_1}$ and $e^{\\beta_1 + \\beta_3}$ as group-specific\nodds ratios, and **explain** why no single odds ratio describes the\nquantitative feature once an interaction is present,\n- **compare** an additive fit against an interaction fit on the\nlinear-predictor scale, where the additive model forces two *parallel* lines,\nand **translate** that comparison onto the probability scale,\n- **define** the decision boundary as the feature value at which\n$\\hat p(x) = 0.5$ and **compute** it separately within each level of a\ncategorical feature,\n- **test** $H_0: \\beta_3 = 0$ with a $z$-statistic and **evaluate** whether an\ninteraction is supported, **recognizing** that a plausible interaction often\nturns out not to be, and\n- **explain** why polynomial and step-function features transfer from linear\nregression to logistic regression unchanged.\n:::\n\n## Interaction model\n\nAn interaction lets one feature's effect on the log-odds depend on the value of\nanother feature. Adding one turns the additive structure of the previous\nlecture — the structure that let a single odds ratio describe each feature —\ninto a claim the data can be asked about.\n\n### Additive assumption\n\nThe previous lecture's model was **additive**: each feature contributed its own\nterm $\\beta_j X_{ij}$ to the linear predictor, and no term involved two\nfeatures at once. That structure is what licensed the interpretation \"a\none-unit increase in $X_j$ multiplies the odds by $e^{\\beta_j}$, holding every\nother feature fixed\" — the same $e^{\\beta_j}$ at every value of every other\nfeature.\n\nThat is an assumption, not a convenience. The fitted curves of the previous\nlecture showed it directly: two curves of identical shape, separated by a\nconstant $\\hat\\beta_2$ on the log-odds scale at every balance.\n\nThere is no reason a real process has to work that way. Whether it does is a\nquestion about the data, and it can be asked and answered with a model that\ndoes not impose it.\n\n### Model form\n\nThe fix is the one from the feature engineering lecture, applied to the linear\npredictor instead of to the mean response. With a quantitative feature $X$ and\nan indicator $D$, that lecture wrote\n\n$$Y_i = \\beta_0 + \\beta_1 X_i + \\beta_2 D_i + \\beta_3 X_i D_i + \\epsilon_i,$$\n\ngiving group A (where $D = 0$) intercept $\\beta_0$ and slope $\\beta_1$, and\ngroup B (where $D = 1$) intercept $\\beta_0 + \\beta_2$ and slope\n$\\beta_1 + \\beta_3$. Logistic regression uses that same linear predictor and\npasses it through the logistic function,\n\n$$p(X, D) = P(Y = 1 | X, D) = \\text{logistic}(\\eta) = \\frac{e^{\\eta}}{1 + e^{\\eta}}, \\qquad \\eta = \\beta_0 + \\beta_1 X + \\beta_2 D + \\beta_3 X D,$$\n\nwhere\n\n- $X$ is the quantitative feature,\n- $D$ is the indicator for the non-reference level of the categorical feature,\n- $\\eta$ is the linear predictor, the log-odds of the event, and\n- $\\beta_3$ is the coefficient on the product $XD$, the **interaction**.\n\nEquivalently, on the log-odds scale,\n\n$$\\log\\left(\\frac{p(X,D)}{1 - p(X,D)}\\right) = \\beta_0 + \\beta_1 X + \\beta_2 D + \\beta_3 X D.$$\n\nThe product $XD$ is just another column of the model matrix — written\n$\\mathbf{X}$ here, to keep it distinct from the scalar feature $X$ — built from\ntwo columns already in it. Estimation is unchanged: $\\hat\\beta$ still maximizes\nthe Bernoulli log-likelihood\n\n$$\\ell(\\beta) = \\sum_{i=1}^n \\left\\{ y_i \\, x_i\\beta - \\log\\left(1 + e^{x_i\\beta}\\right)\\right\\},$$\n\nwith $x_i$ the $i$th row of $\\mathbf{X}$, so it still has no closed-form\nmaximizer and is still found numerically by `glm()`.\n\nHierarchy applies here as it did in linear regression: keep $X$ and $D$ in the\nmodel whenever $XD$ is present.\n\n### Interpreting coefficients\n\nCollect the terms involving $X$:\n\n$$\\log\\left(\\frac{p(X,D)}{1 - p(X,D)}\\right) = \\underbrace{(\\beta_0 + \\beta_2 D)}_{\\text{log-odds intercept}} + \\underbrace{(\\beta_1 + \\beta_3 D)}_{\\text{log-odds slope on } X} X.$$\n\nSetting $X = 0$ and $D = 0$ leaves $\\beta_0$, the log-odds of the event in the\nreference group at $X = 0$, so $e^{\\beta_0}$ are the odds and\n$\\text{logistic}(\\beta_0)$ the probability there. Adding $\\beta_2$ shifts that\nbaseline to the indicated group, still at $X = 0$.\n\nThe slope on $X$ is a function of $D$, which is the whole point of the\ninteraction. Writing out the two levels:\n\n- **Reference level ($D = 0$):** log-odds $= \\beta_0 + \\beta_1 X$. A one-unit\nincrease in $X$ adds $\\beta_1$ to the log-odds and multiplies the odds by\n$e^{\\beta_1}$.\n- **Indicated level ($D = 1$):** log-odds\n$= (\\beta_0 + \\beta_2) + (\\beta_1 + \\beta_3) X$. A one-unit increase in $X$\nadds $\\beta_1 + \\beta_3$ to the log-odds and multiplies the odds by\n$e^{\\beta_1 + \\beta_3}$.\n\nSo there is no single odds ratio for $X$. There are two, one per group, and\ntheir ratio is\n\n$$\\frac{e^{\\beta_1 + \\beta_3}}{e^{\\beta_1}} = e^{\\beta_3}.$$\n\n$e^{\\beta_3}$ is a ratio of odds ratios: the factor by which one group's\nper-unit odds ratio for $X$ differs from the other's. $\\beta_3 = 0$ makes that\nfactor $1$ and returns the additive model.\n\nOne caution carries over from the feature engineering lecture: $\\beta_1$ is the\nlog-odds slope **when $D = 0$**, not an average across the two groups. A second\nis that the $X = 0$ at which $\\beta_0$ and $\\beta_2$ are defined may be a value\n$X$ never takes.\n\n### Fitting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm(default ~ balance * student, data = Default, family = \"binomial\")\n```\n:::\n\n\nThe `*` expands to `balance + student + balance:student`, so the fitted model\ncontains both main effects and the product, satisfying hierarchy\nautomatically. Writing `balance:student` alone would drop the main effects,\nviolating hierarchy: R responds by giving each group its own balance slope\nwhile forcing both to share a single intercept.\n\n## Fitted model geometry\n\nA fitted interaction differs from a fitted additive model in two visible ways:\nthe shape of the two groups' fitted curves, and the feature value at which each\ngroup's predicted class flips. Both are read off the linear predictor, where\neach group's fit is a straight line.\n\n### Two scales, two pictures\n\nThe two models are easiest to tell apart on the scale where both are linear.\nWritten as functions of $X$, the fitted log-odds are two straight lines:\n\n$$\\hat\\eta(X, 0) = \\hat\\beta_0 + \\hat\\beta_1 X, \\qquad \\hat\\eta(X, 1) = (\\hat\\beta_0 + \\hat\\beta_2) + (\\hat\\beta_1 + \\hat\\beta_3) X.$$\n\nUnder the additive model $\\hat\\beta_3 = 0$, both lines have slope\n$\\hat\\beta_1$: they are **parallel**, separated by exactly $\\hat\\beta_2$ at\nevery $X$. Under the interaction model the slopes differ by $\\hat\\beta_3$, so\nthe lines are not parallel and, extended far enough, must cross. Parallel\nversus non-parallel on the linear-predictor scale is the visual signature that\nseparates the two models.\n\nThe probability scale is what a decision actually uses, and it is a distorted\nview of the same two lines. Passing each line through\n$\\text{logistic}(\\cdot)$ compresses it toward $0$ and $1$, so two parallel\nlines become two S-curves of identical shape that never cross, while two\nnon-parallel lines become two S-curves of different steepness that can cross\nwithin the range of the data.\n\nIn R, `predict()` on a `glm` object returns these two scales:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit, newdata = grid)                    # eta-hat, the linear predictor\npredict(fit, newdata = grid, type = \"response\") # p-hat, the probability\n```\n:::\n\n\nThe examples below plot both for each model: the linear predictor first, to\ndiagnose whether the fitted slopes differ, and the probability scale after, to\nsee what that difference is worth.\n\n### Decision boundaries\n\nA fitted probability is often turned into a predicted class by comparing it to\na threshold, most commonly $0.5$. The **decision boundary** is the set of\nfeature values at which the model estimates the two classes as equally likely,\n\n$$\\hat p(x) = 0.5 \\iff \\frac{\\hat p(x)}{1 - \\hat p(x)} = 1 \\iff \\hat\\eta(x) = 0,$$\n\nwhere\n\n- $\\hat p(x)$ is the estimated probability of the event at feature values $x$,\nand\n- $\\hat\\eta(x) = x\\hat\\beta$ is the estimated linear predictor.\n\nBecause the logistic function is strictly increasing, $\\hat p(x) > 0.5$ exactly\nwhen $\\hat\\eta(x) > 0$. The boundary is therefore where the *linear* predictor\ncrosses zero, which is why it is a simple set — here, with one quantitative\nfeature, a single threshold value of that feature computed separately within\neach level of the categorical feature.\n\nSolving $\\hat\\eta = 0$ in the interaction model gives\n\n$$x^{*}_{D=0} = -\\frac{\\hat\\beta_0}{\\hat\\beta_1}, \\qquad x^{*}_{D=1} = -\\frac{\\hat\\beta_0 + \\hat\\beta_2}{\\hat\\beta_1 + \\hat\\beta_3},$$\n\nwhere $x^{*}_{D=d}$ is the value of $X$ at which $\\hat p = 0.5$ for group $d$.\nDropping the interaction sets $\\hat\\beta_3 = 0$, so the two thresholds share a\ndenominator:\n\n$$x^{*}_{D=0} = -\\frac{\\hat\\beta_0}{\\hat\\beta_1}, \\qquad x^{*}_{D=1} = -\\frac{\\hat\\beta_0 + \\hat\\beta_2}{\\hat\\beta_1} = x^{*}_{D=0} - \\frac{\\hat\\beta_2}{\\hat\\beta_1}.$$\n\nThe additive model still gives the two groups different thresholds; what it\ncannot give them is different *steepness*, since both groups cross the boundary\nat the common rate $\\hat\\beta_1$ per unit of $X$.\n\n## Student-specific balance effects\n\n**Question.** The previous lecture fit `default ~ balance + student`\nadditively, which forces the student-versus-non-student odds ratio to be\nidentical at every balance and the balance odds ratio to be identical for\nstudents and non-students. Is that additive assumption right, or does balance\nact differently on the two groups?\n\n**Data.** The same 10,000 simulated credit\ncard customers as in the previous two lectures, with `balance` as the\nquantitative feature $X$, the student indicator\n$D = \\mathrm{I}(\\texttt{student} = \\texttt{Yes})$, and $Y_i = 1$ when customer\n$i$ defaults.\n\n### Fitting both models\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_additive    <- glm(default ~ balance + student,\n                           data = Default, family = \"binomial\")\ndefault_interaction <- glm(default ~ balance * student,\n                           data = Default, family = \"binomial\")\nsummary(default_interaction)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        Estimate   Std. Error     z value      Pr(>|z|)\n(Intercept)        -1.087468e+01 0.4639679171 -23.4384348 1.734470e-121\nbalance             5.818816e-03 0.0002936985  19.8122090  2.336069e-87\nstudentYes         -3.512310e-01 0.8037332689  -0.4369994  6.621118e-01\nbalance:studentYes -2.196288e-04 0.0004780734  -0.4594039  6.459441e-01\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code for the table below\n\n::: {.cell}\n\n```{.r .cell-code}\nDefault <- Default |>\n  mutate(default01 = as.numeric(default == \"Yes\"))\n\nbda <- coef(default_additive)\nbdi <- coef(default_interaction)\n\ndefault_coef_table <- tibble(\n  term        = names(bdi),\n  additive    = c(bda, NA),\n  interaction = bdi\n) |>\n  mutate(across(c(additive, interaction),\n                \\(x) ifelse(is.na(x), \"\", sprintf(\"%.6f\", x)))) |>\n  knitr::kable(col.names = c(\"Coefficient\", \"Additive fit\",\n                             \"Interaction fit\"),\n               align = \"lcc\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Coefficient        | Additive fit | Interaction fit |\n|:------------------|:------------:|:---------------:|\n|(Intercept)        |  -10.749496  |   -10.874682    |\n|balance            |   0.005738   |    0.005819     |\n|studentYes         |  -0.714878   |    -0.351231    |\n|balance:studentYes |              |    -0.000220    |\n\n\n:::\n:::\n\n\nThe two fits agree closely on the intercept and on the `balance` slope, and the\nestimated interaction is $\\hat\\beta_3 = -2.2\\times 10^{-4}$ —\n26 times smaller than the `balance`\nmain effect it modifies.\n\n### Fitted log-odds\n\nPlotting $\\hat\\eta$ against balance for each model shows the two straight lines\neach one produces.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the plots below\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_grid <- expand_grid(\n  balance = seq(0, max(Default$balance), length.out = 300),\n  student = factor(c(\"No\", \"Yes\"), levels = levels(Default$student)))\n\ndefault_link <- bind_rows(\n  default_grid |> mutate(Model = \"Additive\",\n                         eta = predict(default_additive, newdata = default_grid)),\n  default_grid |> mutate(Model = \"Interaction\",\n                         eta = predict(default_interaction, newdata = default_grid)))\n\n# A shared base layer, so the two tabs below differ only in which model's\n# lines are drawn on it -- the panel itself never changes size or shape.\ndefault_link_base <- ggplot(mapping = aes(x = balance, y = eta,\n                                          color = student, linetype = student)) +\n  geom_hline(yintercept = 0, color = \"grey60\", linewidth = 0.3) +\n  coord_cartesian(xlim = range(default_grid$balance),\n                  ylim = range(default_link$eta)) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  labs(x = \"Credit card balance ($)\", y = expression(hat(eta)),\n       color = \"Student\", linetype = \"Student\", title = \"ISLR2::Default\")\n\ndefault_link_additive <- default_link_base +\n  geom_line(data = filter(default_link, Model == \"Additive\"), linewidth = 0.9)\n\ndefault_link_interaction <- default_link_base +\n  geom_line(data = filter(default_link, Model == \"Interaction\"), linewidth = 0.9)\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Additive\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/default-link-additive-plot-1.png){width=672}\n:::\n:::\n\n\n#### Interaction\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/default-link-interaction-plot-1.png){width=672}\n:::\n:::\n\n:::\n\nThe additive tab's two lines are exactly parallel, both with slope\n$0.005738$ log-odds per dollar and separated by\n$\\hat\\beta_2 = -0.715$ at every balance. The interaction\ntab's two lines have slopes $0.005819$ and\n$0.005599$, a difference too small to see: switching\nbetween the tabs barely moves the picture.\n\n### Fitted probabilities\n\nBuilding the same comparison up from the raw data puts both fitted models on\nthe scale a lending decision would use.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the plots below\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_prob <- bind_rows(\n  default_grid |>\n    mutate(Model = \"Additive\",\n           p_hat = predict(default_additive, newdata = default_grid,\n                           type = \"response\")),\n  default_grid |>\n    mutate(Model = \"Interaction\",\n           p_hat = predict(default_interaction, newdata = default_grid,\n                           type = \"response\")))\n\n# The jitter is computed once, here, and stored as a column rather than left\n# to geom_jitter() -- geom_jitter() re-randomizes every time a plot is drawn,\n# and each tab below is drawn separately, so leaving it to geom_jitter() would\n# put the points in slightly different places from one tab to the next and\n# make it look like the data had changed. Seeded so re-rendering the chapter\n# does not also churn the committed figure for no reason.\nset.seed(20260925)\ndefault_jittered <- Default |>\n  mutate(default01_jittered = default01 + runif(n(), -0.03, 0.03))\n\n# The same shared-base idea, with the raw data as the layer every tab keeps.\n# The legend is kept on every tab (with more visible swatches than the\n# points themselves) rather than suppressed on this one layer, so the panel\n# is the same width in all three tabs -- an unequal panel width across tabs\n# is the same \"the data looks different\" problem the jitter fix above solves.\ndefault_prob_base <- ggplot(mapping = aes(x = balance, y = p_hat,\n                                          color = student, linetype = student)) +\n  geom_point(data = default_jittered,\n             aes(y = default01_jittered, shape = student),\n             alpha = 0.08, size = 0.7) +\n  guides(color = guide_legend(override.aes = list(alpha = 1, size = 2))) +\n  coord_cartesian(xlim = range(default_grid$balance), ylim = c(-0.05, 1.05)) +\n  scale_y_continuous(breaks = c(0, 0.5, 1)) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  labs(x = \"Credit card balance ($)\", y = \"P(default = Yes)\",\n       color = \"Student\", linetype = \"Student\", shape = \"Student\",\n       title = \"ISLR2::Default\")\n\ndefault_prob_data <- default_prob_base\n\ndefault_prob_additive <- default_prob_base +\n  geom_line(data = filter(default_prob, Model == \"Additive\"), linewidth = 0.9)\n\ndefault_prob_interaction <- default_prob_base +\n  geom_line(data = filter(default_prob, Model == \"Interaction\"), linewidth = 0.9)\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Data\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/default-prob-data-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Additive\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/default-prob-additive-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Interaction\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/default-prob-interaction-plot-1.png){width=672}\n:::\n:::\n\n:::\n\nThe data tab replots the previous lecture's jittered scatter in a single\npanel, with students and non-students distinguished by color and shape. The\ntwo model tabs are nearly the same picture: two S-curves of all but identical\nshape, the student curve shifted right, whether or not\nthe interaction is in the model.\n\n### Interaction test\n\n::: {.callout-note collapse=\"true\"}\n### Code for the values quoted below\n\n::: {.cell}\n\n```{.r .cell-code}\ndcoef   <- summary(default_interaction)$coefficients\nz_d     <- dcoef[\"balance:studentYes\", \"z value\"]\np_d     <- dcoef[\"balance:studentYes\", \"Pr(>|z|)\"]\nci_d    <- confint.default(default_interaction)[\"balance:studentYes\", ]\n\nor_d <- tibble(\n  student = c(\"No (reference)\", \"Yes\"),\n  slope   = c(bdi[2], bdi[2] + bdi[4]),\n  or100   = exp(100 * c(bdi[2], bdi[2] + bdi[4]))\n)\n\nor_d_table <- or_d |>\n  mutate(slope = sprintf(\"%.6f\", slope),\n         or100 = sprintf(\"%.3f\", or100)) |>\n  knitr::kable(col.names = c(\"Student\", \"Slope (log-odds per \\\\$1)\",\n                             \"Odds ratio per \\\\$100\"),\n               align = \"lcc\")\n\naic_d_table <- tibble(\n  Model = c(\"`default ~ balance + student`\", \"`default ~ balance * student`\"),\n  k     = c(length(bda), length(bdi)),\n  AIC   = sprintf(\"%.2f\", c(AIC(default_additive), AIC(default_interaction)))\n) |>\n  knitr::kable(col.names = c(\"Model\", \"Parameters\", \"AIC\"), align = \"lcc\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Student        | Slope (log-odds per \\$1) | Odds ratio per \\$100 |\n|:--------------|:------------------------:|:--------------------:|\n|No (reference) |         0.005819         |        1.789         |\n|Yes            |         0.005599         |        1.751         |\n\n\n:::\n:::\n\n\nThe two per-\\$100 odds ratios differ by\n0.04, which is the difference the\ninteraction was added to capture. The $z$-test asks whether that difference is\nlarger than sampling error can explain:\n$z = -0.46$ with a $p$-value of\n$0.646$, and the 95% confidence interval for $\\beta_3$\nruns from $-0.00116$ to $0.00072$,\ncomfortably containing $0$.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nThe **Akaike information criterion**, $\\text{AIC} = -2\\ell(\\hat\\beta) + 2k$ for\na model with $k$ estimated parameters, scores a fit by its log-likelihood with\na penalty for the number of parameters it used; lower is better. It gives a\nsecond, test-free reading of whether a term earns its place.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Model                         | Parameters |   AIC   |\n|:-----------------------------|:----------:|:-------:|\n|`default ~ balance + student` |     3      | 1577.68 |\n|`default ~ balance * student` |     4      | 1579.47 |\n\n\n:::\n:::\n\n\nAdding the interaction makes AIC *worse* here: the extra parameter buys less\nlog-likelihood than it costs.\n:::\n\n**Conclusion.** Balance's effect on the odds of default does not depend on\nstudent status in these data. The estimated interaction is tiny, the two\nfitted models are visually indistinguishable on both scales, and the $z$-test\ngives no reason to prefer the more complicated one. The additive model of the\nprevious lecture is the one to report. The decision boundaries move\ncorrespondingly little: the balance at which $\\hat p = 0.5$ shifts from\n\\$1,873 to\n\\$1,869 for non-students and from\n\\$1,998 to\n\\$2,005 for\nstudents.\n\nNot every plausible interaction is a real one. Fitting it was still the right\nmove: the additive assumption was checked rather than assumed.\n\n## Store-specific price effects\n\n**Question.** Citrus Hill and Minute Maid are competing orange juice brands. If\na store raises the price of Citrus Hill, fewer customers should buy it — but\ndoes price act the same way in every store, or does the size of its effect\ndepend on where the purchase happens?\n\n**Data.** `ISLR2::OJ` records 1,070 individual\norange juice purchases. These are observed purchases, not simulated ones. Three\nof its 18 variables are used here:\n\n- `Purchase`: which brand the customer bought, a factor with levels\nCH and MM (Citrus Hill and Minute\nMaid). This is the response.\n- `SalePriceCH`: the price actually paid for Citrus Hill, in dollars, ranging\nfrom \\$1.39 to\n\\$2.09. This is the quantitative feature\n$X$.\n- `Store7`: whether the purchase happened at store 7, a factor with\n714 `No` and 356 `Yes`\npurchases. This supplies the indicator\n$D = \\mathrm{I}(\\texttt{Store7} = \\texttt{Yes})$.\n\nBuying Citrus Hill is the event of interest, so $Y_i = 1$ when purchase $i$ is\na Citrus Hill purchase. `glm()` models the probability of a factor's *second*\nlevel, and MM is second, so the event has to be set\nexplicitly with `relevel()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nOJ <- OJ |> mutate(Purchase = relevel(Purchase, ref = \"MM\"))\nlevels(OJ$Purchase)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"MM\" \"CH\"\n```\n\n\n:::\n:::\n\n\nWith `MM` as the reference level, every model below estimates\n$P(\\texttt{Purchase} = \\texttt{CH})$.\n\n### Exploratory analysis\n\nBefore fitting anything, plot each purchase against the price paid for\nCitrus Hill, split by whether the store was store 7:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\nOJ <- OJ |> mutate(ch01 = as.numeric(Purchase == \"CH\"))\n\noj_rates <- OJ |>\n  group_by(Store7, SalePriceCH) |>\n  summarize(n = n(), rate = mean(ch01), .groups = \"drop\")\n\noj_eda_plot <- ggplot(OJ, aes(x = SalePriceCH, y = ch01)) +\n  geom_jitter(height = 0.05, width = 0.008, alpha = 0.15, size = 0.8) +\n  geom_point(data = oj_rates, aes(y = rate, size = n),\n             shape = 1, color = \"#D55E00\") +\n  facet_wrap(~ Store7, labeller = label_both) +\n  scale_y_continuous(breaks = c(0, 0.5, 1),\n                     labels = c(\"MM (0)\", \"0.5\", \"CH (1)\")) +\n  scale_size_area(max_size = 5) +\n  labs(x = \"Citrus Hill sale price ($)\", y = \"Purchase\",\n       size = \"Purchases\\nat that price\", title = \"ISLR2::OJ\")\n\ncheap_max     <- 1.70\nexpensive_min <- 1.90\n\noj_ends <- OJ |>\n  filter(SalePriceCH <= cheap_max | SalePriceCH >= expensive_min) |>\n  mutate(band = ifelse(SalePriceCH <= cheap_max, \"cheap\", \"expensive\")) |>\n  group_by(Store7, band) |>\n  summarize(n = n(), rate = mean(ch01), .groups = \"drop\")\n\nend_of <- function(store, band, column) {\n  oj_ends[[column]][oj_ends$Store7 == store & oj_ends$band == band]\n}\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/oj-eda-figure-1.png){width=720}\n:::\n:::\n\n\nThe open circles are the observed proportion of Citrus Hill purchases at each\ndistinct price, sized by how many purchases were made at that price. Citrus\nHill takes 77% of\npurchases at store 7 against\n53% elsewhere.\n\nWithin each panel the proportions move with price, and they move in opposite\ndirections. Comparing the two ends of the price range, at store 7 Citrus Hill's\nshare falls from\n89% of the\n131 purchases priced at or below\n\\$1.70 to\n32% of the\n25 purchases at or above\n\\$1.90. Elsewhere it *rises* across the same two\nbands, from 35% of\n68 purchases to\n54% of\n200.\n\n### Fitting both models\n\n\n::: {.cell}\n\n```{.r .cell-code}\noj_additive    <- glm(Purchase ~ SalePriceCH + Store7,\n                      data = OJ, family = \"binomial\")\noj_interaction <- glm(Purchase ~ SalePriceCH * Store7,\n                      data = OJ, family = \"binomial\")\nsummary(oj_interaction)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       Estimate Std. Error   z value     Pr(>|z|)\n(Intercept)           -2.457672  1.2891769 -1.906388 5.659987e-02\nSalePriceCH            1.391651  0.6940046  2.005247 4.493662e-02\nStore7Yes             10.695551  2.0907256  5.115713 3.125587e-07\nSalePriceCH:Store7Yes -5.373799  1.1486621 -4.678312 2.892469e-06\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code for the table below\n\n::: {.cell}\n\n```{.r .cell-code}\nboa <- coef(oj_additive)\nboi <- coef(oj_interaction)\n\noj_coef_table <- tibble(\n  term        = names(boi),\n  additive    = c(boa, NA),\n  interaction = boi\n) |>\n  mutate(across(c(additive, interaction),\n                \\(x) ifelse(is.na(x), \"\", sprintf(\"%.3f\", x)))) |>\n  knitr::kable(col.names = c(\"Coefficient\", \"Additive fit\",\n                             \"Interaction fit\"),\n               align = \"lcc\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Coefficient           | Additive fit | Interaction fit |\n|:---------------------|:------------:|:---------------:|\n|(Intercept)           |    1.633     |     -2.458      |\n|SalePriceCH           |    -0.814    |      1.392      |\n|Store7Yes             |    0.991     |     10.696      |\n|SalePriceCH:Store7Yes |              |     -5.374      |\n\n\n:::\n:::\n\n\nThe intercept is the log-odds of a Citrus Hill purchase outside store 7 at a\nCitrus Hill price of \\$0, an extrapolation well below the\n\\$1.39 minimum in the data:\n$1.633$ in the additive fit and\n$-2.458$ in the interaction fit, since each fit carries\nits own reference-group slope back to \\$0 and those slopes have opposite signs.\nThe additive fit puts a single `SalePriceCH` coefficient of\n$-0.814$ on both stores. The interaction fit replaces it\nwith $1.392$ and\n$-3.982$, which have opposite signs.\n\n### Fitted log-odds\n\nPlotting $\\hat\\eta$ against price for each store shows what those two signs\nmean for the fitted lines:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the plots below\n\n::: {.cell}\n\n```{.r .cell-code}\noj_grid <- expand_grid(\n  SalePriceCH = seq(min(OJ$SalePriceCH), max(OJ$SalePriceCH), length.out = 300),\n  Store7 = factor(c(\"No\", \"Yes\"), levels = levels(OJ$Store7)))\n\noj_link <- bind_rows(\n  oj_grid |> mutate(Model = \"Additive\",\n                    eta = predict(oj_additive, newdata = oj_grid)),\n  oj_grid |> mutate(Model = \"Interaction\",\n                    eta = predict(oj_interaction, newdata = oj_grid)))\n\n# A shared base layer, so the two tabs below differ only in which model's\n# lines are drawn on it.\noj_link_base <- ggplot(mapping = aes(x = SalePriceCH, y = eta,\n                                     color = Store7, linetype = Store7)) +\n  geom_hline(yintercept = 0, color = \"grey60\", linewidth = 0.3) +\n  coord_cartesian(xlim = range(oj_grid$SalePriceCH),\n                  ylim = range(oj_link$eta)) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  labs(x = \"Citrus Hill sale price ($)\", y = expression(hat(eta)),\n       color = \"Store 7\", linetype = \"Store 7\", title = \"ISLR2::OJ\")\n\noj_link_additive <- oj_link_base +\n  geom_line(data = filter(oj_link, Model == \"Additive\"), linewidth = 0.9)\n\noj_link_interaction <- oj_link_base +\n  geom_line(data = filter(oj_link, Model == \"Interaction\"), linewidth = 0.9)\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Additive\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/oj-link-additive-plot-1.png){width=672}\n:::\n:::\n\n\n#### Interaction\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/oj-link-interaction-plot-1.png){width=672}\n:::\n:::\n\n:::\n\nThe additive tab shows the parallel lines the additive model requires, both\nsloping down at $-0.814$ log-odds per dollar. The\ninteraction tab shows lines of opposite sign: the store 7 line falls steeply\nwhile the other rises, and they cross at\n\\$1.99, inside the observed price range.\nSwitching between these two tabs changes the picture substantially, which is\nwhat the `Default` example did not do.\n\n### Fitted probabilities\n\nThe same two model fits, now on the scale a purchase decision actually uses,\nwith the observed proportions overlaid:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the plots below\n\n::: {.cell}\n\n```{.r .cell-code}\noj_prob <- bind_rows(\n  oj_grid |> mutate(Model = \"Additive\",\n                    p_hat = predict(oj_additive, newdata = oj_grid,\n                                    type = \"response\")),\n  oj_grid |> mutate(Model = \"Interaction\",\n                    p_hat = predict(oj_interaction, newdata = oj_grid,\n                                    type = \"response\")))\n\n# The same shared-base idea, with the observed proportions as the layer every\n# tab keeps.\noj_prob_base <- ggplot(mapping = aes(x = SalePriceCH, y = p_hat,\n                                     color = Store7, linetype = Store7)) +\n  geom_hline(yintercept = 0.5, color = \"grey60\", linewidth = 0.3) +\n  geom_point(data = oj_rates, aes(y = rate, size = n, shape = Store7),\n             alpha = 0.8) +\n  coord_cartesian(xlim = range(oj_grid$SalePriceCH), ylim = c(0, 1)) +\n  scale_y_continuous(breaks = c(0, 0.5, 1)) +\n  scale_size_area(max_size = 5) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  labs(x = \"Citrus Hill sale price ($)\", y = \"P(Purchase = CH)\",\n       color = \"Store 7\", linetype = \"Store 7\", shape = \"Store 7\",\n       size = \"Purchases\\nat that price\", title = \"ISLR2::OJ\")\n\noj_prob_data <- oj_prob_base\n\noj_prob_additive <- oj_prob_base +\n  geom_line(data = filter(oj_prob, Model == \"Additive\"), linewidth = 0.9)\n\noj_prob_interaction <- oj_prob_base +\n  geom_line(data = filter(oj_prob, Model == \"Interaction\"), linewidth = 0.9)\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Data\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/oj-prob-data-plot-1.png){width=720}\n:::\n:::\n\n\n#### + Additive\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/oj-prob-additive-plot-1.png){width=720}\n:::\n:::\n\n\n#### + Interaction\n\n::: {.cell}\n::: {.cell-output-display}\n![](30-flexible-logistic-regression_files/figure-html/oj-prob-interaction-plot-1.png){width=720}\n:::\n:::\n\n:::\n\nThe data tab shows the observed proportion of Citrus Hill purchases at each\nprice, by store. The additive tab fits them with two curves of identical shape\nthat never cross, both drifting down with price; the store 7 curve sits above\nthe other but is forced to decline at the same log-odds rate. The interaction\ntab lets store 7's curve fall steeply while the other edges upward, and the two\nmeet near the top of the observed price range.\n\n### Interpreting price slopes\n\nReading the two group-specific slopes off the interaction fit, and converting\neach to an odds ratio, makes the reversal concrete:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the table below\n\n::: {.cell}\n\n```{.r .cell-code}\nslope_no   <- unname(boi[2])\nslope_yes  <- unname(boi[2] + boi[4])\n\noj_slope_table <- tibble(\n  store = c(\"Not store 7 (reference)\", \"Store 7\"),\n  param = c(\"$\\\\beta_1$\", \"$\\\\beta_1 + \\\\beta_3$\"),\n  slope = c(slope_no, slope_yes),\n  or10  = exp(0.10 * c(slope_no, slope_yes))\n) |>\n  mutate(slope = sprintf(\"%.3f\", slope),\n         or10  = sprintf(\"%.3f\", or10)) |>\n  knitr::kable(col.names = c(\"Store\", \"Slope parameter\",\n                             \"Estimate (log-odds per \\\\$1)\",\n                             \"Odds ratio per \\\\$0.10\"),\n               align = \"llcc\")\n\nor10_no  <- exp(0.10 * slope_no)\nor10_yes <- exp(0.10 * slope_yes)\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Store                   |Slope parameter     | Estimate (log-odds per \\$1) | Odds ratio per \\$0.10 |\n|:-----------------------|:-------------------|:---------------------------:|:---------------------:|\n|Not store 7 (reference) |$\\beta_1$           |            1.392            |         1.149         |\n|Store 7                 |$\\beta_1 + \\beta_3$ |           -3.982            |         0.672         |\n\n\n:::\n:::\n\n\nAt store 7, each additional \\$0.10 on the Citrus Hill price multiplies the\nestimated odds of a Citrus Hill purchase by\n0.672 — a\n33% drop in the odds, the direction a price\nincrease is expected to push demand. Everywhere else the same \\$0.10 multiplies\nthe odds by 1.149, a\n15% *increase*.\n\nThat second estimate runs backwards from what price alone would predict, and\nthe observed proportions in the exploratory plot show the same thing without\nany model: outside store 7, Citrus Hill's share does not fall as its price\nrises. What these data cannot say is why — `SalePriceCH` records what was\npaid, not what else varied alongside it across stores and weeks, so the association it\ncarries need not be the effect of price by itself. The honest report is the\npattern and its limits, not a mechanism the data cannot supply.\n\n### Break-even prices\n\nThe decision boundary here is the Citrus Hill price at which the model puts the\ntwo brands at 50/50, computed separately for each store.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the table below\n\n::: {.cell}\n\n```{.r .cell-code}\noj_boundary <- function(b, interaction = TRUE) {\n  b3 <- if (interaction) b[4] else 0\n  c(`Not store 7` = unname(-b[1] / b[2]),\n    `Store 7`     = unname(-(b[1] + b[3]) / (b[2] + b3)))\n}\n\noj_boundaries <- bind_rows(\n  tibble(Model = \"Additive\",\n         Store = c(\"Not store 7\", \"Store 7\"),\n         price = oj_boundary(boa, interaction = FALSE)),\n  tibble(Model = \"Interaction\",\n         Store = c(\"Not store 7\", \"Store 7\"),\n         price = oj_boundary(boi)))\n\noj_boundary_table <- oj_boundaries |>\n  mutate(observed = ifelse(price >= min(OJ$SalePriceCH) &\n                           price <= max(OJ$SalePriceCH), \"yes\", \"no\"),\n         price = sprintf(\"\\\\$%.2f\", price)) |>\n  relocate(observed, .after = price) |>\n  knitr::kable(col.names = c(\"Model\", \"Store\", \"Price where $\\\\hat p = 0.5$\",\n                             \"In observed range?\"),\n               align = \"llcc\")\n\nboundary_at <- function(m, s) {\n  oj_boundaries$price[oj_boundaries$Model == m & oj_boundaries$Store == s]\n}\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Model       |Store       | Price where $\\hat p = 0.5$ | In observed range? |\n|:-----------|:-----------|:--------------------------:|:------------------:|\n|Additive    |Not store 7 |           \\$2.01           |        yes         |\n|Additive    |Store 7     |           \\$3.22           |         no         |\n|Interaction |Not store 7 |           \\$1.77           |        yes         |\n|Interaction |Store 7     |           \\$2.07           |        yes         |\n\n\n:::\n:::\n\n\nUnder the additive model, store 7's break-even price is\n\\$3.22, well beyond the\n\\$2.09 maximum any customer in the data\nactually paid: a single shared slope can only explain store 7's high Citrus\nHill share by pushing its break-even point outside the observed prices\nentirely. The interaction model brings it back to\n\\$2.07, inside the price\nrange, and moves the other stores' break-even point from\n\\$2.01 to\n\\$1.77. All four\nthresholds differ, and only the interaction model places both of its own\nwithin the prices customers actually paid.\n\n### Interaction test\n\n::: {.callout-note collapse=\"true\"}\n### Code for the values quoted below\n\n::: {.cell}\n\n```{.r .cell-code}\nocoef <- summary(oj_interaction)$coefficients\nz_o   <- ocoef[\"SalePriceCH:Store7Yes\", \"z value\"]\np_o   <- ocoef[\"SalePriceCH:Store7Yes\", \"Pr(>|z|)\"]\nci_o  <- confint.default(oj_interaction)[\"SalePriceCH:Store7Yes\", ]\n\naic_o_table <- tibble(\n  Model = c(\"`Purchase ~ SalePriceCH + Store7`\",\n            \"`Purchase ~ SalePriceCH * Store7`\"),\n  k     = c(length(boa), length(boi)),\n  AIC   = sprintf(\"%.2f\", c(AIC(oj_additive), AIC(oj_interaction)))\n) |>\n  knitr::kable(col.names = c(\"Model\", \"Parameters\", \"AIC\"), align = \"lcc\")\n```\n:::\n\n:::\n\nThe interaction coefficient is $\\hat\\beta_3 = -5.374$ with\n$z = -4.68$ and a $p$-value of $2.9\\times 10^{-6}$. The 95% confidence\ninterval for $\\beta_3$ runs from $-7.63$ to\n$-3.12$, entirely below $0$, so the interval for\n$e^{\\beta_3}$ lies entirely below $1$: store 7's per-dollar odds ratio is\nfirmly smaller than the other stores'.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nThe same AIC comparison used in the previous example, applied here:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Model                             | Parameters |   AIC   |\n|:---------------------------------|:----------:|:-------:|\n|`Purchase ~ SalePriceCH + Store7` |     3      | 1374.81 |\n|`Purchase ~ SalePriceCH * Store7` |     4      | 1352.75 |\n\n\n:::\n:::\n\n\nThe interaction lowers AIC by\n22.1, so the extra\nparameter earns more log-likelihood than it costs — the opposite of the verdict\nin the `Default` example.\n:::\n\n**Conclusion.** The association between Citrus Hill's price and the chance a\ncustomer buys it differs sharply between store 7 and the rest. At store 7 the\nestimated odds fall 33% per \\$0.10; elsewhere they\ndo not fall at all. The $z$-test rejects $H_0: \\beta_3 = 0$ decisively\n($z = -4.68$), the two models' fitted lines diverge visibly\non both scales, and the interaction model is the one to report — while noting\nthat the non-store-7 slope points the wrong way for a price effect and that\nthese data cannot say why.\n\n## Two examples, two verdicts\n\nBoth examples asked the same question with the same syntax, the same estimator,\nand the same test. `Default` answered no: the fitted slopes differed by almost\nnothing, the curves were indistinguishable, and the $p$-value was\n$0.646$. `OJ` answered yes: the fitted slopes had opposite\nsigns and the $p$-value was $2.9\\times 10^{-6}$.\n\nNothing about either pair of features announced which answer was coming. The\nadditive assumption is checkable, and checking it is the only way to find out —\nwhich is a reason to fit the interaction even when you expect the additive\nmodel to survive.\n\n## Polynomials and step functions\n\nInteractions are not the only flexibility available. Everything built in the\nfeature engineering and flexibility lectures for linear regression transfers to\nlogistic regression without modification, because those lectures worked on the\nlinear predictor and the linear predictor is unchanged here.\n\nRecall the structure. The log-odds form is\n\n$$\\log\\left(\\frac{p(X_i)}{1 - p(X_i)}\\right) = x_i\\beta,$$\n\nso anything that can be a column of the model matrix $\\mathbf{X}$ is available:\na squared feature, a step-function indicator\n$C_j(X) = \\mathrm{I}(c_j \\le X < c_{j+1})$ built from cut points\n$c_1 < c_2 < \\cdots$ exactly as in the flexibility lecture, a log-transformed\nfeature, a product of two features. The logistic function wrapped around\n$x_i\\beta$ never inspects what those columns contain.\n\nIn R this means the same formula syntax:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm(y ~ poly(x, 3),       data = d, family = \"binomial\")  # cubic in x\nglm(y ~ cut(x, breaks),   data = d, family = \"binomial\")  # step function in x\nglm(y ~ poly(x, 2) * sex, data = d, family = \"binomial\")  # separate quadratics by group\n```\n:::\n\n\nThree things do change, and all three are consequences of the logistic form\nrather than of the features:\n\n1. **The fitted curve is flexible on the log-odds scale**, and the logistic\nfunction then bends it toward $0$ and $1$. A cubic in the log-odds is not a\ncubic in $p(X)$.\n2. **Coefficients are read as changes in log-odds and odds ratios**, exactly as\nin the simple logistic regression lecture. For a step function, $\\beta_j$ is\nthe log-odds difference between bin $j$ and the baseline bin, so\n$e^{\\beta_j}$ is the odds ratio between those two bins — where in linear\nregression $\\beta_j$ was a difference between bin means.\n3. **Estimation is maximum likelihood, not least squares.** The extra columns\nadd parameters to the same Bernoulli log-likelihood, which `glm()` maximizes\nnumerically.\n\nThe costs are also unchanged. More flexible features fit the training data\nbetter and estimate more parameters from the same $n$, which is the\nbias-variance tradeoff of the flexibility lecture; a high-degree polynomial\nextrapolates just as badly in the log-odds as it does in a mean response.\n\n## Conclusion\n\nAn interaction lets a feature's effect on the log-odds depend on another\nfeature's value. With a quantitative feature and an indicator, it gives each\ngroup its own log-odds slope — $\\beta_1$ and $\\beta_1 + \\beta_3$ — and so its\nown odds ratio for that feature, with $e^{\\beta_3}$ the ratio between the two.\nThat is the same interaction structure used in linear regression, evaluated on\nthe log-odds scale instead of the mean-response scale, and fit by the same\nmaximum likelihood machinery as every other logistic regression.\n\nThe diagnostic is a picture on the linear-predictor scale: parallel lines mean\nthe additive model is adequate, non-parallel lines mean it is not.\n`ISLR2::Default` produced lines that were parallel to the eye and an\ninteraction the $z$-test could not distinguish from zero. `ISLR2::OJ` produced\nlines with opposite slopes, an interaction\n$\\hat\\beta_3 = -5.37$ that the same test rejected\ndecisively, and two stores whose break-even prices sit\n\\$0.30\napart.\n\nPolynomials, step functions, and interactions all enter logistic regression as\ncolumns of the same model matrix, so the model can be made as flexible as the\ndata support. Adding columns to a binary-response model can also break the\nestimation itself in a way that least squares never breaks, a failure that goes\nby the name separation.\n",
    "supporting": [
      "30-flexible-logistic-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}