{
  "hash": "0bf60ae4b86bf2859fc3f0d01bdc56cd",
  "result": {
    "engine": "knitr",
    "markdown": "# Quadratic Discriminant Analysis and Naive Bayes\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **derive** the QDA discriminant function $\\delta_k(x)$ from Gaussian\nclass-conditional densities with class-specific covariance matrices\n$\\Sigma_k$, and **show** that the resulting decision boundary is quadratic in\n$x$, with up to two boundary points when $p = 1$,\n- **count** the mean and covariance parameters that LDA, QDA, and Gaussian\nnaive Bayes estimate, and **use** the counts to **explain** through the\nbias-variance tradeoff when each should have the lowest test error rate,\n- **state** the naive Bayes assumption that the features are conditionally\nindependent given the class, **write** $f_k(x)$ as a product of one-feature\ndensities of possibly different types, and **show** that the log posterior\nodds are a sum of one-feature terms,\n- **identify** Gaussian naive Bayes as LDA or QDA with a diagonal covariance\nmatrix,\n- **compare** logistic regression, LDA, QDA, naive Bayes, and KNN by the shape\nof their decision boundaries, their assumptions, and how they are affected by\n$n$ and $p$, and **evaluate** which should perform best in a described\nsetting, and\n- **fit** QDA with `MASS::qda()` and naive Bayes with `e1071::naiveBayes()`,\n**interpret** their estimates, and **compare** classifiers by test error\nrate, sensitivity, specificity, and AUC on a held-out test set.\n:::\n\n## Generative classifier recap\n\nThe previous lecture built a classifier from the prior probabilities\n$\\pi_k = P(Y = k)$ and the class-conditional densities $f_k(x)$ of the\nfeatures through Bayes' theorem,\n\n$$p_k(x) = P(Y = k \\mid X = x) = \\frac{\\pi_k f_k(x)}{\\sum_{l=1}^K \\pi_l f_l(x)},$$\n\nand assigned each observation to the class with the largest posterior\nprobability. Every generative classifier in this course estimates $\\pi_k$ by\nthe class proportion $n_k/n$. They differ only in the model assumed for $f_k(x)$.\n\nLDA assumed $X \\mid Y = k \\sim N_p\\left(\\mu_k, \\Sigma\\right)$, with one\ncovariance matrix $\\Sigma$ shared by every class. That is what made the\nquadratic term in $x$ cancel and the boundary linear. In the credit card data\nit is already doubtful: the standard deviation of balance was smaller among\ndefaulters than among non-defaulters.\n\nThis lecture changes the model for $f_k(x)$ in two directions. Quadratic\ndiscriminant analysis gives each class its own covariance matrix. Naive Bayes\ndrops the multivariate Gaussian and treats the features as independent within\neach class.\n\n## Quadratic discriminant analysis\n\n### Class-specific covariance matrices\n\nQuadratic discriminant analysis (QDA) assumes the statistical model\n\n$$P(Y = k) = \\pi_k, \\qquad X \\mid Y = k \\sim N_p\\left(\\mu_k, \\Sigma_k\\right), \\qquad k = 1, \\ldots, K,$$\n\nwhere\n\n- $\\mu_k = E[X \\mid Y = k]$ is the $p$-vector of feature means in class $k$,\nas in LDA, and\n- $\\Sigma_k = Cov[X \\mid Y = k]$ is the $p \\times p$ covariance matrix of the\nfeatures **in class $k$**, symmetric and positive definite, and free to differ\nfrom class to class.\n\nThe class-conditional density is therefore\n\n$$f_k(x) = \\frac{1}{(2\\pi)^{p/2}\\left|\\Sigma_k\\right|^{1/2}} \\exp\\left[-\\frac{1}{2}\\left(x - \\mu_k\\right)^\\top \\Sigma_k^{-1} \\left(x - \\mu_k\\right)\\right],$$\n\nwhere $\\left|\\Sigma_k\\right|$ is the determinant of $\\Sigma_k$. Each class's\ncontours are still ellipses centered at $\\mu_k$, but now each class's\nellipses have their own size, shape, and orientation.\n\n### Quadratic discriminant\n\nAs in LDA, the class with the largest posterior probability is the class with\nthe largest $\\log\\left(\\pi_k f_k(x)\\right)$,\n\n$$\\log\\left(\\pi_k f_k(x)\\right) = \\log \\pi_k - \\frac{p}{2}\\log(2\\pi) - \\frac{1}{2}\\log\\left|\\Sigma_k\\right| - \\frac{1}{2}\\left(x - \\mu_k\\right)^\\top \\Sigma_k^{-1}\\left(x - \\mu_k\\right).$$\n\nOnly the term $-\\frac{p}{2}\\log(2\\pi)$ is common to every class. Dropping it\ngives the **quadratic discriminant function**\n\n$$\\delta_k(x) = -\\frac{1}{2}x^\\top \\Sigma_k^{-1} x + x^\\top \\Sigma_k^{-1}\\mu_k - \\frac{1}{2}\\mu_k^\\top \\Sigma_k^{-1}\\mu_k - \\frac{1}{2}\\log\\left|\\Sigma_k\\right| + \\log \\pi_k,$$\n\nafter expanding the quadratic form as in the previous lecture. Two terms that\ncancelled in LDA survive here:\n\n- $-\\frac{1}{2}x^\\top \\Sigma_k^{-1} x$ is quadratic in $x$ and carries a\ndifferent matrix in each class, and\n- $-\\frac{1}{2}\\log\\left|\\Sigma_k\\right|$ penalizes a class whose density is\nspread over a larger volume.\n\nWhen every $\\Sigma_k$ equals a common $\\Sigma$, both terms are the same in\nevery class, drop out, and $\\delta_k(x)$ reduces to the LDA discriminant.\nBecause only $-\\frac{p}{2}\\log(2\\pi)$, common to every class, was dropped,\nthe posterior probabilities are recovered as before, $p_k(x) = e^{\\delta_k(x)} / \\sum_l e^{\\delta_l(x)}$.\n\n### Quadratic decision boundary\n\nWith $K = 2$ classes the log posterior odds of class $2$ are\n\n$$\\log\\left(\\frac{p_2(x)}{1 - p_2(x)}\\right) = \\delta_2(x) - \\delta_1(x) = -\\frac{1}{2}x^\\top \\left(\\Sigma_2^{-1} - \\Sigma_1^{-1}\\right) x + x^\\top\\left(\\Sigma_2^{-1}\\mu_2 - \\Sigma_1^{-1}\\mu_1\\right) + \\beta_0,$$\n\nwhere\n\n- $\\beta_0 = \\log(\\pi_2/\\pi_1) - \\frac{1}{2}\\left(\\mu_2^\\top \\Sigma_2^{-1}\\mu_2 - \\mu_1^\\top \\Sigma_1^{-1}\\mu_1\\right) - \\frac{1}{2}\\log\\left(\\left|\\Sigma_2\\right| / \\left|\\Sigma_1\\right|\\right)$\nis the intercept, collecting the terms that do not involve $x$.\n\nThe log posterior odds are a quadratic function of the features: an\nintercept, $p$ linear terms $x_j$, where $x_j$ is the $j$th entry of $x$, and\n$p(p+1)/2$ squares $x_j^2$ and cross-products $x_j x_l$, with coefficients\ndetermined by the $\\mu_k$ and $\\Sigma_k$. The decision boundary, where the log\nposterior odds are zero, is a conic section when $p = 2$ instead of a line.\n\nWith one feature, writing $\\sigma_k^2$ for the class-$k$ variance, the log\nposterior odds are\n\n$$\\log\\left(\\frac{p_2(x)}{1 - p_2(x)}\\right) = \\frac{1}{2}\\left(\\frac{1}{\\sigma_1^2} - \\frac{1}{\\sigma_2^2}\\right)x^2 + \\left(\\frac{\\mu_2}{\\sigma_2^2} - \\frac{\\mu_1}{\\sigma_1^2}\\right)x + \\frac{\\mu_1^2}{2\\sigma_1^2} - \\frac{\\mu_2^2}{2\\sigma_2^2} + \\log\\frac{\\sigma_1}{\\sigma_2} + \\log\\frac{\\pi_2}{\\pi_1}.$$\n\nA quadratic in $x$ has up to two roots, so the boundary is up to two points.\nIf $\\sigma_2 > \\sigma_1$, the coefficient of $x^2$ is positive, the log\nposterior odds grow without bound in both directions, and the class with the\nlarger variance is assigned in both tails.\n\nThe figure below uses $\\mu_1 = 0$, $\\mu_2 = 1$, and equal priors. Each curve is\n$\\pi_k f_k(x)$, so the classifier switches classes wherever the curves cross.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_1 <- 0\nmu_2 <- 1\nsigma_shared <- 1\nsigma_1 <- 0.7\nsigma_2 <- 1.5\n\n# Roots of the one-feature QDA log posterior odds (equal priors).\nqda_roots_1d <- function(m1, s1, m2, s2) {\n  a  <- (1 / s1^2 - 1 / s2^2) / 2\n  b  <- m2 / s2^2 - m1 / s1^2\n  c0 <- m1^2 / (2 * s1^2) - m2^2 / (2 * s2^2) + log(s1 / s2)\n  sort(Re(polyroot(c(c0, b, a))))\n}\nroots_1d <- qda_roots_1d(mu_1, sigma_1, mu_2, sigma_2)\nx_star_shared <- (mu_1 + mu_2) / 2\n\ngrid_1d <- tibble(x = seq(-4, 5, length.out = 600))\n\ncurves_1d <- function(s1, s2) {\n  grid_1d |>\n    mutate(`k = 1` = 0.5 * dnorm(x, mu_1, s1),\n           `k = 2` = 0.5 * dnorm(x, mu_2, s2))\n}\n\nweighted_1d_plot <- function(s1, s2, x_star, title) {\n  curves_1d(s1, s2) |>\n    select(x, `k = 1`, `k = 2`) |>\n    pivot_longer(-x, names_to = \"class\", values_to = \"density\") |>\n    ggplot(aes(x = x, y = density, color = class, linetype = class)) +\n    geom_line(linewidth = 0.9) +\n    geom_vline(xintercept = x_star, linetype = \"dotted\") +\n    scale_color_manual(values = class_colors) +\n    labs(x = \"x\", y = expression(pi[k] * f[k](x)), color = \"Class\",\n         linetype = \"Class\", title = title)\n}\n\nshared_1d_plot <- weighted_1d_plot(\n  sigma_shared, sigma_shared, x_star_shared,\n  bquote(paste(\"Shared variance: \", sigma[1] == sigma[2],\n               \" = \", .(sigma_shared))))\n\nunequal_1d_plot <- weighted_1d_plot(\n  sigma_1, sigma_2, roots_1d,\n  bquote(paste(\"Class-specific variances: \", sigma[1] == .(sigma_1), \", \",\n               sigma[2] == .(sigma_2))))\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Shared variance\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/theory-1d-shared-figure-1.png){width=672}\n:::\n:::\n\n\n#### Class-specific variances\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/theory-1d-unequal-figure-1.png){width=672}\n:::\n:::\n\n:::\n\nWith a shared variance the curves cross once, at the midpoint\n$x^* = 0.5$: the LDA picture. With $\\sigma_2 > \\sigma_1$ the wider\nclass-$2$ curve rises above the narrow class-$1$ curve on both sides, and the\nclassifier assigns class $1$ only between\n$x = -1.42$ and\n$x = 0.87$.\n\nIn two dimensions the boundary is a curve. The figure below gives class $1$\nmean $(0, 0)^\\top$ and positively correlated features, and class $2$ mean\n$(1.5, 0.5)^\\top$, larger variances, and negatively correlated features, with\nequal priors. The ellipses are contours of each $f_k$.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_a    <- c(0, 0)\nmu_b    <- c(1.5, 0.5)\nSigma_a <- matrix(c(1, 0.5, 0.5, 1), nrow = 2)\nSigma_b <- matrix(c(3, -0.6, -0.6, 2), nrow = 2)\n\n# Two-class Gaussian log posterior odds of class 2, equal priors.\nlog_odds_gauss <- function(x1, x2, mu1, S1, mu2, S2) {\n  log(dmvnorm2(x1, x2, mu2, S2)) - log(dmvnorm2(x1, x2, mu1, S1))\n}\n\ngrid_2d <- expand_grid(x1 = seq(-3.5, 5.5, length.out = 220),\n                       x2 = seq(-3.5, 4, length.out = 200)) |>\n  mutate(`k = 1` = dmvnorm2(x1, x2, mu_a, Sigma_a),\n         `k = 2` = dmvnorm2(x1, x2, mu_b, Sigma_b),\n         qda = log_odds_gauss(x1, x2, mu_a, Sigma_a, mu_b, Sigma_b))\n\ngrid_2d_long <- grid_2d |>\n  pivot_longer(c(`k = 1`, `k = 2`), names_to = \"class\",\n               values_to = \"density\")\n\n# Contours at Mahalanobis radii 1 and 2 for each class.\ncontour_at <- function(S) exp(-c(1, 2)^2 / 2) / (2 * pi * sqrt(det(S)))\n\nmeans_2d <- tibble(class = c(\"k = 1\", \"k = 2\"),\n                   x1 = c(mu_a[1], mu_b[1]), x2 = c(mu_a[2], mu_b[2]))\n\ndensity_layers <- function(long_grid) {\n  list(\n    geom_contour(data = filter(long_grid, class == \"k = 1\"),\n                 aes(z = density, color = class, linetype = class),\n                 breaks = contour_at(Sigma_a), linewidth = 0.7),\n    geom_contour(data = filter(long_grid, class == \"k = 2\"),\n                 aes(z = density, color = class, linetype = class),\n                 breaks = contour_at(Sigma_b), linewidth = 0.7),\n    geom_point(data = means_2d, aes(color = class, shape = class), size = 3),\n    scale_color_manual(values = class_colors),\n    coord_fixed(xlim = c(-3.5, 5.5), ylim = c(-3.5, 4), expand = FALSE),\n    labs(x = expression(X[1]), y = expression(X[2]), color = \"Class\",\n         linetype = \"Class\", shape = \"Class\")\n  )\n}\n\ntheory_2d_base <- ggplot(mapping = aes(x = x1, y = x2)) +\n  density_layers(grid_2d_long)\n\ntheory_2d_densities <- theory_2d_base +\n  labs(title = \"Class densities with class-specific covariance matrices\")\n\n# The boundary uses \"longdash\", distinct from both class-contour linetypes.\ntheory_2d_qda <- theory_2d_base +\n  geom_contour(data = grid_2d, aes(z = qda), breaks = 0, color = \"black\",\n               linewidth = 1.1, linetype = \"longdash\") +\n  labs(title = \"QDA boundary (black, long dashes)\")\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Class densities\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/theory-2d-densities-figure-1.png){width=576}\n:::\n:::\n\n\n#### QDA boundary\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/theory-2d-qda-figure-1.png){width=576}\n:::\n:::\n\n:::\n\nThe class-$2$ ellipses are larger in every direction, so the QDA boundary is\nan ellipse around the class-$1$ mean, long enough to run off the plot at the\nlower left: class $1$ is assigned inside it and class $2$ everywhere outside\nit.\n\n### Class-specific covariance estimates\n\nThe priors and means are estimated as in LDA, $\\hat\\pi_k = n_k/n$ and\n$\\hat\\mu_k = \\frac{1}{n_k}\\sum_{i:\\, y_i = k} x_i$. Each covariance matrix is\nestimated from its own class alone,\n\n$$\\hat\\Sigma_k = \\frac{1}{n_k - 1}\\sum_{i:\\, y_i = k}\\left(x_i - \\hat\\mu_k\\right)\\left(x_i - \\hat\\mu_k\\right)^\\top,$$\n\nwhere\n\n- $x_i$ is the $p$-vector of feature values of observation $i$, as in the\nprevious lecture, and\n- $\\hat\\Sigma_k$ is the **class-$k$ sample covariance matrix**, whose divisor\n$n_k - 1$ accounts for the one estimated mean.\n\n`MASS::qda()` uses this divisor (maximum likelihood would use $n_k$), and\n$\\hat\\Sigma_k$, whose rank is at most $n_k - 1$, is invertible only if\n$n_k > p$.\n\n### Bias-variance tradeoff\n\nQDA's flexibility costs parameters. Not counting the $K - 1$ free priors,\nwhich every generative classifier estimates,\n\n$$\\text{LDA: } Kp + \\frac{p(p+1)}{2}, \\qquad \\text{QDA: } Kp + K\\,\\frac{p(p+1)}{2},$$\n\nwhere\n\n- $Kp$ counts the entries of the $K$ mean vectors, and\n- $p(p+1)/2$ counts the distinct entries of one symmetric $p \\times p$\ncovariance matrix: $p$ variances and $p(p-1)/2$ covariances.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_lda <- function(K, p) K * p + p * (p + 1) / 2\ncount_qda <- function(K, p) K * p + K * p * (p + 1) / 2\n\nparameter_table <- tibble(p = c(1, 2, 5, 10, 50)) |>\n  mutate(LDA = count_lda(2, p), QDA = count_qda(2, p),\n         across(c(LDA, QDA), \\(v) format(v, big.mark = \",\"))) |>\n  knitr::kable(col.names = c(\"Features $p$\", \"LDA\", \"QDA\"), align = \"ccc\")\n```\n:::\n\n:::\n\nWith $K = 2$ classes:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Features $p$ |  LDA  |  QDA  |\n|:------------:|:-----:|:-----:|\n|      1       |   3   |   4   |\n|      2       |   7   |  10   |\n|      5       |  25   |  40   |\n|      10      |  75   |  130  |\n|      50      | 1,375 | 2,650 |\n\n\n:::\n:::\n\n\nQDA's count grows like $Kp^2/2$, against LDA's $p^2/2$. When the\n$\\Sigma_k$ really differ, LDA's shared $\\Sigma$ makes its boundary the wrong\nshape however much data it sees: bias. QDA's boundary has the right shape, but\neach of its many covariance estimates comes from one class's observations and\nvaries from one training set to the next: variance.\n\nThe figure below draws repeated training sets from the two classes of the\nprevious figure, fits LDA and QDA to each, and overlays the fitted boundaries\n(thin grey) on the Bayes decision boundary (thick dashed), which is the QDA\nboundary computed from the true parameters. The first tab uses small training\nsets and the second large ones.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nrmvnorm2 <- function(n, mu, Sigma) {\n  sweep(matrix(rnorm(n * 2), n) %*% chol(Sigma), 2, mu, \"+\")\n}\n\ndraw_quadratic <- function(n_k) {\n  X <- rbind(rmvnorm2(n_k, mu_a, Sigma_a), rmvnorm2(n_k, mu_b, Sigma_b))\n  tibble(y = factor(rep(c(\"k = 1\", \"k = 2\"), each = n_k)),\n         x1 = X[, 1], x2 = X[, 2])\n}\n\ngrid_fit <- expand_grid(x1 = seq(-3.5, 5.5, length.out = 120),\n                        x2 = seq(-3.5, 4, length.out = 110))\n\nn_k_small <- 25\nn_k_large <- 250\nn_boundary_reps <- 20\n\nfitted_boundaries <- expand_grid(n_k = c(n_k_small, n_k_large),\n                                 rep = seq_len(n_boundary_reps)) |>\n  mutate(data = map(n_k, draw_quadratic),\n         LDA = map(data, \\(d) {\n           predict(MASS::lda(y ~ x1 + x2, data = d),\n                   newdata = grid_fit)$posterior[, \"k = 2\"]\n         }),\n         QDA = map(data, \\(d) {\n           predict(MASS::qda(y ~ x1 + x2, data = d),\n                   newdata = grid_fit)$posterior[, \"k = 2\"]\n         })) |>\n  select(-data) |>\n  pivot_longer(c(LDA, QDA), names_to = \"method\", values_to = \"p_hat\") |>\n  mutate(grid = list(grid_fit)) |>\n  unnest(c(grid, p_hat))\n\nvariability_plot <- function(nk) {\n  ggplot(filter(fitted_boundaries, n_k == nk), aes(x = x1, y = x2)) +\n    geom_contour(aes(z = p_hat - 0.5, group = rep), breaks = 0,\n                 color = \"grey55\", linewidth = 0.35) +\n    geom_contour(data = grid_2d, aes(z = qda), breaks = 0, color = \"black\",\n                 linewidth = 1.1, linetype = \"dashed\") +\n    facet_wrap(~ method) +\n    coord_fixed(xlim = c(-3.5, 5.5), ylim = c(-3.5, 4), expand = FALSE) +\n    labs(x = expression(X[1]), y = expression(X[2]),\n         title = bquote(paste(.(n_boundary_reps), \" fitted boundaries, \",\n                              n[k] == .(nk),\n                              \" per class; Bayes boundary dashed\")))\n}\nvariability_small <- variability_plot(n_k_small)\nvariability_large <- variability_plot(n_k_large)\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Small training sets\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/variability-small-figure-1.png){width=768}\n:::\n:::\n\n\n#### Large training sets\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/variability-large-figure-1.png){width=768}\n:::\n:::\n\n:::\n\nWith 25 observations per class the LDA lines vary in angle, and\nnone follows the curvature of the Bayes boundary.\nThe QDA curves follow the shape of the Bayes boundary but scatter widely\naround it, some closing into small ellipses and others opening out of the\nplot. With 250 per class the LDA lines tighten around a single line\nthat still misses the curvature, while the QDA curves collapse onto the Bayes\nboundary: more data reduces QDA's variance but not LDA's bias.\n\nLDA should therefore win when the training set is small relative to the\nnumber of covariance parameters, or when the class covariance matrices are\nclose to equal so that its bias is small. QDA should win when the covariance\nmatrices clearly differ and the training set is large enough to estimate\nthem. The simulation study later in this lecture checks the covariance half\nof this at a fixed training-set size.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nRegularized discriminant analysis compromises between the two by shrinking\neach class covariance toward the pooled one,\n$\\hat\\Sigma_k(\\alpha) = \\alpha\\hat\\Sigma_k + (1 - \\alpha)\\hat\\Sigma$, where\n$\\alpha = 0$ gives LDA and $\\alpha = 1$ gives QDA. The value of $\\alpha$ is a\nflexibility dial chosen from the data, as the next unit will choose the\nnumber of neighbors for KNN.\n:::\n\n## Naive Bayes\n\n### Conditional independence\n\nNaive Bayes keeps the generative framework but replaces the multivariate model\nfor $f_k$ with an assumption about how the features relate to one another:\n\n$$P(Y = k) = \\pi_k, \\qquad X_1, \\ldots, X_p \\text{ are independent given } Y = k, \\qquad X_j \\mid Y = k \\sim f_{kj},$$\n\nwhere\n\n- $X_j$ is the $j$th feature, the $j$th entry of the random vector $X$, and\n- $f_{kj}$ is the one-feature density (or probability mass function) of $X_j$\namong observations in class $k$.\n\nIndependence turns the joint density into a product of its marginals, so the\nclass-conditional density is\n\n$$f_k(x) = f_{k1}(x_1) \\times f_{k2}(x_2) \\times \\cdots \\times f_{kp}(x_p) = \\prod_{j=1}^p f_{kj}(x_j).$$\n\nThe posterior probability is Bayes' theorem with this product in place of\n$f_k(x)$.\n\nThe assumption is conditional on the class. Features that are related only\nbecause both differ between classes, such as two symptoms that are each more\ncommon among patients with a disease, can be independent within each class\nwhile being correlated overall.\n\n### Feature densities\n\nEach $f_{kj}$ describes a single feature in a single class, so each can be\nmodeled and estimated separately, and features of different types can use\ndensities of different types.\n\n- A quantitative feature is usually modeled as Gaussian,\n$X_j \\mid Y = k \\sim N\\left(\\mu_{kj}, \\sigma_{kj}^2\\right)$, with $\\mu_{kj}$\nand $\\sigma_{kj}^2$ estimated by the sample mean and variance of feature $j$\namong the class-$k$ training observations.\n- A binary feature is Bernoulli,\n$f_{kj}(x_j) = \\theta_{kj}^{x_j}\\left(1 - \\theta_{kj}\\right)^{1 - x_j}$ for\n$x_j \\in \\{0, 1\\}$, where $\\theta_{kj} = P(X_j = 1 \\mid Y = k)$ is estimated\nby the proportion of class-$k$ training observations with $x_j = 1$.\n- A categorical feature with more than two levels gets one probability per\nlevel in each class, estimated by the class-$k$ proportions at each level.\n\n### Additive log posterior odds\n\nWith $K = 2$, the logarithm of the product is a sum, and the log posterior\nodds of class $2$ are\n\n$$\\log\\left(\\frac{p_2(x)}{1 - p_2(x)}\\right) = \\log\\frac{\\pi_2}{\\pi_1} + \\sum_{j=1}^p \\log\\frac{f_{2j}(x_j)}{f_{1j}(x_j)} = \\log\\frac{\\pi_2}{\\pi_1} + \\sum_{j=1}^p g_j(x_j),$$\n\nwhere\n\n- $g_j(x_j) = \\log\\left(f_{2j}(x_j)/f_{1j}(x_j)\\right)$ is the contribution of\nfeature $j$, a function of $x_j$ alone.\n\nEach feature shifts the log posterior odds by an amount that does not depend\non the values of the other features: naive Bayes is an additive model with no\ninteractions, the same structural restriction as the additive logistic\nregressions of the multiple logistic regression lecture. The form of each\n$g_j$ follows from the type of $f_{kj}$:\n\n- Gaussian with class-specific variances: $g_j$ is quadratic in $x_j$, with\ncoefficient $\\frac{1}{2}\\left(1/\\sigma_{1j}^2 - 1/\\sigma_{2j}^2\\right)$ on\n$x_j^2$.\n- Gaussian with a variance shared by the two classes: the $x_j^2$ terms\ncancel and $g_j$ is linear in $x_j$.\n- Bernoulli: $g_j(x_j) = x_j\\log\\left(\\theta_{2j}/\\theta_{1j}\\right) + \\left(1 - x_j\\right)\\log\\left[\\left(1 - \\theta_{2j}\\right)/\\left(1 - \\theta_{1j}\\right)\\right]$,\nlinear in $x_j$, so the feature shifts the log posterior odds by\n$\\log\\left\\{\\left[\\theta_{2j}/\\left(1 - \\theta_{2j}\\right)\\right] / \\left[\\theta_{1j}/\\left(1 - \\theta_{1j}\\right)\\right]\\right\\}$\nwhen $x_j$ changes from $0$ to $1$.\n\n### Diagonal covariance\n\nWhen every $f_{kj}$ is Gaussian, the product of $p$ independent normal\ndensities is a multivariate normal density with a diagonal covariance matrix:\n\n$$\\prod_{j=1}^p \\frac{1}{\\sqrt{2\\pi}\\,\\sigma_{kj}}\\exp\\left[-\\frac{\\left(x_j - \\mu_{kj}\\right)^2}{2\\sigma_{kj}^2}\\right] = \\frac{1}{(2\\pi)^{p/2}\\left|\\Lambda_k\\right|^{1/2}}\\exp\\left[-\\frac{1}{2}\\left(x - \\mu_k\\right)^\\top \\Lambda_k^{-1}\\left(x - \\mu_k\\right)\\right],$$\n\nwhere\n\n- $\\Lambda_k = \\text{diag}\\left(\\sigma_{k1}^2, \\ldots, \\sigma_{kp}^2\\right)$ is the\ndiagonal matrix of class-$k$ feature variances, whose determinant is\n$\\prod_j \\sigma_{kj}^2$ and whose inverse is diagonal with entries\n$1/\\sigma_{kj}^2$.\n\nGaussian naive Bayes with class-specific variances is therefore QDA with\nevery $\\Sigma_k$ restricted to be diagonal, and Gaussian naive Bayes with one\nvariance per feature shared across classes is LDA with $\\Sigma$ restricted to\nbe diagonal.\n\nThe figure below uses the two classes of the QDA figures. Naive Bayes keeps\neach class's mean and feature variances but discards the correlations; the\nellipses drawn are contours of the naive Bayes densities.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nLambda_a <- diag(diag(Sigma_a))   # diagonal covariance: variances only\nLambda_b <- diag(diag(Sigma_b))\n\ngrid_nb <- grid_2d |>\n  select(x1, x2, qda) |>\n  mutate(nb = log_odds_gauss(x1, x2, mu_a, Lambda_a, mu_b, Lambda_b),\n         `k = 1` = dmvnorm2(x1, x2, mu_a, Lambda_a),\n         `k = 2` = dmvnorm2(x1, x2, mu_b, Lambda_b))\n\ngrid_nb_long <- grid_nb |>\n  pivot_longer(c(`k = 1`, `k = 2`), names_to = \"class\",\n               values_to = \"density\")\n\nnb_density_plot <- ggplot(mapping = aes(x = x1, y = x2)) +\n  geom_contour(data = filter(grid_nb_long, class == \"k = 1\"),\n               aes(z = density, color = class, linetype = class),\n               breaks = contour_at(Lambda_a), linewidth = 0.7) +\n  geom_contour(data = filter(grid_nb_long, class == \"k = 2\"),\n               aes(z = density, color = class, linetype = class),\n               breaks = contour_at(Lambda_b), linewidth = 0.7) +\n  geom_point(data = means_2d, aes(color = class, shape = class), size = 3) +\n  scale_color_manual(values = class_colors) +\n  coord_fixed(xlim = c(-3.5, 5.5), ylim = c(-3.5, 4), expand = FALSE) +\n  labs(x = expression(X[1]), y = expression(X[2]), color = \"Class\",\n       linetype = \"Class\", shape = \"Class\")\n\n# Boundary linetypes \"longdash\" and \"twodash\" differ from the contour linetypes.\nnb_boundary_plot <- nb_density_plot +\n  geom_contour(data = grid_nb, aes(z = nb), breaks = 0, color = \"grey40\",\n               linewidth = 1.1, linetype = \"twodash\") +\n  geom_contour(data = grid_nb, aes(z = qda), breaks = 0, color = \"black\",\n               linewidth = 1.1, linetype = \"longdash\") +\n  labs(title = \"Bayes boundary (black, long dashes) and\\nnaive Bayes boundary (grey, dash-dot)\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/theory-nb-boundary-figure-1.png){width=576}\n:::\n:::\n\n\nUnlike the class densities of the QDA figure, the naive Bayes ellipses are\naligned with the feature axes. The naive Bayes boundary is still an ellipse,\nbecause class $2$'s variance is the larger in both features, and since its\nquadratic has no $x_1 x_2$ term it is aligned with the axes too. Ignoring the\ncorrelations replaces the long, tilted Bayes ellipse with a rounder one: naive Bayes assigns class $1$ to\npart of the upper left where the Bayes classifier assigns class $2$, and\nclass $2$ to the lower-left extension of the Bayes ellipse, where the Bayes\nclassifier assigns class $1$.\n\n### Parameter count\n\nGaussian naive Bayes with class-specific variances estimates $Kp$ means and\n$Kp$ variances, $2Kp$ parameters, against QDA's\n$Kp + Kp(p+1)/2$. With $K = 2$ and $p = 50$ that is\n200 parameters against\n2,650. The count grows linearly in\n$p$, and each parameter is estimated from one feature in one class, using all\n$n_k$ observations of that class.\n\nFor $p$ binary features the saving is larger still: a joint probability mass\nfunction has $2^p$ cells per class ($2^p - 1$ free probabilities, or\n1,048,575 when $p = 20$), most of them never\nobserved in a training set, against naive Bayes's $p$ Bernoulli\nprobabilities, which sidesteps the curse of dimensionality of the flexibility\nlecture.\n\nThe price is bias whenever the features are dependent within a class, which\nin practice is almost always. A classification depends only on which side of\nthe threshold the estimated posterior probability falls, so a biased estimate\nof $f_k(x)$ still gives the Bayes classifier's answer wherever the posterior\nprobability it produces falls on the same side of the threshold as the true\none. Whether it does is a question for data, taken up in the\nnext two sections.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nA quantitative feature need not be modeled as Gaussian. Each $f_{kj}$ can\ninstead be estimated nonparametrically, by a histogram or a kernel density\nestimate of feature $j$ within class $k$, since each is a one-dimensional\ndensity. The `naivebayes` package offers this option.\n:::\n\n## Classifier comparison\n\n### KNN classification\n\nFive classifiers are now available: logistic regression, LDA, QDA, naive\nBayes, and K-nearest neighbors (KNN). From here through the worked example,\n$K$ is the number of neighbors rather than the number of classes: every comparison has two classes, and the number of\nclasses is written as $2$.\n\nThe flexibility lecture introduced KNN for a quantitative response. For a\nqualitative response the neighbors vote:\n\n$$\\hat p_k(x_0) = \\frac{1}{K}\\sum_{i \\in \\mathcal{N}_0}\\mathrm{I}(y_i = k),$$\n\nwhere\n\n- $K$ is the **number of neighbors**,\n- $\\mathcal{N}_0$ is the set of the $K$ training observations closest to $x_0$\nin Euclidean distance after every feature, in the training data and in $x_0$\nalike, is standardized by its training mean and standard deviation, since\nthat distance depends on each feature's scale (as in the flexibility\nlecture), and\n- $\\hat p_k(x_0)$ is the proportion of those neighbors in class $k$, and the\nclassifier assigns the class with the largest proportion.\n\n### Boundary shapes\n\nWith two classes, the four model-based classifiers differ in the form of the\nlog posterior odds they can represent:\n\n$$\\begin{aligned}\n\\text{Logistic regression, LDA: } & \\beta_0 + \\sum_{j=1}^p \\beta_j x_j, \\\\\n\\text{QDA: } & \\beta_0 + \\sum_{j=1}^p \\beta_j x_j + \\sum_{j \\le l} \\gamma_{jl} x_j x_l, \\\\\n\\text{Gaussian naive Bayes: } & \\beta_0 + \\sum_{j=1}^p \\left(\\beta_j x_j + \\gamma_{jj} x_j^2\\right),\n\\end{aligned}$$\n\nwhere\n\n- $\\beta_0$ is an intercept and $\\beta_j$ the coefficient of $x_j$, with\nvalues that differ from method to method, and\n- $\\gamma_{jl}$ is the coefficient of the product $x_j x_l$, a square when\n$l = j$.\n\nA naive Bayes classifier with Bernoulli or categorical features adds terms\nlinear in those features' indicators. KNN has no formula for its log\nposterior odds. The table summarizes all five:\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison_table <- tibble(\n  Method = c(\"Logistic regression\", \"LDA\", \"QDA\", \"Gaussian naive Bayes\",\n             \"KNN\"),\n  Boundary = c(\"Linear\", \"Linear\", \"Quadratic\", \"Quadratic, no cross-products\",\n               \"Any shape\"),\n  Assumption = c(\"Linear log-odds\",\n                 \"Gaussian, shared covariance\",\n                 \"Gaussian, class covariances\",\n                 \"Features independent within each class\",\n                 \"Smooth class probabilities\"),\n  Estimation = c(\"Iterative\", \"Closed form\", \"Closed form\", \"Closed form\",\n                 \"None (stores data)\")\n) |>\n  knitr::kable(align = \"llll\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Method               |Boundary                     |Assumption                             |Estimation         |\n|:--------------------|:----------------------------|:--------------------------------------|:------------------|\n|Logistic regression  |Linear                       |Linear log-odds                        |Iterative          |\n|LDA                  |Linear                       |Gaussian, shared covariance            |Closed form        |\n|QDA                  |Quadratic                    |Gaussian, class covariances            |Closed form        |\n|Gaussian naive Bayes |Quadratic, no cross-products |Features independent within each class |Closed form        |\n|KNN                  |Any shape                    |Smooth class probabilities             |None (stores data) |\n\n\n:::\n:::\n\n\nReading down the table:\n\n- **Logistic regression and LDA** share a linear form and differ in\nestimation. LDA adds the Gaussian, shared-covariance assumption; when it\nholds, both estimate the same log posterior odds, and when it fails, logistic\nregression, which never models the features' distribution, is unaffected by\nthat failure provided the log-odds remain linear.\n- **QDA** adds every square and cross-product. A logistic regression given\nthose same squared and product features, as in the flexible logistic\nregression lecture, has the same quadratic form, fit by the conditional\nlikelihood instead.\n- **Naive Bayes** is the most restricted of the quadratic forms, with no\ncross-products, and in exchange has fewer parameters than QDA.\n- **KNN** is nonparametric: it assumes no form at all, and its flexibility is\nset by $1/K$. It can follow any boundary given enough data, but it needs $n$\nlarge relative to $p$, suffers most from the curse of dimensionality, and has\nno coefficients to interpret.\n\nIncreasing $n$ favors the more flexible methods, QDA and KNN, whose lower\nbias becomes affordable as their variance shrinks. Increasing $p$ favors the\nmore restricted ones: naive Bayes, whose parameter count grows linearly in\n$p$, and LDA, whose count grows like $p^2/2$ rather than like QDA's $p^2$ for\ntwo classes. No method is best in every setting.\n\n### Simulated scenarios\n\nA small simulation puts these predictions to a test. Each of four scenarios\nhas two classes with equal priors, a data-generating process chosen so that a\ndifferent method's assumptions hold:\n\n- **Linear**: two Gaussian features, a shared covariance matrix with\ncorrelation $0.5$, and different means, so the Bayes boundary is a line.\n- **Quadratic**: the two classes of the QDA figures, with class-specific\ncovariance matrices.\n- **Independent, $p = 10$**: ten Gaussian features, independent within each\nclass; the classes differ in the means of the first five features and the\nvariances of the last five.\n- **Non-linear**: two features uniform on a square, class $2$ above the curve\n$x_2 = \\sin(2x_1)$ and class $1$ below it, and then $10\\%$ of the class labels\nflipped at random, so neither class is Gaussian and the Bayes boundary is the\nsine curve.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nscenario_names <- c(\"Linear\", \"Quadratic\", \"Independent, p = 10\",\n                    \"Non-linear\")\nn_reps <- 100       # training sets per scenario\nn_train_k <- 50     # training observations per class\nn_test_k <- 2000    # test observations per class\nk_sim <- odd_above_sqrt(2 * n_train_k)\nknn_sim_name <- paste0(\"KNN, K = \", k_sim)\n\nrmvnorm_p <- function(n, mu, Sigma) {\n  sweep(matrix(rnorm(n * length(mu)), n) %*% chol(Sigma), 2, mu, \"+\")\n}\n\n# One data set of 2 * n_k observations, n_k per class (in expectation for the\n# non-linear scenario, whose class sizes are random).\ndraw_scenario <- function(scenario, n_k) {\n  labels <- c(\"Class 1\", \"Class 2\")\n  if (scenario == \"Non-linear\") {\n    X <- matrix(runif(4 * n_k, -2, 2), ncol = 2)\n    y <- as.numeric(X[, 2] > sin(2 * X[, 1]))\n    flip <- runif(2 * n_k) < 0.1\n    y[flip] <- 1 - y[flip]\n    y <- factor(labels[y + 1], levels = labels)\n  } else {\n    if (scenario == \"Linear\") {\n      S <- matrix(c(1, 0.5, 0.5, 1), nrow = 2)\n      X <- rbind(rmvnorm_p(n_k, c(0, 0), S), rmvnorm_p(n_k, c(1.5, 0.5), S))\n    }\n    if (scenario == \"Quadratic\") {\n      X <- rbind(rmvnorm_p(n_k, mu_a, Sigma_a), rmvnorm_p(n_k, mu_b, Sigma_b))\n    }\n    if (scenario == \"Independent, p = 10\") {\n      X <- rbind(rmvnorm_p(n_k, rep(0, 10), diag(10)),\n                 rmvnorm_p(n_k, rep(c(0.5, 0), each = 5),\n                           diag(rep(c(1, 2), each = 5))))\n    }\n    y <- factor(rep(labels, each = n_k), levels = labels)\n  }\n  colnames(X) <- paste0(\"x\", seq_len(ncol(X)))\n  bind_cols(tibble(y = y), as_tibble(X))\n}\n\n# Bayes classifier's error rate on a test set, from the true model.\nbayes_error <- function(scenario, test) {\n  X <- as.matrix(select(test, -y))\n  truth <- test$y == \"Class 2\"\n  if (scenario == \"Non-linear\") {\n    pred <- X[, 2] > sin(2 * X[, 1])\n  } else {\n    if (scenario == \"Linear\") {\n      S <- matrix(c(1, 0.5, 0.5, 1), nrow = 2)\n      lo <- log_odds_gauss(X[, 1], X[, 2], c(0, 0), S, c(1.5, 0.5), S)\n    }\n    if (scenario == \"Quadratic\") {\n      lo <- log_odds_gauss(X[, 1], X[, 2], mu_a, Sigma_a, mu_b, Sigma_b)\n    }\n    if (scenario == \"Independent, p = 10\") {\n      lo <- rowSums(dnorm(X, rep(c(0.5, 0), each = 5)[col(X)],\n                          sqrt(rep(c(1, 2), each = 5))[col(X)], log = TRUE) -\n                    dnorm(X, 0, 1, log = TRUE))\n    }\n    pred <- lo > 0\n  }\n  mean(pred != truth)\n}\n\n# Test error rate of each method fit to one training set.\nfit_methods <- function(train, test) {\n  truth <- test$y\n  X_train <- as.matrix(select(train, -y))\n  X_test  <- as.matrix(select(test, -y))\n  # KNN uses features standardized by the training means and SDs.\n  centers <- colMeans(X_train)\n  scales  <- apply(X_train, 2, sd)\n  Z_train <- scale(X_train, centers, scales)\n  Z_test  <- scale(X_test, centers, scales)\n  k_sqrt  <- odd_above_sqrt(nrow(train))\n  glm_fit <- glm(y ~ ., data = train, family = \"binomial\")\n  errors <- c(`Logistic regression` = mean(\n      (predict(glm_fit, newdata = test, type = \"response\") > 0.5) !=\n        (truth == \"Class 2\")),\n    LDA = mean(predict(MASS::lda(y ~ ., data = train), test)$class != truth),\n    QDA = mean(predict(MASS::qda(y ~ ., data = train), test)$class != truth),\n    `Naive Bayes` = mean(\n      predict(e1071::naiveBayes(y ~ ., data = train), test) != truth),\n    `KNN, K = 1` = mean(class::knn(Z_train, Z_test, train$y, k = 1) != truth),\n    knn_sqrt = mean(class::knn(Z_train, Z_test, train$y, k = k_sqrt) != truth))\n  names(errors)[names(errors) == \"knn_sqrt\"] <- paste0(\"KNN, K = \", k_sqrt)\n  errors\n}\n\nscenario_results <- map(scenario_names, \\(s) {\n  test <- draw_scenario(s, n_test_k)\n  errors <- map(seq_len(n_reps),\n                \\(r) fit_methods(draw_scenario(s, n_train_k), test))\n  list(errors = bind_rows(errors) |> mutate(scenario = s, rep = row_number()),\n       bayes = bayes_error(s, test))\n})\n\nmethod_levels <- c(\"Logistic regression\", \"LDA\", \"QDA\", \"Naive Bayes\",\n                   \"KNN, K = 1\", knn_sim_name)\n\nscenario_errors <- map(scenario_results, \"errors\") |>\n  bind_rows() |>\n  pivot_longer(all_of(method_levels), names_to = \"method\",\n               values_to = \"error\") |>\n  mutate(method = factor(method, levels = method_levels),\n         scenario = factor(scenario, levels = scenario_names))\n\nscenario_bayes <- tibble(\n  scenario = factor(scenario_names, levels = scenario_names),\n  bayes = map_dbl(scenario_results, \"bayes\"))\n\nscenario_means <- scenario_errors |>\n  group_by(scenario, method) |>\n  summarize(mean_error = mean(error), .groups = \"drop\")\n\nmean_error_of <- function(s, m) {\n  scenario_means$mean_error[scenario_means$scenario == s &\n                              scenario_means$method == m]\n}\nbest_method <- function(s) {\n  d <- filter(scenario_means, scenario == s)\n  as.character(d$method[which.min(d$mean_error)])\n}\npct <- function(v) sprintf(\"%.1f%%\", 100 * v)\n\n# Prose labels for the winning method of each scenario.\nprose_label <- c(\"Logistic regression\" = \"logistic regression\", \"LDA\" = \"LDA\",\n                 \"QDA\" = \"QDA\", \"Naive Bayes\" = \"naive Bayes\",\n                 \"KNN, K = 1\" = \"KNN with $K = 1$\")\nprose_label[knn_sim_name] <- paste0(\"KNN with $K = \", k_sim, \"$\")\nwinner <- function(s) unname(prose_label[best_method(s)])\n\npp <- function(v) sprintf(\"%.3f\", 100 * v)   # percentage points\n\n# One training set per scenario to show what the data look like; the\n# independent scenario is shown in features 1 (mean shift) and 6 (variance).\nscenario_examples <- map(scenario_names, \\(s) {\n  draw_scenario(s, n_train_k) |>\n    transmute(y, first = x1, second = if (s == \"Independent, p = 10\") x6 else x2,\n              scenario = s)\n}) |>\n  bind_rows() |>\n  mutate(scenario = factor(scenario, levels = scenario_names))\n\nscenario_data_plot <- ggplot(scenario_examples,\n                             aes(x = first, y = second, color = y, shape = y)) +\n  geom_point(size = 1.6, alpha = 0.8) +\n  facet_wrap(~ scenario, scales = \"free\") +\n  scale_color_manual(values = class_colors) +\n  labs(x = \"First plotted feature\", y = \"Second plotted feature\",\n       color = \"Class\", shape = \"Class\",\n       title = \"One training set per scenario (Independent: features 1 and 6)\")\n\nscenario_error_plot <- ggplot(scenario_errors, aes(x = method, y = error)) +\n  geom_boxplot(outlier.size = 0.6, fill = \"grey90\") +\n  geom_hline(data = scenario_bayes, aes(yintercept = bayes),\n             linetype = \"dashed\") +\n  facet_wrap(~ scenario, scales = \"free_y\") +\n  labs(x = NULL, y = \"Test error rate\",\n       title = paste(\"Test error rates over\", n_reps,\n                     \"training sets; Bayes error rate dashed\")) +\n  theme(axis.text.x = element_text(angle = 35, hjust = 1))\n```\n:::\n\n:::\n\nIn each scenario, 100 training sets of 100 observations\nwere drawn, 50 per class (in expectation in the non-linear\nscenario). Each method was fit to every training set and its error rate\ncomputed on one large test set of 4,000\nobservations drawn from the same scenario. KNN was fit on standardized\nfeatures with $K = 1$ and with\n$K = 11$, the smallest odd integer above $\\sqrt{n}$ for the\n$n = 100$ training observations: odd so that a two-class vote\ncannot tie, and near $\\sqrt{n}$ as a rule of thumb rather than an optimal\nchoice. Both are fixed in advance, since choosing $K$ from the data requires\nthe resampling methods of the next unit.\n\n::: {.panel-tabset}\n#### Scenarios\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/scenario-data-figure-1.png){width=768}\n:::\n:::\n\n\n#### Test error rates\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/scenario-error-figure-1.png){width=768}\n:::\n:::\n\n:::\n\nEach box summarizes the test error rates of one method over the\n100 training sets, and the dashed line is the Bayes error rate, the\nfloor no classifier can beat on average.\n\n- **Linear.** Logistic regression and LDA\nboth average 22.6%,\nagainst a Bayes error rate of\n22.1%. QDA, whose extra covariance parameters are\nunnecessary here, averages 22.9%: with only\ntwo features its variance penalty is small. Naive Bayes, which ignores the\ncorrelation, averages 24.7%.\n- **Quadratic.** QDA's average of 22.5%\nbeats logistic regression's\n28.4% and LDA's\n28.3%: the linear methods' bias outweighs\nQDA's variance. Naive Bayes, curved but missing the cross-product, falls between\nat 24.7%.\n- **Independent, $p = 10$.** Naive Bayes, whose assumption holds exactly,\naverages 25.7% with\n40 parameters. QDA's model also contains the truth, but it\nestimates 130 parameters from 100 observations and averages\n31.8%. KNN, with ten\ndimensions to search for neighbors, averages\n35.6% with\n$K = 11$.\n- **Non-linear.** No model-based method can represent a sine curve, and all\nfour average between\n21.7%\nand\n21.8%.\nKNN with $K = 11$ averages\n17.8%. With $K = 1$ its variance\nerases that advantage: it averages\n21.8%, about the same as the\nmodel-based methods.\n\nIn the quadratic, independent, and non-linear scenarios the best method is the\none whose assumptions are the most restrictive ones that still hold:\nQDA in the quadratic, naive Bayes in\nthe independent, and KNN with $K = 11$ in the non-linear scenario. In\nthe linear scenario both LDA and logistic regression are correct models, and\ntheir averages differ by only\n0.012\npercentage points, with\nlogistic regression ahead:\nwith two features, LDA's extra assumption buys essentially nothing. None wins\nin every scenario.\n\n## Credit card default classification\n\n**Question.** Do QDA and naive Bayes, which change LDA's model in different\ndirections, classify new credit card customers more accurately than LDA and\nlogistic regression, and how does KNN compare?\n\nThese customers were analyzed in the logistic regression lectures and, with\n`balance` and `income`, in the previous lecture, which found LDA's\nassumptions strained. This lecture keeps those two features, evaluates every\nclassifier on customers it was not fit to, and ends with separate models for\nstudents and non-students.\n\n**Data.** `ISLR2::Default` records 10,000\ncustomers. The response is `default`, with `Yes` the positive class. The\nexplanatory variables are `balance`, the monthly credit card balance in\ndollars, and `income`, the customer's income in dollars; the features are the\nexplanatory variables themselves. Student status defines the strata of the\nlast subsection.\n\n### Training and test sets\n\nThe previous lecture's error rates were training error rates, optimistic\nbecause each customer helped fit the model that classified it. Here, as in the\nclassification lecture's bias-variance script, the customers are split at\nrandom into halves; every model is fit to the training half and evaluated on\nthe test half, whose customers it never saw.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# Its own seed, so the split does not depend on the simulation above.\nset.seed(20261001)\ntrain_id <- sample(nrow(Default), nrow(Default) / 2)\ntrain <- Default[train_id, ]\ntest  <- Default[-train_id, ]\n\nn_defaults <- c(train = sum(train$default == \"Yes\"),\n                test  = sum(test$default == \"Yes\"))\n```\n:::\n\n:::\n\nEach half holds 5,000 customers, with\n176 defaulters in the training set and\n157 in the test set. A different split would give somewhat\ndifferent test error rates; averaging over many splits is a topic of the\nresampling unit.\n\n### Class summaries\n\nThe figure below plots income against balance for the training customers,\ndefaulters and non-defaulters distinguished by color and shape, with each\nclass's 95% normal-theory ellipse, the contour of a Gaussian density with that\nclass's sample mean and covariance matrix.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndollars <- function(v) paste0(\"\\\\$\", format(round(v), big.mark = \",\"))\n# Axis labels such as $60,000, without the scales package.\ndollar_labels <- function(v) ifelse(is.na(v), NA, paste0(\"$\", format(v, big.mark = \",\", scientific = FALSE, trim = TRUE)))\n\nclass_summary <- train |>\n  group_by(default) |>\n  summarize(sd_balance = sd(balance), sd_income = sd(income),\n            cor_balance_income = cor(balance, income), .groups = \"drop\")\nsummary_of <- function(k, col) class_summary[[col]][class_summary$default == k]\nstudent_income <- function(s) median(train$income[train$student == s])\n\n# Defaulters are drawn last so they are not hidden under non-defaulters.\neda_scatter <- ggplot(arrange(train, default), aes(x = balance, y = income)) +\n  geom_point(aes(color = default, shape = default), alpha = 0.35, size = 0.8) +\n  stat_ellipse(aes(color = default, linetype = default), type = \"norm\",\n               level = 0.95, linewidth = 0.9) +\n  scale_color_manual(values = class_colors) +\n  scale_shape_manual(values = c(16, 17)) +\n  guides(color = guide_legend(override.aes = list(alpha = 1, size = 2))) +\n  scale_x_continuous(labels = dollar_labels) +\n  scale_y_continuous(labels = dollar_labels) +\n  labs(x = \"Credit card balance ($)\", y = \"Income ($)\", color = \"Default\",\n       shape = \"Default\", linetype = \"Default\",\n       title = \"Training set, with each class's 95% normal-theory ellipse\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/default-eda-figure-1.png){width=672}\n:::\n:::\n\n\nThe defaulters' ellipse is centered at higher balances and is narrower in the\nbalance direction: the standard deviation of balance is\n\\$458 among non-defaulters and\n\\$342 among defaulters, a difference\nQDA can represent and LDA cannot. Income is about equally spread in the two\nclasses, with standard deviations of \\$13,370\nand \\$13,731.\n\nWithin each class balance and income are weakly correlated, with\n$r = -0.150$ among\nnon-defaulters and\n$r = -0.096$ among\ndefaulters, so the two ellipses are only slightly tilted and the naive Bayes\nassumption of within-class independence is nearly met. In both classes the\npoints are densest in two horizontal bands, the bimodal income of the\nprevious lecture's histograms. The lower band is mostly students: in the training set\nstudents' median income is \\$17,980, against\n\\$40,135 for non-students. No Gaussian density, in\nQDA or naive Bayes, has two modes.\n\n### QDA and naive Bayes fits\n\n`MASS::qda()` takes the same formula as `MASS::lda()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_qda <- MASS::qda(default ~ balance + income, data = train)\ndefault_qda\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nqda(default ~ balance + income, data = train)\n\nPrior probabilities of groups:\n    No    Yes \n0.9648 0.0352 \n\nGroup means:\n      balance   income\nNo   808.2541 33549.49\nYes 1732.5500 32482.56\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# Coefficient of balance^2 in QDA's log posterior odds of Yes:\n# -1/2 times the (balance, balance) entry of Sigma_Yes^{-1} - Sigma_No^{-1}.\nSigma_inv <- map(c(No = \"No\", Yes = \"Yes\"), \\(k) {\n  solve(cov(train[train$default == k, c(\"balance\", \"income\")]))\n})\nbalance_sq_coef <- -0.5 * (Sigma_inv$Yes - Sigma_inv$No)[1, 1]\n\n# Balances at which QDA's posterior crosses 0.5 at a fixed income.\nqda_gap <- function(b, inc) {\n  predict(default_qda, newdata = tibble(balance = b, income = inc))$posterior[, \"Yes\"] - 0.5\n}\nincome_levels <- quantile(train$income, c(0.25, 0.5, 0.75))\nqda_cross <- map(income_levels, \\(inc) {\n  b <- seq(0, 10000, by = 10)\n  j <- which(diff(sign(qda_gap(b, inc))) != 0)\n  map_dbl(j, \\(i) uniroot(qda_gap, b[c(i, i + 1)], inc = inc)$root)\n})\ncross_at <- function(i) map_dbl(qda_cross, i)\n# The prose describes two crossings, the second beyond the training data.\nstopifnot(balance_sq_coef < 0, all(lengths(qda_cross) == 2),\n          all(cross_at(2) > max(train$balance)))\n```\n:::\n\n:::\n\nThe output reports the prior probabilities and the class means of balance and\nincome, the same priors and means LDA reports. The covariance matrices are\nnot printed; they are the two class-specific sample covariance matrices whose\nellipses appear in the scatterplot.\n\nBecause balance varies less among defaulters at a given income, the\ncoefficient of $\\texttt{balance}^2$ in QDA's log posterior odds is negative,\n$-1.9 \\times 10^{-6}$, and QDA's posterior probability of default\neventually falls as balance grows. At the lower quartile, median, and upper\nquartile of income, \\$21,297,\n\\$34,613, and \\$43,904, the\nposterior crosses $0.5$ at balances of \\$2,033,\n\\$1,969, and \\$1,918, and again at\n\\$3,795, \\$3,890, and\n\\$3,964, beyond the largest training balance of\n\\$2,499: the boundary depends on income as well as\nbalance, and it has a second branch at high balances.\n\n`e1071::naiveBayes()` models each numeric explanatory variable with a\nGaussian density in each class:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_nb <- e1071::naiveBayes(default ~ balance + income, data = train)\ndefault_nb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNaive Bayes Classifier for Discrete Predictors\n\nCall:\nnaiveBayes.default(x = X, y = Y, laplace = laplace)\n\nA-priori probabilities:\nY\n    No    Yes \n0.9648 0.0352 \n\nConditional probabilities:\n     balance\nY          [,1]     [,2]\n  No   808.2541 458.3208\n  Yes 1732.5500 342.2770\n\n     income\nY         [,1]     [,2]\n  No  33549.49 13369.50\n  Yes 32482.56 13731.38\n```\n\n\n:::\n:::\n\n\nThe **A-priori probabilities** are $\\hat\\pi_k$, the same as QDA's. Under\n**Conditional probabilities**, the `balance` and `income` tables give each\nclass's mean (first column) and standard deviation (second column),\n$\\hat\\mu_{kj}$ and $\\hat\\sigma_{kj}$: QDA's estimates with the within-class\ncovariance set to zero. The balance variances differ between classes, so\nnaive Bayes's balance term is quadratic too.\n\n### Decision boundaries\n\nWith LDA and logistic regression refit to the training half, the figure draws\nall four models' decision boundaries over the training customers,\nnon-defaulters as grey circles and defaulters as black triangles, shading\nbalances beyond the largest training balance.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_lda <- MASS::lda(default ~ balance + income, data = train)\ndefault_glm <- glm(default ~ balance + income, data = train,\n                   family = \"binomial\")\n\nposterior_all <- function(newdata) {\n  tibble(`Logistic regression` = unname(predict(default_glm, newdata = newdata,\n                                                type = \"response\")),\n         LDA = predict(default_lda, newdata = newdata)$posterior[, \"Yes\"],\n         QDA = predict(default_qda, newdata = newdata)$posterior[, \"Yes\"],\n         `Naive Bayes` = predict(default_nb, newdata = newdata,\n                                 type = \"raw\")[, \"Yes\"])\n}\n\nboundary_grid <- expand_grid(\n  balance = seq(0, 4500, length.out = 181),\n  income = seq(min(Default$income), max(Default$income), length.out = 121))\n\nboundary_curves <- bind_cols(boundary_grid, posterior_all(boundary_grid)) |>\n  pivot_longer(-c(balance, income), names_to = \"model\",\n               values_to = \"p_hat\") |>\n  mutate(model = factor(model, levels = names(model_colors)))\n\n# Training customers under each model's 0.5 contour.\nboundaries_figure <- ggplot(mapping = aes(x = balance, y = income)) +\n  annotate(\"rect\", xmin = max(train$balance), xmax = Inf, ymin = -Inf,\n           ymax = Inf, fill = \"grey92\") +\n  geom_point(data = arrange(train, default), aes(shape = default, fill = default),\n             color = \"grey40\", stroke = 0.2, size = 1.1, alpha = 0.6) +\n  geom_contour(data = boundary_curves, aes(z = p_hat, color = model,\n                                           linetype = model),\n               breaks = 0.5, linewidth = 0.9) +\n  scale_shape_manual(values = c(21, 24)) +\n  scale_fill_manual(values = c(\"grey70\", \"black\")) +\n  scale_color_manual(values = model_colors) +\n  scale_linetype_manual(values = model_linetypes) +\n  scale_x_continuous(labels = dollar_labels) +\n  scale_y_continuous(labels = dollar_labels) +\n  labs(x = \"Credit card balance ($)\", y = \"Income ($)\", shape = \"Default\",\n       fill = \"Default\", color = \"Model\", linetype = \"Model\",\n       title = \"Decision boundaries; shading beyond the largest training balance\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](60-qda-naive-bayes_files/figure-html/default-boundary-figure-1.png){width=720}\n:::\n:::\n\n\nThe LDA and logistic regression boundaries are nearly vertical lines, so\nincome barely moves either model's balance threshold. Within the training\nbalances, the QDA and naive Bayes boundaries run close to those lines. Each\nalso has a second branch beyond the training balances, at the second\ncrossings computed for QDA above, past which its posterior probability falls\nback below $0.5$.\n\n### Test performance\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nk_default <- odd_above_sqrt(nrow(train))\n\n# KNN vote proportion for \"Yes\", on features standardized by training means/SDs.\nstandardize <- function(d) {\n  cbind((d$balance - mean(train$balance)) / sd(train$balance),\n        (d$income - mean(train$income)) / sd(train$income))\n}\nknn_yes <- function(target, K) {\n  fit <- class::knn(standardize(train), standardize(target), train$default,\n                    k = K, prob = TRUE)\n  ifelse(fit == \"Yes\", attr(fit, \"prob\"), 1 - attr(fit, \"prob\"))\n}\n\nknn_default_name <- paste0(\"KNN, K = \", k_default)\nall_scores <- function(d) {\n  posterior_all(d) |>\n    mutate(`KNN, K = 1` = knn_yes(d, 1), \"{knn_default_name}\" := knn_yes(d, k_default))\n}\nscores_train <- all_scores(train)\nscores_test  <- all_scores(test)\n\n# AUC as the proportion of (defaulter, non-defaulter) pairs ordered correctly.\nauc_pairs <- function(s, pos) {\n  mean(outer(s[pos], s[!pos], \">\")) + 0.5 * mean(outer(s[pos], s[!pos], \"==\"))\n}\nyes_train <- train$default == \"Yes\"\nyes_test  <- test$default == \"Yes\"\n\nrates <- function(p_train, p_test) {\n  tibble(train_error = mean((p_train > 0.5) != yes_train),\n         test_error  = mean((p_test > 0.5) != yes_test),\n         sensitivity = mean(p_test[yes_test] > 0.5),\n         specificity = mean(p_test[!yes_test] <= 0.5),\n         auc         = auc_pairs(p_test, yes_test))\n}\nperformance <- map(names(scores_test), \\(m) rates(scores_train[[m]], scores_test[[m]])) |>\n  set_names(names(scores_test)) |>\n  list_rbind(names_to = \"model\")\nperf_of <- function(m, col) performance[[col]][performance$model == m]\nmodel_based <- performance |> slice(1:4)\n\npct2 <- function(v) sprintf(\"%.2f%%\", 100 * v)\nperformance_table <- performance |>\n  mutate(across(train_error:specificity, pct2), auc = sprintf(\"%.4f\", auc)) |>\n  knitr::kable(col.names = c(\"Model\", \"Training error\", \"Test error\",\n                             \"Test sensitivity\", \"Test specificity\", \"Test AUC\"),\n               align = \"lccccc\")\n\n# Naive Bayes against QDA, as signed differences described in words.\ndirection <- function(d) if (d > 0) \"higher\" else \"lower\"\nnb_error_diff <- perf_of(\"Naive Bayes\", \"test_error\") - perf_of(\"QDA\", \"test_error\")\nnb_auc_diff   <- perf_of(\"Naive Bayes\", \"auc\") - perf_of(\"QDA\", \"auc\")\n# The prose says KNN with the larger K has a lower test AUC than every\n# model-based classifier, and KNN with K = 1 the worst test error rate.\nstopifnot(perf_of(knn_default_name, \"auc\") < min(model_based$auc),\n          perf_of(\"KNN, K = 1\", \"test_error\") == max(performance$test_error))\n```\n:::\n\n:::\n\nKNN uses balance and income, each standardized by its training mean and\nstandard deviation, with $K = 1$ and $K = 71$, the smallest odd\ninteger above $\\sqrt{5{,}000}$. Every\nclassifier is evaluated at threshold $0.5$ (for KNN, a majority vote), with\nthe training error rate computed on the customers each model was fit to.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Model               | Training error | Test error | Test sensitivity | Test specificity | Test AUC |\n|:-------------------|:--------------:|:----------:|:----------------:|:----------------:|:--------:|\n|Logistic regression |     2.78%      |   2.46%    |      31.85%      |      99.67%      |  0.9551  |\n|LDA                 |     2.96%      |   2.54%    |      24.84%      |      99.81%      |  0.9553  |\n|QDA                 |     2.92%      |   2.52%    |      27.39%      |      99.75%      |  0.9550  |\n|Naive Bayes         |     3.12%      |   2.46%    |      28.03%      |      99.79%      |  0.9533  |\n|KNN, K = 1          |     0.00%      |   4.18%    |      29.94%      |      97.96%      |  0.6395  |\n|KNN, K = 71         |     3.12%      |   2.88%    |      10.83%      |      99.92%      |  0.9326  |\n\n\n:::\n:::\n\n\nThe training error rates are optimistic. KNN with $K = 1$ has a training\nerror rate of 0.00%, since each\ntraining customer is its own nearest neighbor, but a test error rate of\n4.18%, the worst in the table.\n\nThe four model-based classifiers have test error rates between\n2.46% and\n2.54%, against the\n3.14% of predicting `No` for every test customer. They\ndiffer more in sensitivity, from\n24.8% to\n31.8%, a difference of\n11 of the\n157 test defaulters. Their test AUCs range only from\n0.9533 to\n0.9553. With the within-class correlation\nthis small, dropping it costs naive Bayes little: its test error rate is\n0.06 percentage points lower than QDA's,\nand its AUC is 0.0017 lower.\nKNN with $K = 71$ has a lower test AUC than any of them,\n0.9326.\n\n### Student strata\n\nQDA with `balance` and `income` is now fit separately to the training set's\n3,508 non-students and\n1,492 students, beside the\nlogistic regression whose intercept and slopes all interact with student\nstatus; every customer is scored by its own stratum's model.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nstrata <- c(No = \"No\", Yes = \"Yes\")\ntrain_by <- map(strata, \\(s) filter(train, student == s))\nstrata_qda <- map(train_by, \\(d) MASS::qda(default ~ balance + income, data = d))\nstrata_glm <- map(train_by, \\(d) glm(default ~ balance + income, data = d,\n                                     family = \"binomial\"))\ninteracted_glm <- glm(default ~ (balance + income) * student, data = train,\n                      family = \"binomial\")\n\n# Score every customer with its own stratum's model.\nby_stratum <- function(d, score) {\n  p <- numeric(nrow(d))\n  for (s in strata) p[d$student == s] <- score(s, d[d$student == s, ])\n  p\n}\nqda_strat <- function(d) by_stratum(d, \\(s, ds) predict(strata_qda[[s]], ds)$posterior[, \"Yes\"])\nmax_diff_int <- max(abs(fitted(interacted_glm) - by_stratum(train, \\(s, ds) {\n  predict(strata_glm[[s]], ds, type = \"response\")\n})))\nglm_int <- function(d) predict(interacted_glm, newdata = d, type = \"response\")\n\nstrata_rates <- list(\n  \"QDA, single fit\" = rates(scores_train$QDA, scores_test$QDA),\n  \"QDA, by student stratum\" = rates(qda_strat(train), qda_strat(test)),\n  \"Logistic regression, additive\" = rates(scores_train$`Logistic regression`,\n                                          scores_test$`Logistic regression`),\n  \"Logistic regression, interacted with student\" =\n    rates(glm_int(train), glm_int(test))\n) |>\n  list_rbind(names_to = \"model\")\nstrata_table <- strata_rates |>\n  select(-specificity) |>\n  mutate(across(train_error:sensitivity, pct2), auc = sprintf(\"%.4f\", auc)) |>\n  knitr::kable(col.names = c(\"Model\", \"Training error\", \"Test error\",\n                             \"Test sensitivity\", \"Test AUC\"), align = \"lcccc\")\n# Largest change in test error rate and test AUC from stratifying either\n# model: rows 2 and 4 are the stratified versions of rows 1 and 3.\nmax_error_change <- max(abs(diff(strata_rates$test_error)[c(1, 3)]))\nmax_auc_change   <- max(abs(diff(strata_rates$auc)[c(1, 3)]))\n# QDA estimates K - 1 priors, K p means, and K p (p + 1) / 2 covariances.\nn_par_qda <- (2 - 1) + count_qda(2, 2)\nstratum_rate <- function(s) mean(train_by[[s]]$default == \"Yes\")\n```\n:::\n\n:::\n\nThe table gives each model's training error rate, and its test error rate,\nsensitivity, and AUC at $t = 0.5$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Model                                        | Training error | Test error | Test sensitivity | Test AUC |\n|:--------------------------------------------|:--------------:|:----------:|:----------------:|:--------:|\n|QDA, single fit                              |     2.92%      |   2.52%    |      27.39%      |  0.9550  |\n|QDA, by student stratum                      |     2.78%      |   2.66%    |      24.84%      |  0.9533  |\n|Logistic regression, additive                |     2.78%      |   2.46%    |      31.85%      |  0.9551  |\n|Logistic regression, interacted with student |     2.82%      |   2.56%    |      30.57%      |  0.9547  |\n\n\n:::\n:::\n\n\nFitting the logistic regression with every coefficient interacted with\nstudent status is the same as fitting separate logistic regressions to the\ntwo strata: on the training set the two give the same fitted probabilities,\nto within $1 \\times 10^{-14}$.\n\nIn the training set students default more often, 4.29% against\n3.19%, so the stratified QDA gives\nthem a larger prior for `Yes`. Naive Bayes could instead take `student` as a third\nfeature with its own Bernoulli density, without a separate fit per stratum.\n\nStratifying changes no model's test error rate by more than\n0.14 percentage points or its test AUC\nby more than 0.0016. Each stratified model\nestimates twice as many parameters — 22 against\n11 for QDA, and 6 against\n3 for logistic regression — which makes its\ntraining error rate the more optimistic; the test rates are the fair\ncomparison, and they come from a single split.\n\n**Conclusion.** The data show the departure from LDA that QDA is built for, a\nsmaller balance spread among defaulters, and within-class correlations small\nenough that naive Bayes's independence assumption nearly holds. Yet changing\nLDA's model makes no practical difference to classifying new customers: the\nfour model-based test error rates lie within\n0.08 percentage\npoints of each other and their AUCs within\n0.002, and the curvature of QDA\nand naive Bayes shows only beyond the training balances. KNN with\n$K = 71$ has a lower test AUC than any model-based classifier, and\nwith $K = 1$ its 0.00% training error\nrate is no guide to its test error rate. Separate models for students and\nnon-students double the parameters without changing any test error rate by\nmore than 0.14 percentage points.\n\n## Conclusion\n\nQDA is the generative classifier with Gaussian class-conditional densities and\na covariance matrix $\\Sigma_k$ for each class. The quadratic term\n$-\\frac{1}{2}x^\\top\\Sigma_k^{-1}x$ and the term\n$-\\frac{1}{2}\\log\\left|\\Sigma_k\\right|$ no longer cancel between classes, so\nthe discriminant functions and the log posterior odds are quadratic in $x$,\nthe decision boundary is a quadratic curve, and with one feature the class\nwith the larger variance is assigned in both tails. Each $\\Sigma_k$ is\nestimated by its class's sample covariance matrix, which requires $n_k > p$.\n\nThe choice between LDA and QDA is a bias-variance tradeoff. With $K$ classes,\nQDA estimates $K p(p+1)/2$ covariance parameters against LDA's $p(p+1)/2$, so it removes\nLDA's bias when the class covariances differ at the cost of variance that\ngrows with $p$ and shrinks with $n$.\n\nNaive Bayes assumes the features are independent within each class, so\n$f_k(x) = \\prod_j f_{kj}(x_j)$, each one-feature density estimated on its own\nand of whatever type suits the feature. The log posterior odds are a sum of\none-feature terms, with no interactions. Gaussian naive Bayes is LDA or QDA\nwith a diagonal covariance matrix. With class-specific variances it estimates\n$2Kp$ parameters, sidestepping the curse of dimensionality that a joint\ndensity faces. Its bias, which comes from ignoring within-class dependence,\nneed not change its classifications: it agrees with the Bayes classifier\nwherever its estimated posterior probability falls on the same side of the\nthreshold as the true one.\n\nLogistic regression and LDA produce linear boundaries, QDA and naive Bayes\nquadratic ones, and KNN boundaries of any shape. Which classifier has the\nlowest test error rate depends on how closely its assumptions match the\ndata-generating process and on the sizes of $n$ and $p$; no method is best\nin every setting. Comparing classifiers requires test data the models were\nnot fit to, since training error rates reward flexibility.\n\nThe next lecture steps back from classification to a framework that contains\nlinear and logistic regression as special cases. Generalized linear models\npair a distribution for the response with a link function for its mean, and\nPoisson regression, the generalized linear model for counts, is the first new\nmember of the family.\n",
    "supporting": [
      "60-qda-naive-bayes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}