{
  "hash": "369e7e6adac4da1e696e1cbd27ee9aa4",
  "result": {
    "engine": "knitr",
    "markdown": "# Flexibility and Its Costs\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **construct** a step function model and **explain** why it is the\ndummy-variable machinery applied to a quantitative feature,\n- **describe** K-nearest neighbors regression and **identify** $K$ as its\nflexibility parameter,\n- **compare** a parametric fit against a nonparametric one and **state** the\nconditions under which each is preferable,\n- **diagnose** the potential problems of ISLR2 Section 3.3.3 from a residual\nplot, leverage values, and variance inflation factors,\n- **distinguish** a high-leverage point from an outlier, and **use** Cook's\ndistance to judge which observations actually influence the fit, and\n- **evaluate** added flexibility in terms of the bias-variance tradeoff.\n:::\n\n## Step functions\n\nLast lecture we used polynomials, which impose one global shape on the whole\nrange of $X$. A step function gives up smoothness instead. Choose cut points\n\n$$-\\infty = c_0 < c_1 < \\cdots < c_p < c_{p+1} = \\infty,$$\n\npinning the outer two at $\\pm\\infty$ so the bins they define cover the entire\nrange of $X$, and define indicators\n\n$$C_j(X) = I(c_j \\le X < c_{j+1}), \\quad j = 1, \\ldots, p.$$\n\nThen fit\n\n$$Y_i = \\beta_0 + \\beta_1 C_1(X_i) + \\cdots + \\beta_p C_p(X_i) + \\epsilon_i,$$\n\ndropping the first bin as the baseline. This is **exactly** the dummy-variable\nmachinery from multiple regression: we have turned a quantitative feature into a\ncategorical one. The fitted value in a bin is the sample mean of $y$ in that\nbin, and $\\beta_j$ is that bin's mean minus the baseline bin's mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(wage ~ cut(age, breaks = c(18, 30, 42, 54, 66, 80)))\n```\n:::\n\n\nWe can see how a step function compares to a polynomial on real data: wages\nagainst age for the 3000 workers in `ISLR2::Wage`.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\nage_cuts <- seq(min(Wage$age), max(Wage$age), length.out = 6)\nage_grid <- tibble(age = seq(min(Wage$age), max(Wage$age), length.out = 400))\n\nfit_grid <- function(model, label, binned = FALSE) {\n  age_grid |>\n    mutate(yhat = predict(model, age_grid),\n           fit  = label,\n           bin  = if (binned) as.character(cut(age, age_cuts, include.lowest = TRUE))\n                  else \"all\")\n}\n\nwage_pred <- bind_rows(\n  fit_grid(lm(wage ~ age,                                       data = Wage), \"Linear in age\"),\n  fit_grid(lm(wage ~ poly(age, 5),                              data = Wage), \"Polynomial (degree 5)\"),\n  fit_grid(lm(wage ~ cut(age, age_cuts, include.lowest = TRUE), data = Wage), \"Step function (5 bins)\",\n           binned = TRUE)\n)\n\nflexibility_plot <- ggplot(Wage, aes(x = age, y = wage)) +\n  geom_point(alpha = 0.1) +\n  geom_line(data = wage_pred, aes(y = yhat, group = interaction(fit, bin)),\n            color = \"blue\", linewidth = 1) +\n  facet_wrap(~ fit) +\n  labs(title = \"ISLR2::Wage\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-40-flexibility_files/figure-html/flexibility-comparison-figure-1.png){width=864}\n:::\n:::\n\n\nThe costs are visible on the right: the fit jumps at the cut points and ignores\nany trend within a bin. And *we* chose those cut points — nothing in the data\ntold us where to put them.\n\n::: {.callout-important collapse=\"true\"}\n### Where this is going\nThat last complaint is the whole idea behind **regression trees** (ISLR2 Chapter 8).\nA tree is a step function whose cut points are *learned from the data*, applied\nrecursively and in several features at once — so a tree gets interactions for\nfree, without our specifying them. A **random forest** averages many such step\nfunctions to cut their variance.\n:::\n\n## K-nearest neighbors regression\n\nA step function lets the data choose the *value* taken in each bin, but we still\nchose the bins. K-nearest neighbors abandons fixed bins altogether and lets the\nneighborhood move with the point being predicted.\n\nFix a value $K$ and a target point $x_0$, and let $\\mathcal{N}_0$ be the set of\nthe $K$ training observations whose feature values are closest to $x_0$. Then\n\n$$\\hat{f}(x_0) = \\frac{1}{K} \\sum_{i \\in \\mathcal{N}_0} y_i.$$\n\nThat is the whole method: average the responses of the nearest neighbors. There\nis no $\\beta$, nothing is fit by least squares, and no functional form is\nassumed anywhere. KNN is a **nonparametric** method, unlike every model we have\nseen so far.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_reg <- function(x0, x, y, K) {\n  sapply(x0, function(z) mean(y[order(abs(x - z))[1:K]]))\n}\n```\n:::\n\n\n$K$ is the flexibility dial, and it runs backwards:\n\n- $K = 1$ makes $\\hat{f}$ interpolate the training data — zero training error\nand enormous variance.\n- $K = n$ makes $\\hat{f}$ the overall mean $\\bar{y}$, a flat line — maximum bias\nand minimum variance.\n\nSo it is $1/K$ that plays the role of flexibility.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_pred <- map_df(c(1, 10, 50), function(K) {\n  age_grid |>\n    mutate(yhat = knn_reg(age, Wage$age, Wage$wage, K),\n           K    = paste(\"K =\", K))\n}) |>\n  mutate(K = factor(K, levels = paste(\"K =\", c(1, 10, 50))))\n\nknn_plot <- ggplot(Wage, aes(x = age, y = wage)) +\n  geom_point(alpha = 0.1) +\n  geom_line(data = knn_pred, aes(y = yhat), color = \"blue\", linewidth = 1) +\n  facet_wrap(~ K) +\n  labs(title = \"ISLR2::Wage\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-40-flexibility_files/figure-html/knn-comparison-figure-1.png){width=864}\n:::\n:::\n\n\n### KNN with more than one feature\n\nNothing about the method changes with $p > 1$ features — only what \"closest\"\nmeans. With $p$ features, $\\mathcal{N}_0$ becomes the $K$ training points with\nthe smallest Euclidean distance to $x_0$ in $p$-dimensional space,\n\n$$d(x_i, x_0) = \\sqrt{\\sum_{j=1}^p (x_{ij} - x_{0j})^2},$$\n\nand because that distance depends on the scale of each feature, every feature\nshould be standardized first, or a feature measured in thousands of dollars\nwould dominate one measured in single digits regardless of which one actually\npredicts the response.\n\n`ISLR2::Boston` has two such features: the percentage of the neighborhood that\nis lower-status (`lstat`) and the average number of rooms per home (`rm`),\nboth used to predict median home value (`medv`). Before fitting anything, look\nat the relationship itself:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the plots below\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_reg_multi <- function(X0, X, y, K) {\n  Xs  <- scale(X)\n  X0s <- scale(X0, center = attr(Xs, \"scaled:center\"), scale = attr(Xs, \"scaled:scale\"))\n  apply(X0s, 1, function(z) {\n    d <- sqrt(rowSums((Xs - matrix(z, nrow(Xs), length(z), byrow = TRUE))^2))\n    mean(y[order(d)[1:K]])\n  })\n}\n\nknn_2d_grid <- expand_grid(\n  lstat = seq(min(Boston$lstat), max(Boston$lstat), length.out = 60),\n  rm    = seq(min(Boston$rm), max(Boston$rm), length.out = 60)\n)\n\nknn_2d_grid$medv_lstat <- knn_reg_multi(\n  as.matrix(knn_2d_grid[, \"lstat\", drop = FALSE]),\n  as.matrix(Boston[, \"lstat\", drop = FALSE]),\n  Boston$medv, K = 10)\n\nknn_2d_grid$medv_rm <- knn_reg_multi(\n  as.matrix(knn_2d_grid[, \"rm\", drop = FALSE]),\n  as.matrix(Boston[, \"rm\", drop = FALSE]),\n  Boston$medv, K = 10)\n\nknn_2d_grid$medv_both <- knn_reg_multi(\n  as.matrix(knn_2d_grid[, c(\"lstat\", \"rm\")]),\n  as.matrix(Boston[, c(\"lstat\", \"rm\")]),\n  Boston$medv, K = 10)\n\n# Same color scale on every tab, so only the surface itself changes.\nmedv_range <- range(Boston$medv, knn_2d_grid$medv_lstat,\n                     knn_2d_grid$medv_rm, knn_2d_grid$medv_both)\n\n# A shared base layer, so the four views below differ only in what's drawn\n# over it -- the panel itself never changes size, shape, or color scale.\nknn_2d_base <- ggplot(mapping = aes(x = lstat, y = rm)) +\n  coord_cartesian(xlim = range(Boston$lstat), ylim = range(Boston$rm)) +\n  labs(x = \"Percent lower-status population (lstat)\",\n       y = \"Average rooms per dwelling (rm)\",\n       title = \"ISLR2::Boston\") +\n  theme(legend.position = \"inside\",\n        legend.position.inside = c(0.98, 0.98),\n        legend.justification = c(1, 1),\n        legend.background = element_rect(fill = alpha(\"white\", 0.8), color = \"grey70\"))\n\nknn_2d_data_plot <- knn_2d_base +\n  geom_point(data = Boston, aes(color = medv)) +\n  scale_color_viridis_c(name = \"medv\", limits = medv_range)\n\nknn_2d_lstat_plot <- knn_2d_base +\n  geom_raster(data = knn_2d_grid, aes(fill = medv_lstat)) +\n  geom_point(data = Boston, color = \"white\", alpha = 0.4, size = 0.6) +\n  scale_fill_viridis_c(name = \"medv\", limits = medv_range)\n\nknn_2d_rm_plot <- knn_2d_base +\n  geom_raster(data = knn_2d_grid, aes(fill = medv_rm)) +\n  geom_point(data = Boston, color = \"white\", alpha = 0.4, size = 0.6) +\n  scale_fill_viridis_c(name = \"medv\", limits = medv_range)\n\nknn_2d_both_plot <- knn_2d_base +\n  geom_raster(data = knn_2d_grid, aes(fill = medv_both)) +\n  geom_point(data = Boston, color = \"white\", alpha = 0.4, size = 0.6) +\n  scale_fill_viridis_c(name = \"medv\", limits = medv_range)\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Data\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-40-flexibility_files/figure-html/knn-2d-data-plot-1.png){width=672}\n:::\n:::\n\n\n#### + lstat\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-40-flexibility_files/figure-html/knn-2d-lstat-plot-1.png){width=672}\n:::\n:::\n\n\n#### + rm\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-40-flexibility_files/figure-html/knn-2d-rm-plot-1.png){width=672}\n:::\n:::\n\n\n#### + lstat and rm\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-40-flexibility_files/figure-html/knn-2d-both-plot-1.png){width=672}\n:::\n:::\n\n:::\n\nClick through the tabs: KNN on `lstat` alone varies only left to right, KNN on\n`rm` alone varies only bottom to top, and KNN on both varies in every\ndirection at once — the fitted value genuinely depends on where $x_0$ sits in\nthe full two-dimensional feature space, not just its position on one axis.\n\n### When does KNN beat linear regression?\n\nWhen the true $f$ is far from linear, KNN wins, and it does so without our\nhaving to guess the right polynomial degree or the right cut points.\n\nWhen $f$ really is close to linear, least squares wins, because it estimates\nthat line using every observation at once rather than only $K$ of them.\n\nThe decisive issue is the number of features. As $p$ grows, the $K$ \"nearest\"\nneighbors of $x_0$ stop being anywhere near it — in high dimensions everything\nis far from everything — so averaging their responses estimates $f$ somewhere\nother than at $x_0$, which is bias. This is the **curse of dimensionality**.\n\nA parametric model that is merely approximately right will usually beat a\nnonparametric one when $p$ is large relative to $n$ — even when the true\nrelationship is not linear, because the nonparametric method's variance from\nhaving too few effective neighbors outweighs the parametric method's bias from\nhaving the wrong functional form.\n\n## Potential problems\n\nLast lecture's feature engineering is the *cure* for the first of these and the\n*cause* of the last two.\n\n1. **Non-linearity.** Structure in a plot of residuals against fitted values\nmeans the model is missing systematic signal — the motivation for polynomials,\nstep functions, and KNN alike.\n2. **Correlated errors.** Common with data over time or space. Standard errors\ncome out too small, so you are more confident than you have earned.\n3. **Non-constant variance.** A funnel in the residual plot; often handled by\ntransforming the response, $\\log Y$ or $\\sqrt{Y}$.\n4. **Outliers.** An unusual *response*. Inflates $\\hat\\sigma^2$ and depresses\n$R^2$ without necessarily moving the line.\n5. **High-leverage points.** An unusual *feature* value. These do move the line,\nand polynomials make it worse — an extreme $x$ raised to the fifth power is an\nextraordinarily influential row.\n6. **Collinearity.** Features carrying nearly the same information. The data\ncannot separate their effects, so $\\text{SE}(\\hat\\beta_j)$ inflates and the\nt-test loses power: a coefficient can matter and still look \"insignificant.\"\nPolynomials and interactions create collinearity by construction.\n\n::: {.callout-note collapse=\"true\"}\n### Detecting leverage and collinearity\n**Leverage** is $h_i$, the $i$th diagonal element of the hat matrix\n$H = X(X^\\top X)^{-1}X^\\top$. It averages $(p+1)/n$, so values several times\nthat deserve a look. Leverage depends only on the features — you can compute it\nbefore seeing a single response.\n\n**Cook's distance** combines leverage with the size of the residual into a\nsingle number measuring how much the fitted values would move if an observation\nwere deleted. Values near or above $1$ warrant attention. In R, `hatvalues()`,\n`rstudent()`, and `cooks.distance()` compute all three.\n\n**Collinearity** is measured by the variance inflation factor\n\n$$\\text{VIF}(\\hat\\beta_j) = \\frac{1}{1 - R^2_{X_j | X_{-j}}}$$\n\nwhere $R^2_{X_j|X_{-j}}$ comes from regressing $X_j$ on all other features. VIF\nis 1 under no collinearity; past 5 or 10 is commonly flagged. Remedies: drop one\nfeature, combine them, center them, or — for polynomials — use `poly()`.\n:::\n\nEvery one of these shows up in data we have already used this semester. Number\n2 is the least visible, because most of our examples are not collected over\ntime — but the CAPM demonstration, with weekly returns ordered by date, is\nexactly where you would worry about it.\n\n### Reading residuals: curvature and changing spread\n\nA plot of residuals against fitted values diagnoses problems 1 and 3 at a\nglance. Both of our regressions from last lecture have something to confess.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\ngalileo_lin <- lm(Distance ~ Height,          data = Sleuth3::case1001)\nmetabol_fit <- lm(Metabol  ~ Gastric * Sex,   data = Sleuth3::case1101)\n\nresidual_data <- bind_rows(\n  tibble(fitted = fitted(galileo_lin), resid = residuals(galileo_lin),\n         panel  = \"Galileo, linear fit: curvature\"),\n  tibble(fitted = fitted(metabol_fit), resid = residuals(metabol_fit),\n         panel  = \"Metabolism: non-constant variance\")\n)\n\nresidual_plot <- ggplot(residual_data, aes(x = fitted, y = resid)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey40\") +\n  geom_point() +\n  facet_wrap(~ panel, scales = \"free\") +\n  labs(x = \"Fitted value\", y = \"Residual\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-40-flexibility_files/figure-html/residual-diagnostics-figure-1.png){width=864}\n:::\n:::\n\n\nOn the left, the residuals from the *linear* fit to Galileo's data run negative,\npositive, then negative again — the inverted U that says a straight line is the\nwrong shape. That is problem 1, and it is precisely what the quadratic term\nfixed last lecture.\n\nOn the right, the residuals from the alcohol metabolism model fan out: near zero\nfor small fitted values and spanning several units for large ones. That is\nproblem 3. The constant-variance assumption behind every standard error in that\noutput is not holding, and a $\\log$ or $\\sqrt{\\cdot}$ transformation of the\nresponse would be the usual response.\n\n### Leverage and outliers are different things\n\nLast lecture we labelled three subjects on the metabolism plot — 17, 31, and\n32. Now we can be precise about them. With\n$p + 1 = 4$ coefficients and\n$n = 32$ observations, average leverage is\n$4/32 = 0.125$.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the figure below\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_leverage <- length(coef(metabol_fit)) / nrow(Sleuth3::case1101)\n\ninfluence_data <- Sleuth3::case1101 |>\n  mutate(leverage    = hatvalues(metabol_fit),\n         studentized = rstudent(metabol_fit))\n\ninfluence_plot <- ggplot(influence_data, aes(x = leverage, y = studentized)) +\n  geom_hline(yintercept = c(-3, 3),            linetype = \"dashed\", color = \"grey40\") +\n  geom_vline(xintercept = 2 * average_leverage, linetype = \"dashed\", color = \"grey40\") +\n  geom_point() +\n  geom_text(aes(label = ifelse(leverage > 2 * average_leverage | abs(studentized) > 3,\n                               paste(\"Subject\", Subject), \"\")),\n            hjust = -0.15, size = 3) +\n  expand_limits(x = 0.65) +\n  labs(x = \"Leverage\", y = \"Studentized residual\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-40-flexibility_files/figure-html/leverage-diagnostics-figure-1.png){width=672}\n:::\n:::\n\n\nThree subjects sit outside the dashed guides, and they are outside for different\nreasons. **Cook's distance** settles which of them actually matter.\n\n::: {.callout-note collapse=\"true\"}\n### Code for the table below\n\n::: {.cell}\n\n```{.r .cell-code}\ninfluence_data_full <- tibble(\n  Subject     = Sleuth3::case1101$Subject,\n  Studentized = rstudent(metabol_fit),\n  Leverage    = hatvalues(metabol_fit),\n  CooksD      = cooks.distance(metabol_fit))\n\ninfluence_table_data <- influence_data_full |>\n  filter(Subject %in% c(17, 31, 32))\n\ninfluence_table <- influence_table_data |>\n  knitr::kable(digits = 3,\n               col.names = c(\"Subject\", \"Studentized residual\", \"Leverage\", \"Cook's D\"))\n\ninfluence_of <- function(subject, column) {\n  influence_table_data[[column]][influence_table_data$Subject == subject]\n}\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Subject| Studentized residual| Leverage| Cook's D|\n|-------:|--------------------:|--------:|--------:|\n|      17|                0.195|    0.393|    0.006|\n|      31|               -1.910|    0.535|    0.961|\n|      32|                5.121|    0.253|    1.167|\n\n\n:::\n:::\n\n\nCook's distance answers a direct question: if we deleted this one observation\nand refit, how much would all the fitted values move? A large value means the\nmodel depends meaningfully on that single point.\n\nIt rises with both of the columns beside it. A point has to disagree with the\nmodel *and* have room to pull the line toward itself before it can do real\ndamage — and having room is exactly what leverage measures. Either ingredient\nalone is harmless; the combination is not.\n\nThe table makes the distinction concrete. Subject 17 has leverage\n$0.393$, more than three times the average\nof $4/32 = 0.125$,\nand yet Cook's distance is $0.006$. It sits\nfar from the other feature values and agrees completely with the trend, so\ndeleting it would change essentially nothing. High leverage by itself is not a\nproblem.\n\nSubjects 31 and 32 both land near or above $1$, the conventional cutoff, and\nthey get there by opposite routes. Subject 32 has only moderate leverage but a\nstudentized residual of $5.12$ — it\ndisagrees violently. Subject 31 has the largest leverage in the data\n(0.535) with an unremarkable residual\nof $-1.91$ — it barely disagrees, but\nit has so much room that a small disagreement is enough.\n\nDeleting either one would visibly move the male line, which is worth knowing\nbefore reporting that men metabolize alcohol at three times the female rate.\n\n### Collinearity you create yourself\n\nLast lecture's `poly()` callout claimed that raw powers are dangerously\ncorrelated. Galileo's data lets us put a number on it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif <- function(X) {\n  sapply(seq_along(X), function(j)\n    1 / (1 - summary(lm(X[[j]] ~ ., data = X[-j]))$r.squared))\n}\n\nHeight     <- Sleuth3::case1001$Height\nraw_powers <- data.frame(Height = Height, Height2 = Height^2, Height3 = Height^3)\nraw_power_vif <- vif(raw_powers)\n\nround(raw_power_vif, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 172.2 960.3 356.2\n```\n\n\n:::\n\n```{.r .cell-code}\nround(vif(as.data.frame(poly(Height, 3))), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 1 1\n```\n\n\n:::\n:::\n\n\nThe raw powers carry variance inflation factors of roughly\n$172$, $960$, and\n$356$ — the standard errors on those coefficients are\ninflated by factors of $\\sqrt{960} \\approx 31$.\nThe orthogonal basis from `poly()` gives\nexactly $1$, $1$, and $1$.\n\nBoth parameterizations produce **identical** fitted values, residuals, and\n$R^2$. Nothing about the quality of the fit changed. What changed is whether the\nindividual coefficients can be interpreted and tested one at a time — and this\nis collinearity we manufactured ourselves by choosing a basis, not a defect in\nGalileo's measurements.\n\n### Why not just look at the data?\n\nEvery problem in this section could have been caught by eye:\n7 observations of Galileo's, 32\nsubjects, one or two features — plot the data and you\ncan see the curvature, see the two men stranded out on the right, see the spread\nwidening.\n\nThat is about to stop being true. From here on the course adds features faster\nthan you can plot them and models whose fitted surface cannot be drawn at all.\nThere is no scatterplot of a random forest on twenty features, and no way to\nsquint at observation 4,812 of 50,000 to decide whether it is dragging the fit.\n\nWhat survives the transition is the numbers. Leverage, studentized residuals,\nCook's distance, and variance inflation factors are defined for any number of\nfeatures, and they can be sorted, thresholded, and scanned without a human\nlooking at anything. So can the diagnostic plots we just used: residuals against\nfitted values, or leverage against studentized residual, stay two-dimensional no\nmatter how large $p$ gets, because they plot *model output* rather than the data\nitself.\n\nThe habit worth building now, while you can still check the answer by looking,\nis to compute the diagnostic anyway and learn what its values mean. Later the\nnumber is all you will have.\n\n## The cost of flexibility\n\nEvery feature you add to $X$, and every reduction in the number of neighbors\n$K$, is another turn of the flexibility dial from ISLR2 Chapter 2. The training\nRSS can only fall as you turn it; the **test** MSE need not, because you are\ntrading bias for variance.\n\nSo these methods hand us more candidate models than we can judge by eye, and\ntraining error cannot referee among them. Honest test-error estimates come from\nresampling (ISLR2 Chapter 5), and automatic ways to choose which features to\nkeep come from selection and regularization (ISLR2 Chapter 6).\n",
    "supporting": [
      "03-40-flexibility_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}