{
  "hash": "435d62d421b6dd9ff801ccf5f8d83830",
  "result": {
    "engine": "knitr",
    "markdown": "# Linear Discriminant Analysis\n\n[Slides for this lecture](50-lda_slides.html)\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **derive** the posterior probability $p_k(x) = P(Y = k \\mid X = x)$ from the\nprior probabilities $\\pi_k$ and the class-conditional densities $f_k(x)$ using\nBayes' theorem, and **explain** why classifying to the class with the largest\nposterior probability minimizes the expected error rate,\n- **derive** the LDA discriminant function $\\delta_k(x)$ for one feature under\nGaussian class-conditional densities with a shared variance $\\sigma^2$, and\n**show** that it is linear in $x$, so that the decision boundary is a single\npoint that moves toward, and when the prior is small enough past, the mean of\nthe class whose prior probability is smaller,\n- **write** the discriminant function for $p > 1$ features in matrix form using\nclass mean vectors $\\mu_k$ and a shared covariance matrix $\\Sigma$, and\n**compute** the estimates $\\hat\\pi_k$, $\\hat\\mu_k$, and $\\hat\\sigma^2$ or\n$\\hat\\Sigma$ from training data,\n- **fit** LDA with `MASS::lda()`, **interpret** its prior probabilities, group\nmeans, and posterior probabilities, and **compare** its posterior\nprobabilities and decision boundary with those of logistic regression.\n:::\n\n\n## Generative classifiers\n\n### Credit card default data\n\n**Question.** How does a classifier built from how balance and income are\ndistributed within defaulters and within non-defaulters assign credit card\ncustomers to classes, and how do its posterior probabilities and decision\nboundary compare with those of logistic regressions fit to the same customers\nand features?\n\nThese customers were analyzed in the logistic regression lectures: the\n[Simple Logistic Regression](10-logistic-regression.qmd) lecture modeled\ndefault from `balance`, the\n[Multiple Logistic Regression](20-multiple-logistic-regression.qmd) lecture\nfrom `balance` and `student`, and the\n[Flexible Logistic Regression](30-flexible-logistic-regression.qmd) lecture\nadded interactions, including one between `balance` and `income`.\n\n**Data.** `ISLR2::Default` is a simulated data set of\n10,000 credit card customers. The response\nis `default`, with `Yes` the positive class. This lecture uses the two\nquantitative explanatory variables, `balance`, the customer's monthly credit\ncard balance in dollars, and `income`, the customer's income in dollars,\nbecause linear discriminant analysis (LDA), the method of this lecture,\nmodels each class's features with a Gaussian density. The\nfeatures are the explanatory variables themselves. `income` enters the models\nin dollars as recorded, as in the flexible logistic regression lecture; its\ncoefficients are reported here per \\$1,000 of income. `student` (Yes/No)\nexplains the bimodal income distribution in the Multiple-feature LDA\nsection.\n\nThe table gives each default class's number and proportion of customers and\nthe mean, standard deviation, and number of zero values of its balances. The\nfirst tab below\nshows balance within each class, one panel per class, on the density scale;\nthe second shows all customers in one histogram on the count scale, with each\nbar split into non-defaulters (light blue) and defaulters (dark orange).\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nDefault <- Default |>\n  mutate(default01   = as.numeric(default == \"Yes\"),\n         default_jit = default01 + runif(n(), -0.03, 0.03))\n\ndollars <- function(v) format(round(v), big.mark = \",\")\n# Axis labels such as $60,000, without the scales package.\ndollar_labels <- function(v) {\n  ifelse(is.na(v), NA,\n         paste0(\"$\", format(v, big.mark = \",\", scientific = FALSE, trim = TRUE)))\n}\n\nclass_summary <- Default |>\n  group_by(default) |>\n  summarize(n = n(), prop = n() / nrow(Default),\n            mean_balance = mean(balance), sd_balance = sd(balance),\n            n_zero = sum(balance == 0), .groups = \"drop\")\nsummary_of <- function(k, col) class_summary[[col]][class_summary$default == k]\n\nclass_summary_table <- class_summary |>\n  transmute(default, n = format(n, big.mark = \",\"),\n            prop = sprintf(\"%.4f\", prop),\n            mean_balance = dollars(mean_balance),\n            sd_balance = dollars(sd_balance),\n            n_zero = format(n_zero, big.mark = \",\")) |>\n  knitr::kable(col.names = c(\"Default\", \"Customers\", \"Proportion\",\n                             \"Mean balance (\\\\$)\", \"SD of balance (\\\\$)\",\n                             \"Zero balances\"),\n               align = \"cccccc\")\n\nbalance_hist_plot <- ggplot(Default, aes(x = balance)) +\n  geom_histogram(aes(y = after_stat(density)), binwidth = 100,\n                 boundary = 0, fill = \"grey80\", color = \"grey55\") +\n  facet_wrap(~ default, ncol = 1, labeller = label_both) +\n  scale_x_continuous(labels = dollar_labels) +\n  labs(x = \"Credit card balance ($)\", y = \"Density\",\n       title = \"ISLR2::Default, balance within each default class\")\n\n# All customers on the count scale, each bar split by default status. The\n# fills differ in lightness so the split survives without color.\nbalance_stack_plot <- ggplot(Default, aes(x = balance, fill = default)) +\n  geom_histogram(binwidth = 100, boundary = 0, color = \"grey30\",\n                 linewidth = 0.2) +\n  scale_fill_manual(values = c(No = \"#9DC3E6\", Yes = \"#D55E00\")) +\n  scale_x_continuous(labels = dollar_labels) +\n  labs(x = \"Credit card balance ($)\", y = \"Customers\", fill = \"Default\",\n       title = \"ISLR2::Default, all customers by default status\")\n\n# Share of defaulters in each $100 balance bin holding at least min_bin_n\n# customers.\nbin_width <- 100\nmin_bin_n <- 10\nexample_bin <- 2000\nbin_share <- Default |>\n  mutate(bin = floor(balance / bin_width) * bin_width) |>\n  group_by(bin) |>\n  summarize(n = n(), share = mean(default == \"Yes\"), .groups = \"drop\") |>\n  filter(n >= min_bin_n)\nshare_at <- function(b) bin_share$share[bin_share$bin == b]\nfirst_majority_bin <- min(bin_share$bin[bin_share$share > 0.5])\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Default | Customers | Proportion | Mean balance (\\$) | SD of balance (\\$) | Zero balances |\n|:-------:|:---------:|:----------:|:-----------------:|:------------------:|:-------------:|\n|   No    |   9,667   |   0.9667   |        804        |        456         |      499      |\n|   Yes   |    333    |   0.0333   |       1,748       |        341         |       0       |\n\n\n:::\n:::\n\n\n::: {.panel-tabset}\n#### Within each class\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/default-hist-figure-1.png){width=672}\n:::\n:::\n\n\n#### All customers\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/default-stack-figure-1.png){width=672}\n:::\n:::\n\n:::\n\nOnly 333 customers, a proportion\nof 0.0333, defaulted. Within each\nclass the balances form a single, roughly bell-shaped pile, and the two piles\nare centered at different values: defaulters average\n\\$1,748 against\n\\$804 for non-defaulters. The\nstandard deviations, \\$456 for\nnon-defaulters and \\$341 for\ndefaulters, are of the same order but not equal, and the non-defaulter\nhistogram has a spike at zero:\n499 customers carry no\nbalance, and\nno defaulter does.\n\nOn the count scale, defaulters are a thin layer at the bottom of the bars at\nmost balances and make up most of a bar only at the largest balances.\n\n### Bayes' theorem\n\nWith the response falling in one of $K$ classes, indexed $k = 1, \\ldots, K$,\nlogistic regression models the conditional probability\n$P(Y = k \\mid X = x)$ directly. Its likelihood is the conditional\ndistribution of the response given the features, and the distribution of the\nfeatures themselves never enters it.\n\nA **generative classifier** takes the other route. It models how the features\nare distributed *within* each class, as in the first tab above, and how\ncommon each class is, and then reverses the conditioning with Bayes' theorem\nto obtain $P(Y = k \\mid X = x)$. LDA is the first generative classifier in\nthis course.\n\nEvery earlier lecture conditioned on the features and treated them as fixed. A\ngenerative classifier models their distribution, so here $X$ is a random\nvector — the features of a randomly chosen observation — and $x$ is a value it\ntakes. With $Y$ the response, define\n\n$$\\pi_k = P(Y = k), \\qquad f_k(x) = \\text{density of } X \\text{ given } Y = k,$$\n\nwhere\n\n- $K$ is the number of classes ($K = 2$ for a binary response),\n- $\\pi_k$ is the **prior probability** of class $k$, the probability that a\nrandomly chosen observation belongs to class $k$ before its features are\nseen, with $\\sum_{k=1}^K \\pi_k = 1$, and\n- $f_k(x)$ is the **class-conditional density** of $X$ among observations in\nclass $k$ (a probability mass function if $X$ is discrete).\n\nThe classification and logistic regression lectures wrote $C$ for the number\nof classes; following ISLR2, this and later lectures write $K$.\n\nBayes' theorem, with densities in place of the probabilities of the events\n$\\{X = x\\}$, gives\n\n$$P(Y = k \\mid X = x) = \\frac{P(Y = k)\\, f_k(x)}{f(x)},$$\n\nwhere $f(x)$ is the marginal density of $X$. By the law of total probability,\n$f(x) = \\sum_{l=1}^K P(Y = l)\\, f_l(x)$, so\n\n$$p_k(x) = P(Y = k \\mid X = x) = \\frac{\\pi_k f_k(x)}{\\sum_{l=1}^K \\pi_l f_l(x)} \\propto \\pi_k f_k(x),$$\n\nwhere\n\n- $p_k(x)$ is the **posterior probability** of class $k$ for an observation\nwith features $x$,\n- $l$ indexes the classes in the sum, kept distinct from the $k$ being\nevaluated, and\n- $\\propto$ means \"proportional to\" as a function of $k$ at a fixed $x$.\n\nOnly the numerator distinguishes one class from another: a class is probable\nat $x$ when it is common ($\\pi_k$ large) and when $x$ is a typical feature\nvalue for it ($f_k(x)$ large).\n\nFor the credit card customers the class proportions estimate the priors,\n$\\hat\\pi_{\\text{No}} = 0.9667$ and\n$\\hat\\pi_{\\text{Yes}} = 0.0333$, and\nthe two panels of the first tab picture $f_{\\text{No}}$ and\n$f_{\\text{Yes}}$ for balance. The second tab pictures the numerators: each\ncolored segment's height is proportional to $\\pi_k f_k(x)$ over its bin, the\nwhole bar's to their sum $f(x)$, and the defaulters' share of the bar\nestimates $p_{\\text{Yes}}(x)$. Among customers with balances from\n\\$2,000 to \\$2,100, for\nexample, a share of 0.702 defaulted.\n\n### Bayes classifier\n\nA **classifier** is an assignment rule $\\hat y(x)$ that maps each value of\nthe features to one of the classes $1, \\ldots, K$. The **Bayes classifier**\nassigns each observation to the class with the largest posterior probability,\n\n$$\\hat y(x) = \\arg\\max_k\\, p_k(x),$$\n\nwhere\n\n- $\\hat y(x)$ is the class assigned to an observation with features $x$, and\n- $\\arg\\max_k p_k(x)$ is the class $k$ at which $p_k(x)$ is largest.\n\nWith $K = 2$ classes, $p_1(x) = 1 - p_2(x)$, so the Bayes classifier assigns\nclass $2$ whenever $p_2(x) > 0.5$.\n\nFor any classifier, the probability that the assignment at $x$ is wrong is\n\n$$P\\left(Y \\ne \\hat y(x) \\mid X = x\\right) = 1 - p_{\\hat y(x)}(x).$$\n\nThis is smallest when $p_{\\hat y(x)}(x)$ is largest, which is exactly the\nBayes classifier's choice. The Bayes classifier therefore minimizes the\nconditional error probability at every $x$, and so it also minimizes the\noverall error rate $E\\left[1 - p_{\\hat y(X)}(X)\\right]$, which averages those\nconditional error probabilities over the distribution of $X$. Its overall\nerror rate, the **Bayes error rate**, is the lowest achievable by any\nclassifier.\n\nAn estimate of this rule from the bars of the stacked histogram assigns `Yes`\nwhere defaulters make up more than half a bar, which first happens in the bin\nstarting at \\$2,000 (among bins with at least\n10 customers). With no feature information the largest posterior\nprobability is the largest prior, so every customer would be assigned `No`, and the\n3.33% who defaulted would all\nbe misclassified; that error rate is the one any classifier using features\nhas to beat.\n\nThe Bayes classifier needs the true $\\pi_k$ and $f_k$, which are never known.\nA generative classifier estimates both from training data and substitutes the\nestimates into Bayes' theorem. Estimating $\\pi_k$ takes nothing more than the\nproportion of training observations in class $k$. Estimating $f_k$ requires an\nassumption about its form, and LDA's assumption is that it is Gaussian.\n\n## One-feature LDA\n\nThe one feature here is balance. The histograms below show balance within\neach default class, one panel per class, on the density scale.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/onefeature-hist-figure-1.png){width=672}\n:::\n:::\n\n\nEach class's balances form a single, roughly bell-shaped pile; the two piles\nare centered at different balances and have spreads of the same order. That\nsuggests a model: describe each class's balance by a Gaussian density with its\nown mean, the center of its pile, and one variance shared by both classes, the\ncommon width of the piles.\n\n### Gaussian class-conditional densities\n\nWith a single feature ($p = 1$) and observations indexed $i = 1, \\ldots, n$,\nLDA assumes the statistical model\n\n$$Y_i \\stackrel{ind}{\\sim} \\text{Categorical}\\left(\\pi_1, \\ldots, \\pi_K\\right), \\qquad X_i \\mid Y_i = k \\stackrel{ind}{\\sim} N\\left(\\mu_k, \\sigma^2\\right), \\qquad i = 1, \\ldots, n,$$\n\nwhere\n\n- $Y_i$ is the class of observation $i$ and $X_i$ its feature value, both\nrandom, with observed values $y_i$ and $x_i$,\n- $\\text{Categorical}\\left(\\pi_1, \\ldots, \\pi_K\\right)$ is the distribution on\nthe classes $\\{1, \\ldots, K\\}$ with $P(Y_i = k) = \\pi_k$,\n- $\\stackrel{ind}{\\sim}$ means independent over $i$: the $Y_i$ are independent,\nand given $Y_1, \\ldots, Y_n$ the $X_i$ are independent, each depending only on\nits own class $Y_i$,\n- $\\mu_k = E[X_i \\mid Y_i = k]$ is the mean of the feature in class $k$, and\n- $\\sigma^2 = Var[X_i \\mid Y_i = k]$ is the variance of the feature, **the same\nin every class**.\n\nA new observation $(X, Y)$, the one to be classified, follows the same model,\nso $\\pi_k = P(Y = k)$ and $f_k$ is the density of $X$ given $Y = k$, as in\nBayes' theorem above. The class-conditional density is therefore the normal\ndensity\n\n$$f_k(x) = \\frac{1}{\\sqrt{2\\pi}\\,\\sigma} \\exp\\left[-\\frac{(x - \\mu_k)^2}{2\\sigma^2}\\right],$$\n\nwhere $\\pi$ without a subscript is the constant $3.14159\\ldots$, unrelated to the\nprior probabilities $\\pi_k$.\n\nThe classes differ only in where their densities are centered. For the credit\ncard customers, $\\mu_k$ is the center of class $k$'s pile of balances in the\nhistograms above, and $\\sigma$ is the width the two piles share.\n\n### Parameter estimation\n\nThe parameters $\\pi_k$, $\\mu_k$, and $\\sigma^2$ are estimated from the\nobserved training data $(x_1, y_1), \\ldots, (x_n, y_n)$, here with $x_i$ the\nscalar feature value of observation $i$:\n\n$$\\hat\\pi_k = \\frac{n_k}{n}, \\qquad \\hat\\mu_k = \\frac{1}{n_k}\\sum_{i:\\, y_i = k} x_i, \\qquad \\hat\\sigma^2 = \\frac{1}{n - K}\\sum_{k=1}^K \\sum_{i:\\, y_i = k}\\left(x_i - \\hat\\mu_k\\right)^2,$$\n\nwhere\n\n- $n_k$ is the number of training observations in class $k$, so\n$\\sum_k n_k = n$,\n- $\\sum_{i:\\, y_i = k}$ sums over the training observations in class $k$, and\n- $\\hat\\sigma^2$ is the **pooled variance**: squared deviations from each\nobservation's own class mean, summed over all classes and divided by $n - K$.\n\n$\\hat\\pi_k$ and $\\hat\\mu_k$ are maximum likelihood estimates; $\\hat\\sigma^2$\nis the maximum likelihood estimate rescaled by $n/(n - K)$ to make it\nunbiased. Under the generative model the joint\ndensity of observation $i$ is $P(Y_i = y_i)\\, f_{y_i}(x_i) = \\pi_{y_i} f_{y_i}(x_i)$,\nand the independence over $i$ in the model makes the likelihood the product of\nthese densities, so the log-likelihood is\n\n$$\\ell(\\pi_1, \\ldots, \\pi_K, \\mu_1, \\ldots, \\mu_K, \\sigma^2) = \\sum_{k=1}^K n_k \\log \\pi_k \\;+\\; \\sum_{k=1}^K \\sum_{i:\\, y_i = k}\\left[-\\frac{1}{2}\\log\\left(2\\pi\\sigma^2\\right) - \\frac{(x_i - \\mu_k)^2}{2\\sigma^2}\\right].$$\n\nThe first sum involves only the priors; maximizing it subject to\n$\\sum_k \\pi_k = 1$ (with a Lagrange multiplier) gives $\\hat\\pi_k = n_k/n$. In\nthe second, $\\mu_k$ appears only in class $k$'s terms, so its maximizer is the\nclass-$k$ sample mean. Setting the derivative with respect to $\\sigma^2$ to\nzero gives the pooled sum of squares divided by $n$; dividing by $n - K$\ninstead, one degree of freedom per estimated mean, makes it unbiased, in the\nsame way that $RSS/(n-2)$ replaced $RSS/n$ in simple linear regression.\n`MASS::lda()` uses $n - K$.\n\nLogistic regression maximizes a different likelihood, the conditional one,\n$\\prod_{i=1}^n p(x_i)^{y_i}\\left[1 - p(x_i)\\right]^{1 - y_i}$ (with $y_i$\ncoded $0/1$ as in the logistic regression lectures), which has no closed-form\nmaximizer. LDA maximizes the joint likelihood of features and\nresponses under a stronger assumption — Gaussian features with a shared\nvariance — and every estimate is a sample proportion, mean, or variance.\n\n`MASS::lda()` takes the same formula interface as `glm()`. Fitting `default`\non `balance` prints three blocks: the prior probabilities, the group means,\nand the coefficients of linear discriminants.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbalance_lda <- MASS::lda(default ~ balance, data = Default)\nbalance_lda\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nlda(default ~ balance, data = Default)\n\nPrior probabilities of groups:\n    No    Yes \n0.9667 0.0333 \n\nGroup means:\n      balance\nNo   803.9438\nYes 1747.8217\n\nCoefficients of linear discriminants:\n                LD1\nbalance 0.002206916\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimates of pi_k, mu_k, Sigma and the implied log posterior odds\n# beta0 + x' beta of the second class, computed from the formulas above.\nlda_by_hand <- function(X, y) {\n  X <- as.matrix(X)\n  classes <- levels(y)\n  n <- nrow(X)\n  K <- length(classes)\n  pi_hat <- as.numeric(table(y)) / n\n  mu_hat <- do.call(rbind, lapply(classes, function(k) {\n    colMeans(X[y == k, , drop = FALSE])\n  }))\n  rownames(mu_hat) <- classes\n  Sigma_hat <- Reduce(`+`, lapply(classes, function(k) {\n    Z <- sweep(X[y == k, , drop = FALSE], 2, mu_hat[k, ])\n    crossprod(Z)\n  })) / (n - K)\n  beta  <- solve(Sigma_hat, mu_hat[2, ] - mu_hat[1, ])\n  beta0 <- log(pi_hat[2] / pi_hat[1]) -\n    0.5 * (sum(mu_hat[2, ] * solve(Sigma_hat, mu_hat[2, ])) -\n           sum(mu_hat[1, ] * solve(Sigma_hat, mu_hat[1, ])))\n  list(pi = pi_hat, mu = mu_hat, Sigma = Sigma_hat,\n       beta0 = beta0, beta = beta)\n}\n\nhand_1 <- lda_by_hand(Default[\"balance\"], Default$default)\nsigma_hat_1 <- sqrt(hand_1$Sigma[1, 1])\n\nbalance_grid <- tibble(balance = seq(0, 2800, length.out = 500))\ngauss_curves <- tibble(default = factor(c(\"No\", \"Yes\"))) |>\n  mutate(mu = hand_1$mu[, 1]) |>\n  cross_join(balance_grid) |>\n  mutate(f = dnorm(balance, mu, sigma_hat_1))\n\ngauss_plot <- balance_hist_plot +\n  geom_line(data = gauss_curves, aes(y = f, color = default,\n                                     linetype = default),\n            linewidth = 0.9) +\n  scale_color_manual(values = class_colors) +\n  labs(color = \"Default\", linetype = \"Default\",\n       title = expression(paste(\"Histograms with fitted \",\n                                N(hat(mu)[k], hat(sigma)^2), \" densities\")))\n```\n:::\n\n:::\n\nThe figure below draws each class's fitted density\n$N\\left(\\hat\\mu_k, \\hat\\sigma^2\\right)$ over that class's histogram from the\nstart of this section.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/balance-gauss-figure-1.png){width=672}\n:::\n:::\n\n\nThe **prior probabilities** are $\\hat\\pi_{\\text{No}} = 0.9667$\nand $\\hat\\pi_{\\text{Yes}} = 0.0333$, the class\nproportions of the class summary table. The **group means** are\n$\\hat\\mu_{\\text{No}} = 803.94$\nand $\\hat\\mu_{\\text{Yes}} = 1{,}747.82$\ndollars, the mean balances of the same table. The pooled standard deviation is\n$\\hat\\sigma = 453.12$, between the two\nclass-specific standard deviations.\n\nIn the figure, the fitted density for non-defaulters misses the spike at zero,\nand the one for defaulters, forced to share $\\hat\\sigma$ with the larger\nclass, is wider than their histogram: the two departures from LDA's\nassumptions that the histograms showed.\n\nThe **coefficient of the linear discriminant**,\n0.002207, equals\n$1/\\hat\\sigma = 0.002207$: `MASS::lda()`\nreports the discriminant direction rescaled so that the printed linear\ncombination, $\\text{LD1} = \\text{coefficient} \\times \\texttt{balance}$, has\nvariance $1$ within each class, and with one feature the direction itself is\njust \"larger balance points toward `Yes`.\" This is Fisher's scaling,\ndescribed in the callout below.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\nThe \"coefficients of linear discriminants\" printed by `MASS::lda()` come from\nR. A. Fisher's original formulation of discriminant analysis, which asks for\nthe linear combination of features that maximizes the ratio of\nbetween-class to within-class variance and makes no Gaussian assumption.\nWith $K$ classes that problem yields up to $K - 1$ discriminant directions,\nprinted as `LD1`, `LD2`, ..., and normalized to have unit within-class\nvariance. With Gaussian classes and a shared covariance matrix, Fisher's\ndirections and the Bayes'-theorem discriminants of this lecture produce the\nsame classifier.\n:::\n\n::: {.callout-note collapse=\"true\"}\n### For example,\nLDA's estimates have closed forms, and separation does not prevent them from\nexisting, though a zero pooled variance still would. The previous\nlecture's completely separated toy data, $x = 1, \\ldots, 10$ with $y = 1$\nexactly when $x > 5$, left logistic regression with no finite maximum\nlikelihood estimate. `MASS::lda()` fits LDA to the same data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntoy <- tibble(x = 1:10, y = factor(as.numeric(x > 5)))\ntoy_lda <- MASS::lda(y ~ x, data = toy)\ntoy_lda$means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x\n0 3\n1 8\n```\n\n\n:::\n:::\n\n\nThe class means are 3 and 8 and the\npriors are equal, so LDA classifies by which class mean is closer: the\nboundary is their midpoint, 5.5.\n:::\n\n### Discriminant function\n\nSince $p_k(x)$ is proportional to $\\pi_k f_k(x)$ and the logarithm is\nincreasing, the class with the largest posterior probability is also the class\nwith the largest $\\log\\left[\\pi_k f_k(x)\\right]$. Expanding the square and\ncollecting terms,\n\n$$\\log\\left[\\pi_k f_k(x)\\right] = \\log \\pi_k - \\frac{\\mu_k^2}{2\\sigma^2} + \\frac{\\mu_k}{\\sigma^2}\\, x - \\log\\left(\\sqrt{2\\pi}\\,\\sigma\\right) - \\frac{x^2}{2\\sigma^2}.$$\n\nThe last two terms do not involve $k$ because $\\sigma^2$ is shared, so they\ncannot change which class is largest. Dropping them gives the **discriminant\nfunction**\n\n$$\\delta_k(x) = \\left(\\log \\pi_k - \\frac{\\mu_k^2}{2\\sigma^2}\\right) + \\frac{\\mu_k}{\\sigma^2}\\, x,$$\n\nwhere\n\n- $\\delta_k(x)$ is the discriminant value of class $k$ at feature value $x$,\n- $\\log \\pi_k - \\mu_k^2/\\left(2\\sigma^2\\right)$ is its intercept, the score\nat $x = 0$, and\n- $\\mu_k/\\sigma^2$ is its slope.\n\nThe dropped term $-x^2/\\left(2\\sigma^2\\right)$ was the only one quadratic in\n$x$, so each $\\delta_k$ is linear in $x$, with the same intercept-plus-slope form as a regression's\nlinear predictor. The classifier assigns an observation to the\nclass with the largest $\\delta_k(x)$. The slope $\\mu_k/\\sigma^2$ is not the\ncoefficient of the linear discriminant printed by `MASS::lda()`, which is\nFisher's scaling of the discriminant direction.\n\nHad the variances differed, with $\\sigma_k^2$ the class-$k$ variance, the\nterm $-\\log\\left(\\sqrt{2\\pi}\\,\\sigma_k\\right)$ would differ between classes\nand stay in each intercept, and the term $-x^2/\\left(2\\sigma_k^2\\right)$ would\ncarry a different coefficient in each class, would not drop out, and would\nmake each discriminant quadratic in $x$.\n\nThe terms dropped from $\\log\\left[\\pi_k f_k(x)\\right]$ to form $\\delta_k(x)$\nare the same in every class, so $e^{\\delta_k(x)}$ is $\\pi_k f_k(x)$ multiplied\nby a factor common to every class. That factor cancels from the ratio in Bayes'\ntheorem and the posterior probabilities can be recovered from the discriminant\nvalues alone:\n\n$$p_k(x) = \\frac{e^{\\delta_k(x)}}{\\sum_{l=1}^K e^{\\delta_l(x)}}.$$\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndelta_1 <- tibble(default = c(\"No\", \"Yes\"),\n                  intercept = log(hand_1$pi) -\n                    hand_1$mu[, 1]^2 / (2 * sigma_hat_1^2),\n                  slope = hand_1$mu[, 1] / sigma_hat_1^2)\ndelta_of <- function(k, col) delta_1[[col]][delta_1$default == k]\n```\n:::\n\n:::\n\nSubstituting $\\hat\\pi_k$, $\\hat\\mu_k$, and $\\hat\\sigma^2$ for the credit card\ncustomers gives the estimated discriminants, with balance in dollars,\n\n$$\\hat\\delta_{\\text{No}}(x) = -1.608 + 0.003916\\, x, \\qquad \\hat\\delta_{\\text{Yes}}(x) = -10.842 + 0.008513\\, x.$$\n\nThe defaulters' line starts far lower, because $\\hat\\pi_{\\text{Yes}}$ is\nsmall and $\\hat\\mu_{\\text{Yes}}$ large, and climbs\n2.2 times\nas fast, because $\\hat\\mu_{\\text{Yes}}$ is the larger mean.\n\n### Decision boundary\n\nWith $K = 2$ classes, $p_1(x) = 1 - p_2(x)$, and the log posterior odds of\nclass $2$ are\n\n$$\\log\\left[\\frac{p_2(x)}{1 - p_2(x)}\\right] = \\delta_2(x) - \\delta_1(x) = \\underbrace{\\log\\frac{\\pi_2}{\\pi_1} - \\frac{\\mu_2^2 - \\mu_1^2}{2\\sigma^2}}_{\\beta_0} + \\underbrace{\\frac{\\mu_2 - \\mu_1}{\\sigma^2}}_{\\beta_1}\\, x.$$\n\nThe log-odds are linear in $x$, so LDA's posterior probability has exactly the\nform of a simple logistic regression. The two methods differ in how they\nestimate $\\beta_0$ and $\\beta_1$, not in the shape of the curve they fit.\n\nThe **decision boundary** is the set of $x$ where the two classes are equally\nprobable, $\\delta_1(x) = \\delta_2(x)$. Setting the log posterior odds to zero\nand solving,\n\n$$x^* = \\frac{\\mu_1 + \\mu_2}{2} + \\frac{\\sigma^2}{\\mu_2 - \\mu_1}\\log\\frac{\\pi_1}{\\pi_2},$$\n\nwhere\n\n- $x^*$ is the feature value at which the classifier switches from one class\nto the other.\n\nWith equal prior probabilities the logarithm is zero and the boundary is the\nmidpoint of the two means. Take $\\mu_2 > \\mu_1$. If class $2$ is the rarer\nclass, $\\pi_2 < \\pi_1$, the logarithm is positive and the boundary moves to the\nright, toward $\\mu_2$, and past it once\n$\\sigma^2 \\log(\\pi_1/\\pi_2)/(\\mu_2 - \\mu_1) > (\\mu_2 - \\mu_1)/2$: an observation must look more like a typical class-$2$\nobservation before the classifier assigns it to the rarer class. Since\n$\\delta_1(x) = \\delta_2(x)$ exactly where $\\pi_1 f_1(x) = \\pi_2 f_2(x)$, the\nboundary is also where the two prior-weighted densities cross.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nx_mid <- mean(hand_1$mu[, 1])\nx_star_lda <- -hand_1$beta0 / hand_1$beta[1]\n\n# Prior-weighted densities pi_k f_k(x) and discriminant functions delta_k(x)\n# for the fitted means and pooled variance, under a given pair of priors.\nweighted_curves <- function(priors) {\n  tibble(default = factor(c(\"No\", \"Yes\")), mu = hand_1$mu[, 1],\n         prior = priors) |>\n    cross_join(balance_grid) |>\n    mutate(weighted = prior * dnorm(balance, mu, sigma_hat_1),\n           delta = (log(prior) - mu^2 / (2 * sigma_hat_1^2)) +\n                   mu / sigma_hat_1^2 * balance)\n}\n\nweighted_plot <- function(priors, boundary, title, y_label) {\n  ggplot(weighted_curves(priors),\n         aes(x = balance, y = weighted, color = default, linetype = default)) +\n    geom_line(linewidth = 0.9) +\n    geom_vline(xintercept = boundary, linetype = \"dotted\") +\n    scale_color_manual(values = class_colors) +\n    scale_x_continuous(labels = dollar_labels) +\n    labs(x = \"Credit card balance ($)\",\n         y = y_label,\n         color = \"Default\", linetype = \"Default\", title = title)\n}\n\nequal_priors_plot <- weighted_plot(\n  c(0.5, 0.5), x_mid,\n  expression(paste(\"Equal priors, \", pi[No] == pi[Yes], \" = 0.5\")),\n  expression(pi[k] * hat(f)[k](x)))\nestimated_priors_plot <- weighted_plot(\n  hand_1$pi, x_star_lda,\n  bquote(paste(\"Estimated priors, \",\n               hat(pi)[Yes] == .(sprintf(\"%.4f\", hand_1$pi[2])))),\n  expression(hat(pi)[k] * hat(f)[k](x)))\n\ndelta_default_plot <- ggplot(weighted_curves(hand_1$pi),\n                             aes(x = balance, y = delta,\n                                 color = default, linetype = default)) +\n  geom_line(linewidth = 0.9) +\n  geom_vline(xintercept = x_star_lda, linetype = \"dotted\") +\n  scale_color_manual(values = class_colors) +\n  scale_x_continuous(labels = dollar_labels) +\n  labs(x = \"Credit card balance ($)\", y = expression(hat(delta)[k](x)),\n       color = \"Default\", linetype = \"Default\",\n       title = \"Estimated discriminant functions, estimated priors\")\n```\n:::\n\n:::\n\nFor the credit card fit, the first tab below plots the prior-weighted fitted\ndensities with equal priors, a counterfactual in which defaulting is as\ncommon as not, and the second with the estimated priors. The third plots the\ntwo estimated discriminant functions. In every tab a dotted line marks that\ntab's decision boundary.\n\n::: {.panel-tabset}\n#### Equal priors\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/balance-equal-figure-1.png){width=672}\n:::\n:::\n\n\n#### Estimated priors\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/balance-weighted-figure-1.png){width=672}\n:::\n:::\n\n\n#### Discriminant functions\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/balance-delta-figure-1.png){width=672}\n:::\n:::\n\n:::\n\nWith equal priors the two curves are the same height and cross at the\nmidpoint of the class means, \\$1,276. With the estimated priors\nthe defaulter curve shrinks to a small bump that rises above the non-defaulter\ncurve only past\n$\\hat x^* = \\$2{,}009$, deep in\nthe non-defaulters' right tail. In the boundary formula that shift is\nthe prior term\n$\\hat\\sigma^2\\log\\left(\\hat\\pi_{\\text{No}}/\\hat\\pi_{\\text{Yes}}\\right)/\\left(\\hat\\mu_{\\text{Yes}} - \\hat\\mu_{\\text{No}}\\right)$,\nwhich adds \\$733 because $\\hat\\pi_{\\text{Yes}}$ is\nso small. The boundary lies beyond\n$\\hat\\mu_{\\text{Yes}} = \\$1{,}748$,\nso even a customer with the defaulters' average balance is classified `No`. The discriminant functions are two straight lines crossing at the\nsame balance. A linear discriminant function for each class, with the\nboundary where two of them are equal, is the \"linear\" in linear discriminant\nanalysis.\n\n### Simple logistic regression comparison\n\nBecause the log posterior odds are linear in $x$, LDA's fit can be set beside\nthe simple logistic regression of the same customers on the log-odds scale.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nbalance_glm <- glm(default ~ balance, data = Default, family = \"binomial\")\nb_glm_1     <- coef(balance_glm)\nx_star_glm  <- -b_glm_1[1] / b_glm_1[2]\n\npost_1 <- predict(balance_lda)$posterior[, \"Yes\"]\nmax_diff_1 <- max(abs(post_1 - plogis(hand_1$beta0 +\n                                       hand_1$beta[1] * Default$balance)))\n\ncoef_table_1 <- tibble(\n  term = c(\"Intercept $\\\\hat\\\\beta_0$\", \"`balance` $\\\\hat\\\\beta_1$\"),\n  lda = c(hand_1$beta0, hand_1$beta[1]),\n  glm = unname(b_glm_1)\n) |>\n  mutate(across(c(lda, glm), \\(v) sprintf(\"%.6f\", v))) |>\n  knitr::kable(col.names = c(\"Coefficient\", \"LDA\", \"Logistic regression\"),\n               align = \"lcc\")\n\nposterior_curves <- balance_grid |>\n  mutate(LDA = plogis(hand_1$beta0 + hand_1$beta[1] * balance),\n         `Logistic regression` = predict(balance_glm,\n                                         newdata = balance_grid,\n                                         type = \"response\")) |>\n  pivot_longer(-balance, names_to = \"model\", values_to = \"p_hat\")\n\nposterior_default_plot <- ggplot(posterior_curves,\n                                 aes(x = balance, y = p_hat)) +\n  geom_point(data = Default, aes(y = default_jit), alpha = 0.08,\n             size = 0.7) +\n  geom_hline(yintercept = 0.5, color = \"grey60\") +\n  geom_line(aes(color = model, linetype = model), linewidth = 0.9) +\n  scale_color_manual(values = model_colors) +\n  scale_y_continuous(breaks = c(0, 0.5, 1)) +\n  scale_x_continuous(labels = dollar_labels) +\n  labs(x = \"Credit card balance ($)\", y = \"P(default = Yes)\",\n       color = \"Model\", linetype = \"Model\",\n       title = \"Posterior probability of default\")\n```\n:::\n\n:::\n\nThe table gives LDA's $\\hat\\beta_0$ and $\\hat\\beta_1$, from the estimates\nabove, beside the simple logistic regression's coefficients. The figure plots\nboth models' probability of default against balance, with each customer's\njittered outcome and a grey line at $0.5$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Coefficient             |    LDA    | Logistic regression |\n|:-----------------------|:---------:|:-------------------:|\n|Intercept $\\hat\\beta_0$ | -9.233739 |     -10.651331      |\n|`balance` $\\hat\\beta_1$ | 0.004597  |      0.005499       |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/balance-posterior-figure-1.png){width=672}\n:::\n:::\n\n\nThe intercept $\\hat\\beta_0 = -9.234$ is LDA's\nestimated log posterior odds of default for a customer carrying no balance, a\nposterior probability of\n0.000098. Each additional\n\\$100 of balance adds 0.460 to the log\nposterior odds, against 0.550 in the logistic\nregression. Applying the logistic function to\n$\\hat\\beta_0 + \\hat\\beta_1 x$ reproduces the posterior probabilities returned\nby `predict()` to within $1 \\times 10^{-14}$.\n\nThe LDA curve is a logistic curve, slightly flatter than the logistic\nregression fit, and it crosses $0.5$ a little further right, at\n\\$2,009 against \\$1,937. Logistic\nregression has no priors or class means; its boundary is high because\ndefaults are rare among customers at all but the largest balances, so its\nfitted probability reaches $0.5$ only there.\n\n## Multiple-feature LDA\n\nA second feature turns each customer into a point. The first tab below plots\nincome against credit card balance for every customer, with defaulters and\nnon-defaulters distinguished by color and shape; the second shows income\nwithin each default class, one panel per class, on the density scale.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# Defaulters are drawn last so they are not hidden under non-defaulters.\nscatter_base <- ggplot(arrange(Default, default),\n                       aes(x = balance, y = income)) +\n  geom_point(aes(color = default, shape = default), alpha = 0.35,\n             size = 0.8) +\n  scale_color_manual(values = class_colors) +\n  scale_shape_manual(values = c(16, 17)) +\n  guides(color = guide_legend(override.aes = list(alpha = 1, size = 2))) +\n  scale_x_continuous(labels = dollar_labels) +\n  scale_y_continuous(labels = dollar_labels) +\n  labs(x = \"Credit card balance ($)\", y = \"Income ($)\", color = \"Default\",\n       shape = \"Default\")\n\neda_scatter <- scatter_base +\n  labs(title = \"ISLR2::Default, income against balance\")\n\nincome_hist_plot <- ggplot(Default, aes(x = income)) +\n  geom_histogram(aes(y = after_stat(density)), binwidth = 2500,\n                 boundary = 0, fill = \"grey80\", color = \"grey55\") +\n  facet_wrap(~ default, ncol = 1, labeller = label_both) +\n  scale_x_continuous(labels = dollar_labels) +\n  labs(x = \"Income ($)\", y = \"Density\",\n       title = \"ISLR2::Default, income within each default class\")\n\nwithin_cor <- Default |>\n  group_by(default) |>\n  summarize(r = cor(balance, income), mean_income = mean(income),\n            .groups = \"drop\")\nwithin_of <- function(k, col) within_cor[[col]][within_cor$default == k]\n\nincome_by_student <- Default |>\n  group_by(student) |>\n  summarize(median_income = median(income), .groups = \"drop\")\nstudent_income <- function(s) {\n  income_by_student$median_income[income_by_student$student == s]\n}\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Scatterplot\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/default-scatter-figure-1.png){width=672}\n:::\n:::\n\n\n#### Income histograms\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/default-income-figure-1.png){width=672}\n:::\n:::\n\n:::\n\nEach class forms a broad cloud, and the two clouds overlap heavily:\ndefaulters sit at larger balances, across nearly the whole range of income.\nWithin each class balance and income are weakly negatively correlated,\n$r = -0.155$ among non-defaulters and\n$r = -0.166$ among defaulters, so a\ndescription of each class's cloud needs a center and a spread for each\nfeature and the correlation between them. The two classes' mean incomes are\nclose, \\$32,089 for defaulters against\n\\$33,566.\n\nThe two classes' income histograms look alike, and each is bimodal. The\nlower mode is mostly students: in these data students' median income is\n\\$17,994, against\n\\$39,893 for non-students. No Gaussian density has\ntwo modes, so income strains LDA's assumptions just as balance did.\n\nThe clouds suggest the multivariate version of the one-feature model:\ndescribe each class's features by a multivariate Gaussian density with its own\nmean vector, the center of its cloud, and a covariance matrix shared by both\nclasses, which gives the clouds one common spread and tilt.\n\n### Multivariate Gaussian densities\n\nWith $p > 1$ features, the features of observation $i$ form a random column\nvector $X_i = (X_{i1}, \\ldots, X_{ip})^\\top$, and $x$ is a $p$-vector value\nit takes. A value $x$ holds the same kind of entries as a row of the model\nmatrix $\\mathbf{X}$ but without the leading $1$, and it is a column because it\nis the argument of a multivariate density. LDA assumes the statistical model\n\n$$Y_i \\stackrel{ind}{\\sim} \\text{Categorical}\\left(\\pi_1, \\ldots, \\pi_K\\right), \\qquad X_i \\mid Y_i = k \\stackrel{ind}{\\sim} N_p\\left(\\mu_k, \\Sigma\\right), \\qquad i = 1, \\ldots, n,$$\n\nwhere\n\n- $Y_i$, $\\text{Categorical}\\left(\\pi_1, \\ldots, \\pi_K\\right)$, and\n$\\stackrel{ind}{\\sim}$ are as in the one-feature model, so the observations\nare independent while the $p$ features within one observation may be\ncorrelated,\n- $N_p$ is the $p$-dimensional multivariate normal distribution,\n- $\\mu_k = E[X_i \\mid Y_i = k] = (\\mu_{k1}, \\ldots, \\mu_{kp})^\\top$ is the\n$p$-vector of feature means in class $k$, and\n- $\\Sigma = Cov[X_i \\mid Y_i = k]$ is the $p \\times p$ covariance matrix of\nthe features, **the same in every class**, with feature variances on its\ndiagonal and covariances between pairs of features off it; it is symmetric\nand positive definite.\n\nThe class-conditional density is therefore the multivariate normal density\n\n$$f_k(x) = \\frac{1}{(2\\pi)^{p/2}\\,|\\Sigma|^{1/2}} \\exp\\left[-\\frac{1}{2}\\left(x - \\mu_k\\right)^\\top \\Sigma^{-1} \\left(x - \\mu_k\\right)\\right],$$\n\nwhere $|\\Sigma|$ is the determinant of $\\Sigma$.\n\nEach class's density has contours that are nested ellipses centered at\n$\\mu_k$. Sharing\n$\\Sigma$ means every class's ellipses have the same shape and orientation and\ndiffer only in their center. For the credit card customers, $\\mu_k$ is the\ncenter of class $k$'s cloud in the scatterplot above, and $\\Sigma$ gives the\ntwo clouds one common spread and tilt.\n\n### Pooled covariance estimate\n\nThe estimates generalize directly. The priors are still $\\hat\\pi_k = n_k/n$,\nand with $x_i = (x_{i1}, \\ldots, x_{ip})^\\top$ now the observed value of\n$X_i$, the $p$-vector of feature values for observation $i$ (again without\nthe leading $1$),\n\n$$\\hat\\mu_k = \\frac{1}{n_k}\\sum_{i:\\, y_i = k} x_i, \\qquad \\hat\\Sigma = \\frac{1}{n - K}\\sum_{k=1}^K \\sum_{i:\\, y_i = k}\\left(x_i - \\hat\\mu_k\\right)\\left(x_i - \\hat\\mu_k\\right)^\\top,$$\n\nwhere\n\n- $\\hat\\mu_k$ is the vector of class-$k$ sample means, one per feature, and\n- $\\hat\\Sigma$ is the **pooled covariance matrix**, the sum of each class's\nmatrix of cross-products of deviations from its own mean, divided by $n - K$;\nas in one dimension, it is the maximum likelihood estimate rescaled by\n$n/(n - K)$ to make it unbiased.\n\nAdding `income` to the formula fits the $p = 2$ model to the credit card\ncustomers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadditive_lda <- MASS::lda(default ~ balance + income, data = Default)\nadditive_lda\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nlda(default ~ balance + income, data = Default)\n\nPrior probabilities of groups:\n    No    Yes \n0.9667 0.0333 \n\nGroup means:\n      balance   income\nNo   803.9438 33566.17\nYes 1747.8217 32089.15\n\nCoefficients of linear discriminants:\n                 LD1\nbalance 2.230835e-03\nincome  7.793355e-06\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nX2 <- as.matrix(Default[c(\"balance\", \"income\")])\nhand_2 <- lda_by_hand(X2, Default$default)\n\nscaling_ratio <- additive_lda$scaling[, 1] / hand_2$beta\nsd_within <- sqrt(diag(hand_2$Sigma))\ncor_within <- hand_2$Sigma[1, 2] / prod(sd_within)\n\npost_lda_2 <- predict(additive_lda)$posterior[, \"Yes\"]\nmax_diff_2 <- max(abs(post_lda_2 -\n                      plogis(hand_2$beta0 + drop(X2 %*% hand_2$beta))))\n```\n:::\n\n:::\n\nThe prior probabilities are unchanged, since they do not depend on the\nfeatures. The group means now form a vector for each class: the `balance`\ncolumn repeats the one-feature means, and the `income` column holds the class\nmean incomes. The pooled covariance matrix $\\hat\\Sigma$ has within-class\nstandard deviations of \\$453 for balance and\n\\$13,335 for income and a within-class correlation of\n$-0.155$, a pooled version of the two correlations\nquoted with the scatterplot.\n\n### Matrix-form discriminant\n\nThe derivation follows the one-feature case. Because $\\Sigma^{-1}$ is\nsymmetric, the scalar $\\mu_k^\\top \\Sigma^{-1} x$ equals its own transpose\n$x^\\top \\Sigma^{-1} \\mu_k$, and the quadratic form expands to\n\n$$\\left(x - \\mu_k\\right)^\\top \\Sigma^{-1} \\left(x - \\mu_k\\right) = x^\\top \\Sigma^{-1} x - 2\\, x^\\top \\Sigma^{-1} \\mu_k + \\mu_k^\\top \\Sigma^{-1} \\mu_k.$$\n\nThen, collecting terms in the same order as before,\n\n$$\\log\\left[\\pi_k f_k(x)\\right] = \\log \\pi_k - \\frac{1}{2}\\mu_k^\\top \\Sigma^{-1} \\mu_k + x^\\top \\Sigma^{-1} \\mu_k - \\frac{p}{2}\\log(2\\pi) - \\frac{1}{2}\\log|\\Sigma| - \\frac{1}{2}x^\\top \\Sigma^{-1} x.$$\n\nThe last three terms do not involve $k$: the first is a constant, and the\nother two because $\\Sigma$ is shared. Dropping them gives\n\n$$\\delta_k(x) = \\left(\\log \\pi_k - \\frac{1}{2}\\mu_k^\\top \\Sigma^{-1} \\mu_k\\right) + x^\\top \\Sigma^{-1} \\mu_k,$$\n\nwhere\n\n- $\\log \\pi_k - \\frac{1}{2}\\mu_k^\\top \\Sigma^{-1} \\mu_k$ is the intercept of\nclass $k$'s discriminant, and\n- $\\Sigma^{-1}\\mu_k$ is its $p$-vector of slopes, one per feature.\n\nThe dropped term $-\\frac{1}{2}x^\\top \\Sigma^{-1} x$ was the only one quadratic\nin $x$, so the discriminant is linear in $x$ and reduces to the one-feature discriminant\nwhen $\\Sigma = \\sigma^2$. As before, the classifier assigns the class with the\nlargest $\\delta_k(x)$, and $p_k(x) = e^{\\delta_k(x)} / \\sum_l e^{\\delta_l(x)}$.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nSigma2_inv <- solve(hand_2$Sigma)\n# Each class's estimated discriminant: intercept and slopes Sigma^{-1} mu_k.\ndelta_row_2 <- function(k) {\n  slopes <- drop(Sigma2_inv %*% hand_2$mu[k, ])\n  tibble(default = k,\n         intercept = log(hand_2$pi[rownames(hand_2$mu) == k]) -\n           0.5 * sum(hand_2$mu[k, ] * slopes),\n         balance = slopes[1], income = 1000 * slopes[2])\n}\ndelta_table_2 <- map(c(\"No\", \"Yes\"), delta_row_2) |> list_rbind()\ndelta_kable_2 <- delta_table_2 |>\n  mutate(intercept = sprintf(\"%.3f\", intercept),\n         balance = sprintf(\"%.6f\", balance),\n         income = sprintf(\"%.6f\", income)) |>\n  knitr::kable(col.names = c(\"Default\", \"Intercept\", \"`balance` slope\",\n                             \"`income` slope, per \\\\$1,000\"),\n               align = \"lccc\")\n```\n:::\n\n:::\n\nFor the credit card fit, the table gives each class's estimated\ndiscriminant, $\\hat\\delta_k(x)$, with income slopes per \\$1,000 of income.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Default | Intercept | `balance` slope | `income` slope, per \\$1,000 |\n|:-------|:---------:|:---------------:|:---------------------------:|\n|No      |  -5.603   |    0.004895     |          0.214577           |\n|Yes     |  -15.467  |    0.009567     |          0.230897           |\n\n\n:::\n:::\n\n\nAs in one dimension, the defaulters' discriminant starts far lower and climbs\nfaster in balance. Its income slope is also the larger of the two, so at a\nfixed balance a higher income moves the comparison slightly toward `Yes`.\n\n### Linear decision boundary\n\nWith $K = 2$, subtracting the two discriminants gives the log posterior odds\nof class $2$,\n\n$$\\log\\left[\\frac{p_2(x)}{1 - p_2(x)}\\right] = \\delta_2(x) - \\delta_1(x) = \\beta_0 + x^\\top\\beta,$$\n\nwhere\n\n- $\\beta = \\Sigma^{-1}(\\mu_2 - \\mu_1)$ is a $p$-vector of slopes, one per\nfeature, with no intercept entry, and\n- $\\beta_0 = \\log(\\pi_2/\\pi_1) - \\frac{1}{2}\\left(\\mu_2^\\top \\Sigma^{-1} \\mu_2 - \\mu_1^\\top \\Sigma^{-1} \\mu_1\\right)$\nis the intercept.\n\nThis is again the form of a multiple logistic regression with $p$ features.\nThe decision boundary $\\{x : \\beta_0 + x^\\top\\beta = 0\\}$ is a hyperplane in\nthe $p$-dimensional feature space — a line when $p = 2$.\n\nThe slopes are $\\Sigma^{-1}(\\mu_2 - \\mu_1)$, not $\\mu_2 - \\mu_1$, so the\nboundary is generally not perpendicular to the segment joining the two means:\n$\\Sigma^{-1}$ tilts it according to how the features covary. With equal\npriors it still passes through the midpoint $(\\mu_1 + \\mu_2)/2$, since\nsubstituting that point gives\n$\\frac{1}{2}\\left(\\mu_1 + \\mu_2\\right)^\\top\\Sigma^{-1}\\left(\\mu_2 - \\mu_1\\right) = \\frac{1}{2}\\left(\\mu_2^\\top \\Sigma^{-1} \\mu_2 - \\mu_1^\\top \\Sigma^{-1} \\mu_1\\right)$.\nThe boundary is where $\\pi_1 f_1(x) = \\pi_2 f_2(x)$, so it passes through\nevery point where a contour of $\\pi_1 f_1$ crosses the contour of $\\pi_2 f_2$\nof the same height.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_No  <- hand_2$mu[\"No\", ]\nmu_Yes <- hand_2$mu[\"Yes\", ]\nbeta_2 <- hand_2$beta\nf_peak_2 <- 1 / (2 * pi * sqrt(det(hand_2$Sigma)))\ndens_2 <- function(b, i, mu) {\n  d <- cbind(b - mu[1], i - mu[2])\n  f_peak_2 * exp(-rowSums((d %*% Sigma2_inv) * d) / 2)\n}\n\nwindow_2 <- list(balance = c(0, 2700), income = c(0, 75000))\ngrid_2 <- expand_grid(balance = seq(0, 2700, length.out = 240),\n                      income = seq(0, 75000, length.out = 220)) |>\n  mutate(f_No = dens_2(balance, income, mu_No),\n         f_Yes = dens_2(balance, income, mu_Yes))\n\n# Long grid of pi_k * f_k(x); prior weights of 1 give the unweighted f_k.\nweighted_grid_2 <- function(p) {\n  grid_2 |>\n    transmute(balance, income, No = p[1] * f_No, Yes = p[2] * f_Yes) |>\n    pivot_longer(c(No, Yes), names_to = \"default\", values_to = \"density\")\n}\n\n# Fitted densities: contours where (x - mu_k)' Sigma^{-1} (x - mu_k) is 1 and\n# 4. Prior-weighted\n# densities: the same three heights, as fractions of the peak of f_k, in both\n# prior tabs.\ndensity_levels_2  <- f_peak_2 * exp(-c(1, 2)^2 / 2)\nweighted_levels_2 <- f_peak_2 * c(0.01, 0.02, 0.03)\n\nbeta0_2 <- function(p) {\n  log(p[2] / p[1]) -\n    0.5 * (sum(mu_Yes * (Sigma2_inv %*% mu_Yes)) -\n           sum(mu_No * (Sigma2_inv %*% mu_No)))\n}\n# beta0 + beta1 balance + beta2 income = 0 => income = intercept + slope balance\nline_2 <- function(p) {\n  c(intercept = unname(-beta0_2(p) / beta_2[2]),\n    slope = unname(-beta_2[1] / beta_2[2]))\n}\n\n# Where the same-height contours of the two classes cross: where the boundary\n# line, on which pi_1 f_1 = pi_2 f_2, meets the class-1 contour at that height.\n# Along the line x = p0 + s u, log(pi_1 f_1(x)) is quadratic in s. Only\n# crossings inside the plotted window are kept.\ncrossings_2 <- function(p, levels) {\n  p0 <- -beta0_2(p) * beta_2 / sum(beta_2^2)\n  u  <- c(beta_2[2], -beta_2[1])\n  d0 <- p0 - mu_No\n  a  <- 0.5 * sum(u * (Sigma2_inv %*% u))\n  b  <- sum(u * (Sigma2_inv %*% d0))\n  map(levels, \\(L) {\n    c0 <- 0.5 * sum(d0 * (Sigma2_inv %*% d0)) - log(p[1] * f_peak_2 / L)\n    disc <- b^2 - 4 * a * c0\n    if (disc < 0) return(NULL)\n    s <- (-b + c(-1, 1) * sqrt(disc)) / (2 * a)\n    tibble(balance = p0[1] + s * u[1], income = p0[2] + s * u[2])\n  }) |>\n    list_rbind() |>\n    filter(between(balance, window_2$balance[1], window_2$balance[2]),\n           between(income, window_2$income[1], window_2$income[2]))\n}\n\nmeans_2 <- tibble(balance = c(mu_No[1], mu_Yes[1]),\n                  income = c(mu_No[2], mu_Yes[2]))\n\ncontour_plot_2 <- function(p, levels) {\n  ggplot(weighted_grid_2(p), aes(x = balance, y = income)) +\n    geom_point(data = Default, aes(color = default, shape = default),\n               alpha = 0.12, size = 0.6) +\n    geom_contour(aes(z = density, color = default, linetype = default),\n                 breaks = levels, linewidth = 0.8) +\n    geom_line(data = means_2, color = \"grey40\", linewidth = 0.5) +\n    geom_point(data = means_2, shape = 4, size = 4, stroke = 1.5) +\n    scale_color_manual(values = class_colors) +\n    scale_shape_manual(values = c(16, 17)) +\n    scale_x_continuous(labels = dollar_labels) +\n    scale_y_continuous(labels = dollar_labels) +\n    coord_cartesian(xlim = window_2$balance, ylim = window_2$income) +\n    guides(color = guide_legend(override.aes = list(alpha = 1))) +\n    labs(x = \"Credit card balance ($)\", y = \"Income ($)\", color = \"Default\",\n         shape = \"Default\", linetype = \"Default\")\n}\n# The boundary uses \"longdash\", distinct from both class-contour linetypes.\nboundary_line_2 <- function(p, ...) {\n  l <- line_2(p)\n  geom_abline(intercept = l[\"intercept\"], slope = l[\"slope\"], ...)\n}\ncrossing_points_2 <- function(p) {\n  geom_point(data = crossings_2(p, weighted_levels_2),\n             aes(x = balance, y = income), inherit.aes = FALSE,\n             shape = 21, size = 3, stroke = 1, fill = \"white\", color = \"black\")\n}\n\ncontour_densities_2 <- contour_plot_2(c(1, 1), density_levels_2) +\n  labs(title = expression(paste(\"Contours of \", hat(f)[k](x))))\ncontour_equal_2 <- contour_plot_2(c(0.5, 0.5), weighted_levels_2) +\n  boundary_line_2(c(0.5, 0.5), linewidth = 1, linetype = \"longdash\") +\n  crossing_points_2(c(0.5, 0.5)) +\n  labs(title = expression(paste(\"Contours of \", pi[k] * hat(f)[k](x), \"; \",\n                                pi[No] == pi[Yes], \" = 0.5\")))\ncontour_estimated_2 <- contour_plot_2(hand_2$pi, weighted_levels_2) +\n  boundary_line_2(c(0.5, 0.5), linewidth = 0.6, color = \"grey50\",\n                  linetype = \"dotted\") +\n  boundary_line_2(hand_2$pi, linewidth = 1, linetype = \"longdash\") +\n  crossing_points_2(hand_2$pi) +\n  labs(title = bquote(paste(\"Contours of \", hat(pi)[k] * hat(f)[k](x), \"; \",\n                            hat(pi)[Yes] == .(sprintf(\"%.4f\", hand_2$pi[2])))))\n\n# Read as a balance threshold at a given income, and over the whole observed\n# range of income; and the change in the log posterior odds per standard\n# deviation of each feature.\nthreshold_at <- function(b0, b1, b2, inc) -(b0 + b2 * inc) / b1\nx_star_lda_range <- threshold_at(hand_2$beta0, hand_2$beta[1],\n                                 hand_2$beta[2], range(Default$income))\nper_sd_lda <- hand_2$beta * c(sd(Default$balance), sd(Default$income))\nyes_peak_share <- hand_2$pi[2]\n```\n:::\n\n:::\n\nFor the credit card fit, each tab below draws faint customer points, the two\nestimated class means (crosses) joined by a grey segment, and contours: the\nfirst tab draws two contours of each class's fitted density $\\hat f_k$, the\nellipses on which\n$\\left(x - \\hat\\mu_k\\right)^\\top \\hat\\Sigma^{-1} \\left(x - \\hat\\mu_k\\right)$\nequals $1$ and $4$, and the second and third draw contours of the\nprior-weighted densities at the same three heights,\n$\\pi_k \\hat f_k$ with equal priors and $\\hat\\pi_k \\hat f_k$ with the\nestimated priors, together with that tab's decision boundary (long dashes).\nOpen circles mark where a non-defaulter contour crosses the defaulter\ncontour of the same height, and the dotted line in the third tab is the equal-prior boundary.\n\n::: {.panel-tabset}\n#### Fitted densities\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/additive-densities-figure-1.png){width=672}\n:::\n:::\n\n\n#### Equal priors\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/additive-equal-figure-1.png){width=672}\n:::\n:::\n\n\n#### Estimated priors\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/additive-estimated-figure-1.png){width=672}\n:::\n:::\n\n:::\n\nThe two sets of ellipses in the first tab have the same shape and tilt,\nbecause $\\hat\\Sigma$ is shared, and they tilt only slightly, as the weak\nnegative correlation implies. With equal priors the\nboundary passes through the midpoint of the grey segment, as the algebra\nrequires, and through every circled crossing. With the estimated priors the\ndefaulter surface is scaled by $\\hat\\pi_{\\text{Yes}} =\n0.0333$, so its contours shrink to small\nellipses around the defaulters' mean, and the boundary, still through the\ncircled crossings, moves parallel to the equal-prior line toward the\ndefaulters, because the prior enters only $\\beta_0$.\n\nThe estimated boundary is nearly vertical: across the whole observed range of\nincome, LDA's balance threshold shifts by only\n\\$254, against a range of balance of\n\\$2,654.\n\n### Multiple logistic regression comparison {#balance-and-income}\n\nThe log posterior odds $\\hat\\beta_0 + x^\\top\\hat\\beta$ can again be set beside\na logistic regression with the same two features.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nadditive_glm <- glm(default ~ balance + income, data = Default,\n                    family = \"binomial\")\nb_glm_2 <- coef(additive_glm)\nz_income_glm <- summary(additive_glm)$coefficients[\"income\", \"z value\"]\n\n# Income difference between the classes that their balance difference\n# predicts through the pooled within-class regression of income on balance.\nmean_diff <- hand_2$mu[\"Yes\", ] - hand_2$mu[\"No\", ]\nincome_diff_predicted <- hand_2$Sigma[1, 2] / hand_2$Sigma[1, 1] * mean_diff[1]\n\n# Income coefficients are reported per $1,000 of income.\ncoef_table_2 <- tibble(\n  term = c(\"Intercept $\\\\hat\\\\beta_0$\", \"`balance` $\\\\hat\\\\beta_1$\",\n           \"`income` $\\\\hat\\\\beta_2$, per \\\\$1,000\"),\n  lda = c(hand_2$beta0, hand_2$beta[1], 1000 * hand_2$beta[2]),\n  glm = c(b_glm_2[1], b_glm_2[2], 1000 * b_glm_2[3])\n) |>\n  mutate(across(c(lda, glm), \\(v) sprintf(\"%.6f\", v))) |>\n  knitr::kable(col.names = c(\"Coefficient\", \"LDA\", \"Logistic regression\"),\n               align = \"lcc\")\n\nincome_levels <- quantile(Default$income, c(0.25, 0.5, 0.75))\nincome_level_names <- c(\"lower quartile\", \"median\", \"upper quartile\")\nx_star_lda_2 <- threshold_at(hand_2$beta0, hand_2$beta[1], hand_2$beta[2],\n                             income_levels)\nx_star_glm_2 <- threshold_at(b_glm_2[1], b_glm_2[2], b_glm_2[3],\n                             income_levels)\n\nboundary_lines <- tibble(\n  model = c(\"LDA\", \"Logistic regression\"),\n  intercept = c(-hand_2$beta0 / hand_2$beta[2], -b_glm_2[1] / b_glm_2[3]),\n  slope = c(-hand_2$beta[1] / hand_2$beta[2], -b_glm_2[2] / b_glm_2[3])\n)\n\n# Boundary lines take the models' colors as fixed colors, because the color\n# scale already encodes default; linetype carries the legend.\nboundary_layers <- function(lines) {\n  list(\n    geom_abline(data = filter(lines, model == \"LDA\"),\n                aes(intercept = intercept, slope = slope, linetype = model),\n                color = model_colors[[\"LDA\"]], linewidth = 1),\n    geom_abline(data = filter(lines, model == \"Logistic regression\"),\n                aes(intercept = intercept, slope = slope, linetype = model),\n                color = model_colors[[\"Logistic regression\"]], linewidth = 1),\n    scale_linetype_manual(values = c(\"solid\", \"dashed\")),\n    guides(linetype = guide_legend(\n      override.aes = list(color = unname(model_colors))))\n  )\n}\n\nboundary_plot <- scatter_base +\n  boundary_layers(boundary_lines) +\n  coord_cartesian(xlim = range(Default$balance),\n                  ylim = range(Default$income)) +\n  labs(linetype = \"Boundary\",\n       title = \"Decision boundaries in the (balance, income) plane\")\n\n# Posterior probability against balance at three fixed incomes.\nincome_facet <- function(v) {\n  factor(v, levels = unname(income_levels),\n         labels = sprintf(\"Income $%s (%s)\", dollars(income_levels),\n                          income_level_names))\n}\nposterior_grid_2 <- expand_grid(balance = seq(0, 2800, length.out = 400),\n                                income = unname(income_levels))\nposterior_curves_2 <- posterior_grid_2 |>\n  mutate(LDA = predict(additive_lda, newdata = posterior_grid_2)$posterior[, \"Yes\"],\n         `Logistic regression` = predict(additive_glm,\n                                         newdata = posterior_grid_2,\n                                         type = \"response\"),\n         income_label = income_facet(income)) |>\n  pivot_longer(c(LDA, `Logistic regression`), names_to = \"model\",\n               values_to = \"p_hat\")\n\nposterior_plot_2 <- ggplot(posterior_curves_2, aes(x = balance, y = p_hat)) +\n  geom_hline(yintercept = 0.5, color = \"grey60\") +\n  geom_line(aes(color = model, linetype = model), linewidth = 0.9) +\n  facet_wrap(~ income_label, nrow = 1) +\n  scale_color_manual(values = model_colors) +\n  scale_y_continuous(breaks = c(0, 0.5, 1)) +\n  scale_x_continuous(labels = dollar_labels) +\n  labs(x = \"Credit card balance ($)\", y = \"P(default = Yes)\",\n       color = \"Model\", linetype = \"Model\",\n       title = \"Posterior probability of default at three incomes\")\n```\n:::\n\n:::\n\nThe table gives LDA's $\\hat\\beta_0$ and $\\hat\\beta$ beside the coefficients of\nthe logistic regression with the same two features. The first tab below draws\neach model's decision boundary over the scatterplot of income against\nbalance, LDA's as a solid green line and logistic regression's as a dashed\npink one. The second plots each model's posterior probability of default\nagainst balance at the lower quartile, median, and upper quartile of income,\nwith a grey line at $0.5$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Coefficient                         |    LDA    | Logistic regression |\n|:-----------------------------------|:---------:|:-------------------:|\n|Intercept $\\hat\\beta_0$             | -9.864558 |     -11.540468      |\n|`balance` $\\hat\\beta_1$             | 0.004672  |      0.005647       |\n|`income` $\\hat\\beta_2$, per \\$1,000 | 0.016320  |      0.020809       |\n\n\n:::\n:::\n\n\n::: {.panel-tabset}\n#### Decision boundary\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/additive-boundary-figure-1.png){width=672}\n:::\n:::\n\n\n#### Posterior\n\n::: {.cell}\n::: {.cell-output-display}\n![](50-lda_files/figure-html/additive-posterior-figure-1.png){width=768}\n:::\n:::\n\n:::\n\nThe intercept $\\hat\\beta_0 = -9.865$ is the log\nposterior odds of default for a customer with no balance and no income, an\nextrapolation, since the lowest recorded income is\n\\$772. The `balance` slope plays the same role as\nbefore. The `income` slope,\n$0.0163$ per \\$1,000, is positive: at a\nfixed balance, LDA assigns a slightly higher posterior probability of default\nto a customer with a higher income, although defaulters' mean income is the\nlower of the two. Multiplying by $\\hat\\Sigma^{-1}$ adjusts each feature for\nthe other. With the pooled within-class correlation of\n$-0.155$, defaulters' higher balances predict a mean\nincome \\$4,309 below non-defaulters', but it is\nonly \\$1,477 below; the positive slope reflects that\nexcess. Logistic regression's `income` coefficient,\n$0.0208$ per \\$1,000, is also positive, with\n$z = 4.17$; it too compares customers with the\nsame balance. Applying the logistic function to\n$\\hat\\beta_0 + x^\\top\\hat\\beta$ again reproduces `predict()`'s posterior\nprobabilities, to within $1 \\times 10^{-14}$.\n\nPer overall standard deviation, balance moves LDA's log posterior odds by\n2.26 and income by only\n0.22. The coefficients of the linear\ndiscriminant printed by `MASS::lda()` are proportional to the LDA column of\nthe table: dividing each printed coefficient by the corresponding entry of\n$\\hat\\beta = \\hat\\Sigma^{-1}\\left(\\hat\\mu_{\\text{Yes}} - \\hat\\mu_{\\text{No}}\\right)$\ngives 0.4775 for both.\n\nRead as a balance threshold, LDA's boundary sits at\n\\$2,037 for a customer at the lower quartile of\nincome and \\$1,959 at the upper quartile; logistic\nregression's sits at \\$1,965 and\n\\$1,882. In both models the threshold falls as income\nrises, and logistic regression's lies to the left of LDA's. At each income\nthe LDA posterior curve is flatter than the logistic regression curve and\ncrosses $0.5$ further right.\n\n## Conclusion\n\nA generative classifier models the distribution of the features within each\nclass, $f_k(x)$, and the prior probability of each class, $\\pi_k$, and\ncombines them through Bayes' theorem into the posterior probability\n$p_k(x) = \\pi_k f_k(x) / \\sum_l \\pi_l f_l(x)$. Assigning each observation to\nthe class with the largest posterior probability is the Bayes classifier,\nwhich minimizes the expected error rate; a generative classifier approximates\nit by estimating $\\pi_k$ and $f_k$ from training data.\n\nLinear discriminant analysis assumes Gaussian class-conditional densities with\nclass-specific means and a covariance matrix shared by every class. Because\nthe covariance is shared, the quadratic term in $x$ is the same for every\nclass, so it can be dropped from the discriminant functions $\\delta_k(x)$,\nleaving them linear in $x$ and a decision boundary that is a point, a line, or a\nhyperplane. With two classes the log posterior odds are linear in the\nfeatures, the same form as logistic regression, but the coefficients come\nfrom closed-form estimates from the joint likelihood of features and\nresponses rather than from the iteratively maximized conditional likelihood\nof logistic regression. The class proportions and class means maximize that\njoint likelihood, and the pooled variance or covariance matrix is its\nmaximizer rescaled to be unbiased. A smaller prior probability moves the\nboundary toward that class's mean, and past it when the prior is small\nenough.\n\nThe next lecture evaluates classifiers, using this lecture's LDA and\nlogistic regression fits: the confusion matrix, sensitivity and specificity,\nthe choice of classification threshold, and the ROC curve and AUC. The\nlecture after it relaxes LDA's shared covariance assumption with quadratic\ndiscriminant analysis and naive Bayes.\n",
    "supporting": [
      "50-lda_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}