{
  "hash": "4542db74f6221cb36ed630f8def2e3b9",
  "result": {
    "engine": "knitr",
    "markdown": "# Feature Engineering\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **explain** why a model built from polynomials and interactions is still a\n*linear* model,\n- **construct** these features and **write** the corresponding `lm()` formula,\n- **interpret** a coefficient in each case, and explain why \"a one-unit increase,\nholding all else constant\" can stop making sense, and\n- **use** an F-test to decide how much curvature, or whether an interaction, the\ndata actually support.\n:::\n\n## Linear in the parameters\n\nMultiple linear regression looks restrictive: a straight line in each feature.\nIt is not. Consider\n\n$$Y_i = \\beta_0 + \\beta_1 h_1(X_i) + \\cdots + \\beta_p h_p(X_i) + \\epsilon_i$$\n\nwhere $h_1, \\ldots, h_p$ are known, fixed functions of the features $X_i$,\ncalled *basis functions*.\n\nThis model is linear in $\\beta$, which is all least squares ever required.\nEvery result from last lecture therefore carries over **unchanged**:\n$\\hat\\beta = (X^\\top X)^{-1}X^\\top y$, the t-tests, the F-tests, the intervals.\nOnly the columns of the design matrix change.\n\nChoosing the $h_j$ is **feature engineering**, and it is where most of the\nmodeling judgment in a regression analysis lives.\n\n\n## Polynomials\n\nUse the powers of a single feature as the basis:\n\n$$Y_i = \\beta_0 + \\beta_1 X_i + \\beta_2 X_i^2 + \\cdots + \\beta_d X_i^d + \\epsilon_i.$$\n\nThe fit is now a curve, and no single coefficient is \"the effect of $X$.\" That\neffect is the derivative\n\n$$\\frac{\\partial}{\\partial x} E[Y|X = x] = \\beta_1 + 2\\beta_2 x + \\cdots + d\\beta_d x^{d-1},$$\n\nwhich **depends on where you are**. Reporting $\\hat\\beta_1$ by itself is\nmeaningless.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(y ~ poly(x, 3))               # orthogonal polynomial basis\nlm(y ~ x + I(x^2) + I(x^3))      # raw powers\nlm(y ~ poly(x, 3, raw = TRUE))   # also raw powers\n```\n:::\n\n\nTwo cautions:\n\n- **Hierarchy**: if $X^2$ is in the model, keep $X$. \n- **Extrapolation**: high-degree polynomials behave badly outside the range of the data.\n\n::: {.callout-note collapse=\"true\"}\n### Why `poly()` instead of raw powers?\nOver a range like $x \\in [0,10]$, the columns $x$, $x^2$, and $x^3$ are\nenormously correlated — they all increase together. That is collinearity, and it\ninflates standard errors and destabilizes $\\hat\\beta$ numerically.\n\n`poly()` builds an *orthogonal* basis spanning the same space, so $\\hat{y}$,\nthe RSS, and $R^2$ are **identical**. What changes is that the coefficients are\nnow uncorrelated, so their t-tests can be read one at a time — a convenient way\nto ask \"is the cubic term needed?\"\n:::\n\n\n\n\n### Example: Galileo's falling bodies\n\nGalileo released a ball from a ramp at seven different heights and measured how\nfar it travelled horizontally. Physics says that relationship should be curved,\nso this is a natural place to ask *how much* curvature the data support.\n\nBefore fitting anything, look at the relationship itself:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the plots below\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(Distance ~ Height,          data = Sleuth3::case1001)\nm2 <- lm(Distance ~ poly(Height, 2), data = Sleuth3::case1001)\nm3 <- lm(Distance ~ poly(Height, 3), data = Sleuth3::case1001)\n\nmodel_levels    <- c(\"linear\", \"quadratic\", \"cubic\")\nmodel_colors    <- c(linear = \"#E69F00\", quadratic = \"#56B4E9\", cubic = \"#009E73\")\nmodel_linetypes <- c(linear = \"solid\",   quadratic = \"dashed\",  cubic = \"dotted\")\n\ngalileo_grid <- tibble(Height = seq(100, 1000, length.out = 200))\n\ngalileo_pred <- bind_rows(\n  galileo_grid |> mutate(Distance = predict(m1, galileo_grid), Model = \"linear\"),\n  galileo_grid |> mutate(Distance = predict(m2, galileo_grid), Model = \"quadratic\"),\n  galileo_grid |> mutate(Distance = predict(m3, galileo_grid), Model = \"cubic\")\n)\n\n# A shared base layer, so the four views below differ only in which lines\n# (and legend rows) are layered on top of it. The color/linetype scales are\n# attached separately below, only on the plots that actually map them --\n# attaching an unused manual scale to the data-only plot triggers a spurious\n# \"no shared levels\" warning from ggplot2.\ngalileo_base <- ggplot(Sleuth3::case1001, aes(x = Height, y = Distance)) +\n  geom_point() +\n  coord_cartesian(xlim = range(galileo_grid$Height),\n                   ylim = range(Sleuth3::case1001$Distance, galileo_pred$Distance)) +\n  labs(title = \"Sleuth3::case1001\", x = \"Release height\", y = \"Horizontal distance\") +\n  # Legend drawn inside the panel, bottom right, so the panel itself is the\n  # same size on every tab -- an outside legend would grow the plot's total\n  # width as rows are added, shifting the panel between tabs.\n  theme(legend.position = \"inside\",\n        legend.position.inside = c(0.98, 0.02),\n        legend.justification = c(1, 0),\n        legend.background = element_rect(fill = alpha(\"white\", 0.8), color = \"grey70\"))\n\ngalileo_data_plot <- galileo_base\n\ngalileo_linear_plot <- galileo_base +\n  geom_line(\n    data = galileo_pred |>\n      filter(Model == \"linear\") |>\n      mutate(Model = factor(Model, levels = \"linear\")),\n    aes(color = Model, linetype = Model)\n  ) +\n  scale_color_manual(values = model_colors) +\n  scale_linetype_manual(values = model_linetypes)\n\ngalileo_quadratic_plot <- galileo_base +\n  geom_line(\n    data = galileo_pred |>\n      filter(Model %in% c(\"linear\", \"quadratic\")) |>\n      mutate(Model = factor(Model, levels = c(\"linear\", \"quadratic\"))),\n    aes(color = Model, linetype = Model)\n  ) +\n  scale_color_manual(values = model_colors) +\n  scale_linetype_manual(values = model_linetypes)\n\ngalileo_cubic_plot <- galileo_base +\n  geom_line(\n    data = galileo_pred |> mutate(Model = factor(Model, levels = model_levels)),\n    aes(color = Model, linetype = Model)\n  ) +\n  scale_color_manual(values = model_colors) +\n  scale_linetype_manual(values = model_linetypes)\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Data\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/galileo-data-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Linear\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/galileo-linear-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Quadratic\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/galileo-quadratic-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Cubic\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/galileo-cubic-plot-1.png){width=672}\n:::\n:::\n\n:::\n\nClick through the tabs: a line is added, and a row joins the legend, each\ntime. Even by eye, the cubic barely bends past the quadratic — the question is\nwhether that bend is worth the extra parameter.\n\nNow fit the three models explicitly and compare them with a nested F-test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(Distance ~ Height,          data = Sleuth3::case1001)\nm2 <- lm(Distance ~ poly(Height, 2), data = Sleuth3::case1001)\nm3 <- lm(Distance ~ poly(Height, 3), data = Sleuth3::case1001)\n\ngalileo_anova <- anova(m1, m2, m3)\ngalileo_anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: Distance ~ Height\nModel 2: Distance ~ poly(Height, 2)\nModel 3: Distance ~ poly(Height, 3)\n  Res.Df    RSS Df Sum of Sq      F    Pr(>F)    \n1      5 5671.2                                  \n2      4  744.1  1    4927.1 306.33 0.0004065 ***\n3      3   48.3  1     695.8  43.26 0.0071503 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nBecause each model is nested in the next, `anova()` reports a *sequential*\nF-test on each row, comparing that model to the one above it. With three\nmodels compared at once, every row's F-test uses the residual degrees of\nfreedom of the **largest** model, 3, in the denominator —\nnot each row's own `Res.Df`. Row 2 tests $H_0: \\beta_2 = 0$ and gives\n$F = 306.33$ on $1$ and\n$3$ degrees of freedom — the quadratic term is clearly\nneeded. Row 3 tests $H_0: \\beta_3 = 0$ and gives\n$F = 43.26$, so the cubic term improves the fit as\nwell. The residual sum of squares falls from\n$5671$ to $744$ to\n$48$.\n\nBe careful about what that second F-test has established. There are\n$n = 7$ observations, and the cubic model spends\n$4$ parameters on them, leaving\n$3$ degrees of freedom — the cubic curve nearly interpolates\nthe data. A significant\nF-test says the cubic fits the *training* data better than the quadratic. It\ndoes not say the cubic will predict a new release height better. Physics in a\nvacuum argues for a quadratic, but physics with air resistance can make a\ncubic a reasonable approximation too — statistical significance alone should\nnot settle which curve to extrapolate with. We return to this distinction next\nlecture.\n\n\n## Interactions\n\nLet the effect of one feature depend on another:\n\n$$Y_i = \\beta_0 + \\beta_1 X_{i1} + \\beta_2 X_{i2} + \\beta_3 X_{i1}X_{i2} + \\epsilon_i.$$\n\nCollect the terms involving $X_{i1}$:\n\n$$Y_i = \\underbrace{(\\beta_0 + \\beta_2 X_{i2})}_{\\text{intercept on } X_1} + \\underbrace{(\\beta_1 + \\beta_3 X_{i2})}_{\\text{slope on } X_1} X_{i1} + \\epsilon_i.$$\n\nThe slope on $X_1$ is a *function of the other feature*. This is exactly where\n\"holding all else constant\" breaks: you cannot move $X_1$ while holding\n$X_1X_2$ fixed. And $\\beta_1$ is now the slope on $X_1$ **when $X_2 = 0$**,\nwhich may be a value $X_2$ never takes — centering usually makes the main\neffects interpretable again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(y ~ x1 * x2)   # expands to x1 + x2 + x1:x2\n```\n:::\n\n\nHierarchy applies here too: keep $X_1$ and $X_2$ whenever $X_1X_2$ is present,\nwhatever their individual p-values say.\n\n::: {.callout-note collapse=\"true\"}\n### Interaction with a categorical feature\nWith $D = 1$ for group B and $0$ for group A,\n\n$$Y_i = \\beta_0 + \\beta_1 X_i + \\beta_2 D_i + \\beta_3 X_i D_i + \\epsilon_i$$\n\nfits group A with intercept $\\beta_0$ and slope $\\beta_1$, and group B with\nintercept $\\beta_0 + \\beta_2$ and slope $\\beta_1 + \\beta_3$. Without the\ninteraction, the groups are forced to share a slope (parallel lines). With it,\n$H_0: \\beta_3 = 0$ tests whether the slopes differ.\n:::\n\n### Example: meadowfoam, where the interaction is not needed\n\nTwenty-four meadowfoam plots were grown at six light intensities, with the light\nbegun either early or late. Does the timing change the *slope* on intensity, or\nonly the intercept?\n\nBefore fitting anything, look at the relationship itself:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the plots below\n\n::: {.cell}\n\n```{.r .cell-code}\nmeadowfoam <- Sleuth3::case0901 |>\n  mutate(Time = factor(Time, levels = 1:2, labels = c(\"Late\", \"Early\")))\n\nmeadowfoam_single      <- lm(Flowers ~ Intensity,        data = meadowfoam)\nmeadowfoam_additive    <- lm(Flowers ~ Intensity + Time, data = meadowfoam)\nmeadowfoam_interaction <- lm(Flowers ~ Intensity * Time, data = meadowfoam)\n\nmeadowfoam_grid <- expand_grid(\n  Intensity = seq(min(meadowfoam$Intensity), max(meadowfoam$Intensity), length.out = 100),\n  Time = levels(meadowfoam$Time)\n) |>\n  mutate(Time = factor(Time, levels = levels(meadowfoam$Time)))\n\n# A shared base layer, so the four views below differ only in which line(s)\n# are layered on top of it -- the panel itself never changes size or shape.\nmeadowfoam_base <- ggplot(meadowfoam, aes(x = Intensity, y = Flowers)) +\n  geom_point(aes(color = Time, shape = Time)) +\n  coord_cartesian(xlim = range(meadowfoam$Intensity),\n                   ylim = range(meadowfoam$Flowers)) +\n  labs(title = \"Sleuth3::case0901\") +\n  theme(legend.position = \"inside\",\n        legend.position.inside = c(0.98, 0.98),\n        legend.justification = c(1, 1),\n        legend.background = element_rect(fill = alpha(\"white\", 0.8), color = \"grey70\"))\n\nmeadowfoam_data_plot <- meadowfoam_base\n\nmeadowfoam_single_plot <- meadowfoam_base +\n  geom_line(\n    data = meadowfoam_grid |> mutate(Flowers = predict(meadowfoam_single, meadowfoam_grid)),\n    linewidth = 1\n  )\n\nmeadowfoam_additive_plot <- meadowfoam_base +\n  geom_line(\n    data = meadowfoam_grid |> mutate(Flowers = predict(meadowfoam_additive, meadowfoam_grid)),\n    aes(color = Time, linetype = Time)\n  )\n\nmeadowfoam_interaction_plot <- meadowfoam_base +\n  geom_line(\n    data = meadowfoam_grid |> mutate(Flowers = predict(meadowfoam_interaction, meadowfoam_grid)),\n    aes(color = Time, linetype = Time)\n  )\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Data\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/meadowfoam-data-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Single line\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/meadowfoam-single-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Additive\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/meadowfoam-additive-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Interaction\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/meadowfoam-interaction-plot-1.png){width=672}\n:::\n:::\n\n:::\n\nA single line, ignoring timing, is pulled between the two groups and fits\nneither well. The additive model gives each timing its own intercept but\nforces a common slope. The interaction model frees the slopes entirely — click\nthrough and notice how little that changes the fit here: the two slopes were\nalready nearly identical without it.\n\nNow fit the interaction model explicitly and test whether it earns its extra\nparameter:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeadowfoam_anova <- anova(meadowfoam_interaction)\nmeadowfoam_anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Flowers\n               Df  Sum Sq Mean Sq F value    Pr(>F)    \nIntensity       1 2579.75 2579.75 59.2597 2.101e-07 ***\nTime            1  886.95  886.95 20.3742 0.0002119 ***\nIntensity:Time  1    0.58    0.58  0.0132 0.9095675    \nResiduals      20  870.66   43.53                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe interaction gives\n$F = 0.013$ on\n$1$ and\n$20$ degrees of freedom, so\n$p = 0.91$. The two\nslopes are about as close as noisy data allow, and the test agrees: no\nevidence that the slope on intensity depends on timing. Drop the interaction\nand report the additive model, in which timing shifts the intercept by a\nconstant amount and \"the effect of intensity\" is a single number again.\n\nDropping the *interaction* is fine. Dropping a main effect would not be.\n\n### Example: alcohol metabolism, where the interaction matters\n\nThirty-two subjects had their first-pass metabolism of alcohol measured along\nwith the activity of gastric alcohol dehydrogenase, the enzyme that breaks\nalcohol down in the stomach.\n\nBefore fitting anything, look at the relationship itself:\n\n::: {.callout-note collapse=\"true\"}\n### Code for the plots below\n\n::: {.cell}\n\n```{.r .cell-code}\nnoteworthy <- Sleuth3::case1101 |> filter(Subject %in% c(17, 31, 32))\n\nmetabolism_single      <- lm(Metabol ~ Gastric,        data = Sleuth3::case1101)\nmetabolism_additive    <- lm(Metabol ~ Gastric + Sex,  data = Sleuth3::case1101)\nmetabolism_interaction <- lm(Metabol ~ Gastric * Sex,  data = Sleuth3::case1101)\n\nmetabolism_grid <- expand_grid(\n  Gastric = seq(min(Sleuth3::case1101$Gastric), max(Sleuth3::case1101$Gastric), length.out = 100),\n  Sex = levels(Sleuth3::case1101$Sex)\n) |>\n  mutate(Sex = factor(Sex, levels = levels(Sleuth3::case1101$Sex)))\n\n# A shared base layer, so the four views below differ only in which line(s)\n# are layered on top of it -- the panel itself never changes size or shape.\nmetabolism_base <- ggplot(Sleuth3::case1101, aes(x = Gastric, y = Metabol)) +\n  geom_point(aes(color = Sex, shape = Sex)) +\n  geom_text(data = noteworthy, aes(label = Subject),\n            hjust = -0.6, size = 3, show.legend = FALSE) +\n  coord_cartesian(xlim = c(min(Sleuth3::case1101$Gastric), 5.6),\n                   ylim = range(Sleuth3::case1101$Metabol)) +\n  labs(title = \"Sleuth3::case1101\",\n       x = \"Gastric alcohol dehydrogenase activity\",\n       y = \"First-pass metabolism\") +\n  theme(legend.position = \"inside\",\n        legend.position.inside = c(0.02, 0.98),\n        legend.justification = c(0, 1),\n        legend.background = element_rect(fill = alpha(\"white\", 0.8), color = \"grey70\"))\n\nmetabolism_data_plot <- metabolism_base\n\nmetabolism_single_plot <- metabolism_base +\n  geom_line(\n    data = metabolism_grid |> mutate(Metabol = predict(metabolism_single, metabolism_grid)),\n    linewidth = 1\n  )\n\nmetabolism_additive_plot <- metabolism_base +\n  geom_line(\n    data = metabolism_grid |> mutate(Metabol = predict(metabolism_additive, metabolism_grid)),\n    aes(color = Sex, linetype = Sex)\n  )\n\nmetabolism_interaction_plot <- metabolism_base +\n  geom_line(\n    data = metabolism_grid |> mutate(Metabol = predict(metabolism_interaction, metabolism_grid)),\n    aes(color = Sex, linetype = Sex)\n  )\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Data\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/metabolism-data-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Single line\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/metabolism-single-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Additive\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/metabolism-additive-plot-1.png){width=672}\n:::\n:::\n\n\n#### + Interaction\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-30-feature-engineering_files/figure-html/metabolism-interaction-plot-1.png){width=672}\n:::\n:::\n\n:::\n\nA single line, ignoring sex, cuts across both groups. The additive model gives\neach sex its own intercept but forces a common slope. The interaction model\nfrees the slopes — and here, unlike meadowfoam, that visibly matters: the\nlines are far from parallel.\n\nNow fit the interaction model explicitly and test whether it earns its extra\nparameter:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetabolism_anova <- anova(metabolism_interaction)\nmetabolism_anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Metabol\n            Df  Sum Sq Mean Sq  F value    Pr(>F)    \nGastric      1 149.965 149.965 102.8855 7.025e-11 ***\nSex          1  17.729  17.729  12.1634  0.001628 ** \nGastric:Sex  1  10.587  10.587   7.2635  0.011765 *  \nResiduals   28  40.813   1.458                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(metabolism_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    (Intercept)         Gastric         SexMale Gastric:SexMale \n     -0.1972691       0.8369478      -0.9884969       1.5069236 \n```\n\n\n:::\n:::\n\n\nHere the interaction gives\n$F = 7.26$ on\n$1$ and\n$28$ degrees of freedom, so\n$p = 0.012$, and the lines\nare visibly non-parallel. The fitted slope is\n$0.84$ for females and\n$0.84 + 1.51 = 2.34$\nfor males — nearly three times steeper.\n\nIn this model there is no such thing as \"the effect of gastric activity.\" There\nare two of them, and you have to say which sex you mean.\n\n::: {.callout-note collapse=\"true\"}\n### A preview of a problem\nThree observations are labeled by subject number in each plot above. Subjects 31 and\n32 have gastric activity well beyond any other man's, and subject 17 is the most\nextreme of the women. These are high-leverage points: they sit far from the bulk\nof the feature values, so they do a disproportionate share of the work in\nestimating the two slopes.\n\nNotice that they are not all the same kind of unusual. Subject 31 sits close to\nthe male line, while subject 32 is far above it. Next lecture we return to these\nthree by number and separate leverage — an unusual *feature* value — from\noutliers, an unusual *response*.\n:::\n\n## What we have not fixed\n\nPolynomials and interactions both stay inside the linear model: we pick the\nbasis functions $h_k$ by hand and least squares does the rest. Next lecture we\nlet the data take over more of that choice — step functions and K-nearest\nneighbors — and then take stock of what can go wrong.\n",
    "supporting": [
      "03-30-feature-engineering_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}