{
  "hash": "380e503638072ca070d829fc2917e24e",
  "result": {
    "engine": "knitr",
    "markdown": "# Multiple Logistic Regression\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **write** the multiple logistic regression model in its probability and\nlog-odds forms using the linear predictor $X_i\\beta$, and **encode** a\ntwo-level categorical feature as an indicator against a reference level,\n- **interpret** $\\beta_j$ as a change in log-odds and $e^{\\beta_j}$ as an odds\nratio *holding every other feature fixed*, and **distinguish** that from the\ninterpretation of the same feature's coefficient fit alone,\n- **fit** an additive multiple logistic regression with `glm()`, **predict**\n$\\hat p(x)$ for a specified combination of feature values, and **construct** a\nconfidence interval for that probability by transforming a log-odds interval\nto the odds scale and then to the probability scale,\n- **test** $H_0: \\beta_j = 0$ with a $z$-statistic and **interpret** a\nconfidence interval for the odds ratio $e^{\\beta_j}$ as a statement about\nfeature $j$ after accounting for the other features,\n- **conduct** a drop-in-deviance test comparing two nested logistic regression\nmodels and **explain** its parallel with the F-test comparing two nested linear\nregression models, and\n- **diagnose** a coefficient whose sign reverses between a one-feature and a\nmulti-feature model as confounding, and **explain** the mechanism from\ndescriptive summaries of the features.\n:::\n\n## Multiple features\n\nThe previous lecture modeled the probability of default from a single feature,\ncredit card balance. `ISLR2::Default` records two more variables on the same\n10,000 customers:\n\n- `student`: is the customer a student? A factor with levels\nNo and Yes.\n- `income`: the customer's income, in dollars. This one is set aside for this\nlecture; everything below uses `balance` and `student`.\n\nHaving more than one feature raises a question that a one-feature model cannot\nanswer: what does each feature tell us that the others do not? This lecture\nanswers it for an **additive** model, in which each feature contributes its own\nterm to the linear predictor.\n\n### Categorical features\n\nA categorical feature enters a logistic regression exactly as it enters a\nmultiple linear regression: through dummy variables against a reference level.\nA feature with $L$ levels contributes $L-1$ indicators, and the level left\nwithout an indicator is the reference.\n\n`student` has two levels, so it contributes one indicator. Taking\nNo as the reference level,\n\n$$D_i = \\mathrm{I}(\\texttt{student}_i = \\texttt{Yes}) = \\begin{cases} 1 & \\text{customer } i \\text{ is a student} \\\\ 0 & \\text{otherwise,}\\end{cases}$$\n\nwhere\n\n- $D_i$ is the indicator for observation $i$, and\n- $\\mathrm{I}(\\cdot)$ is $1$ when its argument is true and $0$ otherwise.\n\nR builds this column automatically from a factor, using the first level as the\nreference, and names the coefficient after the level being indicated —\n`studentYes` below.\n\n### Student status and default\n\n**Question.** Are students more likely to default than non-students?\n\n**Data.** The same 10,000 customers as in the\nprevious lecture, now using `student` as the feature and `default` as the\nresponse, with $Y_i = 1$ when customer $i$ defaults.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nDefault <- Default |>\n  mutate(default01 = as.numeric(default == \"Yes\"),\n         default_jit = default01 + runif(n(), -0.03, 0.03))\n\nstudent_rates <- Default |>\n  group_by(student) |>\n  summarize(n = n(),\n            defaults = sum(default01),\n            rate = mean(default01),\n            .groups = \"drop\")\n\nstudent_rate_table <- student_rates |>\n  mutate(n = format(n, big.mark = \",\"),\n         rate = sprintf(\"%.2f%%\", 100 * rate)) |>\n  knitr::kable(col.names = c(\"Student\", \"Customers\", \"Defaults\",\n                             \"Percent defaulting\"),\n               align = \"cccc\")\n\nrate_of <- function(s) student_rates$rate[student_rates$student == s]\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Student | Customers | Defaults | Percent defaulting |\n|:-------:|:---------:|:--------:|:------------------:|\n|   No    |   7,056   |   206    |       2.92%        |\n|   Yes   |   2,944   |   127    |       4.31%        |\n\n\n:::\n:::\n\n\nStudents default at 4.31% versus\n2.92% for non-students, so the student\ndefault rate is 1.48 times the\nnon-student rate. That is a ratio of *rates*, not of odds; the two happen to\nbe close here only because both rates are small.\n\nFitting the simple logistic regression with $D$ as the feature turns that\ncomparison into a coefficient:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudent_glm <- glm(default ~ student, data = Default, family = \"binomial\")\ncoef(student_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  studentYes \n -3.5041278   0.4048871 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nbs <- coef(student_glm)\nor_student_alone <- unname(exp(bs[\"studentYes\"]))\nci_student_alone <- exp(confint.default(student_glm)[\"studentYes\", ])\n```\n:::\n\n:::\n\nThe estimated log-odds of default are\n\n$$\\log\\left(\\frac{\\hat p(D)}{1 - \\hat p(D)}\\right) = -3.50 +0.405 \\, D.$$\n\nWith a single indicator feature, the two fitted values are the two observed\nlog-odds. The intercept $\\hat\\beta_0 = -3.50$ is the\nlog-odds of default among non-students, and $\\hat\\beta_0 + \\hat\\beta_1$ is the\nlog-odds among students. The coefficient\n$\\hat\\beta_1 = 0.405$ is the difference between them, so\n$e^{\\hat\\beta_1} = 1.50$ is the odds of\ndefault for a student divided by the odds for a non-student. The confidence\ninterval for that odds ratio runs from\n1.20 to\n1.88, entirely above $1$.\n\n**Conclusion.** Taken by itself, student status is associated with a\n50% increase in the odds of default.\n\n### Balance and student together\n\nThe previous lecture found balance strongly associated with default; this\nlecture has now found student status associated with default as well. Before\nputting both in one model, start with the individual customers rather than a\nsummary of them: the same jittered scatter of default against balance from\nthe previous lecture, now split into two panels by student status.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_plot <- ggplot(Default, aes(x = balance, y = default_jit)) +\n  geom_point(alpha = 0.08, size = 0.7) +\n  facet_wrap(~ student, labeller = label_both) +\n  scale_y_continuous(breaks = c(0, 1), labels = c(\"No (0)\", \"Yes (1)\")) +\n  labs(x = \"Credit card balance ($)\", y = \"Default\",\n       title = \"ISLR2::Default\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-multiple-logistic-regression_files/figure-html/student-default-raw-figure-1.png){width=672}\n:::\n:::\n\n\nThe student panel's points sit further right on average, a first hint of a\nbalance difference between the two groups, but with\n2,944 students against\n7,056 non-students plotted\nat the same jitter and transparency, that shift is hard to read precisely by\neye. Two descriptive summaries make it precise.\n\nThe first compares the distribution of balance for students and non-students.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nbalance_means <- Default |>\n  group_by(student) |>\n  summarize(mean_balance = mean(balance), .groups = \"drop\")\n\nbalance_density_plot <- ggplot(Default,\n                               aes(x = balance,\n                                   color = student, linetype = student)) +\n  geom_density(linewidth = 0.9) +\n  geom_vline(data = balance_means,\n             aes(xintercept = mean_balance,\n                 color = student, linetype = student),\n             linewidth = 0.5, show.legend = FALSE) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  labs(x = \"Credit card balance ($)\", y = \"Density\",\n       color = \"Student\", linetype = \"Student\",\n       title = \"ISLR2::Default\")\n\nmean_balance_of <- function(s) {\n  balance_means$mean_balance[balance_means$student == s]\n}\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-multiple-logistic-regression_files/figure-html/balance-by-student-figure-1.png){width=672}\n:::\n:::\n\n\nThe two densities are shifted relative to one another, with the vertical lines\nmarking the group means: students average\n\\$988 versus\n\\$772 for non-students, a\ndifference of\n\\$216.\nStudents carry more balance.\n\n\n\nThe second summary asks what happens to the default rate within a narrow range\nof balance. Splitting balance into \\$400-wide bins and computing the\nobserved default rate separately for students and non-students within each bin\ngives a model-free comparison of two customers who carry similar balances.\nBins holding too few customers of a given student status to estimate a rate\nare dropped.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nbinned_rates <- Default |>\n  mutate(bin = cut(balance, breaks = seq(0, 2800, by = bin_width),\n                   include.lowest = TRUE)) |>\n  group_by(student, bin) |>\n  summarize(balance = mean(balance), rate = mean(default01), n = n(),\n            .groups = \"drop\") |>\n  filter(n >= min_bin_n)\n\nbinned_plot <- ggplot(binned_rates,\n                      aes(x = balance, y = rate,\n                          color = student, shape = student,\n                          linetype = student)) +\n  geom_line(linewidth = 0.9) +\n  geom_point(size = 2.5) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  labs(x = \"Mean balance within bin ($)\",\n       y = \"Observed proportion defaulting\",\n       color = \"Student\", shape = \"Student\", linetype = \"Student\",\n       title = paste0(\"ISLR2::Default, $\", bin_width, \"-wide balance bins\"))\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-multiple-logistic-regression_files/figure-html/binned-rates-figure-1.png){width=672}\n:::\n:::\n\n\nWithin every bin shown, the student curve sits at or below the non-student\ncurve. Comparing customers who carry similar balances reverses the direction of\nthe association that the aggregate rates showed. The curves stop near\n\\$1,773 because every\nbin beyond that holds fewer than 100 customers in at least one of the\ntwo groups.\n\nNeither summary used a model. Together they say that students carry higher\nbalances, that higher balances default more, and that at a fixed balance\nstudents default less; a model with both features lets us separate those\nstatements.\n\n## Multiple logistic regression model\n\nLet $X_{i1}, \\ldots, X_{ip}$ be the $p$ features recorded on observation $i$.\nThe **multiple logistic regression** model is\n\n$$p(X_i) = P(Y_i = 1|X_i) = \\frac{e^{\\beta_0 + \\beta_1 X_{i1} + \\cdots + \\beta_p X_{ip}}}{1 + e^{\\beta_0 + \\beta_1 X_{i1} + \\cdots + \\beta_p X_{ip}}},$$\n\nwhere\n\n- $p(X_i)$ is the probability the event occurs for observation $i$,\n- $X_{ij}$ is the value of feature $j$ for observation $i$, and\n- $\\beta_0, \\beta_1, \\ldots, \\beta_p$ are the regression coefficients.\n\nThe same algebra as in the previous lecture — form $1 - p(X_i)$, divide, take\nlogarithms — puts the model in its log-odds form,\n\n$$\\log\\left(\\frac{p(X)}{1 - p(X)}\\right) = \\beta_0 + \\beta_1 X_1 + \\cdots + \\beta_p X_p.$$\n\nThe right side is exactly the linear predictor of the multiple linear\nregression lecture. Using that lecture's model matrix notation together with\nthe linear predictor $\\eta$ of the previous lecture,\n\n- $X_i = (1, X_{i1}, \\ldots, X_{ip})$ is the $i$th row of the $n \\times (p+1)$\nmodel matrix $\\mathbf{X}$,\n- $\\beta = (\\beta_0, \\ldots, \\beta_p)^\\top$ is the vector of coefficients, and\n- $\\eta = \\mathbf{X}\\beta$ is the $n$-vector of linear predictors, with $i$th element\n$\\eta_i = X_i\\beta$,\n\nthe model is\n\n$$p(X_i) = \\text{logistic}(X_i\\beta) = \\frac{e^{X_i\\beta}}{1 + e^{X_i\\beta}}.$$\n\nSo multiple logistic regression is multiple linear regression's linear\npredictor passed through the logistic function. Everything the linear predictor\ncan express — several quantitative features, dummy variables for categorical\nfeatures, polynomial terms, step functions — is available here unchanged,\nbecause none of it touches the logistic function wrapped around it.\n\nThe model above is **additive**: each feature contributes its own term\n$\\beta_j X_{ij}$ to $\\eta_i$, and no term involves two features at once.\n\n### Maximum likelihood estimation\n\nThe observations are still independent Bernoulli trials,\n$Y_i \\stackrel{ind}{\\sim} \\text{Bernoulli}(p(x_i))$, so the log-likelihood\nderived in the previous lecture carries over with $\\beta_0 + \\beta_1 x_i$\nreplaced by $x_i\\beta$:\n\n$$\\ell(\\beta) = \\ell(\\beta_0, \\beta_1, \\ldots, \\beta_p) = \\sum_{i=1}^n \\left\\{ y_i \\, x_i\\beta - \\log\\left(1 + e^{x_i\\beta}\\right)\\right\\},$$\n\nwhere\n\n- $x_i = (1, x_{i1}, \\ldots, x_{ip})$ is the observed feature row for\nobservation $i$, and\n- $y_i \\in \\{0, 1\\}$ is the observed response.\n\nNothing structural changed. There are now $p+1$ parameters rather than $2$,\nstill no $\\sigma^2$, and still no closed-form maximizer, because $p(x_i)$\nremains a nonlinear function of the coefficients. The **maximum likelihood\nestimator** $\\hat\\beta$ is the maximizer of $\\ell$, and `glm()` finds it\nnumerically by the same iterative algorithm as before.\n\nDifferentiating with respect to $\\beta_j$ and setting the result to zero gives\none score equation per coefficient,\n\n$$\\sum_{i=1}^n x_{ij}\\left[y_i - p(x_i)\\right] = 0, \\qquad j = 0, 1, \\ldots, p,$$\n\nwith $x_{i0} = 1$. As in the one-feature case, these say the residuals\n$y_i - p(x_i)$ sum to zero and are orthogonal to every feature — the same\nconditions the least squares normal equations impose, though here the\nequations are nonlinear in $\\beta$.\n\n### Interpreting coefficients\n\nFix the values of all features other than $X_j$ and increase $X_j$ by one unit.\nOn the log-odds scale, every term except the $j$th is identical on both sides,\nso the difference is\n\n$$\\left[\\beta_0 + \\cdots + \\beta_j(x_j + 1) + \\cdots + \\beta_p x_p\\right] - \\left[\\beta_0 + \\cdots + \\beta_j x_j + \\cdots + \\beta_p x_p\\right] = \\beta_j.$$\n\nSo $\\beta_j$ is the change in the log-odds of the event per one-unit increase\nin $X_j$ **holding every other feature fixed**, and exponentiating,\n$e^{\\beta_j}$ is the multiplicative change in the odds of the event per\none-unit increase in $X_j$ **holding every other feature fixed**.\n\nThe qualifier is the whole difference between this lecture and the last one,\nand it is the same qualifier that attaches to a multiple linear regression\ncoefficient. The cancellation above is what licenses it: the comparison\n$\\beta_j$ describes is between two observations that differ in $X_j$ and agree\non everything else in the model.\n\nTwo consequences follow.\n\n1. **$\\beta_j$ from a multi-feature fit and from a one-feature fit answer\ndifferent questions.** Fit alone, a feature's coefficient describes the\ncomparison between observations that differ in that feature and in whatever\nelse happens to vary with it. In an additive model, it describes the\ncomparison holding the other included features fixed. The two can differ in\nmagnitude, and they can differ in sign.\n\n2. **\"Holding fixed\" covers only features in the model.** A variable not in\n$X$ is not held fixed by including other features, so a coefficient never\ndescribes a comparison that adjusts for something the model never saw.\n\nFor a dummy variable — a feature $X_j$ taking only the values $0$ and $1$ — a\n\"one-unit increase\" is the change from the reference level to the indicated\nlevel, so $e^{\\beta_j}$ is the odds of the event at that level divided by the\nodds at the reference level, again holding the other features fixed.\n\nThe intercept $\\beta_0$ is the log-odds of the event when every feature is $0$\n— for a dummy variable, when the observation is at the reference level.\n\n### Fitting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm(default ~ balance + student, data = Default, family = \"binomial\")\n```\n:::\n\n\nThe `+` makes the model additive: `balance` and `student` each contribute one\nterm to the linear predictor. Terms joined by `*` or `:` would add products of\nfeatures, which the additive model excludes.\n\nFitting it to the credit card data,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadditive_glm <- glm(default ~ balance + student, data = Default,\n                    family = \"binomial\")\ncoef(additive_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)       balance    studentYes \n-10.749495878   0.005738104  -0.714877620 \n```\n\n\n:::\n:::\n\n\n3 coefficients are estimated for\n$p = 2$ features, and the third is named\n`studentYes`: R built the indicator $D$ from the factor and took\nNo as the reference level, as promised above.\nWriting $X_1 = \\texttt{balance}$ and $X_2 = D$, the three estimates are\n$\\hat\\beta_0$, $\\hat\\beta_1$, and $\\hat\\beta_2$.\n\n### Coefficient inference\n\nInference proceeds coefficient by coefficient with the same machinery as the\nprevious lecture. Maximum likelihood estimators are approximately normal in\nlarge samples, so\n\n$$z = \\frac{\\hat\\beta_j - \\beta_j^0}{\\text{SE}(\\hat\\beta_j)}$$\n\nis approximately standard normal under $H_0: \\beta_j = \\beta_j^0$, where\n\n- $\\beta_j^0$ is the null value, almost always $0$, and\n- $\\text{SE}(\\hat\\beta_j)$ is the standard error computed by `glm()` from the\ncurvature of the log-likelihood at $\\hat\\beta$.\n\nAn approximate $(1-\\alpha)100\\%$ confidence interval is\n$\\hat\\beta_j \\pm z_{1-\\alpha/2}\\text{SE}(\\hat\\beta_j)$, and exponentiating both\nendpoints gives an interval for the odds ratio $e^{\\beta_j}$.\n\nEvery one of these statements is about $\\beta_j$ with the other features in the\nmodel held fixed, so the test of $H_0: \\beta_j = 0$ asks whether feature $j$ is\nassociated with the response *after accounting for* the other features — not\nwhether it is associated with the response at all.\n\n`glm()` reports the test for every coefficient at once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(additive_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = default ~ balance + student, family = \"binomial\", \n    data = Default)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.075e+01  3.692e-01 -29.116  < 2e-16 ***\nbalance      5.738e-03  2.318e-04  24.750  < 2e-16 ***\nstudentYes  -7.149e-01  1.475e-01  -4.846 1.26e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2920.6  on 9999  degrees of freedom\nResidual deviance: 1571.7  on 9997  degrees of freedom\nAIC: 1577.7\n\nNumber of Fisher Scoring iterations: 8\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nba <- coef(additive_glm)\nor_balance_100 <- unname(exp(100 * ba[\"balance\"]))\nor_student_adj <- unname(exp(ba[\"studentYes\"]))\nci_adj <- confint.default(additive_glm)\nci_or_student_adj <- exp(ci_adj[\"studentYes\", ])\nci_or_balance_100 <- exp(100 * ci_adj[\"balance\", ])\nz_student_adj <- summary(additive_glm)$coefficients[\"studentYes\", \"z value\"]\np_student_adj <- summary(additive_glm)$coefficients[\"studentYes\", \"Pr(>|z|)\"]\n```\n:::\n\n:::\n\nCollecting the two tests and the two odds ratios on interpretable scales:\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ninference_table <- tibble(\n  coefficient = c(\"balance (per $100)\", \"student (Yes vs. No)\"),\n  estimate    = c(100 * ba[\"balance\"], ba[\"studentYes\"]),\n  z           = summary(additive_glm)$coefficients[c(\"balance\", \"studentYes\"),\n                                                   \"z value\"],\n  odds_ratio  = c(or_balance_100, or_student_adj),\n  lower       = c(ci_or_balance_100[1], ci_or_student_adj[1]),\n  upper       = c(ci_or_balance_100[2], ci_or_student_adj[2])\n) |>\n  mutate(across(c(estimate, z, odds_ratio, lower, upper),\n                \\(x) sprintf(\"%.3f\", x))) |>\n  knitr::kable(col.names = c(\"Coefficient\", \"Estimate (log-odds)\", \"z\",\n                             \"Odds ratio\", \"95% CI lower\", \"95% CI upper\"),\n               align = \"lccccc\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Coefficient          | Estimate (log-odds) |   z    | Odds ratio | 95% CI lower | 95% CI upper |\n|:--------------------|:-------------------:|:------:|:----------:|:------------:|:------------:|\n|balance (per $100)   |        0.574        | 24.750 |   1.775    |    1.696     |    1.858     |\n|student (Yes vs. No) |       -0.715        | -4.846 |   0.489    |    0.366     |    0.653     |\n\n\n:::\n:::\n\n\nBoth $z$-statistics are far from zero. The interval for the balance odds ratio\nper \\$100 lies entirely above $1$, and the interval for the student odds ratio\nlies entirely below $1$, running from\n0.37 to\n0.65.\n\n### Drop-in-deviance test\n\nA $z$-statistic tests one coefficient at a time. Asking whether a *group* of\ncoefficients is all zero at once — every dummy variable of a five-level\ncategorical feature, say — requires comparing two models rather than reading\none row of a coefficient table.\n\nThe multiple linear regression lecture answered that question with an F-test:\nfit a **reduced** model without the group and a **full** model with it, and\ncompare their residual sums of squares. Logistic regression has no residual\nsum of squares, but it has the quantity that plays the same role.\n\nFor a binary response, the **residual deviance** of a fitted logistic\nregression is\n\n$$D = -2\\,\\ell(\\hat\\beta),$$\n\nwhere\n\n- $\\ell$ is the Bernoulli log-likelihood above and\n- $\\hat\\beta$ is the maximum likelihood estimate.\n\n`glm()` prints it as `Residual deviance` in the summary above, alongside\n`Null deviance`, which is $-2\\ell$ for the intercept-only model. Smaller\ndeviance means a larger maximized likelihood. Because a reduced model's\ncoefficients are a special case of the full model's (the dropped ones fixed\nat zero), the full model's maximized likelihood is at least as large, so\nadding features cannot increase the deviance — exactly as adding features\ncannot increase RSS in a linear model.\n\nThe **drop-in-deviance** statistic compares a reduced model, nested in a full\nmodel with $k$ more parameters, by\n\n$$G^2 = D_r - D_f,$$\n\nwhere\n\n- $D_r$ is the residual deviance of the reduced model, and\n- $D_f$ is the residual deviance of the full model.\n\nUnder $H_0$ that the reduced model is adequate — that all $k$ of the dropped\ncoefficients are zero — $G^2$ is approximately $\\chi^2$ with $k$ degrees of\nfreedom in large samples, and the $p$-value is the upper tail probability\n$P(\\chi^2_k > G^2)$.\n\nTwo differences from the F-test are worth naming. The F-statistic divides the\ndrop in RSS *per degree of freedom* by $\\hat\\sigma^2_f$, because a linear\nmodel has an error variance to estimate; a logistic regression has none, so\n$G^2$ needs no such divisor and carries $k$ in its reference distribution\ninstead. And the F-distribution is exact under normal errors, while the\n$\\chi^2$ reference distribution here is a large-sample approximation.\n\nIn R, `anova()` on two fitted models with `test = \"Chisq\"` performs the test.\nApplying it to this lecture's two models — reduced `default ~ balance`, full\n`default ~ balance + student` — tests $H_0: \\beta_2 = 0$, that student status\nadds nothing once balance is in the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbalance_glm <- glm(default ~ balance, data = Default, family = \"binomial\")\nanova(balance_glm, additive_glm, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: default ~ balance\nModel 2: default ~ balance + student\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1      9998     1596.5                          \n2      9997     1571.7  1    24.77 6.459e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe same numbers assembled from the deviances directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG2    <- deviance(balance_glm) - deviance(additive_glm)\nk     <- length(coef(additive_glm)) - length(coef(balance_glm))\np_dev <- pchisq(G2, df = k, lower.tail = FALSE)\n\ndata.frame(G2 = G2, k = k, p_value = p_dev)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        G2 k      p_value\n1 24.77009 1 6.459215e-07\n```\n\n\n:::\n:::\n\n\nAdding `student` to the balance-only model drops the deviance by\n$G^2 = 24.77$ on $k = 1$ degree of freedom, giving\n$p = 6.5 \\times 10^{-7}$. The data are strongly inconsistent with a model in\nwhich student status contributes nothing beyond balance.\n\nThe $z$-test from the coefficient table tests the same $H_0$, since the two\nmodels differ by one coefficient. It gives\n$z = -4.85$, so $z^2 = 23.48$\nagainst $G^2 = 24.77$, and $p = 1.3 \\times 10^{-6}$\nagainst $p = 6.5 \\times 10^{-7}$. The two agree on the conclusion without\nagreeing to the digit, and there is no reason they should: they are different\nstatistics, each approximately $\\chi^2_1$ under the null rather than exactly\nequal to one another.\n\nWhen the two models differ by more than one coefficient, no single $z$-test\nanswers the question and the drop-in-deviance test is the tool that does.\nComparing the intercept-only model to the additive model, for instance, tests\n$H_0: \\beta_1 = \\beta_2 = 0$ with $k = 2$, and the two deviances needed are the\n`Null deviance` and `Residual deviance` lines already printed in the summary\nabove.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\n$G^2$ is a **likelihood-ratio statistic**: because\n$D_r - D_f = -2\\left[\\ell(\\hat\\beta_r) - \\ell(\\hat\\beta_f)\\right] = -2\\log\\left(L(\\hat\\beta_r)/L(\\hat\\beta_f)\\right)$,\nthe test compares the maximized likelihoods of the two models. Wilks' theorem\nsupplies the $\\chi^2_k$ limiting distribution. The per-coefficient $z$-test is a\n**Wald** test instead, built from $\\hat\\beta_j$ and its standard error rather\nthan from the likelihood at two parameter values, which is why the two statistics\ndiffer in finite samples while sharing a null distribution in the limit.\n:::\n\n### Prediction\n\nThe fitted model returns a probability for any combination of feature values,\n\n$$\\hat p(x) = \\frac{e^{x\\hat\\beta}}{1 + e^{x\\hat\\beta}},$$\n\nwhere $x = (1, x_1, \\ldots, x_p)$ is a row of feature values. In R,\n`predict()` with `type = \"response\"` applies the logistic function; the\n`newdata` argument takes a data frame with one column per feature, and a\ncategorical feature must be supplied at one of its observed levels.\n\nEvaluating $\\hat p(x)$ for a student and a non-student at three balances gives\nsix predictions, and the odds ratio between the two customers at each balance:\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\npred_grid <- expand_grid(balance = c(1000, 1500, 2000),\n                         student = factor(c(\"No\", \"Yes\"),\n                                          levels = levels(Default$student)))\npred_grid$p_hat <- predict(additive_glm, newdata = pred_grid,\n                           type = \"response\")\n\npred_table <- pred_grid |>\n  pivot_wider(names_from = student, values_from = p_hat,\n              names_prefix = \"student_\") |>\n  mutate(odds_ratio = (student_Yes / (1 - student_Yes)) /\n                      (student_No  / (1 - student_No))) |>\n  mutate(across(c(student_No, student_Yes), \\(x) sprintf(\"%.4f\", x)),\n         odds_ratio = sprintf(\"%.3f\", odds_ratio),\n         balance = format(balance, big.mark = \",\")) |>\n  knitr::kable(col.names = c(\"Balance ($)\", \"Non-student\", \"Student\",\n                             \"Odds ratio\"),\n               align = \"cccc\")\n\np_at <- function(b, s) {\n  pred_grid$p_hat[pred_grid$balance == b & pred_grid$student == s]\n}\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Balance ($) | Non-student | Student | Odds ratio |\n|:-----------:|:-----------:|:-------:|:----------:|\n|    1,000    |   0.0066    | 0.0032  |   0.489    |\n|    1,500    |   0.1050    | 0.0543  |   0.489    |\n|    2,000    |   0.6741    | 0.5030  |   0.489    |\n\n\n:::\n:::\n\n\nAt a balance of \\$1,500 the estimated probability of default is\n10.5% for a non-student and\n5.4% for a student. At \\$2,000 the two\nestimates are 67.4% and\n50.3%.\n\nThe final column is constant down the table at 0.489,\nwhich is $e^{\\hat\\beta_2}$: the model forces the student-versus-non-student\nodds ratio to be the same at every balance. The difference in *probabilities*\nis not constant — 0.003 at\n\\$1,000 against 0.171 at\n\\$2,000 — for the same reason a logistic curve's slope varies with $x$.\n\nPredicting across the whole range of balance for each student status shows what\na constant odds ratio looks like on the probability scale, with the binned\nobserved rates from the exploratory plot overlaid as a check.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve_grid <- expand_grid(\n  balance = seq(0, max(Default$balance), length.out = 400),\n  student = factor(c(\"No\", \"Yes\"), levels = levels(Default$student)))\ncurve_link <- predict(additive_glm, newdata = curve_grid,\n                      type = \"link\", se.fit = TRUE)\ncurve_grid <- curve_grid |>\n  mutate(p_hat = plogis(curve_link$fit),\n         # lower/upper are not plotted below; reused for the confidence\n         # ribbon in the \"Balance confounds student status\" worked example\n         lower = plogis(curve_link$fit - qnorm(0.975) * curve_link$se.fit),\n         upper = plogis(curve_link$fit + qnorm(0.975) * curve_link$se.fit))\n\ncurve_gap <- curve_grid |>\n  select(balance, student, p_hat) |>\n  pivot_wider(names_from = student, values_from = p_hat) |>\n  mutate(gap = No - Yes)\n\nmax_gap          <- max(curve_gap$gap)\nmax_gap_balance  <- curve_gap$balance[which.max(curve_gap$gap)]\n\ncurve_plot <- ggplot(curve_grid,\n                     aes(x = balance, y = p_hat,\n                         color = student, linetype = student)) +\n  geom_line(linewidth = 0.9) +\n  geom_point(data = binned_rates,\n             aes(y = rate, shape = student), size = 2.5,\n             inherit.aes = TRUE) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  scale_y_continuous(breaks = c(0, 0.5, 1)) +\n  labs(x = \"Credit card balance ($)\", y = \"P(default = Yes)\",\n       color = \"Student\", linetype = \"Student\", shape = \"Student\",\n       title = \"Fitted additive model with binned observed rates\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-multiple-logistic-regression_files/figure-html/additive-curves-figure-1.png){width=672}\n:::\n:::\n\n\nThe two curves have the same shape, with the student curve shifted to the\nright, and both sets of binned points track their own curve. On the log-odds\nscale the curves are parallel lines separated by $\\hat\\beta_2$ at every\nbalance; on the probability scale they never cross, and the gap between them\ncloses at both ends. The gap is widest near a balance of\n\\$1,936, where it reaches\n0.177 in estimated probability — not at the midpoint of\nthe balance range, but where both curves are passing through the steep part of\ntheir climb.\n\nA confidence interval for $p(x)$ goes through the same three scales as\nthe one-feature case, with $x$ now a full row of feature values.\n`predict()` with `type = \"link\"` and `se.fit = TRUE` returns $\\hat\\eta(x) =\nx\\hat\\beta$ and $\\text{SE}(\\hat\\eta(x))$, giving a Wald interval for the\nlog-odds at $x$; exponentiating both endpoints carries it to an interval for\nthe **odds** at $x$; and applying $p = \\text{odds}/(1+\\text{odds})$ to both\nendpoints of that carries it to an interval for $p(x)$ itself.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx0 <- tibble(balance = 1500,\n            student = factor(\"No\", levels = levels(Default$student)))\n```\n:::\n\n\nFor a non-student at a balance of \\$1,500:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlink_x0    <- predict(additive_glm, newdata = x0, type = \"link\", se.fit = TRUE)\neta_hat_x0 <- link_x0$fit\neta_ci_x0  <- eta_hat_x0 + c(-1, 1) * qnorm(0.975) * link_x0$se.fit\nodds_ci_x0 <- exp(eta_ci_x0)\np_ci_x0    <- odds_ci_x0 / (1 + odds_ci_x0)\n\nci_walkthrough <- tibble(\n  Scale    = c(\"Log-odds\", \"Odds\", \"P(default)\"),\n  Estimate = c(eta_hat_x0, exp(eta_hat_x0), plogis(eta_hat_x0)),\n  Lower    = c(eta_ci_x0[1], odds_ci_x0[1], p_ci_x0[1]),\n  Upper    = c(eta_ci_x0[2], odds_ci_x0[2], p_ci_x0[2])\n) |>\n  mutate(across(c(Estimate, Lower, Upper), \\(x) sprintf(\"%.4f\", x))) |>\n  knitr::kable(col.names = c(\"Scale\", \"Estimate\", \"2.5%\", \"97.5%\"),\n               align = \"lccc\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Scale      | Estimate |  2.5%   |  97.5%  |\n|:----------|:--------:|:-------:|:-------:|\n|Log-odds   | -2.1423  | -2.3109 | -1.9738 |\n|Odds       |  0.1174  | 0.0992  | 0.1389  |\n|P(default) |  0.1050  | 0.0902  | 0.1220  |\n\n\n:::\n:::\n\n\nNothing about the three-scale route changed by adding a second feature: $x$\nnow has three entries instead of two, but $\\hat\\eta(x)$, its standard error,\nand the two increasing transforms that follow are exactly what the one-feature\nlecture used.\n\n## Balance confounds student status\n\n**Question.** Does being a student change a customer's risk of default, or\ndoes that comparison change once their balances are put on equal footing?\n\n**Data.** The same 10,000 customers as\nthroughout this lecture, `default` as the response, with `balance` and\n`student` both as features.\n\nThe binned default rates from the exploratory analysis are worth having in\nview again:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-multiple-logistic-regression_files/figure-html/student-recap-plot-1.png){width=672}\n:::\n:::\n\n\nWithin every bin the student curve sat at or below the non-student curve,\nwhile a student's *balance* averaged higher than a non-student's — the two\ndescriptive facts a model with both features has to reconcile.\n\n### Fitting both models\n\nBoth fits are already in hand: `student_glm`, with `student` alone, and\n`additive_glm`, with `balance` and `student` together.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nfits_comparison <- tibble(\n  term = names(ba),\n  \"Student alone\" = c(bs[\"(Intercept)\"], NA, bs[\"studentYes\"]),\n  \"Balance + student\" = ba\n) |>\n  mutate(across(c(\"Student alone\", \"Balance + student\"),\n                \\(x) ifelse(is.na(x), \"\", sprintf(\"%.4f\", x)))) |>\n  knitr::kable(col.names = c(\"Coefficient\", \"Student alone\",\n                             \"Balance + student\"),\n               align = \"lcc\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Coefficient | Student alone | Balance + student |\n|:-----------|:-------------:|:-----------------:|\n|(Intercept) |    -3.5041    |     -10.7495      |\n|balance     |               |      0.0057       |\n|studentYes  |    0.4049     |      -0.7149      |\n\n\n:::\n:::\n\n\nThe two intercepts are not comparable: each is the log-odds for a non-student\nat whatever balance is $0$ in *that* model, and the student-alone model never\nholds balance fixed at all.\n\n### Fitted probabilities\n\nEach model's fitted probabilities, against the same binned observed rates\nused above:\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nstudent_newdata <- tibble(student = factor(c(\"No\", \"Yes\"),\n                                           levels = levels(Default$student)))\nstudent_link    <- predict(student_glm, newdata = student_newdata,\n                           type = \"link\", se.fit = TRUE)\nstudent_ci <- student_newdata |>\n  mutate(eta   = student_link$fit,\n         se    = student_link$se.fit,\n         p_hat = plogis(eta),\n         lower = plogis(eta - qnorm(0.975) * se),\n         upper = plogis(eta + qnorm(0.975) * se))\n\nstudent_band <- curve_grid |>\n  select(balance, student) |>\n  left_join(student_ci |> select(student, p_hat, lower, upper), by = \"student\")\n\ndefault_prob_base <- ggplot(mapping = aes(x = balance, color = student,\n                                          linetype = student)) +\n  geom_point(data = binned_rates, aes(y = rate, shape = student, size = n)) +\n  coord_cartesian(xlim = c(0, max(Default$balance)), ylim = c(0, 1)) +\n  scale_color_manual(values = c(\"#0072B2\", \"#D55E00\")) +\n  scale_size_area(max_size = 5) +\n  labs(x = \"Credit card balance ($)\", y = \"P(default = Yes)\",\n       color = \"Student\", linetype = \"Student\", shape = \"Student\",\n       size = \"Customers\\nin bin\", title = \"ISLR2::Default\")\n\ndefault_prob_data <- default_prob_base\n\ndefault_prob_student_alone <- default_prob_base +\n  geom_ribbon(data = student_band, aes(ymin = lower, ymax = upper, fill = student),\n             color = NA, alpha = 0.2) +\n  geom_line(data = student_band, aes(y = p_hat), linewidth = 0.9) +\n  scale_fill_manual(values = c(\"#0072B2\", \"#D55E00\"), guide = \"none\")\n\ndefault_prob_balance_fixed <- default_prob_base +\n  geom_ribbon(data = curve_grid, aes(ymin = lower, ymax = upper, fill = student),\n             color = NA, alpha = 0.2) +\n  geom_line(data = curve_grid, aes(y = p_hat), linewidth = 0.9) +\n  scale_fill_manual(values = c(\"#0072B2\", \"#D55E00\"), guide = \"none\")\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Data\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-multiple-logistic-regression_files/figure-html/default-prob-data-plot-1.png){width=672}\n:::\n:::\n\n\n#### Student alone\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-multiple-logistic-regression_files/figure-html/default-prob-student-alone-plot-1.png){width=672}\n:::\n:::\n\n\n#### Balance held fixed\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-multiple-logistic-regression_files/figure-html/default-prob-balance-fixed-plot-1.png){width=672}\n:::\n:::\n\n:::\n\nFit alone, `student` cannot respond to balance at all — its tab shows two flat\nlines, and the \"Yes\" line sits *above* the \"No\" line, matching the higher\naggregate default rate students showed at the start of this lecture. Once\n`balance` is in the model, its tab shows two curves that both climb with\nbalance, and now the \"Yes\" curve sits *below* the \"No\" curve at every balance\non the page. The direction of the student effect flips depending on whether\nbalance is held fixed.\n\n### Coefficient reversal\n\nPutting the pieces together algebraically, the fitted log-odds are\n\n$$\\log\\left(\\frac{\\hat p(X)}{1 - \\hat p(X)}\\right) = -10.75 +0.005738 \\times \\texttt{balance} -0.715 \\times D.$$\n\nThe intercept $\\hat\\beta_0 = -10.75$ is the estimated\nlog-odds of default for a non-student carrying no balance — both features at\nzero — which corresponds to an estimated probability of\n0.000021.\n\nThe other two coefficients are easier to read as odds ratios, with `balance`\nrescaled to \\$100 increments as in the previous lecture:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(c(\"balance, per $100\" = or_balance_100,\n        \"student vs. non-student\" = or_student_adj), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      balance, per $100 student vs. non-student \n                  1.775                   0.489 \n```\n\n\n:::\n:::\n\n\nHolding student status fixed, an additional \\$100 of balance multiplies the\nestimated odds of default by 1.78.\n\nHolding balance fixed, a student's estimated odds of default are\n0.49 times a non-student's — a\n51% *reduction* in the odds. Fit alone,\nstudent status multiplied the odds by\n1.50, a\n50% increase. The sign of the `student`\ncoefficient reversed, from $0.405$ to\n$-0.715$, and nothing about the data changed between the\ntwo fits — only which features were held fixed when reading the coefficient.\n\nA marginal association that reverses direction once a third variable is held\nfixed, at every level of that third variable, is an instance of **Simpson's\nparadox**.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison_table <- tibble(\n  Model = c(\"`default ~ student`\", \"`default ~ balance + student`\"),\n  Compares = c(\"a student against a non-student, balances as they happen to be\",\n               \"a student against a non-student **at the same balance**\"),\n  OR = sprintf(\"%.2f\", c(or_student_alone, or_student_adj))\n) |>\n  knitr::kable(col.names = c(\"Model\", \"What the `student` coefficient compares\",\n                              \"Estimated odds ratio\"),\n               align = \"lll\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Model                         |What the `student` coefficient compares                        |Estimated odds ratio |\n|:-----------------------------|:--------------------------------------------------------------|:--------------------|\n|`default ~ student`           |a student against a non-student, balances as they happen to be |1.50                 |\n|`default ~ balance + student` |a student against a non-student **at the same balance**        |0.49                 |\n\n\n:::\n:::\n\n\nThe two descriptive summaries from the exploratory analysis supply the\nmechanism. Students carry\n\\$216\nmore balance on average, and balance raises the odds of default sharply. A\ncomparison of students to non-students that does not hold balance fixed is\ntherefore partly a comparison of higher balances to lower balances. Once\nbalance is in the model and held fixed, that path is closed, and what remains\nis the within-balance comparison the binned plot already showed: at a given\nbalance, students default less.\n\nThis is **confounding**: a feature left out of the model is associated both\nwith the feature being interpreted and with the response, so the included\nfeature's coefficient reports the two associations combined rather than its\nown. In the one-feature model, `student` stood in for balance, and the\nabsorbed part was large enough and of the opposite sign to flip the total.\n\n::: {.callout-note collapse=\"true\"}\n### Choosing which coefficient to report\nNeither is wrong; they answer different questions, and the question decides.\n\nA credit card company deciding what a *new applicant's* student status implies\nabout risk, knowing nothing else about them, wants the one-feature answer:\namong the customers we see, students default more. A company setting a credit\nlimit for a customer whose balance it already knows wants the additive answer:\nat that balance, a student is the safer of the two.\n\nWhat is not defensible is reporting one number and describing it with the\nother's interpretation.\n:::\n\n## Conclusion\n\nMultiple logistic regression passes multiple linear regression's linear\npredictor $\\mathbf{X}\\beta$ through the logistic function, estimated by the same\nBernoulli maximum likelihood as the one-feature case. Each $\\beta_j$ is a\nchange in log-odds, and $e^{\\beta_j}$ an odds ratio, *holding every other\nfeature in the model fixed* — the qualifier that distinguishes a coefficient\nhere from the same feature's coefficient fit alone, and the reason the two can\ndisagree in magnitude or even in sign.\n\nTesting several coefficients at once needs more than a $z$-statistic per\ncoefficient: the drop-in-deviance test compares a reduced and a full model's\nresidual deviances the way an F-test compares two models' residual sums of\nsquares, with a $\\chi^2$ reference distribution in place of an $F$.\n\nA coefficient's sign can reverse between a model that omits a feature and one\nthat includes it whenever the omitted feature is associated with both the\nincluded feature and the response — confounding, and when the association\nruns in the opposite direction at every level of the third variable, an\ninstance of Simpson's paradox. The question being asked decides which\ncomparison — and which coefficient — is the right one to report.\n\nThe additive model forces every feature's odds ratio to be the same regardless\nof the other features' values; relaxing that constraint requires interactions\nbetween features.\n",
    "supporting": [
      "20-multiple-logistic-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}