{
  "hash": "080b3a983ee5946c0366ca8134be5fd4",
  "result": {
    "engine": "knitr",
    "markdown": "# Bootstrap\n\n\n\n::: {.callout-tip}\n### Learning objectives\nAfter this lecture you should be able to\n\n- **explain** the bootstrap principle, that drawing $n$ observations with\nreplacement from the sample imitates drawing new samples from the population,\nand **compute** a bootstrap standard error of a statistic with the bootstrap\nalgorithm,\n- **compare** a bootstrap standard error with a formula-based standard error\nwhen one exists, such as the standard error of a regression coefficient from\n`lm()`, and **explain** why a bootstrap standard error is itself an estimate\nwhose accuracy depends on the statistic and the sample size,\n- **construct** a percentile interval and a normal-approximation interval from\na bootstrap distribution, and **explain** why the two differ when the\nbootstrap distribution is skewed or not centered at the estimate,\n- **derive** the probability $1 - (1 - 1/n)^n \\approx 1 - 1/e \\approx 0.632$\nthat a given observation appears in a bootstrap sample, and **explain** why it\nmakes the bootstrap a poor estimator of test error, and\n- **identify** settings in which bootstrap standard errors and intervals are\nunreliable: small samples, heavy-tailed or skewed populations summarized by a\nmean-type statistic, extreme statistics such as the maximum, and dependent\ndata.\n:::\n\n## Cloud seeding\n\n### Data\n\n**Question.** Does seeding clouds with silver iodide increase rainfall, and by\nwhat factor?\n\n**Data.** `Sleuth3::case0301` records the volume of rainfall, in acre-feet, in\na target area on 52 days suitable for cloud seeding. In a\nrandomized experiment, the clouds were seeded on\n26 of the days and left unseeded on the\nother 26. Each day is one observation.\n\nThe table gives each treatment's number of days and the mean, geometric mean,\nmedian, standard deviation, minimum, and maximum of its rainfall, where the\ngeometric mean is the exponential of the mean of log rainfall. The figure\nplots each day's rainfall by treatment, with segments at each treatment's\nmean (solid), geometric mean (dotted), and median (dashed); the second tab\ndraws rainfall on a log scale.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nclouds <- case0301 |>\n  mutate(Treatment = factor(Treatment, levels = c(\"Unseeded\", \"Seeded\")),\n         seeded = as.integer(Treatment == \"Seeded\"),\n         # Horizontal jitter, computed once so that every figure below puts\n         # each day in the same place.\n         x_jit = as.integer(Treatment) + runif(n(), -0.15, 0.15))\nn <- nrow(clouds)\n\ncloud_summary <- clouds |>\n  group_by(Treatment) |>\n  summarize(days = n(), mean = mean(Rainfall),\n            geo_mean = exp(mean(log(Rainfall))), median = median(Rainfall),\n            sd = sd(Rainfall), min = min(Rainfall), max = max(Rainfall),\n            sd_log = sd(log(Rainfall)), .groups = \"drop\")\nsummary_of <- function(trt, col) cloud_summary[[col]][cloud_summary$Treatment == trt]\n\ncloud_table <- cloud_summary |>\n  transmute(Treatment, days,\n            across(c(mean, geo_mean, median, sd, min, max), \\(v) fmt(v, 1))) |>\n  knitr::kable(col.names = c(\"Treatment\", \"Days\", \"Mean\", \"Geometric mean\",\n                             \"Median\", \"SD\", \"Min\", \"Max\"),\n               align = \"lccccccc\")\n\ncenter_types <- c(\"Mean\", \"Geometric mean\", \"Median\")\ncenter_lines <- cloud_summary |>\n  select(Treatment, Mean = mean, `Geometric mean` = geo_mean,\n         Median = median) |>\n  pivot_longer(-Treatment, names_to = \"summary\", values_to = \"rainfall\") |>\n  mutate(x = as.integer(Treatment),\n         summary = factor(summary, levels = center_types))\n\neda_plot <- ggplot(clouds, aes(x = x_jit, y = Rainfall)) +\n  geom_point(aes(color = Treatment, shape = Treatment), size = 2) +\n  geom_segment(data = center_lines,\n               aes(x = x - 0.3, xend = x + 0.3, y = rainfall, yend = rainfall,\n                   linetype = summary)) +\n  scale_color_manual(values = treatment_colors) +\n  scale_shape_manual(values = treatment_shapes) +\n  scale_linetype_manual(values = c(\"Mean\" = \"solid\",\n                                   \"Geometric mean\" = \"dotted\",\n                                   \"Median\" = \"dashed\")) +\n  scale_x_continuous(breaks = 1:2, labels = levels(clouds$Treatment)) +\n  labs(x = NULL, y = \"Rainfall (acre-feet)\", linetype = NULL,\n       title = \"Sleuth3::case0301, rainfall by treatment\")\n\neda_plot_log <- eda_plot +\n  scale_y_log10(labels = comma_labels) +\n  labs(y = \"Rainfall (acre-feet, log scale)\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Treatment | Days | Mean  | Geometric mean | Median |  SD   | Min |   Max   |\n|:---------|:----:|:-----:|:--------------:|:------:|:-----:|:---:|:-------:|\n|Unseeded  |  26  | 164.6 |      54.1      |  44.2  | 278.4 | 1.0 | 1,202.6 |\n|Seeded    |  26  | 442.0 |     169.7      | 221.6  | 650.8 | 4.1 | 2,745.6 |\n\n\n:::\n:::\n\n\n::: {.panel-tabset}\n#### Acre-feet\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/cloud-eda-plot-1.png){width=624}\n:::\n:::\n\n\n#### Log scale\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/cloud-eda-plot-log-1.png){width=624}\n:::\n:::\n\n:::\n\nBoth groups are strongly right-skewed: a few days with very large rainfall\npull each mean far above its median, and the largest seeded day,\n2,745.6 acre-feet, is more than\n12 times\nthe seeded median. On the log scale the two groups are roughly symmetric with\nsimilar spread (standard deviations of log rainfall\n1.64 unseeded and\n1.60 seeded), and on that axis each\ngeometric mean lies close to its median. Seeded days tend to have more\nrainfall than unseeded days, though the two groups overlap heavily.\n\n### Multiplicative effect\n\nThe log-scale tab suggests modeling log rainfall as normal with a mean that\ndepends on treatment,\n\n$$\\log Y_i = \\beta_0 + \\beta_1 D_i + \\epsilon_i, \\qquad \\epsilon_i \\stackrel{ind}{\\sim} N\\left(0, \\sigma^2\\right),$$\n\nwhere\n\n- $Y_i$ is the rainfall on day $i$, in acre-feet,\n- $D_i = \\mathrm{I}(\\text{day } i \\text{ seeded})$ is the indicator of\nseeding,\n- $\\beta_0$ is the mean log rainfall on unseeded days,\n- $\\beta_1$ is the difference in mean log rainfall, seeded minus unseeded,\nand\n- $\\sigma^2$ is the variance of log rainfall about its treatment mean.\n\nAdding $\\beta_1$ to log rainfall multiplies rainfall by $e^{\\beta_1}$, so the\neffect of seeding is the factor\n\n$$\\theta = e^{\\beta_1}, \\qquad \\hat\\theta = e^{\\hat\\beta_1} = \\frac{\\tilde y_S}{\\tilde y_U},$$\n\nwhere\n\n- $\\theta$ is the factor by which seeding multiplies median rainfall, since\nunder the model the median of $Y_i$ is $e^{\\beta_0 + \\beta_1 D_i}$,\n- $\\hat\\beta_1 = \\overline{\\log y}_S - \\overline{\\log y}_U$ is the least\nsquares estimate of $\\beta_1$, the difference between the sample means of log\nrainfall on seeded and unseeded days, and\n- $\\tilde y_S = \\exp\\left(\\overline{\\log y}_S\\right)$ and\n$\\tilde y_U = \\exp\\left(\\overline{\\log y}_U\\right)$ are the sample geometric\nmeans of rainfall on seeded and unseeded days, so that $\\hat\\theta$ is their\nratio.\n\nThroughout this chapter $\\theta$ is the quantity whose standard error is\nwanted and $\\hat\\theta$ its estimate; for the cloud data,\n$\\theta = e^{\\beta_1}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncloud_lm <- lm(log(Rainfall) ~ seeded, data = clouds)\nsummary(cloud_lm)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error   t value     Pr(>|t|)\n(Intercept) 3.990406  0.3178687 12.553628 4.481375e-17\nseeded      1.143781  0.4495342  2.544369 1.408266e-02\n```\n\n\n:::\n\n```{.r .cell-code}\ntheta_hat <- exp(coef(cloud_lm)[[\"seeded\"]])\ntheta_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.138614\n```\n\n\n:::\n:::\n\n\n\n\nThe estimated mean log rainfall on unseeded days is\n$\\hat\\beta_0 = 3.99$, a geometric mean of\n$e^{\\hat\\beta_0} = 54.1$ acre-feet. Seeded\ndays averaged $\\hat\\beta_1 = 1.14$ more log rainfall,\nwith standard error 0.45, so seeding multiplied the\ngeometric mean rainfall by $\\hat\\theta = 3.14$. `lm()`\nreports a standard error for $\\hat\\beta_1$ but none for $\\hat\\theta$, the\nnumber that answers the question.\n\n## Standard error\n\n### Sampling distribution\n\nRepeating the experiment on 52 new days would give different rainfall and\na different $\\hat\\theta$. Before the data are collected, $\\hat\\theta$ is a\nrandom variable, and its distribution over repeated samples from the\npopulation is its **sampling distribution**. The **standard error** of\n$\\hat\\theta$ is the standard deviation of that distribution,\n\n$$\\text{SE}(\\hat\\theta) = \\sqrt{Var\\left[\\hat\\theta\\right]}.$$\n\nSimulating the sampling distribution would mean running the experiment again\nand again, which requires access to the population.\n\n### Formulas\n\nFor some statistics, probability theory gives the standard error as a\nfunction of population quantities that the sample can estimate. The sample\nmean of $n$ independent observations with standard deviation $\\sigma$ has\n$\\text{SE}(\\bar y) = \\sigma/\\sqrt n$, estimated by $s/\\sqrt n$, and `lm()`\nreports the standard error of each regression coefficient. The estimate\n$\\hat\\theta = e^{\\hat\\beta_1}$ is a nonlinear function of a coefficient, and\nno column of the `lm()` output gives its standard error. A median, a\nquantile, and the AUC of a fitted classifier have no simple standard-error\nformula either, and a statistic computed by an algorithm rather than a\nformula often has none at all.\n\n## Bootstrap\n\n### Resampling\n\nThe first tab below repeats the 52 days on the log scale. Each later tab\ndraws 52 days *with replacement* from those 52, so that a day can be\ndrawn more than once or not at all. Filled points are days that were drawn,\nlarger the more times they were drawn, open grey points are days that were\nnot drawn, and the solid segments mark each treatment's geometric mean\nrainfall in that sample. Each title gives the sample's ratio of geometric\nmeans.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# Draw three illustrative bootstrap samples and record how many times each\n# day was drawn.\nillustrative_counts <- map(1:3, \\(b) tabulate(sample(n, replace = TRUE),\n                                              nbins = n))\n# One size scale for every tab, so a point's size means the same thing in each.\nmax_count <- max(unlist(illustrative_counts))\n\nresample_plot <- function(counts, title) {\n  d <- clouds |> mutate(count = counts)\n  drawn   <- filter(d, count > 0)\n  undrawn <- filter(d, count == 0)\n  group_geo_means <- drawn |>\n    group_by(Treatment) |>\n    summarize(rainfall = exp(weighted.mean(log(Rainfall), count)),\n              .groups = \"drop\") |>\n    mutate(x = as.integer(Treatment))\n  ratio <- group_geo_means$rainfall[2] / group_geo_means$rainfall[1]\n\n  ggplot(drawn, aes(x = x_jit, y = Rainfall)) +\n    geom_point(data = undrawn, color = \"grey60\",\n               shape = ifelse(undrawn$Treatment == \"Seeded\", 2, 1), size = 2) +\n    geom_point(aes(color = Treatment, shape = Treatment, size = count)) +\n    geom_segment(data = group_geo_means,\n                 aes(x = x - 0.3, xend = x + 0.3, y = rainfall,\n                     yend = rainfall)) +\n    scale_color_manual(values = treatment_colors) +\n    scale_shape_manual(values = treatment_shapes) +\n    scale_size_area(max_size = 5, breaks = 1:max_count,\n                    limits = c(0, max_count)) +\n    scale_x_continuous(breaks = 1:2, labels = levels(clouds$Treatment),\n                       limits = c(0.6, 2.4)) +\n    scale_y_log10(labels = comma_labels) +\n    labs(x = NULL, y = \"Rainfall (acre-feet, log scale)\",\n         size = \"Times drawn\",\n         title = sprintf(\"%s: ratio of geometric means = %.2f\", title, ratio))\n}\n\noriginal_plot <- resample_plot(rep(1, n), \"Original sample\")\nresample_plots <- imap(illustrative_counts,\n                       \\(cnt, b) resample_plot(cnt, paste(\"Bootstrap sample\", b)))\nn_distinct_illustrative <- map_int(illustrative_counts, \\(cnt) sum(cnt > 0))\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Original sample\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/resample-original-1.png){width=624}\n:::\n:::\n\n\n#### Bootstrap sample 1\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/resample-1-1.png){width=624}\n:::\n:::\n\n\n#### Bootstrap sample 2\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/resample-2-1.png){width=624}\n:::\n:::\n\n\n#### Bootstrap sample 3\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/resample-3-1.png){width=624}\n:::\n:::\n\n:::\n\nThe three resamples contain\n35, 30, and\n33 of the 52 days, each with some days\nrepeated, and their ratios of geometric means differ from one another and\nfrom $\\hat\\theta = 3.14$.\n\nThis is the **bootstrap**: it treats the sample as if it were the population.\nThe population of all suitable days is unavailable, but the 52 observed\ndays are, and drawing 52 days with replacement from them imitates running\nthe experiment again. Each resample is a **bootstrap sample**, and how much\nthe statistic varies across bootstrap samples estimates how much $\\hat\\theta$\nvaries across experiments.\n\n### Algorithm\n\nWrite the data set of $n$ observations as $Z$ (here 52 days, each a\nrainfall and a treatment). The bootstrap standard error of a statistic\n$\\hat\\theta$ computed from $Z$ is found in three steps.\n\n1. For $b = 1, \\ldots, B$, draw a bootstrap sample $Z^{*b}$ of $n$\nobservations from $Z$ with replacement, each draw choosing each observation\nwith probability $1/n$.\n2. Compute the statistic on each bootstrap sample, exactly as $\\hat\\theta$\nwas computed on $Z$, giving $\\hat\\theta^{*1}, \\ldots, \\hat\\theta^{*B}$.\n3. Take their standard deviation,\n\n$$\\text{SE}_B(\\hat\\theta) = \\sqrt{\\frac{1}{B-1}\\sum_{b=1}^B \\left(\\hat\\theta^{*b} - \\bar\\theta^{*}\\right)^2}, \\qquad \\bar\\theta^{*} = \\frac{1}{B}\\sum_{b=1}^B \\hat\\theta^{*b},$$\n\nwhere\n\n- $B$ is the number of bootstrap samples, chosen by the analyst (a few\nthousand is typical),\n- $\\hat\\theta^{*b}$ is the statistic computed on bootstrap sample $b$,\n- $\\bar\\theta^{*}$ is the mean of the $B$ bootstrap statistics, and\n- $\\text{SE}_B(\\hat\\theta)$ is the **bootstrap standard error** of\n$\\hat\\theta$.\n\nThe $B$ values $\\hat\\theta^{*b}$ form the **bootstrap distribution** of\n$\\hat\\theta$. In R, step 1 is `sample(n, replace = TRUE)`, which returns the\nrow numbers of one bootstrap sample. It draws the 52 days without regard\nto treatment, so the numbers of seeded and unseeded days vary from one\nbootstrap sample to the next. Step 2 refits the regression and\nexponentiates its slope; the loop also keeps the slope $\\hat\\beta_1^{*b}$\nitself, used in the next subsection.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB <- 2000\nboot <- tibble(b = 1:B) |>\n  mutate(\n    i     = map(b, \\(b) sample(n, replace = TRUE)),                 # step 1\n    slope = map_dbl(i, \\(i) coef(lm(log(Rainfall) ~ seeded,\n                                    data = clouds[i, ]))[[\"seeded\"]]),\n    theta = exp(slope)                                              # step 2\n  )\nse_boot_theta <- sd(boot$theta)                                     # step 3\nse_boot_theta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.554263\n```\n\n\n:::\n:::\n\n\nThe histogram shows the 2,000 values of $\\hat\\theta^{*b}$, with a solid\nline at $\\hat\\theta$.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nboot_hist_plot <- ggplot(boot, aes(x = theta)) +\n  geom_histogram(bins = 50, fill = \"grey75\", color = \"grey45\") +\n  geom_vline(xintercept = theta_hat, linewidth = 0.9) +\n  labs(x = expression(\"Bootstrap ratio of geometric means, \" *\n                        hat(theta)^\"*b\"),\n       y = \"Bootstrap samples\",\n       title = \"Bootstrap distribution of the ratio of geometric means\")\nboot_theta_range <- range(boot$theta)\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/boot-hist-figure-1.png){width=624}\n:::\n:::\n\n\nThe bootstrap distribution is right-skewed, running from\n0.66 to 12.62. Its\nstandard deviation is the bootstrap standard error,\n$\\text{SE}_B(\\hat\\theta) = 1.55$.\n\n### Regression slope\n\nWhere a formula exists, the bootstrap should agree with it. The slope\n$\\hat\\beta_1$ has the standard error `lm()` reported, and the loop above\nrecorded $\\hat\\beta_1^{*b}$ on each bootstrap sample. The histogram shows\nthose 2,000 bootstrap slopes on the density scale, with the normal\ndensity centered at $\\hat\\beta_1$ with the `lm()` standard error drawn as a\ndashed curve.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nse_boot_slope <- sd(boot$slope)\nslope_grid <- tibble(slope = seq(min(boot$slope), max(boot$slope),\n                                 length.out = 400)) |>\n  mutate(density = dnorm(slope, b_lm[[\"seeded\"]], se_lm[[\"seeded\"]]))\n\nslope_plot <- ggplot(boot, aes(x = slope)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50,\n                 fill = \"grey75\", color = \"grey45\") +\n  geom_line(data = slope_grid, aes(y = density), linetype = \"dashed\",\n            linewidth = 0.9) +\n  geom_vline(xintercept = b_lm[[\"seeded\"]], linewidth = 0.9) +\n  labs(x = expression(\"Bootstrap slope, \" * hat(beta)[1]^\"*b\" *\n                        \" (difference in mean log rainfall)\"),\n       y = \"Density\",\n       title = \"Bootstrap slopes and the normal density from lm()\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/slope-plot-1.png){width=624}\n:::\n:::\n\n\nThe bootstrap standard error of the slope is\n$\\text{SE}_B(\\hat\\beta_1) = 0.437$, against\n0.450 from `lm()`, and the histogram follows the\nnormal curve. Each $\\hat\\theta^{*b}$ is $e^{\\hat\\beta_1^{*b}}$, so the\nright skew of the $\\hat\\theta^{*b}$ histogram is this bell shape passed\nthrough the exponential function.\n\n### Known population\n\nWhether the bootstrap distribution of $\\hat\\theta$ imitates its sampling\ndistribution can only be checked where the sampling distribution is known,\nso this subsection simulates experiments from a known population: the\nlog-scale regression model with $\\beta_0$, $\\beta_1$, and $\\sigma$ set to\nthe cloud data's estimates\n$\\hat\\beta_0 = 3.99$,\n$\\hat\\beta_1 = 1.14$, and\n$\\hat\\sigma = 1.62$. For this population\n$\\theta = e^{\\beta_1} = 3.14$.\n\nThe simulation runs the experiment, 26 unseeded and\n26 seeded days, many times to obtain the sampling\ndistribution of $\\hat\\theta$. It then runs one more experiment, treats it as\nthe only sample available, and bootstraps it 2,000 times, resampling all\nits days together as for the cloud data. The first tab shows the sampling\ndistribution, with a solid line at $\\theta$; the second shows the bootstrap\ndistribution from the one experiment, with a solid line at that experiment's\n$\\hat\\theta$. Both use the same horizontal axis, cut at the 99.9th percentile\nof the simulated values.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\npop <- list(beta0 = b_lm[[\"(Intercept)\"]], beta1 = b_lm[[\"seeded\"]],\n            sigma = sigma(cloud_lm))\ntheta_pop <- exp(pop$beta1)\n\n# R simulated experiments with m days per treatment, as an m-row matrix of\n# unseeded log rainfall and an m-row matrix of seeded log rainfall, one column\n# per experiment.\ndraw_experiments <- function(m, R) {\n  list(U = matrix(rnorm(m * R, pop$beta0, pop$sigma), m, R),\n       S = matrix(rnorm(m * R, pop$beta0 + pop$beta1, pop$sigma), m, R))\n}\n# Every statistic in this chapter, for each column (experiment): the slope\n# (difference in mean log rainfall, the least squares slope), theta-hat, and\n# the ratio of mean rainfall (used under Limitations).\nexperiment_stats <- function(x) {\n  slope <- colMeans(x$S) - colMeans(x$U)\n  tibble(slope = slope, theta = exp(slope),\n         ratio = colMeans(exp(x$S)) / colMeans(exp(x$U)))\n}\n# B bootstrap samples of one data set (rainfall y, seeding indicator s), all at\n# once: column b of idx holds the row numbers of bootstrap sample b, drawn from\n# all the days together as in the cloud bootstrap.\nbootstrap_stats <- function(y, s, B) {\n  N <- length(y)\n  idx <- matrix(sample.int(N, N * B, replace = TRUE), N, B)\n  Y <- matrix(y[idx], N, B)\n  S <- matrix(s[idx], N, B)\n  n_S <- colSums(S)\n  slope <- colSums(log(Y) * S) / n_S - colSums(log(Y) * (1 - S)) / (N - n_S)\n  tibble(slope = slope, theta = exp(slope),\n         ratio = (colSums(Y * S) / n_S) / (colSums(Y * (1 - S)) / (N - n_S)))\n}\n\n# Statistics for R experiments, simulated in batches of 10,000 to limit memory.\nsimulate_stats <- function(m, R, batch = 10000) {\n  map(seq_len(R / batch), \\(k) experiment_stats(draw_experiments(m, batch))) |>\n    list_rbind()\n}\n\n# The ratio of means has a heavy-tailed sampling distribution, so its standard\n# deviation needs many experiments to pin down: 10,000 can be off by over 10%.\nn_experiments <- 100000\nm_cloud <- sum(clouds$seeded == 1)   # 26 days per treatment\nsampling <- simulate_stats(m_cloud, n_experiments)\nse_true <- map_dbl(sampling, sd)\n# se_true is itself a simulation estimate. Its Monte Carlo standard error, from\n# the spread of the standard deviations of 20 equal batches of experiments, is\n# reported relative to se_true.\nse_true_mcse <- map_dbl(sampling, \\(v) {\n  sd(tapply(v, rep(1:20, each = n_experiments / 20), sd)) / sqrt(20) / sd(v)\n})\n\none_experiment <- draw_experiments(m_cloud, 1)\none_y <- exp(c(one_experiment$U, one_experiment$S))\none_s <- rep(0:1, each = m_cloud)\ntheta_hat_one <- experiment_stats(one_experiment)$theta\none_boot      <- bootstrap_stats(one_y, one_s, B)$theta\nse_boot_one   <- sd(one_boot)\n\n# A shared axis from 0 to the 99.9th percentile of the simulated values; the\n# few experiments beyond it would otherwise squeeze the histograms flat.\nx_limits <- c(0, quantile(c(sampling$theta, one_boot), 0.999))\nknown_hist <- function(values, line_at, title) {\n  ggplot(tibble(value = values), aes(x = value)) +\n    geom_histogram(aes(y = after_stat(density)), boundary = 0,\n                   binwidth = diff(x_limits) / 60,\n                   fill = \"grey75\", color = \"grey45\") +\n    geom_vline(xintercept = line_at, linewidth = 0.9) +\n    coord_cartesian(xlim = x_limits) +\n    labs(x = \"Ratio of geometric means\", y = \"Density\", title = title)\n}\nsampling_plot <- known_hist(\n  sampling$theta, theta_pop,\n  sprintf(\"Sampling distribution: %s experiments, SE = %.2f\",\n          fmt(n_experiments), se_true[[\"theta\"]]))\none_boot_plot <- known_hist(\n  one_boot, theta_hat_one,\n  sprintf(\"Bootstrap distribution: one experiment, SE_B = %.2f\", se_boot_one))\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Sampling distribution\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/sampling-plot-1.png){width=624}\n:::\n:::\n\n\n#### Bootstrap distribution\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/one-boot-plot-1.png){width=624}\n:::\n:::\n\n:::\n\nBoth distributions are right-skewed. Over 100,000\nexperiments, $\\hat\\theta$ has standard error 1.65\n(a simulation estimate, accurate to about\n$\\pm$1%, two Monte Carlo standard\nerrors). The bootstrap distribution is\ncentered at that experiment's $\\hat\\theta = 2.25$, not\nat $\\theta = 3.14$: it estimates the spread and shape of the\nsampling distribution, not the location of $\\theta$. Its standard deviation,\n$\\text{SE}_B(\\hat\\theta) = 1.17$, is\n0.71 times the true standard error,\nand that experiment's $\\hat\\theta$ is\n0.72 times $\\theta$. The next subsection\nshows that these two ratios tend to move together.\n\n### Accuracy\n\n\n\nA bootstrap standard error is itself an estimate, computed from one sample,\nand a different sample gives a different value. To see how far it typically\nlands from the truth, the simulation bootstraps 500 further\nexperiments of 26 days per treatment, 1,000 times\neach, and divides each experiment's $\\text{SE}_B$ by the true standard error.\nThe first tab shows these ratios for the slope $\\hat\\beta_1$ and for\n$\\hat\\theta$; the second plots, for each experiment, the ratio for\n$\\hat\\theta$ against how far that experiment's $\\hat\\theta$ fell from\n$\\theta$.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bootstrap n_check simulated experiments with m days per treatment. Each row\n# holds one experiment's estimates, its bootstrap SEs, and its 95% percentile\n# and normal-approximation intervals for theta.\ncheck_experiments <- function(m, n_check, B_check) {\n  map(1:n_check, \\(r) {\n    x <- draw_experiments(m, 1)\n    est <- experiment_stats(x)\n    bs <- bootstrap_stats(exp(c(x$U, x$S)), rep(0:1, each = m), B_check)\n    tibble(m = m, theta_hat = est$theta,\n           se_b_slope = sd(bs$slope), se_b_theta = sd(bs$theta),\n           se_b_ratio = sd(bs$ratio),\n           perc_lo = quantile(bs$theta, 0.025),\n           perc_hi = quantile(bs$theta, 0.975),\n           norm_lo = est$theta - qnorm(0.975) * sd(bs$theta),\n           norm_hi = est$theta + qnorm(0.975) * sd(bs$theta))\n  }) |> list_rbind()\n}\nchecks <- check_experiments(m_cloud, n_check, B_check) |>\n  mutate(rel_slope = se_b_slope / se_true[[\"slope\"]],\n         rel_theta = se_b_theta / se_true[[\"theta\"]])\n\n# Typical relative error: the median of |SE_B / SE - 1| over experiments.\ntypical_error <- c(slope = median(abs(checks$rel_slope - 1)),\n                   theta = median(abs(checks$rel_theta - 1)))\nmedian_rel    <- c(slope = median(checks$rel_slope),\n                   theta = median(checks$rel_theta))\nslope_within  <- mean(abs(checks$rel_slope - 1) <= 0.10)\n\naccuracy_labels <- c(rel_slope = \"Slope, difference in mean log rainfall\",\n                     rel_theta = \"Ratio of geometric means\")\naccuracy_long <- checks |>\n  select(rel_slope, rel_theta) |>\n  pivot_longer(everything(), names_to = \"stat\", values_to = \"relative\") |>\n  mutate(stat = factor(accuracy_labels[stat], levels = accuracy_labels))\naccuracy_plot <- ggplot(accuracy_long, aes(x = relative)) +\n  geom_histogram(bins = 40, fill = \"grey75\", color = \"grey45\") +\n  geom_vline(xintercept = 1, linewidth = 0.9) +\n  scale_x_log10() +\n  facet_wrap(~ stat, ncol = 1) +\n  labs(x = \"Bootstrap SE divided by true SE (log scale)\",\n       y = \"Simulated experiments\",\n       title = sprintf(\"%d simulated experiments, %d days per treatment\",\n                       n_check, m_cloud))\n\naccuracy_scatter <- ggplot(checks, aes(x = theta_hat / theta_pop,\n                                       y = rel_theta)) +\n  geom_hline(yintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_point(alpha = 0.5) +\n  scale_x_log10() +\n  scale_y_log10() +\n  labs(x = expression(\"Estimate divided by truth, \" * hat(theta) / theta *\n                        \" (log scale)\"),\n       y = \"Bootstrap SE divided by true SE (log scale)\",\n       title = \"Bootstrap SE of the ratio of geometric means\")\nscatter_cor <- cor(log(checks$theta_hat), log(checks$rel_theta))\n\ncoverage <- checks |>\n  summarize(perc = mean(perc_lo < theta_pop & theta_pop < perc_hi),\n            perc_above = mean(perc_hi < theta_pop),\n            perc_below = mean(perc_lo > theta_pop),\n            norm = mean(norm_lo < theta_pop & theta_pop < norm_hi),\n            norm_above = mean(norm_hi < theta_pop),\n            norm_below = mean(norm_lo > theta_pop),\n            norm_negative = mean(norm_lo < 0))\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### SE accuracy\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/accuracy-plot-1.png){width=624}\n:::\n:::\n\n\n#### SE and estimate\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/accuracy-scatter-1.png){width=624}\n:::\n:::\n\n:::\n\nFor the slope, $\\text{SE}_B$ is typically within\n6% of the true standard error (the\nmedian of $|\\text{SE}_B/\\text{SE} - 1|$ over the experiments), and within\n10% in 69% of them. For $\\hat\\theta$ the median\nratio is 0.96, so $\\text{SE}_B$ is not\nsystematically too small or too large, but its typical error is\n31%.\n\nThe second tab shows where that error comes from: experiments whose\n$\\hat\\theta$ overshoots $\\theta$ also overstate its standard error\n(correlation 0.96 on the log scales). Each bootstrap\nstatistic is\n$\\hat\\theta^{*b} = \\hat\\theta\\, e^{\\hat\\beta_1^{*b} - \\hat\\beta_1}$, so\n\n$$\\text{SE}_B(\\hat\\theta) = \\hat\\theta \\times \\text{SD}_B\\left(e^{\\hat\\beta_1^{*b} - \\hat\\beta_1}\\right),$$\n\nwhere\n\n- $\\text{SD}_B(\\cdot)$ is the standard deviation over the $B$ bootstrap\nsamples, and\n- the second factor depends only on the spread of the bootstrap slopes, which\nthe bootstrap estimates as well as it estimates\n$\\text{SE}(\\hat\\beta_1)$.\n\nThe first factor is $\\hat\\theta$ itself. The standard error of $\\hat\\theta$\nis proportional to $\\theta$, which is known only through $\\hat\\theta$, so no\nestimate of $\\text{SE}(\\hat\\theta)$, bootstrap or formula, can be much more\naccurate than $\\hat\\theta$. For the cloud data,\n$\\text{SE}_B(\\hat\\theta) = 1.55$ is best read as\n\"about 1.6, give or take\n31%.\"\n\n## Confidence intervals\n\nA standard error describes the spread of a statistic; a confidence interval\nuses the whole bootstrap distribution. The first tab shows the bootstrap\ndistributions of the slope, $\\hat\\beta_1^{*b}$, and the ratio of geometric\nmeans, $\\hat\\theta^{*b}$, each with a solid line at the original estimate.\nThe second tab adds each statistic's 95% percentile interval as dashed lines,\nand the third adds its 95% normal-approximation interval as dot-dashed lines;\nboth intervals are defined below the figure.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\nz <- qnorm(1 - alpha / 2)\nstat_labels <- c(slope = \"Slope, difference in mean log rainfall\",\n                 theta = \"Ratio of geometric means\")\nestimates <- c(slope = b_lm[[\"seeded\"]], theta = theta_hat)\nse_boot   <- c(slope = se_boot_slope, theta = se_boot_theta)\n\nintervals <- tibble(stat = names(estimates), estimate = estimates,\n                    se = se_boot) |>\n  mutate(perc_lo = map_dbl(stat, \\(s) quantile(boot[[s]], alpha / 2)),\n         perc_hi = map_dbl(stat, \\(s) quantile(boot[[s]], 1 - alpha / 2)),\n         norm_lo = estimate - z * se,\n         norm_hi = estimate + z * se,\n         # The t interval for the slope from lm(), and its exponential for\n         # theta.\n         lm_lo = if_else(stat == \"slope\", ci_lm[[1]], exp(ci_lm[[1]])),\n         lm_hi = if_else(stat == \"slope\", ci_lm[[2]], exp(ci_lm[[2]])))\ninterval_of <- function(s, col) intervals[[col]][intervals$stat == s]\n\nboot_long <- boot |>\n  select(slope, theta) |>\n  pivot_longer(everything(), names_to = \"stat\") |>\n  mutate(stat = factor(stat_labels[stat], levels = stat_labels))\nestimate_lines <- tibble(stat = factor(stat_labels[names(estimates)],\n                                       levels = stat_labels),\n                         value = estimates)\ninterval_lines_df <- intervals |>\n  pivot_longer(c(perc_lo, perc_hi, norm_lo, norm_hi),\n               names_to = c(\"method\", \"end\"), names_sep = \"_\") |>\n  mutate(method = if_else(method == \"perc\", \"Percentile\",\n                          \"Normal approximation\"),\n         method = factor(method, levels = names(interval_colors)),\n         stat = factor(stat_labels[stat], levels = stat_labels))\n\ninterval_base <- ggplot(boot_long, aes(x = value)) +\n  geom_histogram(bins = 50, fill = \"grey75\", color = \"grey45\") +\n  geom_vline(data = estimate_lines, aes(xintercept = value),\n             linewidth = 0.9) +\n  facet_wrap(~ stat, scales = \"free\") +\n  labs(x = \"Bootstrap statistic\", y = \"Bootstrap samples\")\ninterval_layer <- function(methods) {\n  list(\n    geom_vline(data = filter(interval_lines_df, method %in% methods),\n               aes(xintercept = value, color = method, linetype = method),\n               linewidth = 0.9, key_glyph = \"path\"),\n    scale_color_manual(values = interval_colors, drop = FALSE),\n    scale_linetype_manual(values = interval_lines, drop = FALSE),\n    labs(color = \"95% interval\", linetype = \"95% interval\"),\n    theme(legend.position = \"bottom\")\n  )\n}\ninterval_plot_0 <- interval_base\ninterval_plot_1 <- interval_base + interval_layer(\"Percentile\")\ninterval_plot_2 <- interval_base + interval_layer(names(interval_colors))\n\ninterval_text <- function(lo, hi) sprintf(\"(%s, %s)\", fmt(lo, 2), fmt(hi, 2))\ninterval_table <- intervals |>\n  mutate(Statistic = stat_labels[stat],\n         Estimate = fmt(estimate, 2),\n         `Bootstrap SE` = fmt(se, 2),\n         Percentile = interval_text(perc_lo, perc_hi),\n         `Normal approximation` = interval_text(norm_lo, norm_hi),\n         `From lm()` = interval_text(lm_lo, lm_hi)) |>\n  select(Statistic, Estimate, `Bootstrap SE`, Percentile,\n         `Normal approximation`, `From lm()`) |>\n  knitr::kable(align = \"lccccc\")\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### Bootstrap distributions\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/interval-plot-0-1.png){width=768}\n:::\n:::\n\n\n#### + Percentile\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/interval-plot-1-1.png){width=768}\n:::\n:::\n\n\n#### + Normal approximation\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/interval-plot-2-1.png){width=768}\n:::\n:::\n\n:::\n\n### Percentile interval\n\nIf some monotone transformation of $\\hat\\theta$ has an approximately normal\nsampling distribution, as $\\log\\hat\\theta = \\hat\\beta_1$ does here, the\nmiddle $1 - \\alpha$ of the bootstrap distribution gives a range of plausible\nvalues of $\\theta$, without the transformation having to be known. The $(1 - \\alpha)100\\%$ **percentile interval** is\n\n$$\\left(\\hat\\theta^{*}_{(\\alpha/2)},\\ \\hat\\theta^{*}_{(1-\\alpha/2)}\\right),$$\n\nwhere $\\hat\\theta^{*}_{(q)}$ is the $q$ quantile of the $B$ bootstrap\nstatistics $\\hat\\theta^{*1}, \\ldots, \\hat\\theta^{*B}$. In R it is\n`quantile(boot$theta, c(0.025, 0.975))` for a 95% interval.\n\nFor the ratio of geometric means the 95% percentile interval is\n(1.32,\n7.30).\n\n::: {.callout-note collapse=\"true\"}\n### For example,\nA percentile interval moves with a monotone transformation of the statistic.\nSince $\\hat\\theta^{*b} = e^{\\hat\\beta_1^{*b}}$, the quantiles of the\n$\\hat\\theta^{*b}$ are the exponentials of the quantiles of the\n$\\hat\\beta_1^{*b}$. The 95% percentile interval for $\\beta_1$ is\n(0.277,\n1.989), and its exponential,\n(1.32,\n7.30), is the percentile interval\nfor $\\theta$ above. A normal-approximation interval does not move this way:\nexponentiating the one for $\\beta_1$ does not give the one for $\\theta$.\n:::\n\n### Normal-approximation interval\n\nIf the sampling distribution of $\\hat\\theta$ is approximately normal, the\nusual form of interval applies with the bootstrap standard error,\n\n$$\\hat\\theta \\pm z_{1-\\alpha/2}\\,\\text{SE}_B(\\hat\\theta),$$\n\nwhere $z_{1-\\alpha/2}$ is the $(1 - \\alpha/2)$ quantile of the standard normal\ndistribution, 1.96 for a 95% interval.\n\nFor the ratio of geometric means the 95% normal-approximation interval is\n(0.09,\n6.18).\n\n### Comparison\n\nThe table collects both intervals for both statistics. Its last column is\nthe $t$ interval from `lm()` for $\\beta_1$ and, for $\\theta$, the\nexponential of that interval.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Statistic                              | Estimate | Bootstrap SE |  Percentile  | Normal approximation |  From lm()   |\n|:--------------------------------------|:--------:|:------------:|:------------:|:--------------------:|:------------:|\n|Slope, difference in mean log rainfall |   1.14   |     0.44     | (0.28, 1.99) |     (0.29, 2.00)     | (0.24, 2.05) |\n|Ratio of geometric means               |   3.14   |     1.55     | (1.32, 7.30) |     (0.09, 6.18)     | (1.27, 7.74) |\n\n\n:::\n:::\n\n\n\n\nFor the slope the three intervals nearly coincide: each endpoint differs\nfrom the $t$ interval's by at most 0.06, because the\nbootstrap distribution of $\\hat\\beta_1^{*b}$ is close to normal and centered\nat $\\hat\\beta_1$. For the ratio of geometric means the two bootstrap\nintervals differ. The normal-approximation interval is symmetric about\n$\\hat\\theta$, and its lower limit,\n0.09, lies\nbelow every bootstrap value.\nThe percentile interval follows the skew: its upper limit is\n4.17 above $\\hat\\theta$\nand its lower limit 1.82\nbelow it, like the exponentiated $t$ interval\n(1.27,\n7.74).\n\nThe two intervals agree when the bootstrap distribution is approximately\nnormal and centered at $\\hat\\theta$. Skewness separates them, and so does\nbias, a bootstrap distribution centered away from $\\hat\\theta$, which shifts\nthe percentile interval but not the normal-approximation interval.\n\nIn the 500 simulated experiments of the Accuracy subsection, the 95%\npercentile interval contained $\\theta$ in 93.6% of\nthem, missing low (entirely below $\\theta$) in\n3.6% and high in\n2.8%. The normal-approximation interval\ncontained $\\theta$ in 93.2%, missing low in\n6.8% and high in\n0.0%, and its lower limit was negative, a\nvalue no ratio of positive quantities can take, in\n51.0%. Both cover $\\theta$ at close to the\nnominal rate, but only the percentile interval stays within the possible\nvalues of $\\theta$ and splits its misses between the two sides.\n\n## Sample overlap\n\nThe bootstrap samples in the Resampling tabs each left out some of the 52\ndays. The bar chart counts, over all 2,000 bootstrap samples, the number\nof distinct days each one contains.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nboot <- boot |> mutate(distinct = map_int(i, n_distinct))\ndistinct_mean <- mean(boot$distinct)\ndistinct_plot <- ggplot(boot, aes(x = distinct)) +\n  geom_bar(fill = \"grey75\", color = \"grey45\") +\n  labs(x = sprintf(\"Distinct days in a bootstrap sample of %d\", n),\n       y = \"Bootstrap samples\",\n       title = \"Distinct observations in the cloud bootstrap samples\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/distinct-plot-1.png){width=624}\n:::\n:::\n\n\nThe bootstrap samples contain between 25 and\n40 distinct days, 33.0 on average, or\n63.5% of the 52.\n\n### Inclusion probability\n\nEach of the $n$ draws that make up a bootstrap sample picks observation $j$\nwith probability $1/n$, independently of the other draws. So\n\n$$P\\left(\\text{observation } j \\text{ not chosen on one draw}\\right) = 1 - \\frac{1}{n}, \\qquad P\\left(\\text{observation } j \\notin Z^{*b}\\right) = \\left(1 - \\frac{1}{n}\\right)^n,$$\n\nand the probability that observation $j$ appears in the bootstrap sample is\n\n$$P\\left(\\text{observation } j \\in Z^{*b}\\right) = 1 - \\left(1 - \\frac{1}{n}\\right)^n \\longrightarrow 1 - e^{-1} \\approx 0.632 \\quad \\text{as } n \\to \\infty,$$\n\nusing $\\lim_{n \\to \\infty} (1 + x/n)^n = e^x$ with $x = -1$. The number of\ndistinct observations in $Z^{*b}$ is\n$\\sum_{j=1}^n \\mathrm{I}\\left(\\text{observation } j \\in Z^{*b}\\right)$, so by\nlinearity of expectation\n\n$$E\\left[\\sum_{j=1}^n \\mathrm{I}\\left(\\text{observation } j \\in Z^{*b}\\right)\\right] = n\\left[1 - \\left(1 - \\frac{1}{n}\\right)^n\\right].$$\n\n\n\nFor the 52 cloud seeding days, $1 - (1 - 1/52)^{52} = 0.636$,\nso a bootstrap sample is expected to contain 33.1\ndistinct days, against the 33.0 averaged over the\n2,000 samples above. The figure plots the inclusion probability against\n$n$, with a dashed line at $1 - e^{-1}$ and a point at $n = 52$.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\ninclusion_plot <- tibble(n = 1:100) |>\n  mutate(p = p_incl(n)) |>\n  ggplot(aes(x = n, y = p)) +\n  geom_hline(yintercept = 1 - exp(-1), linetype = \"dashed\") +\n  geom_line() +\n  geom_point(data = tibble(n = nrow(clouds), p = p_incl(nrow(clouds))),\n             size = 3, shape = 21, fill = \"white\") +\n  labs(x = \"Sample size n\",\n       y = \"P(observation j in bootstrap sample)\",\n       title = \"Inclusion probability 1 - (1 - 1/n)^n\")\n```\n:::\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/inclusion-plot-1.png){width=624}\n:::\n:::\n\n\nThe inclusion probability is 0.75 at $n = 2$ and falls\nquickly toward $1 - e^{-1} = 0.632$; by $n = 20$ it is\n0.642.\n\n### Test error\n\nA bootstrap sample could serve as a training set: fit the model to $Z^{*b}$,\npredict the original $n$ observations, and average the error over $b$. About\n63.2% of the observations being predicted were\nalso used to fit the model, some of them several times, so this estimate\nmixes training error into test error and is too optimistic, increasingly so\nfor flexible models that fit their training data closely. Cross-validation,\nthe subject of the previous lecture, avoids the overlap: each fold's held-out\nobservations are not in the data the model is fit to.\n\n## Limitations\n\nThe bootstrap replaces the population with the sample, so it is only as good\nas that replacement.\n\n- **Small samples.** A small sample may miss the population's tails, and the\nbootstrap cannot reproduce what the sample does not contain. Even for a\nwell-behaved statistic, $\\text{SE}_B$ is an estimate with sampling error, as\nthe Accuracy subsection showed at 26 days per treatment, and that\nerror shrinks only as $n$ grows, as the first tab below shows for\n$\\hat\\theta$.\n- **Heavy-tailed or skewed populations with a mean-type statistic.** A mean\nof a heavy right tail is driven by its few largest values. The first tab\ncompares $\\text{SE}_B$ with the true standard error for $\\hat\\theta$ and for\nthe ratio of mean rainfall, $\\bar y_S/\\bar y_U$, where $\\bar y_S$ and\n$\\bar y_U$ are the sample mean rainfall on seeded and unseeded days, over\nsimulated experiments of three sizes.\n- **Extreme statistics.** The bootstrap maximum can never exceed the sample\nmaximum, and it equals the sample maximum whenever that observation is drawn,\nwith probability $1 - (1 - 1/n)^n$. The second tab shows the bootstrap\ndistribution of the maximum rainfall on a seeded day, from the 2,000\ncloud bootstrap samples.\n- **Dependent data.** Resampling individual observations assumes they are\nindependent. Temperatures on consecutive days or repeated measurements on\nthe same subject are correlated, and resampling them one at a time breaks that\ncorrelation, which usually makes $\\text{SE}_B$ too small.\n\n::: {.callout-note collapse=\"true\"}\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# The ratio of mean rainfall, and its bootstrap SE, on the cloud data.\nratio_of_means <- function(d) {\n  mean(d$Rainfall[d$seeded == 1]) / mean(d$Rainfall[d$seeded == 0])\n}\nratio_hat <- ratio_of_means(clouds)\nboot <- boot |> mutate(ratio = map_dbl(i, \\(i) ratio_of_means(clouds[i, ])))\nse_boot_ratio <- sd(boot$ratio)\n\n# True SEs and bootstrap SEs at three numbers of days per treatment. The\n# 26-day experiments are the ones already bootstrapped in the Accuracy\n# subsection; the larger sizes reuse the same functions.\nsizes <- c(m_cloud, 100, 400)\nsize_true <- bind_rows(\n  tibble(m = m_cloud, theta = se_true[[\"theta\"]], ratio = se_true[[\"ratio\"]]),\n  map(sizes[-1], \\(m) {\n    st <- simulate_stats(m, n_experiments)\n    tibble(m = m, theta = sd(st$theta), ratio = sd(st$ratio),\n           ratio_mcse = sd(tapply(st$ratio,\n                                  rep(1:20, each = n_experiments / 20),\n                                  sd)) / sqrt(20) / sd(st$ratio))\n  }) |> list_rbind())\nsize_checks <- bind_rows(checks,\n                         map(sizes[-1], \\(m) check_experiments(m, n_check,\n                                                               B_check))) |>\n  left_join(size_true, by = \"m\") |>\n  transmute(m,\n            theta = se_b_theta / theta,\n            ratio = se_b_ratio / ratio)\nsize_summary <- size_checks |>\n  pivot_longer(c(theta, ratio), names_to = \"stat\", values_to = \"relative\") |>\n  group_by(stat, m) |>\n  summarize(within = mean(abs(relative - 1) <= 0.25),\n            median = median(relative), .groups = \"drop\")\nsize_of <- function(st, mm, col) {\n  size_summary[[col]][size_summary$stat == st & size_summary$m == mm]\n}\n\nlimit_labels <- c(theta = \"Ratio of geometric means\",\n                  ratio = \"Ratio of means\")\nsize_plot <- size_checks |>\n  pivot_longer(c(theta, ratio), names_to = \"stat\", values_to = \"relative\") |>\n  mutate(stat = factor(limit_labels[stat], levels = limit_labels)) |>\n  ggplot(aes(x = factor(m), y = relative)) +\n  annotate(\"rect\", xmin = -Inf, xmax = Inf, ymin = 0.75, ymax = 1.25,\n           alpha = 0.15) +\n  geom_hline(yintercept = 1, linewidth = 0.9) +\n  geom_boxplot(outlier.size = 0.8) +\n  scale_y_log10() +\n  facet_wrap(~ stat) +\n  labs(x = \"Days per treatment\",\n       y = \"Bootstrap SE divided by true SE (log scale)\",\n       title = sprintf(\"%d simulated experiments per size; shaded band: within 25%%\",\n                       n_check))\n\nseeded_max <- max(clouds$Rainfall[clouds$seeded == 1])\nboot <- boot |>\n  mutate(max_seeded = map_dbl(i, \\(i) {\n    max(clouds$Rainfall[i][clouds$seeded[i] == 1])\n  }))\nshare_at_max <- mean(boot$max_seeded == seeded_max)\nmax_plot <- ggplot(boot, aes(x = max_seeded)) +\n  geom_histogram(bins = 60, fill = \"grey75\", color = \"grey45\") +\n  labs(x = \"Bootstrap maximum seeded-day rainfall (acre-feet)\",\n       y = \"Bootstrap samples\",\n       title = \"Bootstrap distribution of the maximum\")\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n#### SE accuracy by size\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/size-plot-1.png){width=672}\n:::\n:::\n\n\n#### Maximum\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/max-plot-1.png){width=624}\n:::\n:::\n\n:::\n\nUnder the known population, log rainfall is normal with a common $\\sigma$\nin both treatments, so the mean rainfall on a day with seeding indicator $D$\nis $e^{\\beta_0 + \\beta_1 D + \\sigma^2/2}$, and the ratio of means\n$\\mu_S/\\mu_U$ also equals $\\theta$, where $\\mu_S$ and $\\mu_U$ are the\npopulation mean rainfall on seeded and unseeded days. The two statistics\nestimate the same quantity, but at 26 days per treatment the ratio\nof means $\\bar y_S/\\bar y_U$ has true standard error\n3.66 (accurate to about\n$\\pm$4%), against\n1.65 for $\\hat\\theta$.\n\nThe table gives, for each statistic and size, the percentage of the\n500 simulated experiments whose $\\text{SE}_B$ fell within 25% of the\ntrue standard error. With 500 experiments each percentage is accurate\nto about $\\pm$4 percentage points or\nbetter (two binomial standard errors).\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Statistic                | 26 days per treatment | 100 days per treatment | 400 days per treatment |\n|:------------------------|:---------------------:|:----------------------:|:----------------------:|\n|Ratio of means           |          17%          |          30%           |          49%           |\n|Ratio of geometric means |          41%          |          73%           |          97%           |\n\n\n:::\n:::\n\n\nFor the ratio of geometric means the percentage climbs quickly with $n$, as\nits $\\text{SE}_B$ inherits the shrinking error of $\\hat\\theta$. For the ratio\nof means it is lower at every size and reaches only\n49% at 400 days per\ntreatment. The median ratio of $\\text{SE}_B$ to the truth for the ratio of\nmeans is 0.54,\n0.64, and\n0.79 at the three sizes (each\ntrue standard error is from 100,000 experiments, accurate to\nabout $\\pm$4%\nor better), so its $\\text{SE}_B$ is typically too small.\n\nA likely reason is that a sample seldom holds the population's rare, very\nwet days in their population proportion: it usually holds too few, giving an\n$\\text{SE}_B$ that is too small, and occasionally holds several, giving one\nfar too large, and the bootstrap resamples only the days the sample\ncontains. On the log scale those days are not extreme. The two bootstrap\nstandard errors therefore err for different reasons: that of the ratio of\ngeometric means is noisy because $\\text{SE}(\\hat\\theta)$ is proportional to\n$\\theta$, which is known only through $\\hat\\theta$, while that of the ratio\nof means is also biased low by the heavy right tail. On the cloud data\nthe ratio of means is 2.69 with\n$\\text{SE}_B = 1.51$, likely well below its true\nstandard error.\n\nIn the cloud bootstrap samples, 63.9% of the\nbootstrap maxima equal the sample maximum of 2,745.6\nacre-feet, against $1 - (1 - 1/52)^{52} = 63.6$%\nexpected. Most of the bootstrap distribution is a single spike at the sample\nmaximum, so it carries no information about how far the population maximum\nlies above the sample's.\n\n::: {.callout-note collapse=\"true\"}\n### Beyond this course\n- The **delta method** gives an approximate formula standard error for a\nsmooth function of estimates from a first-order Taylor expansion; for\n$\\hat\\theta = e^{\\hat\\beta_1}$ it is $\\hat\\theta\\,\\text{SE}(\\hat\\beta_1)$.\n- **Out-of-bag error** repairs the bootstrap's test-error estimate by\npredicting each observation only from bootstrap samples that left it out;\nit reappears with bagging and random forests (ISLR2 Chapter 8).\n- The **parametric bootstrap** resamples from a fitted model rather than from\nthe data, much as the known-population simulation above drew experiments from\nthe fitted log-scale regression.\n- **Bias-corrected and accelerated (BCa)** and **bootstrap-$t$** intervals\nimprove on the percentile interval's coverage in small or skewed samples.\n- The **block bootstrap** resamples blocks of consecutive observations to\nkeep the dependence in a time series, and **stratified resampling** draws\nwithin each group (here, 26 days from each treatment) to match a\ndesign with fixed group sizes.\n:::\n\n## Conclusion\n\nThe standard error of a statistic is the standard deviation of its sampling\ndistribution. Simple formulas give it for a few statistics, such as a mean\nor a regression coefficient, and `lm()` reports it for each coefficient but\nnot for a function of the coefficients, such as an exponentiated\ncoefficient. A median, a quantile, an AUC, and many statistics computed by\nan algorithm have no simple formula. The bootstrap estimates the standard\nerror by treating the sample as the population: draw $B$ bootstrap samples\nof $n$ observations with replacement, compute the statistic on each, and\ntake the standard deviation of the $B$ results. Where a formula exists, such\nas for a regression coefficient, the two estimate the same standard error\nand can be checked against each other; where no simple formula is\navailable, the bootstrap is computed in exactly the same way. A bootstrap standard error is itself an estimate, and for a\nstatistic whose standard error grows with the parameter, such as a ratio, it\nis no more accurate than the estimate itself.\n\nThe bootstrap distribution gives two confidence intervals. The percentile\ninterval takes the $\\alpha/2$ and $1 - \\alpha/2$ quantiles of the bootstrap\nstatistics, follows any skew, and moves with a monotone transformation of the\nstatistic; the normal-approximation interval is\n$\\hat\\theta \\pm z_{1-\\alpha/2}\\,\\text{SE}_B(\\hat\\theta)$ and is symmetric.\nThey agree when the bootstrap distribution is approximately normal and\ncentered at $\\hat\\theta$, and skewness or bias separates them.\n\nA bootstrap sample contains each observation with probability\n$1 - (1 - 1/n)^n$, which approaches $1 - 1/e \\approx 0.632$, so a model fit\nto a bootstrap sample and evaluated on the original data is evaluated mostly\non its own training observations; cross-validation, not the bootstrap,\nestimates test error. Bootstrap standard errors and intervals are unreliable\nfor small samples, for heavy-tailed or skewed populations summarized by a\nmean-type statistic, for extreme statistics such as the maximum, and for\ndependent data resampled one observation at a time.\n\nThe next lecture begins regularization (ISLR2 Sections 6.1-6.2): selecting a\nsubset of the features, and shrinking the least squares coefficient estimates\ntoward zero with ridge regression and the lasso, with cross-validation\nchoosing how much.\n",
    "supporting": [
      "20-bootstrap_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}